### ISSUE TITLE
Autofill doesn't work properly on Chrome

### ISSUE THREAD

**Issue by Kenya-West** [uNmAnNeR/imaskjs#1]
Hi from Habr! Too low karma to comment there.

On Chrome 61, auto-filling works, but look at phone number in the following gif in your [demo page](https://unmanner.github.io/imaskjs/):

![auto-fill-bug 1](https://user-images.githubusercontent.com/12271104/30782110-64e4df54-a166-11e7-8a8b-0edf46502422.gif)

It formats with extra "7" in the phone field using auto-filling feature. Seems like a bug.

Didn't test this on other browsers as they don't matter for me.

**Comment by uNmAnNeR** [comment]
Wow! first bug, nice catch! Hi there! :)
Will be fixed soon.

**Comment by uNmAnNeR** [comment]
Should be fixed now.

**Comment by plinionaves** [comment]
Hi @uNmAnNeR,

I'm using vue-imask and almost everything works perfectly, I'm having problems only with the autofill feature in Chrome for a credit card form.

My input has for example the mask `0000 0000 0000 0000` with` lazy: false`, which makes the characters appear in the input.

When the event happens the value is not passed correctly to the input, could you please check?
