### ISSUE TITLE
Jumps over to the next block on invalid enum character

### ISSUE THREAD

**Issue by adamberecz** [uNmAnNeR/imaskjs#1007]
**Describe the bug**
Jumps over to next block (and removes current block) if a non-valid character is typed in an enum block (eg. x on `['aaa', 'bbb']`).

**To Reproduce**
https://stackblitz.com/edit/vitejs-vite-yr8pcz?file=main.js

**Expected behavior**
It should stay at the current block until a valid character is typed.

**Environment:**
 - IMask version: 7.4.0
 - Tested in Chrome & FireFox on Mac

**Additional context**
This issue was brought up earlier ([#191](https://github.com/uNmAnNeR/imaskjs/issues/191) & [#692](https://github.com/uNmAnNeR/imaskjs/issues/692)) and seems to have been resolved in v6, but it apparently came back in v7.

*ps: thank you for all your work on this library!*

**Comment by uNmAnNeR** [comment]
@adamberecz nice catch. thanks
