### ISSUE TITLE
Example of vue-imask component for Vue3 does not work

### ISSUE THREAD

**Issue by medvesekg** [uNmAnNeR/imaskjs#1008]
**Describe the bug**
The example described in the [docs](https://github.com/uNmAnNeR/imaskjs/tree/master/packages/vue-imask) for using vue-imask component with Vue 3 doesn't seem to work correctly. The imask doesn't accept any input.

**To Reproduce**
[CodeSandbox](https://codesandbox.io/p/devbox/red-wave-ktpgym?file=%2Fsrc%2FApp.vue%3A6%2C16) reproduction.

**Expected behavior**
I would expect the imask to accept my input and reflect that in the variable bound by v-model

**Environment:**
 - CodeSandbox
 - vue-imask: 7.5.0
 - vue 3.4.15

**Comment by s-cryptor** [comment]
add `"allowJs": true` to your tsconfig and it will work
