### ISSUE TITLE
Variative element of group

### ISSUE THREAD

**Issue by Farit69** [uNmAnNeR/imaskjs#101]
Can I code something like this?
var Mask = new IMask(
                element, {
                    mask: 'A:B',
                    lazy: false,
                    groups: {
                        A: {
                            mask: '00',
                        },
                        B: {
                            mask: '{1,n}',    <<=== not only n digits
                        },
                    }
				});

**Comment by uNmAnNeR** [comment]
@Farit69 if i understand you correctly, just use `RegExp`
