### ISSUE TITLE
Number Mask on Android does not work like the guide exemple

### ISSUE THREAD

**Issue by Tiago138** [uNmAnNeR/imaskjs#1019]
**Describe the bug**
When using the IMask.createMask to create a number mask it does not behave like the docs example.

**To Reproduce**
```ts
 const maskedAmount = IMask.createMask({
    mask: Number, // enable number mask

    // other options are optional with defaults below
    scale: 2, // digits after point, 0 for integers
    thousandsSeparator: "", // any single char
    padFractionalZeros: false, // if true, then pads zeros at end to the length of scale
    normalizeZeros: true, // appends or removes zeros at ends
    radix: ",", // fractional delimiter
    mapToRadix: ["."], // symbols to process as radix

    // additional number interval options (e.g.)
    min: -10000,
    max: 10000,
    autofix: true
  });

 const v = 0.07
 maskedAmount.resolve(v);
 console.log("value", v);
 console.log("unmaskedValue", maskedAmount.unmaskedValue);
 console.log("maskedValue", maskedAmount.value);
```

**Expected behavior**
The masked value should be 0,07 but it gives me 7.
![Screenshot from 2024-03-20 17-07-52](https://github.com/uNmAnNeR/imaskjs/assets/88953821/c1411052-e0c0-4926-8b4a-46f7f5dc9133)

**Environment:**
 - OS: Android
 - Version: 13
 - expo: 50.0.13
 - react-native: 0.73.5
 - IMask version: 7.5.0

**Comment by uNmAnNeR** [comment]
you actually should get `Uncaught Error: value should be string`. Check your console for errors.
`resolve` accepts a string not a number

**Comment by uNmAnNeR** [comment]
@Tiago138 
`0.07` is unmasked value so it should be set like `maskedAmount.unmaskedValue = '0.07'`
if you want to set masked value then it should be `maskedAmount.value = '0,07'`
raw value is what the user inputs AND what was accepted by mask.

**Comment by Tiago138** [comment]
> @Tiago138 `0.07` is unmasked value so it should be set like `maskedAmount.unmaskedValue = '0.07'` if you want to set masked value then it should be `maskedAmount.value = '0,07'` raw value is what the user inputs AND what was accepted by mask.

Yes, if I input 0.07 it gives me maskedAmount.unmaskedValue = 7 and maskedAmount.value = 7, it is not giving me the correct values.
