### ISSUE TITLE
unmaskedvalue on multiple elements

### ISSUE THREAD

**Issue by nexusblake** [uNmAnNeR/imaskjs#102]
Hello, first of all thanks for the plugin it fits almost everything i need, second.. english isnt my native language so ill try my best.
i found out recently that i need to apply imask to multiple classes in the same html file. Using imask like this works fine:

```
$('.inputAmountMask').each(function(index, element){
    var currencyMask = new IMask(
    element,
  {
    mask: 'num',
    blocks: {
      num: {
        mask: Number,
        thousandsSeparator: '.',
        radix: ','
      }
    }
  });
});
```

At this point im good, but i need the unmasked values of all the inputs with the class "inputAmountMask" to be unmasked on submit of any form, so i tried something like this:
```
$('form').submit(function() {
    $('.inputAmountMask').each(function(index,element){
        $(this).val($(this).unmaskedValue);
         // $(this).val(element.destroy()); //not working
    });
});
```
but trying to do this just, leaves the values of every input in blank. am i doing something wrong?

**Comment by uNmAnNeR** [comment]
Hello @nexusblake !

`$(this).val($(this).unmaskedValue);` this does not work.
You have to store your currency masks somewhere and then use them to get unmasked values. As a storage you could also use jquery https://api.jquery.com/data/.

You are welcome.

**Comment by nexusblake** [comment]
Thanks @uNmAnNeR , i didnt use jquery data. but with your idea i figured out 2 ways to do it.

```
var arrayInputMask = []

$('.inputAmountMask').each(function(index, element){
    var currencyMask = new IMask(
    element,
  {
    mask: 'num',
    blocks: {
      num: {
        mask: Number,
        thousandsSeparator: '.',
        radix: ','
      }
    }
  });
    arrayInputMask.push(currencyMask);
});
```
And then to unmask every value in the array:
1.-
```
$('form').submit(function() {
   $(arrayInputMask).each(function(index,element){
        element.el['input'].value = element.unmaskedValue;
    });
});
```
or 2.-
```
$('form').submit(function() {
$('.inputAmountMask').each(function(index,element){
   $(this).val(arrayInputMask[index].unmaskedValue);
});

```
Thanks again 👍
