### ISSUE TITLE
Number mask ignores radix mapping when value was already loaded in the element before IMask(el,mask) is used.

### ISSUE THREAD

**Issue by efsant0s** [uNmAnNeR/imaskjs#1021]
**What problem you are trying to solve?**
Currently, I apply masks on elements after they have already been loaded with values. And because of that, with numeric values that have the value 111.330 and mask is like
var maskValue = { 
  scale: 8, 
  thousandsSeparator: '',
  radix: ',',
  mapToRadix: ['.'],
  min: -10000,
  max: 10000000, 
}; 
I was expecting to be 111,330 and not 111330

**Describe the solution you'd like**
I would like that similarly like the issue https://github.com/uNmAnNeR/imaskjs/issues/863 to include a flag parameter  (flags: AppendFlags = {input: true}) at IMask(fieldToMask, maskValue) so it can apply the mask without affecting it's original value.

**Describe alternatives you've considered**
Doing server side masking of the value, before loading. But It would be nice if this was a client-side possibility.

**Comment by efsant0s** [comment]
Here is an example of what I mean. https://codepen.io/efsant0s/pen/poBWXoW

**Comment by uNmAnNeR** [comment]
@efsant0s hi,
> I was expecting to be 111,330 and not 111,330

I don't see any difference.

First thing that imo IMask should only be used in the browser. Can you just disable it for SSR?
Second is that the value shown in input is always masked value. So you should put masked value there. It looks like you are trying to use unmasked value instead.
If you still want it to work the way you want initially you can use imask pipe to transform unmasked value to masked value and put it in the input. Mask options can be reused between pipe and input.

**Comment by efsant0s** [comment]
Sorry, it was a typo:
"I was expecting to be 111,330 and not 111330"

And I have updated the https://codepen.io/efsant0s/pen/poBWXoW (I was trying to make some work arounds).

And I did a workaround to make the behavior I wanted:

      const fieldToMask = document.getElementsByName(fieldToMaskName)[0]; 
      const fieldData = fieldToMask.value
      const mask = IMask(fieldToMask, maskValue);
      mask.unmaskedValue = fieldData
