### ISSUE TITLE
setTypedValue not working anymore with version 7.6.0

### ISSUE THREAD

**Issue by smellai** [uNmAnNeR/imaskjs#1024]
**Describe the bug**
`setTypedValue` is not updating the input field anymore after last upgrade

**To Reproduce**
[CodeSandbox](https://codesandbox.io/p/sandbox/elegant-bassi-xr6gkk) reproduction.

**Expected behavior**
Changing the value with setTypedValue with external control should update the input value.
Install react-imask 7.5.0 in the sandbox to see that working.
Install react-imask 7.6.0 in the sandbox to see the issue.

**Environment:**
 - OS: macOS
 - Browser: chrome
 - Version: latest
 - react-imask: 7.6.0

**Comment by uNmAnNeR** [comment]
i am not an expert in react but to me it seems wrong to use `value` prop together with hook. Once you use the hook you shouldn't explicitly set the `value` on input anymore:

https://codesandbox.io/p/sandbox/serverless-sound-dmnlhk?file=%2Fsrc%2FApp.tsx

**Comment by smellai** [comment]
Thanks, I missed that I could use that `defaultTypedValue`.

**Comment by uNmAnNeR** [comment]
@smellai yep it's a new one, added in 7.6.0. Ok, hope it helps
