### ISSUE TITLE
cloudflare error occurred, CDN is not working

### ISSUE THREAD

**Issue by Ramazon88** [uNmAnNeR/imaskjs#1027]
<img width="1723" alt="Screenshot 2024-04-12 at 12 52 03" src="https://github.com/uNmAnNeR/imaskjs/assets/85431603/01bd1985-bb0d-43e0-9166-2eb929e4c40c">

**Comment by uNmAnNeR** [comment]
i do not manage cdns, but you can use https://cdnjs.com/libraries/imask instead
