### ISSUE TITLE
set initial value

### ISSUE THREAD

**Issue by youtnbe** [uNmAnNeR/imaskjs#103]
How can i set initial value of IMaskInput? If i write my render function like this, i see initial value in input field, but i can't change it.
```javascript
const {value} = this.props;
return <IMaskInput
               value={value}
                onAccept={this.handleChange}
                mask={Date}
                pattern={momentFormat}
                lazy={false}
                min={new Date(1970, 0, 1)}
                max={new Date(2030, 0, 1)}
                format={function (date) {
                    return moment(date).format(momentFormat);
                }}
                parse={function (str) {
                    return moment(str, momentFormat);
                }}
                blocks={{
                    HH: {
                        mask: IMask.MaskedRange,
                        from: 0,
                        to: 23
                    },
                    mm: {
                        mask: IMask.MaskedRange,
                        from: 0,
                        to: 59
                    },
                    ss: {
                        mask: IMask.MaskedRange,
                        from: 0,
                        to: 59
                    }
                }}
            />
```
please help

**Comment by uNmAnNeR** [comment]
@youtnbe Did you try `defaultValue`? https://reactjs.org/docs/uncontrolled-components.html

**Comment by youtnbe** [comment]
my bad. I incorrectly transformed the value in the external component. but now I have a new question. is it possible to overwrite the current value as you type, as the "insert button" does

**Comment by uNmAnNeR** [comment]
@youtnbe try using mask `prepare` option

**Comment by zeyuri** [comment]
Hello, sorry to open this again, but I've not found a way to set a initial value reliably using a defaultValue from react.

Here is as codesandbox for this

https://codesandbox.io/s/frosty-sky-yqgk4?file=/src/App.js

**Comment by StanislawVictorovich** [comment]
How to set default value? Any ideas?

**Comment by ErnieBernie10** [comment]
There really should be a way to do this easily. Just adding a prop for a defaultValue would do fine. Any plans on adding this?

**Comment by geoquant** [comment]
can we please have an example?

**Comment by syafilm** [comment]
any update about this?

**Comment by uNmAnNeR** [comment]
should be fixed in the upcoming release

**Comment by L0rdCr1s** [comment]
@uNmAnNeR what is the work around for now

**Comment by L0rdCr1s** [comment]
If any one want a workaround for this problem here is how I did it in react, seems to work for me

1. input jsx 
```
<Input
    ref={ref}
    type="text"
    unmask="true"
/>
```
2. useIMask hook options (IMPORTANT PART)
```
const inputMaskOptions = {
    mask: "HH : MM",
    lazy: true, // lazy loading the input is key to using the setValue to set default value

    blocks: {
        HH: {
            mask: IMask.MaskedRange,
            from: 1,
            to: 12,
        },
        MM: {
            mask: IMask.MaskedRange,
            from: 0,
            to: 59,
        },
    },
};
```
3. useIMask hook
```
const { ref, value, setValue } = useIMask(opts);
```
5. using the useEffect to set the value
```
useEffect(() => {
    setValue('10:00');
}, []);
```

NOTE: if you're not using ``onAccept`` to change the value and you're using ``onChange`` instead, it will bring an error when you try to type the new value, so create an intermediate function to get the value from the input and use ``setValue`` to set a new value

I'm using ``onChange`` because ``onAccept`` is not working for me
