### ISSUE TITLE
Non lazy does not show the placeholder initially

### ISSUE THREAD

**Issue by schogges** [uNmAnNeR/imaskjs#1035]
**Describe the bug**
I am using `react-imask` with `lazy` set to `false` to make the placeholder/pattern always visible. This worked fine until `react-imask@7.5.0` and `imask@7.5.0`, but with `7.6.0` the placeholder is not shown when mounting the masked input. It appears after at least one character has been entered or turning `lazy` on and off again.

**To Reproduce**
- it can be reproduced on the official documentation: [imask.js.org/guide.html#lazy](https://imask.js.org/guide.html#lazy)
- I have created a sandbox: [codesandbox.io/imask-lazy-repro](https://codesandbox.io/p/sandbox/imask-lazy-repro-v92tm7)
- it can also be reproduced with the repro from #1025 : [stackblitz.com/edit/vitejs-vite-r5jzc8](https://stackblitz.com/edit/vitejs-vite-r5jzc8) when clearing the input field before pressing the button `init imask`. Therefore I think it's not react related.

**Expected behavior**
When setting `lazy` to `false`, I expect to see the placeholder/pattern at any time. I expect to see it after mounting, the first render and entering a value.

**Environment:**
 - OS: macOS 14.4.1
 - Browser: Brave Version 1.65.114 Chromium: 124.0.6367.60 (Official Build) (arm64), Firefox 125.0.2 (64-bit)
 - IMask version: 7.6.0
 - Framework/plugin: React

**Additional context**

https://github.com/uNmAnNeR/imaskjs/assets/24444046/a7316271-dd8f-4621-bf73-6d0bee82cf88

https://github.com/uNmAnNeR/imaskjs/assets/24444046/80aa2b7a-a5fb-48a0-a39e-0ee041ed2f76

**Comment by Squixx** [comment]
seeing the same behaviour in angular

**Comment by nyates42** [comment]
I'm also having the same issue. Was not a problem before but something must have changed.

**Comment by npearson72** [comment]
As a work around, I've added a placeholder on the actual input that matches what the mask appears like. But it seems redundant. Indeed lazy false used to work more elegantly in the past, just as this issue describes.

**Comment by alexvoedi** [comment]
Problem is not fixed. If the input is not rendered initially, it still does not show the placeholders. This is the case if the input is for example in a dialog element.
