### ISSUE TITLE
Use in a vuejs model-input hides last character typed

### ISSUE THREAD

**Issue by willjosefi** [uNmAnNeR/imaskjs#104]
I'm using the vuejs version of the plugin and trying to use in a input with a bind model.

Last char typed in the input is hide. But you can see in the VuejsDevtools (in the data field)

Check the video below
http://recordit.co/sfMCVGZIe6

**Comment by raulfdm** [comment]
Having the same issue but with React

**Comment by uNmAnNeR** [comment]
@willjosefi @raulfdm hm, interesting. I will check it

**Comment by uNmAnNeR** [comment]
@willjosefi i tried to reproduce it with no success. Please take a look: http://jsfiddle.net/bfmstw0r/

**Comment by willjosefi** [comment]
It's weird. Now i was unable to reproduce as well. Maybe @raulfdm can give us an example?

**Comment by uNmAnNeR** [comment]
Ok guys, please feel free to reopen.

**Comment by raulfdm** [comment]
Hello guys. Sorry for the delay.

I'll try to isolate my use case in a repo and post here to you analyse it. 

Thanks.
