### ISSUE TITLE
Автодобавление / удаление символов при вводе

### ISSUE THREAD

**Issue by kachurun** [uNmAnNeR/imaskjs#105]
Привет дружище, отличный проект, но возникла одна хотелка:

Маска формата: 8 (000) 000-00-00

Вбиваю `8906`, получаю `8 (906`, а хотелось бы `8 (906) `, т.е если следующий (точнее все следующие) за введенным символом - фиксированный маской, то его следует так же вводить на этом шаге.

Я пытался решить эту задачу лютым костылем - в accept каждый раз переопределяю value, добавляя пробел в конец, в целом работает, но положение курсора остается у введенного ранее символа.

Возможно есть какое то решение?

**Comment by uNmAnNeR** [comment]
@kachurun  Привет! Спасибо на добром слове.
Вижу пару вариантов - быстрый и правильный.
1) В твоем варианте чтобы работал курсор нужно использовать `prepare` и возвращать строку + пробел. Только не говори никому что я это советовал.
2) наследоваться от `MaskedPattern` и переопределить `append` - вызывать родительский и проходить по всем фикс. символам, добавляя их. Тут придется разбираться с внутренней реализацией маски.

**Comment by kachurun** [comment]
@uNmAnNeR 

1. C prepare пробовал, но если возвращать строку + пробел, то эти пробелы потом после каждой цифры так и остаются (и даже стереть их нельзя). 

Я добавлял пробел где то внутри метода _onInput класса InputMask, все оч классно работало до тех пор пока я не начал писать где то посередине уже введенных букв, тогда происходит что то невероятное, все символы после курсора просто начинают дублироваться.

2. Полез в исходники, понял что погряз, но так ничего и не добился. Возможно позже вернусь к этому.

Спасибо!
