### ISSUE TITLE
Добавить событие потери фокуса

### ISSUE THREAD

**Issue by Dionis78** [uNmAnNeR/imaskjs#106]
Очень нужен функционал очистки input если маска заполнена не полностью.
Но для этого нужно отловить момент потери фокуса.

**Comment by uNmAnNeR** [comment]
это событие инпута, причем здесь маска?

**Comment by Dionis78** [comment]
Тогда вопрос - как из инпута получить объект примененного к нему IMask? Чтоб проверить заполнена ли маска, и очистить. Причем, менять надо не только инпут, но и внутренние значения объекта иначе получается "Element value was changed outside of mask."

**Comment by uNmAnNeR** [comment]
Из инпута никак. Это задача приложения сохранить и сопоставить маску с инпутом, не вижу проблемы.
