### ISSUE TITLE
Support for <input /> events

### ISSUE THREAD

**Issue by SilentSpammer** [uNmAnNeR/imaskjs#108]
Now subscription for events without `.native` modifier is not working:
```vue
<imask-input
    @focus="doSomething($event)"
    @blur="doSomething($event)"
/>
```

We have to specify `.native` modifier like 
```vue
<imask-input
    @focus.native="doSomething($event)"
    @blur.native="doSomething($event)"
/>
```

I guess, you should pass listeners futher to `<input />`.

See https://vuejs.org/v2/guide/components-custom-events.html#Binding-Native-Events-to-Components

**Comment by uNmAnNeR** [comment]
indeed, it is a good idea. Thanks
