### ISSUE TITLE
Regexp mask doesn't work in angular 18

### ISSUE THREAD

**Issue by AntonBobylev** [uNmAnNeR/imaskjs#1087]
**Describe the bug**
Regular expression mask doesn't work in angular 18.
![image](https://github.com/user-attachments/assets/79f09fd5-8016-4cc3-a970-21969e71a460)

**To Reproduce**

https://stackblitz.com/edit/stackblitz-starters-7ul1ul

**Expected behavior**
Regular expression should be applied on user's input.

**Environment:**
 - OS: Ubuntu 24
 - Browser: Chrome
 - IMask version: 7.6.1

**Additional note**

If it possible, please, provide me how to use imask to make sure user typed the correct email

**Comment by jeffrey-planon** [comment]
You need to allow for 0 to 6 characters, 
so instead of this: `/^[a-z]{6}$/,`
use this: `/^[a-z]{0,6}$/,`

**Comment by AntonBobylev** [comment]
Oh, sheesh.
I'm sorry, my bad.
Thank you! @jeffrey-planon
