### ISSUE TITLE
Bug with pattern. lost last character. HELP!

### ISSUE THREAD

**Issue by loast** [uNmAnNeR/imaskjs#110]
example: [https://jsfiddle.net/alexyalinc/7pysdcme/1/](url)

**Comment by uNmAnNeR** [comment]
@loast hi! there is no bug here. If you use custom date pattern, then you also have to provide custom `format` and `parse` options. And for only year you don't need `Date` mask, use `MaskedRange` instead.

**Comment by loast** [comment]
@uNmAnNeR Thank for info!
