### ISSUE TITLE
[React] Input with onAccept and mask Number automatically deletes radix symbol (comma)

### ISSUE THREAD

**Issue by ivanov-v** [uNmAnNeR/imaskjs#114]
https://monosnap.com/file/2hT93IXvemPDst6AoZ8s52NNUlnLIn

**Comment by KennyPicavet** [comment]
The same issue exists in angular. Is it possible to fix it there as well?

**Comment by OmarOmeiri** [comment]
The problem still persists in react controlled inputs. Did you manage to solve it?

**Comment by OmarOmeiri** [comment]
It works if you try to insert a `.` or `,` in the middle of the number, but not at the end
