### ISSUE TITLE
[React] Input with onAccept and unmaskedValue

### ISSUE THREAD

**Issue by ivanov-v** [uNmAnNeR/imaskjs#117]
Similarly https://github.com/uNmAnNeR/imaskjs/issues/114 with unmaskedValue

**Comment by uNmAnNeR** [comment]
@ivanov-v not sure i got it, because while using React plugin you do not work directly with `unmaskedValue`, but use `unmask="true"` prop. And this case is working as i know, correct me if i'm wrong.
Or what do you mean?

**Comment by ivanov-v** [comment]
> @ivanov-v not sure i got it, because while using React plugin you do not work directly with `unmaskedValue`, but use `unmask="true"` prop. And this case is working as i know, correct me if i'm wrong.
> Or what do you mean?

Prop "unmask" solves the problem. Thank)
