### ISSUE TITLE
[Angular] Input with onAccept and mask Number automatically deletes radix symbol (comma)

### ISSUE THREAD

**Issue by KennyPicavet** [uNmAnNeR/imaskjs#118]
same as https://github.com/uNmAnNeR/imaskjs/issues/114

**Comment by uNmAnNeR** [comment]
@KennyPicavet can you check #119 ? is it solves the problem?

**Comment by uNmAnNeR** [comment]
@KennyPicavet i could not reproduce it, please fill free to reopen when there will be more details
