### ISSUE TITLE
В маске при типе Date в году 5 символов, при использовании директивы

### ISSUE THREAD

**Issue by victor-ponamariov** [uNmAnNeR/imaskjs#121]
Привет, спасибо за плагин)
Вчера боролся, но так и не понял в чем дело.

У меня есть свой компонент с обычным инпутом, которому я передаю параметры маски:
`       
 birthdayMask: {
          mask: Date,
          lazy: false
},
`

Не использую никаких кастомных форматов, ничего. Внутри компонента директива v-imask="mask". С компонентом общаюсь через v-model, то есть у компонента есть value, которое передается в инпут, и при изменении значения выбрасывается event('input', event.target.value).

В общем, что происходит: маска работает, но почему то я могу вбить значение 24.05.19899, причем, визуально оно не отображается, но срабатывает input event, и в результате в v-model лежит это значение 24.05.19899. Причем больше 5 символов нельзя ввести (ивент выбрасывается но с 5 символами)

Ума не приложу что не так) Если поможешь задоначу в пейпал))

**Comment by uNmAnNeR** [comment]
привет! деловой подход 👍 
не используй событие input, используй событие accept у маски. Маска не глушит стандартный input.

**Comment by victor-ponamariov** [comment]
Подскажи еще пожалуйста, как быть в таком случае. У меня есть свой компонент для инпута, и в нем я использую vee-validate, то есть я просто передаю правила валидации в этот компонент. Но фишка в том, что, в случае если это определенная маска, например дата в каком-то формате, то мне нужно расширить vee-validate и сделать отдельное правило валидации.

Можно ли использовать imask отдельно от инпута, скажем, создать класс, передать значение, и понять подходит ли это значение по маске?) 

Я думал в своем компоненте сразу расширять валидацию (если я передал маску в компонент), либо где-то в другом месте ее расширить, но в общем геморой с интеграцией vee-validate)

**Comment by uNmAnNeR** [comment]
Да, конечно можно.
Вместо
`const imask = new IMask(input, options)`
используй
```js
const mask = IMask.createMask(options);
mask.doValidate('asdasd'); // для валидации
const sanitizedValue = mask.resolve('asdsad'); // все что могли пропихнули
```

**Comment by uNmAnNeR** [comment]
@victor-ponamariov беседа затянулась... :) успехов!

**Comment by victor-ponamariov** [comment]
Под конец проекта решил вернутся к этой задаче)) Кстати, задонатил чуток)

Слушай, таки не получилось последнее что ты написал. Вот у меня есть инпут, __.__.____ с таким плейсхолером (типа плейсхолдер, на самом деле плагин заполняет инпут текстом настоящим).

Мне нужно чтобы если дата рождения не введена до конца, то выдать юзеру ошибку

Смотри

` 
   import IMask from 'imask'

   const mask = IMask.createMask({
      mask: Date
    })

    let result =  mask.doValidate('fdsfsd')
    console.log(result)
`

Вот этот код выдает всегда true, что странно. Но это ладно, главный вопрос как в этом случае проверить то значение полностью заполнено (пробовал по разному писать, не получилось).

То есть, при каждом вводе в инпут значения, я вызываю кастомное правило валидации в vee-alidate, и смотрю пока маска не заполнена полностью и верно. Если нет - ошибка юзеру что "дата рождения не заполнено".  При этом если пользователь просто прошелся по полю (например таб-ом, вызвал blur) и поле пустое (то есть __.__._____), то все равно сказать ему что поле надо бы заполнить)

Сорри если сумбурно, как то перемешался у меня код от vee-validate, imask, и свои компоненты)

**Comment by uNmAnNeR** [comment]
@victor-ponamariov Спасибо, получил :)

В маске есть свойство `isComplete` для проверки полностью она заполнена или нет. Попробуй его.
Да, `doValidate` не так работает, в параметр передаются флаги, а не значение, мой косяк. Думаю проверять значение можно через `resolve(value) === value`.
