### ISSUE TITLE
Value in input duplicated when user input language is Chinese

### ISSUE THREAD

**Issue by ooigheehong** [uNmAnNeR/imaskjs#122]
Text field value respond strange with Chinese Mode keyboard input.
it able to reproduce in imask demo page. uppercase text field.

**Comment by ooigheehong** [comment]
![chinese input](https://user-images.githubusercontent.com/23492569/48534832-4a356180-e8e4-11e8-9d57-6309e9bfd68b.gif)

**Comment by ooigheehong** [comment]
![image](https://user-images.githubusercontent.com/23492569/48534850-56b9ba00-e8e4-11e8-96e5-8a7cd338f1c7.png)

**Comment by ooigheehong** [comment]
step to reproduce,
1. type with English characters(English Input).
2. change to Chinese input.
3. highlight one of the character, then enter numeric number.
4. it will randomly hit the strange output (sometimes it won't).

**Comment by uNmAnNeR** [comment]
thanks for issue! But it takes to much time, sorry i can't help here. Waiting for hero...

**Comment by uNmAnNeR** [comment]
probably outdated and not relevant anymore

**Comment by IvanBean** [comment]
Hi, I have the same issue with version 6.0.5, when the keyboard in Chinese mode leads to duplicated value. 

with mask `[imask]="{ mask: '0000 / 00 / 00' }"`

![1609770186534](https://user-images.githubusercontent.com/20763317/103545424-810fcc80-4edc-11eb-967c-e3a9218b0534.gif)

and `[imask]="{ mask: '(00) 0000 0000' }"`

![1609770914234](https://user-images.githubusercontent.com/20763317/103545922-380c4800-4edd-11eb-94b3-234419fe55c5.gif)
