### ISSUE TITLE
version mismatch due to "latest" in subpackages

### ISSUE THREAD

**Issue by y-nk** [uNmAnNeR/imaskjs#126]
Hi !

I'd like to know if you could fix a problem in `*-imask` packages (vue-imask). We're currently using `vue-imask@3.4.1` which has a `package.json` pointing to `imask: "latest"`.

It makes `vue-imask@3.4.1` to use `imask@4.1.1`, which doesn't seem very "synchronized" per say. Or is it totally normal ?

Thanks a lot,

**Comment by uNmAnNeR** [comment]
Hi! it's not possible to update existed packages in npm, but since v.4.0.0 it uses fixed versions.
