### ISSUE TITLE
Allow keypress to replace/overwrite character of completed mask

### ISSUE THREAD

**Issue by jgelo** [uNmAnNeR/imaskjs#129]
I've got a simple date mask setup using the following -

```javascript
new IMask(input, {
  lazy:   false,
  mask:   'yyyy-mm-dd',
  blocks: {
    dd:   {mask: IMask.MaskedRange, placeholderChar: 'd', from: 1, to: 31, maxLength: 2},
    mm:   {mask: IMask.MaskedRange, placeholderChar: 'm', from: 1, to: 12, maxLength: 2},
    yyyy: {mask: IMask.MaskedRange, placeholderChar: 'y', from: 1900, to: 2999, maxLength: 4}
  }
});
``` 

Once the input contains a complete mask (such as 2018-12-02), it's not possible to replace/overwite an existing digit without first deleting it.

Is there a way to allow valid characters to replace an existing character at the cursor position on keypress when the input already contains a complete mask?

**Comment by uNmAnNeR** [comment]
@jgelo it would be great

**Comment by uNmAnNeR** [comment]
@jgelo Hi!
Some questions about replace behavior:
1) should it replace chars only if it's not possible to shift or anyway (just like in `insert` mode)?
2) another way what cleavejs does is not to overwrite but to shift tail.

What do you think? How should it work and why?

**Comment by jgelo** [comment]
> @jgelo Hi!
> Some questions about replace behavior:
> 
> 1. should it replace chars only if it's not possible to shift or anyway (just like in `insert` mode)?
> 2. another way what cleavejs does is not to overwrite but to shift tail.
> 
> What do you think? How should it work and why?

@uNmAnNeR, I'm on winter holiday so haven't had a chance to look at the code yet.  I've attached a quick demo of a custom jquery date and account number widget that I'm trying to replicate in vanillajs.  The default input for these widgets is to simply overwrite the character at the cursor position (if valid).  Pressing backspace or delete exposes the underlying mask character.

![mask_input](https://user-images.githubusercontent.com/314096/50589221-d16a7480-0e53-11e9-9592-b2a01002801e.gif)

**Comment by uNmAnNeR** [comment]
@jgelo can you please check PR #167 :)

**Comment by uNmAnNeR** [comment]
done in v5.0.0

**Comment by jgelo** [comment]
> @jgelo can you please check PR #167 :)

Just installed v5.0.0 to check the new 'overwrite' flag, works perfectly, many thanks!

**Comment by uNmAnNeR** [comment]
@jgelo consider v5.1.0. I think there might be interesting feature for you.
