### ISSUE TITLE
angular-imask [unmask]="typed" is not defined

### ISSUE THREAD

**Issue by ryanbuening** [uNmAnNeR/imaskjs#131]
I'm trying to use the `[unmask]="typed"` property on an input using angular-imask 4.1.3 and I'm getting an error:

`Identifier 'typed' is not defined. The component declaration, template variable declarations, and element references do not contain such a member`

`<input class="form-control" [(ngModel)]="vm.myValue" name="myValue" #myValue="ngModel" [imask]="this.maskService.numericWithThousandsSeparator(999)" [unmask]="typed" />`

```
    public numericWithThousandsSeparator(maxValue: number): {} {
        return {
            mask: Number,
            scale: 0,
            signed: false,
            thousandsSeparator: ",",
            padFractionalZeros: false,
            normalizeZeros: false,
            max: maxValue,
            min: 0
        };
    }
```

This is the first time I've tried to use the `[unmask]` property. Am I using it incorrectly?

**Comment by uNmAnNeR** [comment]
Seems correct. But very strange, i definitely test it worked. Probably i have to check it again with latest Angular

**Comment by ryanbuening** [comment]
@uNmAnNeR so I think the issue was I had brackets around `[unmask]="typed"`. If I remove the brackets, it doesn't throw any errors `unmask="typed"`. Also, I think the error was coming from the [Angular Language Service extension](https://github.com/angular/vscode-ng-language-service). Not imask. Closing.

**Comment by uNmAnNeR** [comment]
@ryanbuening good news! Sorry i could not help you :(, and thank you for sharing experience 👍
