### ISSUE TITLE
autoclear the value

### ISSUE THREAD

**Issue by nakarmoz** [uNmAnNeR/imaskjs#133]
Hey. Thanks for the great plugin. Tell me, is it possible to clear the value of the mask automatically?
like autoUnmask in inputmask

**Comment by uNmAnNeR** [comment]
@nakarmoz i am not sure i understand you correctly. `imask` has `unmaskedValue` prop. Is it not what you want? what do you mean saying "automatically"?

**Comment by nakarmoz** [comment]
> @nakarmoz i am not sure i understand you correctly. `imask` has `unmaskedValue` prop. Is it not what you want? what do you mean saying "automatically"?

Грубо говоря, маска отправляет в value форматированное значение. Есть опция какая-нибудь, чтобы отправлялось сразу чистое значение в бд? по типу autoUnmask в inputmask

**Comment by uNmAnNeR** [comment]
Нет, такого нет и не планируется. Работа с формами за рамками этой библиотеки.

**Comment by StanislawVictorovich** [comment]
Обнуляется значение при инициализации. Как с этим бороться?
