### ISSUE TITLE
IE11 change event not firing 

### ISSUE THREAD

**Issue by ryanbuening** [uNmAnNeR/imaskjs#135]
See Stackblitz here: https://stackblitz.com/edit/ie11onchangeissue

In Chrome, the change event fires; however, in IE11 the change event does not. A workaround is to use a blur event, but just wondering if this is a known issue or not.

Thanks.

**Comment by uNmAnNeR** [comment]
@ryanbuening  yes this is old as IE :) And in Edge it also does not work. At least it did not work year ago.
The issue with IE is that if value was changed programaticaly then IE does not fire `change` event. Yes, probably the only way is to use `blur` event.
May be i have to describe it in a guide.

**Comment by ryanbuening** [comment]
Ok. Thanks for the clarification. For future reference, another option in Angular is using `(ngModelChange)`. Closing.
