### ISSUE TITLE
Uncaught TypeError: Cannot call a class as a function

### ISSUE THREAD

**Issue by wilfredor** [uNmAnNeR/imaskjs#137]
I'm importing imask in a Bootstrap component, when I'm trying use the mask with IMask.MaskedRange, it show a error onkeypress:

```
Uncaught TypeError: Cannot call a class as a function
    at X (imask.js:435)
    at t.d (imask.js:2523)
    at t.value (imask.js:1238)
    at t.value (imask.js:1146)
    at h.value (imask.js:1953)
    at h.value (imask.js:1143)
    at h.value (imask.js:1176)
    at h.value (imask.js:1261)
    at n.value (imask.js:3234)
```

And yes, I don't know how reproduce the error with a test. Sorry
I'm using babel to compilate the Bootstap component (from ES6 to ES5).

The line 435 on imask.js show:

```
function _classCallCheck(instance, Constructor) {
    if (!(instance instanceof Constructor)) {
      throw new TypeError("Cannot call a class as a function");
    }
  }
```

**Comment by uNmAnNeR** [comment]
it's impossible to understand what is going on by this logs. Can you provide some more info or add some example on jsfiddle for instance?

**Comment by wilfredor** [comment]
The error was because the custom template imask was overdeclarated.

**Comment by sigerello** [comment]
@wilfredor I have the same problem now. Can you please provide a bit more details what the problem is and how I can workaround it?

**Comment by mistersender** [comment]
I had this problem resurface out of the blue on a project that's been running for a while. solved thusly:

```js
MM: new IMask.MaskedRange({
    from: 1,
    to: 12
})
```

**Comment by saeedarshad** [comment]
Hey @mistersender , i tried this but `mask` is required option to pass in MaskedRange. can you please tell me what should we pass as mask value here. Thanks
