### ISSUE TITLE
Caret positioning issue with thousandsSeparator

### ISSUE THREAD

**Issue by kyooriouskoala** [uNmAnNeR/imaskjs#139]
Hi! There is an issue with the cursor positioning when using `thousandsSeparator` option (v4.1.1).

Please refer to this CodePen:
https://codepen.io/kyooriouskoala/pen/dwJXRm

**Steps**
1. Place cursor behind number 4
2. Delete number 4 by pressing delete key

**Current behaviour:**
Caret appears behind number 2.

**Expected behaviour:**
Caret should appear behind number 3 instead of 2.

Currently, expected behaviour only works when number 4 is selected and then deleted.

**Comment by uNmAnNeR** [comment]
partially fixed in #144 
need more time to resolve completely.

Reproduce:
1. set cursor before separator
2. press backspace

Cursor should be aligned before separator.

**Comment by uNmAnNeR** [comment]
fixed in #154
