### ISSUE TITLE
Delete key not working when cursor is in front of thousands separator

### ISSUE THREAD

**Issue by matoilic** [uNmAnNeR/imaskjs#14]
If you use the `Number` mask and have configured a thousands separator, the delete key has no effect when the cursor is to the left of the separator, e.g. 1'000|'000 (pipe symbol is cursor). It's obvious, that the separator `'` will not be deleted. But one would expect that the 0 right to the cursor would be deleted or that the cursor moves one to the right.

This works properly with other mask types but not with the number mask.

**Comment by uNmAnNeR** [comment]
Thanks!
Actually there is one more bug with pattern mask :)
I will fix it and update version in npm.

**Comment by matoilic** [comment]
Thank you for fixing this so quickly and the great work with this library 👍
