### ISSUE TITLE
Can't synchronize input and mask 

### ISSUE THREAD

**Issue by WiseBird** [uNmAnNeR/imaskjs#141]
There is a code inside library that checks that input still holds last known value:

```ts
if (this.value !== this.el.value) {
  console.warn('Element value was changed outside of mask. Syncronize mask using `mask.updateValue()` to work properly.'); // eslint-disable-line no-console
}
```

it suggests to call `updateValue`. But `updateValue` doesn't change `value` property (used in check):

```ts
function updateValue() {
  this.masked.value = this.el.value;
}
```

Hence calling `updateValue` doesn't prevent warning from showing.

**Comment by uNmAnNeR** [comment]
looks really strange :) will check

**Comment by Nemesis19** [comment]
+1
