### ISSUE TITLE
Regular expressions don't work

### ISSUE THREAD

**Issue by ivan-ilinov** [uNmAnNeR/imaskjs#142]
```
new IMask($checkFormFd[0], {
  mask: /^\d{16}$/
});

```
I want to match number with 16 digits.

**Comment by uNmAnNeR** [comment]
Yep, thats why i wrote this guide for you:

![image](https://user-images.githubusercontent.com/1927921/51044495-4b2bfc00-15d2-11e9-8d17-2c9205b16d92.png)
