### ISSUE TITLE
Pattern. Cursor jumps over stopper after deleting group before it

### ISSUE THREAD

**Issue by WiseBird** [uNmAnNeR/imaskjs#143]
Having next pattern ``00`00`` I expect cursor to stay where it is when deleting (with `delete` key) first group. It works as expected when the second group is empty but when it is not cursor jumps.

See this gif for clarification:
![geef](https://user-images.githubusercontent.com/1745378/51166714-7f930700-18b5-11e9-999b-f0c295cc997a.gif)

**Comment by uNmAnNeR** [comment]
no, it's not about cursor position. backslash only prevents shifting chars, not cursor

**Comment by uNmAnNeR** [comment]
but ok, let me check if i can fix it

**Comment by uNmAnNeR** [comment]
@WiseBird can you check PR https://github.com/uNmAnNeR/imaskjs/pull/144 please

**Comment by uNmAnNeR** [comment]
@WiseBird done
