### ISSUE TITLE
imask.js:3086 Element value was changed outside of mask. Syncronize mask using `mask.updateValue()` to work properly.

### ISSUE THREAD

**Issue by danillo10** [uNmAnNeR/imaskjs#146]
ANGULAR IMASK
imask.js:3086 Element value was changed outside of mask. Syncronize mask using `mask.updateValue()` to work properly.

After i get values of products via webService in angular the input not update the values to imaskConfig

imaskConfig: any = {
    mask: Number,
    scale: 2,
    thousandsSeparator: '.',
    padFractionalZeros: true,
    normalizeZeros: true,
    radix: ','
 }

<input [imask]="imaskConfig" (change)="setValorUnit($event.target.value || 0, produto)" value="{{produto.produto_valor_unitario}}" id="valor_unit_produto_1" name="valor_unit_produto_1" data-code="1" class="input-default" type="text">

**Comment by uNmAnNeR** [comment]
@danillo10 i have not used Angular for a log time already :) but as far as i remember `value` prop should be `[value]` to enable binding. Am i right?

**Comment by danillo10** [comment]
No, I removed the imask in this input.
