### ISSUE TITLE
Если стереть первую цифру дня, вторая цифра смещается влево

### ISSUE THREAD

**Issue by shushlyakov** [uNmAnNeR/imaskjs#147]
https://unmanner.github.io/imaskjs/
В поле Date вводим 03.12.1999

Если стереть первую цифру дня, вторая цифра смещается влево: 03.12.1999 => 3_.12.1999

**Comment by uNmAnNeR** [comment]
не вижу проблемы

**Comment by shushlyakov** [comment]
> не вижу проблемы

Если стирать первую цифру в месяце, вторая остается на месте  
03.12.1999 => 03._2.1999.

Я думаю день так же должен себя вести

**Comment by uNmAnNeR** [comment]
не, тут дело в том, что месяц не может начинаться с 2.
Поставьте число 05 и попробуйте, будет также. Но с 3 число может начинаться

**Comment by shushlyakov** [comment]
Логика понятна. Спасибо.
