### ISSUE TITLE
Edge, commit does not fire after value change

### ISSUE THREAD

**Issue by bezua** [uNmAnNeR/imaskjs#159]
commit callback does not fire on IE11/Edge when using regexp mask.
Seems to be fine for "Number" mask, however.

Tested on your guide example (web site):

var caseMask = new IMask(element, {
  mask: /^\w+$/,
  prepare: function (str) {
    return str.toUpperCase();
  },
  commit: function (value, masked) {
    // Don't change value manually! All changes should be done in mask!
    // This example helps to understand what is really changes, only for demo
    masked._value = value.toLowerCase();  // Don't do it
  }
});

**Comment by uNmAnNeR** [comment]
Dup https://github.com/uNmAnNeR/imaskjs/issues/135

**Comment by uNmAnNeR** [comment]
will be fixed in v5.0.0 (`blur` event will be used instead of `change`)
