### ISSUE TITLE
Alpha numeric pattern

### ISSUE THREAD

**Issue by idready** [uNmAnNeR/imaskjs#16]
Hi (@uNmAnNeR and @marcobiedermann) and thanks for this brilliant vanilla plugin; i have one question, maybe i missed something but, how do you set alpha numeric pattern ? 
0 - any digit
a - any letter
* - any char
? - Alpha numeric ?

Thx.

**Comment by uNmAnNeR** [comment]
Hello!
Currently there is no alpha numeric definition, but it is very easy to add it. Just provide custom definitions (from guide):
```javascript
var zipMask = new IMask(element, {
  mask: '#00000',
  definitions: {
    // <any single char>: <same type as mask (RegExp, Function, etc.)>
    // defaults are '0', 'a', '*'
    '#': /[0-9a-Z]/  // <-- your new definition
  }
});
```
Might be added later if more requests will come. But it will break compatibility, because every def-symbol should be escaped.

**Comment by marcobiedermann** [comment]
@idready 
You can simply use a regular expression to do so.

```js
const maskOptions = {
  mask: /^[a-zA-Z0-9]*$/
};
```

This will include alpha lower, alpha upper and numbers.

**Comment by idready** [comment]
@uNmAnNeR @marcobiedermann thanks! 👍
