### ISSUE TITLE
Nested mask / blocks don't work as expected

### ISSUE THREAD

**Issue by afoeder** [uNmAnNeR/imaskjs#160]
Considering

```javascript
new IMask(
  document.getElementById('currency-mask-euro'),
  {
    mask: 'num €',
    blocks: {
      num: {
        // nested masks are available!
        mask: Number,
        thousandsSeparator: ' '
      }
    }
  });
```

the trailing € sign doesn't get rendered; or at least only when a key other than a number is pressed. Compare to the [given fiddle](https://jsfiddle.net/afoeder/7bgt58my/2/).

Thanks for your help, much appreciated!

**Comment by uNmAnNeR** [comment]
try using `lazy: false` https://jsfiddle.net/aognfv8u/
Or consider using `dynamic` mask for empty string and filled value cases.
