### ISSUE TITLE
Cannot update state value

### ISSUE THREAD

**Issue by cadrimiranda** [uNmAnNeR/imaskjs#161]
Hi, i'm using the in React version of MaskedStyledInput with Material UI TextField in a component, like that:

`const MaskedStyledInput = IMaskMixin(({ inputRef, ...props }) => (`
`      <TextField `
`        {...props}`
`        label={stateName}`
`        inputRef={inputRef}`
`      />`
`    ));`
`    return (`
`      <MaskedStyledInput`
`        mask='000.000.000-00'`
`        placeholder=" "`
`        lazy`
`        unmask`
`        onAccept={value => stateChange(stateName, value)}`
`      />`
`    );`

The component receive in props the estate name to change, and my function stateChange is:

`stateChange= (name, value) => {
    const obj = {};
    obj[name] = value;
    this.setState(obj);
  }`

But, when i input somthing on the input, her valur dont change, state dont change and i have [this error](https://imgur.com/0MBEbl2)

**Comment by uNmAnNeR** [comment]
Hi! as i understand from error, something wrong with passing `inputRef`. Make sure that IMask was initialized with correct input. It seems that IMask gets no input element.
If you provide some runnable fiddle, i will be able to help some more.

**Comment by cadrimiranda** [comment]
@uNmAnNeR Sorry about late answer. I'll provide a functional code today yet.

**Comment by uNmAnNeR** [comment]
feel free to reopen if you have more info
