### ISSUE TITLE
Cursor does not position correctly on iPhone/iPad

### ISSUE THREAD

**Issue by alexandre596** [uNmAnNeR/imaskjs#162]
when I focus on a field using pattern mask, on an iphone or ipad, that already contains data, the cursor always get positioned at the end of the block instead where I touched.

by "the end of the block" I mean "the first non-definition character". As an example, when using the mask 00.000.000-0, if I try to click on any 0 character, it always go to the . or the -

It happens on both chrome and safari

The same problem does not happens on android

**Comment by uNmAnNeR** [comment]
Thanks for reporting.
Yes, i know about it, but no ideas how to fix it and even why this happens.
What IMask does is taking current cursor position which is set by browser and aligning it to nearest input position. On ios when input is focused cursor is already in wrong position so nearest input is also getting wrong.
Any help is very appreciated.
