### ISSUE TITLE
IMask.createMask

### ISSUE THREAD

**Issue by MrDestroii** [uNmAnNeR/imaskjs#164]
It would be nice to add this functionality for react-imask

> var masked = IMask.createMask({
>   mask: '+7 (000) 000-00-00',
>   // ...and other options
> });
> var maskedValue = masked.resolve('71234567890');
> 
> // mask keeps state after resolving
> console.log(masked.value);  // same as maskedValue
> // get unmasked value
> console.log(masked.unmaskedValue);

**Comment by uNmAnNeR** [comment]
React is about rendering. In this case vanilla IMask suites well.
