### ISSUE TITLE
raw input value

### ISSUE THREAD

**Issue by danieldocki** [uNmAnNeR/imaskjs#165]
Code exemplo below, mask number like "3.41" to "3,41" is correct, but I need raw value continue "3.41" when send to server.

How can you do it?

```javascript
const options = {
  mask: Number,
  scale: 2,
  signed: false,
  thousandsSeparator: '.',
  padFractionalZeros: true,
  normalizeZeros: true,
  radix: ','
}
new InputMask(el, options)
```

**Comment by uNmAnNeR** [comment]
use `unmaskedValue` or `typedValue`, for more info see [getting started](https://unmanner.github.io/imaskjs/guide.html#getting-started) section.

**Comment by danieldocki** [comment]
how I can set raw value?

**Comment by uNmAnNeR** [comment]
use same props as above, you can find some examples in guide.
