### ISSUE TITLE
Initialization time min input value show without currency symbol. (Mask in mask for currency input)

### ISSUE THREAD

**Issue by sweety-wo** [uNmAnNeR/imaskjs#166]
I have used Mask in mask  for currency input
below is mask Object which I have used for currency input:
```
       {
            mask: '$ num',
            blocks: {
                num: {
                    min: 3,
                    mask: Number,
                    thousandsSeparator: ',',
                    normalizeZeros: false,
                    padFractionalZeros: true,
                    radix: '.',
                    scale: 2
                }
            }
        }
```

It is set 3.00 value input without currency symbol.
Here is code pen for issue: https://codepen.io/anon/pen/zXdwyR

So, how to set min value with currency symbol at Initialization time?

**Comment by uNmAnNeR** [comment]
Looks like a bug. For now as a workaround you can fix it by adding `lazy: false` (https://codepen.io/anon/pen/dLVeav).
Soon in v5.0 `Number` mask behaviour on min value will be changed - it will be allowed to have empty input event if min > 0.
