### ISSUE TITLE
are nested masks/blocks supported in vue-imask

### ISSUE THREAD

**Issue by bgs1979** [uNmAnNeR/imaskjs#168]
Are nested patterns supported in vue-imask

How would I implement it?

**Comment by uNmAnNeR** [comment]
I supposed it should. You can check examples [here](https://github.com/uNmAnNeR/imaskjs/blob/master/packages/vue-imask/example.html).
Let me know if it is not working in your case. And it would be nice if you provide runnable js-fiddle so i will be able to check it.

**Comment by bgs1979** [comment]
Their is only one examples in the example html.

what I want to do is the nested pattern in the imask guide :-
`var blocksMask = new IMask(element, {
  mask: 'Ple\\ase fill ye\\ar 19YY, month MM \\and v\\alue VL',
  lazy: false,  // make placeholder always visible

  blocks: {
    YY: {
      mask: '00',
    },

    MM: {
      mask: IMask.MaskedRange,
      from: 1,
      to: 12
    },

    VL: {
      mask: IMask.MaskedEnum,
      enum: ['TV', 'HD', 'VR']
    }
  }
});`


Using vue-imask as component but I'm unsure of how to apply the syntax.

**Comment by uNmAnNeR** [comment]
Something like this?
```vue
<template>
  <imask-input
    v-model="val"
    :mask="patternMask">
</template>

<script>
export default {
  data () {
    return {
      val: '',
      patternMask: {
        mask: 'Ple\ase fill ye\ar 19YY, month MM \and v\alue VL',
        lazy: false, // make placeholder always visible
        // ...etc
      },
    };
  },
}
</script>
```
Of course plugin should be initialized before using vue component.

**Comment by bgs1979** [comment]
Thats missing the nested block definition which is the bit that confuses me.

**Comment by uNmAnNeR** [comment]
You are right. Example above is not correct. Probably it should be like
```vue
<template>
  <imask-input
    v-model="val"
    mask="Ple\ase fill ye\ar 19YY, month MM \and v\alue VL"
    :blocks="blocks"
>
</template>

<script>
export default {
  data () {
    return {
      val: '',
      blocks: {
        // ...
      }
    };
  },
}
</script>
```
But still I am not sure if this what you want. If you can provide some runnable example then i will be able to help more.

**Comment by bgs1979** [comment]
Is their a working example on js fiddle of vue imask so I can copy the setup?
I'm not reallys sure how fiddle work I couldn't find vue-imask script on unpkg.com to include.

**Comment by uNmAnNeR** [comment]
Hm, i found one in old issues https://codesandbox.io/s/8z0ozzrv9j
`vue-imask` is here: https://unpkg.com/vue-imask

**Comment by bgs1979** [comment]
This is my fiddle
https://jsfiddle.net/bjh497/vc754Lq0/8/
It throws 
Uncaught ReferenceError: IMaskComponent is not defined
    at window.onload 
Error when uing unpckg.com vue-mask url

**Comment by uNmAnNeR** [comment]
check this one https://jsfiddle.net/46w075sL/

**Comment by bgs1979** [comment]
Thank you!
