### ISSUE TITLE
Where is typings

### ISSUE THREAD

**Issue by WiseBird** [uNmAnNeR/imaskjs#176]
Sorry for stupid question. I see you have added typings for the package, it's great!
But where can I find them? I see them in source code but not in installed package from npm:

![image](https://user-images.githubusercontent.com/1745378/57763813-de08ae80-770a-11e9-8850-ee91e11ea23b.png)

**Comment by uNmAnNeR** [comment]
nice question! lost unexpectedly... :) will add them soon again

**Comment by uNmAnNeR** [comment]
@WiseBird fixed in v5.1.4
