### ISSUE TITLE
Pattern mask bug

### ISSUE THREAD

**Issue by WiseBird** [uNmAnNeR/imaskjs#177]
Hello. 

There is a bug with pattern mask when try to type incorrect character:
![Peek 2019-05-15 12-51](https://user-images.githubusercontent.com/1745378/57766614-558d0c80-7710-11e9-937d-2edbc64a4b9f.gif)

Reproduction with 5.1.2  (put cursor in input and type `a`) - https://jsfiddle.net/WiseBird/vwrs2ntj/
The same code with 4.1.5, no bug - https://jsfiddle.net/WiseBird/jpo83rdf/5/

**Comment by uNmAnNeR** [comment]
Oh, man )) so nice bug, thank you! :)

**Comment by uNmAnNeR** [comment]
@WiseBird should be fixed in v5.1.4
