### ISSUE TITLE
Mask for date ranges

### ISSUE THREAD

**Issue by renatodarrigo** [uNmAnNeR/imaskjs#182]
Is it possible to use imask for masking inputs that accepts date-ranges?
For example: "2019-01-01 - 2019-05-23"

**Comment by uNmAnNeR** [comment]
it can be done by using 2 Dates as blocks inside pattern:
```js
IMask(el, {
  mask: 'from - to',
  blocks: {
    from: {
      mask: Date,
    },
    to: {
      mask: Date,
    }
  }
});
```

**Comment by renatodarrigo** [comment]
Thanks a lot!
Is there a way to alter the date format in the range?

For example: "DD/MM/YYYY - DD/MM/YYYY"

**Comment by uNmAnNeR** [comment]
sure, follow guide for Date https://unmanner.github.io/imaskjs/guide.html#date and provide your date pattern and format/parse options.
Seems you are changing input value outside of mask, then you have to call `updateValue` as suggested.
