### ISSUE TITLE
А если на сайте несколько input?

### ISSUE THREAD

**Issue by kiselev-webmaster** [uNmAnNeR/imaskjs#19]
У меня на сайте большое количество input, к которым необходимо прикрутить маску, как быть?
`var phoneinput = document.getElementsByName('user-tel');
var phoneMask = new IMask(phoneinput, {
      mask: '+{7}(000)000-00-00',
      lazy: false,  // make placeholder always visible
      placeholderChar: '_'     // defaults to '_'
    });`
Этот код не работает

**Comment by uNmAnNeR** [comment]
Понятно что не работает. Маска принимает на вход элемент, а не массив.

**Comment by kiselev-webmaster** [comment]
Не знаю на сколько это решение правильное, но скрипт работает
`
var phoneinputs = $(".user-tel > input");
    var phoneMask = [];
    $(phoneinputs).each(function(i,elem) {
        console.log(i);
        phoneMask[i] = new IMask(elem, {
          mask: '+{7}(000)000-00-00',
          lazy: false,  // make placeholder always visible
          placeholderChar: '_'     // defaults to '_'
        });
    });
`

**Comment by uNmAnNeR** [comment]
ну и прекрасно
