### ISSUE TITLE
Bug happened when enter enum value after number value

### ISSUE THREAD

**Issue by combinesellSg** [uNmAnNeR/imaskjs#191]
Hi,
Bug happened when I enter X value after YYYY value. It did not display when I enter any of the X value. I solved by enter any digit value then continue with the X value.
I share my code.
Thanks 

var phoneMask = new IMask(
                document.getElementById('apa_no'), {
                mask: 'aa-MM-YYYY-X-000000',
                lazy: false,
                blocks: {
                    MM: {
                        mask: IMask.MaskedRange,
                        from: 1,
                        to: 12
                    },
                    YYYY: {
                        mask: IMask.MaskedRange,
                        from: 1900,
                        to: 9999,
                    },
                    X: {
                        mask: IMask.MaskedEnum,
                        enum: ['y', 'Y', 'z', 'Z']
                    }
                }
            });

**Comment by uNmAnNeR** [comment]
thanks! seems like a bug
