### ISSUE TITLE
How to add a prefix that cannot be deleted when lazy is enabled?

### ISSUE THREAD

**Issue by KiryaAfimin** [uNmAnNeR/imaskjs#192]
Hello! Is it possible to somehow fix the symbol at the beginning of the field, while `lazy` must be turned on?
There is a phone number entry field, the mask is `+7 (000) 000-00-00`, how to make it impossible to remove `+7 (`?
The behavior should be the same as when `lazy` is disabled, but only for `+7 (`, I tried to break into blocks, but that didn't work out

**Comment by uNmAnNeR** [comment]
Hi! Fixed nested lazy. You can try it from `master`.
As a workaround css pseudo elements could be used.
