### ISSUE TITLE
Deleting part of date not working in react-imask as imask.

### ISSUE THREAD

**Issue by ejuo** [uNmAnNeR/imaskjs#193]
In react-imask deleting part of the date removes the remaining parts.
![react-imask](https://user-images.githubusercontent.com/1243837/59213382-33cb5c00-8bce-11e9-861e-edfb6b2049a5.gif)

**Comment by ejuo** [comment]
I suspect the problem that for each key press, the mask is validated. Is that `IMask.MaskedRange` does not allow `placeholderChar` character to be entered.

@uNmAnNeR 
Can enable `IMask.MaskedRange` for `placeholderChar`?

**Comment by ejuo** [comment]
Find **bad** solution:
```typescript
<IMaskInput
  value={value}
  
  mask={Date}
  pattern={'d{.}`m{.}`Y'}
  blocks={{
    d: {
      mask: IMask.MaskedEnum, enum: ['01', '02', '03', '04', '05', '06', '07', '08', '09',
      '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20',
      '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31']
      },
    m: {
      mask: IMask.MaskedEnum, enum: ['01', '02', '03', '04', '05', '06', '07', '08', '09', 
      '_1', '_2', '_3', '_4', '_5', '_6', '_7', '_8', '_9',
      '1_',
      '_0', '_1', '_2',
      '10', '11', '12']
      },
    Y: {
      mask: IMask.MaskedRange,
      from: 1900,
      to: 9999,
    },
  }}
  format={ (date: Date) => {
    const day = String(date.getDate()).padStart(2, '0');
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const year = date.getFullYear();

    return [day, month, year].join('.');
  }}
  parse={ (str: string) => {
    const [day, month, year] = str.split('.');
    return new Date(Number(year), Number(month) - 1, Number(day));
  }}
  lazy={false}
  overwrite={true}

  onBlur={this.onBlur}
  onComplete={this.onComplete}
  onInput= {this.onChange}
/>
```

**Comment by uNmAnNeR** [comment]
Hi! Probably i don't get what exactly does not work. But yes, there were some issues with range mask, that was fixed recently and not released yet. But it might solve the problem and you can try it from `master` branch.
Btw, have you tried it on vanila version so far? just to be sure that the problem is only React related.

> Can enable IMask.MaskedRange for placeholderChar?

no, it does not work this way.

**Comment by ejuo** [comment]
I'm using controlled component, added listener on change event. That update value for IMask component for each key press.
To reproduce it in vanila, you can copy typed value '12.1_.2009' and paste, and you get '12.12.____'.

**Comment by ejuo** [comment]
![react-imask2](https://user-images.githubusercontent.com/1243837/59435637-80e64280-8e07-11e9-92c7-a4d5f6364f6d.gif)
Then I delete first letter it's ok. Then second, year part shifts. In console onAccetp event emitted twice.

**Comment by uNmAnNeR** [comment]
thanks for details, i'll check if i can do smth.

**Comment by ejuo** [comment]
Thanks, @uNmAnNeR.
I found the solution [above](https://github.com/uNmAnNeR/imaskjs/issues/193#issuecomment-501032704), it is not very native, but it works. If the default realization cannot work according to some principles, you can close the problem.

**Comment by ejuo** [comment]
@uNmAnNeR, I made sandbox examples https://codesandbox.io/s/react-hook-form-custom-input-s50re
All solutions not clear.

**Comment by uNmAnNeR** [comment]
Thanks

**Comment by ejuo** [comment]
@uNmAnNeR 
Tried to figure out the cause. That's what I think.
1. I can be wrong, but, [`rebuild`](https://github.com/uNmAnNeR/imaskjs/blob/00a61e8b32f80a930c6a34aaa495897e963d41e9/packages/imask/src/masked/pattern.js#L79) mask used unmasked value. And for masks eg. `01._2.2007` and `0_.12.2009` has one value `0122009`.
It is necessary to teach to build the mask bijectively or very carefully to cause its rebuilding.
2. For the mask of type `Date`, `updateOptions` [**always calling**](https://github.com/uNmAnNeR/imaskjs/blob/e4a674c0c97ee814319268865b6dc5c1a500e0c9/packages/imask/src/controls/input.js#L218) rebuilding the mask. Even if the options have not changed. I can not see the full picture, as I investigated only the date mask. But I think this is not necessary.
3. In react plugin, when component did updated, mask [update options](https://github.com/uNmAnNeR/imaskjs/blob/master/packages/react-imask/src/imask.mixin.js#L90). It's right. To solve my problem, I'm forked react plugin and put the **crutch** here
`if (!getNumberFromValue(this.props.value).length) this.maskRef.updateOptions(maskOptions);`
Since I need to rebuild the mask only on an empty field to set `lazy` option.

**Comment by ejuo** [comment]
@uNmAnNeR made [PR](https://github.com/uNmAnNeR/imaskjs/pull/198). 
Transferred the check and set the mask value from the date mask [update](https://github.com/uNmAnNeR/imaskjs/blob/e4a674c0c97ee814319268865b6dc5c1a500e0c9/packages/imask/src/masked/date.js#L39) function. Added function comparision for deep equal check. For good, I would get rid of this heavy comparison in `objectIncludes`. I would add the necessary options to the dictionary and compare only them.

**Comment by uNmAnNeR** [comment]
@ejuo hi! I've checked it. About `objectIncludes` i suppose it already works as you said. It finds all new options in current options. May be fact that `a` and `b` arguments is in reversed order is confusing.
