### ISSUE TITLE
Phone mask does not work as expected

### ISSUE THREAD

**Issue by lumenier1** [uNmAnNeR/imaskjs#194]
var dynamicMask = IMask(
      document.getElementById('dynamic-mask'),
      {
        mask: [
          {
            mask: '+{7}(000)000-00-00'
          },
          {
            mask: '8(000)000-00-00'
          }
        ]
      });

How to combine two formats of phone number?

**Comment by uNmAnNeR** [comment]
Hi! what behavior do you want exactly?

**Comment by lumenier1** [comment]
> Hi! what behavior do you want exactly?

Hi, I want to pass numbers which start with `+7` or with just `8` as pattern below.

**Comment by lumenier1** [comment]
I solved this issue by swapping mask patterns. First `8(000)000-00-00` and then `+{7}(000)000-00-00`

**Comment by uNmAnNeR** [comment]
Usually desired behavior is: `7 => +7`, and `8 => +7`, but i am glad that your case is simple enough to be solved declaratively.
