### ISSUE TITLE
Hide mask unless focused

### ISSUE THREAD

**Issue by lumenier1** [uNmAnNeR/imaskjs#195]
I don't want to show mask pattern (default mask placeholder) untill I get to the particular input.
How to show regular DOM placeholder while input is out of focus and empty?

**Comment by uNmAnNeR** [comment]
You can use `lazy: false` option, or toggle mask on some event.

**Comment by lumenier1** [comment]
Actually, `lazy: false` doesn't work.

**Comment by lumenier1** [comment]
`lazy: false` seems to be broken, it doesn't hide mask placeholder for IMask date type

    IMask(document.querySelector('input[name="date"]'), {
      mask: '00.00.0000',
      lazy: false
    });

**Comment by uNmAnNeR** [comment]
yeah, sorry, it should be `true` of course

**Comment by lumenier1** [comment]
Thanks)

**Comment by voskresla** [comment]
But when we back to focus - there is no pattern with `lazy:true` (
Also there is  example for strange behaviour when we update lazy options on event. Try to click a few times. In my case i need show pattern when user type and show placeholder on empty value. Can i achieve this ? )

**Comment by uNmAnNeR** [comment]
@voskresla seems like a bug

**Comment by voskresla** [comment]
I modify repro https://codesandbox.io/s/withered-shadow-kr5zs?file=/src/index.js

After fix we have placeholder from input attribute (it's ok) if no value in input, but when we type something there no placholder from imask `__` (
