### ISSUE TITLE
Custom phone number

### ISSUE THREAD

**Issue by plashenkov** [uNmAnNeR/imaskjs#196]
Hi! I would like to create a mask to allow a user to type a phone in international format with arbitrary digit count. Something like `/^\+\d*$/`. But how to always show the plus sign and prevent a user from deleting it? I'm trying something like this:

```js
const phoneMask = IMask(document.getElementById('phone-input'), {
  lazy: false,
  mask: /^\+\d*$/
});
```

But... it doesn't show the + sign and always requires user to input it.
How to solve this problem?

**Comment by uNmAnNeR** [comment]
Hi! pattern mask with blocks is the solution:
```js
const phoneMask = IMask(document.getElementById('phone-input'), {
  lazy: false,
  mask: '+phone',
  blocks: {
    phone: {
        mask: /^\d*$/,
    }
  }
});
```
I did not test it, but i think you got the idea.
Also `lazy` prop works only with `pattern`, not `RegExp`.

**Comment by plashenkov** [comment]
Thank you! It works.

P.S. Great library, thanks so much!
