### ISSUE TITLE
To change the direction of text input

### ISSUE THREAD

**Issue by exctac** [uNmAnNeR/imaskjs#199]
hi. Now when you enter the number, the cursor moves from left to right and the right character is overwritten, and I need the opposite from right to left? how to do this?

`var element = document.getElementById('elem');`
`var maskOptions = {`
`   mask: '0000000000',`
`   lazy: false,`
`   placeholderChar: '0',`
`   overwrite: true`
`};`
`var mask = IMask(element, maskOptions);`

**Comment by cnovoab** [comment]
Why was this issue closed? Was it attended or dismissed?

**Comment by rejas** [comment]
I'd be interested in that feature too so I am also curious why it was closed?

**Comment by uNmAnNeR** [comment]
ok, but not for now

**Comment by uNmAnNeR** [comment]
close as a dup of https://github.com/uNmAnNeR/imaskjs/issues/452
