### ISSUE TITLE
unmasked number is the same as masked value

### ISSUE THREAD

**Issue by maxkorz** [uNmAnNeR/imaskjs#20]
Codepen: https://codepen.io/anon/pen/vpXgXy
This bug affects Angular plugin. `[unmask]="true"` doesn't change the output.

**Comment by uNmAnNeR** [comment]
It should not, for number `unmaskedValue === value`. How number could be unmasked?

**Comment by maxkorz** [comment]
@uNmAnNeR I expected to get a number without `thousandsSeparator`. If `radix` is `.` a masked number is a valid JS float. For example:

masked value: `999 999 999 999.99`
unmasked value: `999999999999.99`

which is a valid float number in JS:
```js
parseFloat('999999999999.99'); // 999999999999.99
```

**Comment by uNmAnNeR** [comment]
I think it makes sense. why not

**Comment by maxkorz** [comment]
@uNmAnNeR mask is about view and a view should not corrupt model, right?
Therefore if `mask` is `Number`, unmasked value should always be a number.

For example:

imask settings:
```js
{
  mask: Number,
  scale: 2,
  thousandsSeparator: " ",
  padFractionalZeros: true,
  normalizeZeros: true,
  radix: ',',
  mapToRadix: ['.']
}
```

initial value: `1000`
masked value: `'1 000,00'`
unmasked value: `1000` 

initial value: `1000.5`
masked value: `'1 000,50'`
unmasked value: `1000.5` 

Actually, I see that behavior in demo https://unmanner.github.io/imaskjs/ in which you do
```js
        var numberMask = new IMask(document.getElementById('number-mask'), {
          mask: Number,
          min: -10000,
          max: 10000,
          thousandsSeparator: ' '
        }).on('accept', function() {
          document.getElementById('number-value').innerHTML = numberMask.masked.number;
        });
```
I don't know why the unmasked value doesn't do the same

<img src="https://i.imgur.com/RhUk00w.png">

**Comment by uNmAnNeR** [comment]
`unmaskedValue` is always string. I got your idea from previous post. I will try to do something.

**Comment by maxkorz** [comment]
@uNmAnNeR when the new version is going to be released?
