### ISSUE TITLE
Help updateOptions in angular

### ISSUE THREAD

**Issue by krasenkova** [uNmAnNeR/imaskjs#200]
Hello!
Could you please explain how to use updateOptions in angular6?
I need this behavior: https://github.com/uNmAnNeR/imaskjs/issues/152
but I can't understand how to do this in angular.

I use the mask as shown here:
https://github.com/uNmAnNeR/imaskjs/blob/master/packages/angular-imask/README.md

`              <mat-form-field>
                <input matInput 
                       type="text"
                       [imask]="
								{
									mask: 'HH:MM',
									lazy: true,
									overwrite: true,
									blocks: {
									  HH: {
										mask: IMask.MaskedRange,
										from: 0,
										to: 23,
										placeholderChar: 'H'
									  },
									  MM: {
										mask: IMask.MaskedRange,
										from: 0,
										to: 59,
										placeholderChar: 'M'
									  }
									}
								  }
                       "
                       [formControlName]="column"/>
              </mat-form-field>
`

And I'd like to change lazy: true to lazy: false on focus and back - on blur.

**Comment by uNmAnNeR** [comment]
hi! `imask` just like any other property could be defined in typescipt component. Inlining is done only for example purposes.
