### ISSUE TITLE
Create mask with minumum chars, allow users to set unlimited

### ISSUE THREAD

**Issue by lukasamd** [uNmAnNeR/imaskjs#201]
Hello, I use vue-imask and want to create mask with minumum chars, but also allow users to set unlimited chars. For example:

Default view: 2019-0001
Default value: 1 (it's sent to vue)
Available to type: 2019-12334 (or even more)

I use block mask like 2\\019-BLOCK, and on BLOCK I use mask: /^\d*$/
It works, but what when I want to create something like that:

`2019-0001-anotherText`

? 

If I use don't use lazy placeholder, it's not possible to type anything after remove value. If I use lazy placeholder, it's possible, but user must manually type "-" to then see anotherText.

My goal it's to display something like this when we remove values:

`2019-####-anotherText`
(# it's only example, it may be "_" also, so 2019-____-anotherText
User should be able to set only this inside, minumum 4 chars, but may add more.

Is it possible to create such mask?

**Comment by uNmAnNeR** [comment]
hi! it's definitely possible. You can split block into two parts: required which is pattern and optional which could be regexp. Lazy option is only for pattern, so you can set placeholder char for it.

**Comment by lukasamd** [comment]
Thank you for reply. Can you provide some small example? Not sure how
should I split block into two other

**Comment by uNmAnNeR** [comment]
something like
```js
{
  mask: '2\\019-0000rest-text
  blocks: {
    rest: { mask: /^\d*$/ }
  }
}
```
