### ISSUE TITLE
Autocomplate for browser password

### ISSUE THREAD

**Issue by Highter87** [uNmAnNeR/imaskjs#203]
There is a form of user authorization. By phone number (iMask is used, "000 0000 0000") and password entry field.
When you first enter the browser offers to save the password - approx.
But when to try a second time, it is not automatically substituted. But it is only necessary to turn off your plugin in this field - the substitution of the phone number and password successfully works.
How to be in this case?

My Code:
```
var phoneMask = IMask(
	$("input[name=U_LOGIN]")[0], {
	mask: '000 0000 0000',
	placeholderChar: '_',
	lazy: false,
});
```

UPD. If delete "lazy: false," - it's work! But no placeholder char...

**Comment by uNmAnNeR** [comment]
Browser does not use autocompletion because input is already filled with placeholder which browser treats just like standard input. You can set `lazy: true` to disable imask placeholder and use html native placeholder. If you want to show imask placeholder you can turn off lazy mode on focus.

**Comment by Highter87** [comment]
Thank! It works!
