### ISSUE TITLE
Mask with blocks broken or somehow ugly

### ISSUE THREAD

**Issue by Mrks83** [uNmAnNeR/imaskjs#207]
I would like to get a <0..100>- <0..100>- <0..100> input mask (the numeric values between 0 and 100 separated by minus chars).

For that I've used the mask as shown here https://codepen.io/anon/pen/RzjgPQ, but this leads to a weird behavior when trying to enter 90-10-0. 
In the first case it can be achieved (even it's difficult), in the second it's not possible.

DEMO: https://i.ibb.co/2KfDvj0/num.gif

~~In an earlier version (4.x) was possible.~~ (note: with space to separate its working) 
How can I fix it?

**Comment by uNmAnNeR** [comment]
Hi! seems like a bug, will check.
Btw on 4.1.4 does not work also: https://codepen.io/anon/pen/ydpLMB
So as i understand the problem is that the cursor is jumping to the end when deleting chars or inserting '-'.

@Mrks83 on what version does it work correctly?

**Comment by Mrks83** [comment]
Ooops, you are right. I was using "space" key in an older version to separate. So the behavior hasn't changed, without spaces it doesn't work.

**Comment by uNmAnNeR** [comment]
@Mrks83 please check https://github.com/uNmAnNeR/imaskjs/pull/208

**Comment by Mrks83** [comment]
> 
> 
> @Mrks83 please check #208

Way better 👍
