### ISSUE TITLE
onAccept doesn't fire for predefined values

### ISSUE THREAD

**Issue by maxkorz** [uNmAnNeR/imaskjs#21]
Codepen: https://codepen.io/anon/pen/vpXgXy

**Comment by uNmAnNeR** [comment]
When mask applies it immediately format input, but event handlers are not attached yet.
So `accept` is not fired, i dont think it is a bug. You could attach and detach event listeners at any moment and it seems to be correct to fire not when it attaches but when value really changes. In plugins probably it should, but you ask about vanilla, right?

**Comment by maxkorz** [comment]
I was making a demo for another issue and thought this behavior is incorrect. If this is intentional then no problem
