### ISSUE TITLE
[imask-react] Cannot input, when the cursor at the right side

### ISSUE THREAD

**Issue by a-x-** [uNmAnNeR/imaskjs#210]
**bug** 
When user clicks to input-control, text-cursor usually points to the end of text

**Expected**: cursor will be shifted to start of the nearest placeholder input-allowed position 

**Actual**: user must press `backspace` or `right`, or use mouse to reposition the text-cursor

**Comment by a-x-** [comment]
Sometimes imask force move cursor to the begin of the text, but not all the times

**Comment by uNmAnNeR** [comment]
need more info here. Can you provide some demo?

btw. I think somethink was done on this in https://github.com/uNmAnNeR/imaskjs/pull/208
can you please check if it fixes your case?

**Comment by uNmAnNeR** [comment]
closing in favor of inactivity, feel free to reopen
