### ISSUE TITLE
[imask-react] Warning: Received `true` for a non-boolean attribute `overwrite`.

### ISSUE THREAD

**Issue by a-x-** [uNmAnNeR/imaskjs#211]
**bug**: overwrite and autofix should accept boolean true and false

```jsx
<IMaskInput overwrite  { ...someProps} />
```

**expected**: no warning

**actual**: I have to use `overwrite="true"`

**Comment by uNmAnNeR** [comment]
hi! currently proptypes is used:
https://github.com/uNmAnNeR/imaskjs/blob/master/packages/react-imask/src/imask.mixin.js#L23

Any suggestions?

**Comment by a-x-** [comment]
As I unserstand prop reaches dom node

**Comment by uNmAnNeR** [comment]
so can you advise what can be done here? I think this should be quite common in React world. May be you can refer to other examples which are handling bools other way?

**Comment by uNmAnNeR** [comment]
@a-x- 
https://codepen.io/anon/pen/vompQP works as expected
https://codepen.io/anon/pen/NQjXoN shows warning

seems alright.
