### ISSUE TITLE
Dynamic mask type cannot accept blocks

### ISSUE THREAD

**Issue by Dohxis** [uNmAnNeR/imaskjs#213]
Been trying to use dynamic masks and blocks together, but it seems it is not working the way I would like it to. I am trying to hide the dollar sign when the field is empty. Here is what I have [right now](https://stackblitz.com/edit/typescript-clz5lg?file=index.html):
```
  const element = document.getElementById('try');
  const maskOptions = {
    mask: [
      {
        mask:'number $',
        lazy: false,
        blocks: {
          number: {
            mask: Number,
            thousandsSeparator: ',',
            radix: '.'
          }
        }
      },
      {
        mask: Number
      }
    ],
    dispatch(_, masked){
      return element.value === ""
        ? masked.compiledMasks[1] 
        : masked.compiledMasks[0];
    }
  };

  IMask(element, maskOptions);
```
If it is not possible intentionally, what would be the best way to achieve a similar thing? 

Thanks!

**Comment by uNmAnNeR** [comment]
Thanks for reporting! It's better to use `masked.value` in dispatch instead of `element.value`.
To make it more simple it could look like:
```js
const maskOptions = {
    mask: [
      {
        mask: /^$/g
      },
      {
        mask: 'number $',
        lazy: false,
        blocks: {
          number: {
            mask: Number,
            thousandsSeparator: ',',
            radix: '.'
          }
        }
      },
    ],
  };
```
But it does not work because of bug in dynamic mask. I think i'll be able to fix it soon.

**Comment by Dohxis** [comment]
@uNmAnNeR It was partially fixed, now the only thing is that negative numbers do not work.

**Comment by uNmAnNeR** [comment]
@Dohxis to enable negative numbers enable `signed: true` on number mask or set `min: <your minimum negative val>`.

**Comment by Dohxis** [comment]
Thanks!
