### ISSUE TITLE
Masking currencies doesn't seem to work properly

### ISSUE THREAD

**Issue by wwwhatley** [uNmAnNeR/imaskjs#215]
## Issue

Hello--I'm currently using iMask with React Native, and it doesn't appear that I have the right options available to me. The documentation is pretty limited, and doesn't explain masked inputs handling currencies well.

## Expected behavior

I am trying to mask fields with the format of: `$5.78 or $12.00`, with decimals being handled in the tenths place....

It appears there is an option for the thousands separator (`thousandsSeperator`) , but even then, the example provided is pretty vague...

**Comment by uNmAnNeR** [comment]
hi! `thousandsSeperator` is about every 3 digit, currently there is no option to change this somehow. Does not `scale` and `radix` work for you?
Example with currency symbol is on https://unmanner.github.io/imaskjs/ (see Mask in mask currency input)

**Comment by uNmAnNeR** [comment]
Btw any pull requests to improve docs are very welcomed.
