### ISSUE TITLE
Possibility to hide symbols in mask

### ISSUE THREAD

**Issue by Nikami** [uNmAnNeR/imaskjs#216]
Hello,

I need to hide certain numbers in mask with `*` character. So, it may be looks like:

Masked value - 33**
Model value - 3333

I couldn't find related examples in the documentation, so I wonder, is it really possible to do with Imask.js? 

I'm using Angular plugin and I have tried to implement this behavior:
```
<input 
   matInput 
   type="text" 
   formControlName="isin" 
   [unmask]="true" 
   [imask]="{mask: '00\\*\\*'}"
>
```
But in this case, model value is missing last two numbers and looks like this:
![pin-mask](https://user-images.githubusercontent.com/12629525/60870103-db24c880-a238-11e9-86b6-ce8c740223c3.png)

Could you give me advice about it, please?

**Comment by uNmAnNeR** [comment]
Hi! Really interesting and quite complicated question. For now there is no such functionality in imask and i even can't imaging some simple solution. I think handling this on input is pretty hard to implement, it's rather simple to hide/unhide on blur/focus - then mask will be just '0000' and need to implement some wrapper for replacing value just on view, but not in model.
If you still want to implement masking behavior on input i suggest to take a look on not on mask itself, but on HtmlElement view layer: https://github.com/uNmAnNeR/imaskjs/blob/master/packages/imask/src/controls/html-mask-element.js
You can inherit from it and override `value` getter and setter and put your star-masking stuff there. Then in Angular plugin there is an option to provide custom element (see `imaskElement` prop) where you can wrap native element in your custom HtmlElement view.
This all just my thoughts, not verified at all.

**Comment by Nikami** [comment]
@uNmAnNeR 
That's interesting solution to inherit from HtmlElement view layer. I will try it, if I get no luck with other libraries.
Anyway, thank you for quick feedback and smart advice!

**Comment by uNmAnNeR** [comment]
@Nikami no prob. If it's not difficult for you, please share any solution if you'll find it. May be i'll find some ideas to improve imask. Thanks!

**Comment by min9nim** [comment]
I also need this feature. Did you find a solution? @Nikami

**Comment by vspassion007** [comment]
Same here, looking for this functionality in iMaskJs
