### ISSUE TITLE
MD components masking

### ISSUE THREAD

**Issue by IT-Suitapest** [uNmAnNeR/imaskjs#217]
Hello,

Is this plug-in compatible with [material design components](https://github.com/material-components/material-components-web-react)?

I couldn't find any mention in docs. I read the [Extend Existing Components](https://github.com/uNmAnNeR/imaskjs/tree/master/packages/react-imask#extend-existing-components) section, but it looks too specific for [Styled Components](https://www.styled-components.com/).

I've tried to implement the mask in my code, but haven't succeeded since the ref system doesn't look to play well with MDCs.

Let's say I have code like:

```
import React from "react";
import TextField, { Input } from "@material/react-text-field";

export const SingleLineInput = () => {

   return (
      <TextField label="My label">
         <Input
            value = { value }
            onChange = { e => setValue(e.currentTarget.value) }
         />
      </TextField>
   );

}
```

Note that both `<TextField />` & `<Input />` are MD components.

So, if I:

1. Replace `<Input />` with `<IMaskInput />`, I'll get a bunch of errors like:

```React does not recognize the `handleFocusChange` prop on a DOM element.```

2. Try to implement something similar to [Extend Existing Components](https://github.com/uNmAnNeR/imaskjs/tree/master/packages/react-imask#extend-existing-components) section, I'll run into the issue that `<TextField />` doesn't have any `ref`or `innerRef` property (or at least it's not mentioned in [docs](https://github.com/material-components/material-components-web-react/tree/master/packages/text-field) & hence is not intended for use).

The correct way to pass ref in MDCs is to use `ref` property in `<Input />`.

So, if I do something like (which's probably a bad idea):

```
import React from "react";
import TextField, { Input } from "@material/react-text-field";
import {IMaskMixin} from "react-imask";

const MaskedStyledInput = IMaskMixin(({inputRef, ...props}) => (
  <Input
  	{ ...props }
  	innerRef = { inputRef }
  />
));

export const SingleLineInput = () => {

   return (
      <TextField label="My label">
         <MaskedStyledInput 
            mask = { Number }
            radix = "."
            onAccept = { (value, mask) => console.log(value) }
            type = { props.type }
            value = { value }
            onChange = { e => setValue(e.currentTarget.value) }
            inputRef (or just ref) = {i => i}
         />
      </TextField>
   );

}
```
I'll get a bunch of other errors like:

```
Uncaught Invariant Violation: React.Children.only expected to receive a single React element child.
```

What's the correct way to use the plug-in with MDC?

If it's possible, I'll do a pull in docs once it'll be clear.

**Comment by uNmAnNeR** [comment]
From my side I've not used MD with React, so i'am not in context. Believing in you or other hero... :)

**Comment by IT-Suitapest** [comment]
Looks like the best way would be to apply a mask to an input with vanilla JS library.

For instnace the following example would work almost fine:

```
import React from "react";
import ReactDOM from "react-dom";
import TextField, { Input } from "@material/react-text-field";
import IMask from "imask";

export const SingleLineInput = () => {

   let mask;

   // Updates mask && value
   const handleInput = e => {

      mask.updateValue();

      setValue( mask.value );

   };

   // Applies iMask to input.
   const handleMount = i => {

   if ( mask ) return;

      let input = ReactDOM.findDOMNode(i);

      mask = new IMask(
      input,
         {
            mask: '€ numeric',
               blocks: {
                  numeric: {
                     mask: Number,
                     scale: 0,
                     min: 0,
                     max: 500000,
                     thousandsSeparator: '.'
                  }
               }
         }
      );

   mask._unbindEvents();

   };

   return (
      <TextField label="My label">
         <Input
            value = { value }
            onChange = { handleInput }
            ref = { handleMount }
         />
      </TextField>
   );

}
```

Here's a [demo](https://htmlpreview.github.io/?https://github.com/IT-Suitapest/_next-suitaprest-forms/blob/master/dist/index.html) (only first three inputs work), here's slightly more complex [source](https://github.com/IT-Suitapest/_next-suitaprest-forms/blob/master/src/sampleForm/scripts/components/singleLineInput.jsx).

`mask._unbindEvents();` is necessary since otherwise there'll be a conflict between MD component & iMask.

The only problem is that the UX in this case wouldn't be that nice as in the [example](https://unmanner.github.io/imaskjs/).

For instance if you type in "123456" & then delete "4", the result would correctly be "12356" but the cursor would go to the end of the string.

Meanwhile if you put "123456" & delete "3", it'd work perfectly well & completely as expected.

Neither of `updateCursor(cursorPos)`,  `alignCursor()`, `alignCursorFriendly()` produces the desired effect.

---

@uNmAnNeR could you please tell me if this way of applying the mask is stable & is there anything I need to call in order to adjust the cursor position properly?

**Comment by uNmAnNeR** [comment]
I'm not sure this is a good idea, because you need to reimplement all stuff from and react plugin by yourself. I'd rather prefer investigate a little bit MD component and try to use ref from it, may be it will require to inherite from it, but still much better i think.
MD uses new ReactRef:
https://github.com/material-components/material-components-web-react/blob/master/packages/text-field/Input.tsx#L81

And it seems that it does not support old style ref: https://github.com/material-components/material-components-web-react/blob/master/packages/text-field/Input.tsx#L295 check this `inputElement` getter.

So may be it's possible to pass this ref to mask mixin. I don't have too much time to check this.

It you still want to use vanila version, then you probably might take a look at https://github.com/uNmAnNeR/imaskjs/blob/master/packages/imask/src/controls/html-mask-element.js

and connect all events manually. So cursor is not working because you use updateValue/setValue which rewrites value completely and resets cursor position.

PS. If you provide some working jsfiddle to check it will be much easier to help.

**Comment by IT-Suitapest** [comment]
If someone more will have this problem, here is the answer:

[https://material-ui.com/components/text-fields/#formatted-inputs](https://material-ui.com/components/text-fields/#formatted-inputs)

The example uses Material-UI package with react-number-format, but looks like it might be adapted to use with imask as well.

**Comment by uNmAnNeR** [comment]
@IT-Suitapest thanks
