### ISSUE TITLE
Unable to use nested blocks (masking) [Angular 7] [TypeScript 3]

### ISSUE THREAD

**Issue by git4spsumar** [uNmAnNeR/imaskjs#218]
I want to display the currency ($ 500,000.00). I am unable to make nested masking work ('blocks') to display a $ sign with type Number due to the following error. 

_[ts]
Argument of type '{ mask: string; blocks: { num: { mask: NumberConstructor; thousandsSeparator: string; }; }; }' is not assignable to parameter of type 'AnyMaskedOptions'.
  Type '{ mask: string; blocks: { num: { mask: NumberConstructor; thousandsSeparator: string; }; }; }' is not assignable to type 'MaskedOptions<typeof Masked>'.
    Type '{ mask: string; blocks: { num: { mask: NumberConstructor; thousandsSeparator: string; }; }; }' is not assignable to type '{ mask: typeof Masked; }'.
      Types of property 'mask' are incompatible.
        Type 'string' is not assignable to type 'typeof Masked'._

I have taken code from the demo. [Click here for demo link](https://unmanner.github.io/imaskjs/). 

Demo screenshot:

![image](https://user-images.githubusercontent.com/52953503/61284448-6cb3ad80-a7d8-11e9-84d6-3ce0956d9271.png)

I have tried various other examples and they work but as soon as I add something in 'blocks' it throws the same compilation error. Am I missing something here? 
Note: I am using the latest version of imask and angular-imask (5.1.7). 
I have tried previous versions as well but it did not fix the issue.
My angular version is 7 and Typescript version is 3. 

Before nested masking:

![image](https://user-images.githubusercontent.com/52953503/61284699-f1063080-a7d8-11e9-8be3-6469c8951fa1.png)

After nested masking:

![image](https://user-images.githubusercontent.com/52953503/61284686-e8155f00-a7d8-11e9-906d-0c6db6beee21.png)

Please find the error and console screenshot below:

_ERROR in src/app/protected/dashboard/executive-dashboard/executive-dashboard.component.ts(391,7): error TS2345: Argument of type '{ mask: string; blocks: { num: { mask: NumberConstructor; thousandsSeparator: string; }; }; }' is not assignable to parameter of type 'AnyMaskedOptions'.
  Type '{ mask: string; blocks: { num: { mask: NumberConstructor; thousandsSeparator: string; }; }; }' is not assignable to type 'MaskedPatternOptions<string>'.
    Type '{ mask: string; blocks: { num: { mask: NumberConstructor; thousandsSeparator: string; }; }; }' is not assignable to type 'Partial<Pick<MaskedPattern<string>, "blocks" | "definitions" | "placeholderChar" | "lazy">>'.
      Types of property 'blocks' are incompatible.
        Type '{ num: { mask: NumberConstructor; thousandsSeparator: string; }; }' is not assignable to type '{ [key: string]: AnyMasked; }'.
          Property 'num' is incompatible with index signature.
            Type '{ mask: NumberConstructor; thousandsSeparator: string; }' is missing the following properties from type 'AnyMasked': state, value, unmaskedValue, typedValue, and 18 more._

![image](https://user-images.githubusercontent.com/52953503/61284639-ce741780-a7d8-11e9-8d20-d733f62593e3.png)

**Comment by uNmAnNeR** [comment]
@git4spsumar thanks! and sorry for long delay.
