### ISSUE TITLE
date-mask not working in Internet Explorer

### ISSUE THREAD

**Issue by AxelMarckx** [uNmAnNeR/imaskjs#219]
In the function _objectSpread2 there is a reference to Object.getOwnPropertyDescriptors. However, this method is not supported in Internet Explorer! As a result, I get an error message on my webapplication when I create a date-mask. In all other browsers, everything works fine. I was wondering if it is possible to fix this? If not, is there a workaround? Or should I just prevent access to my application for those who are still using Internet Explorer?

**Comment by uNmAnNeR** [comment]
thanks! fixed

**Comment by AxelMarckx** [comment]
Maybe I am missing something, but if I include imaskjs like this : <script src="https://unpkg.com/imask"></script>

**Comment by uNmAnNeR** [comment]
if you use it this way, then it will start working after next release which i plan to do this week.

**Comment by AxelMarckx** [comment]
OK, many thanks!
