### ISSUE TITLE
[Angular] masked number value doesn't work well with empty initial value

### ISSUE THREAD

**Issue by maxkorz** [uNmAnNeR/imaskjs#22]
Vanilla JS demo: https://codepen.io/anon/pen/ypaxJL - empty values transforms to "0.00"
Angular demo: https://plnkr.co/edit/AWRLTycv5ueSYn0DJvwE?p=preview - empty value transforms to ".00"

**Comment by uNmAnNeR** [comment]
it depends on (from guide):
```
  padFractionalZeros: false,  // if true, then pads zeros at end to the length of scale
  normalizeZeros: true,  // appends or removes zeros at ends
```
Use
```
  padFractionalZeros: false,
  normalizeZeros: true,  // or false
```
to disable transforming empty

**Comment by maxkorz** [comment]
@uNmAnNeR did you open the demos? I want transforming, but it doesn't work properly. The result in Angular is different from Vanilla JS.
