### ISSUE TITLE
Failed prop type: Invalid prop `unmask`

### ISSUE THREAD

**Issue by qramilq** [uNmAnNeR/imaskjs#220]
Hi. 
I have some warning, typed in title with unmask prop.
Code on [codesandbox](https://codesandbox.io/s/compassionate-swanson-2ue2e)

What is my mistake?

**Comment by uNmAnNeR** [comment]
hi, i guess it should be `unmask={true}`

**Comment by qramilq** [comment]
@uNmAnNeR oh, my mistake, yeah. 
I took this code from your [example](https://github.com/uNmAnNeR/imaskjs/tree/master/packages/react-imask). Could you fix it too? Thank's

**Comment by uNmAnNeR** [comment]
@qramilq fixed, thanks
