### ISSUE TITLE
v3.4.0 android issue

### ISSUE THREAD

**Issue by futurewebsites** [uNmAnNeR/imaskjs#222]
I have a mask for credit card expiry date mm/yyyy on some android phones the user cannot enter the 4 digit year:

` var expirationdate_mask = new IMask(expirationdate, {
        mask: 'MM{/}YYYY',
        groups: {
            YYYY: new IMask.MaskedPattern.Group.Range([2019, 2039]),
            MM: new IMask.MaskedPattern.Group.Range([1, 12]),
        }
    });`

`<fieldset class="fieldset-expiration">
                            <input name="cardExpiry" id="expirationdate" class="cc-exp form-control" type="tel" inputmode="numeric" required novalidate autocomplete="cc-exp" placeholder="EXPIRY/END DATE (MM/YYYY)" style="border-radius: 0;text-transform: uppercase;letter-spacing: .5px;font-size: 12px;height:38px;">
                        </fieldset>
`

**Comment by uNmAnNeR** [comment]
hi! current version is very far from 3.4.0, even if issue still exists it will be fixed in newest release. But in general there is nothing special in library to work on mobiles, besides vague w3c-standard support on devices themselves. I'd like to make this lib working everywhere, but it seems impossible for now.
PR are still welcomed.

**Comment by futurewebsites** [comment]
Hi thanks for the quick reply I have tried updating to version 5 but groups don't seem to be supported anymore - is there an alternative method to achieve this mask in v5?

`var expirationdate_mask = new IMask(expirationdate, { mask: 'MM{/}YYYY', groups: { YYYY: new IMask.MaskedPattern.Group.Range([2019, 2039]), MM: new IMask.MaskedPattern.Group.Range([1, 12]), } });`

**Comment by uNmAnNeR** [comment]
sure, there is `blocks` property. Blocks are very similar to groups, but allows to use other masks recursively. So instead of `IMask.MaskedPattern.Group.Range` you can use IMask.MaskedRange (https://unmanner.github.io/imaskjs/guide.html#range).

**Comment by uNmAnNeR** [comment]
ok, please reopen if something needs to be fixed.
