### ISSUE TITLE
Angular 7 Lazy: false

### ISSUE THREAD

**Issue by Hiomma** [uNmAnNeR/imaskjs#224]
Angular - ngOnInit() error. This happens when the lazy field is false. I tried to put setTimeout and it didn't work. I tried to modify the variable, it didn't work either, because the mask is not inserted after the modification

ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'mat-form-field-should-float: false'. Current value: 'mat-form-field-should-float: true'.
    at viewDebugError (core.js:20439)
    at expressionChangedAfterItHasBeenCheckedError (core.js:20427)
    at checkBindingNoChanges (core.js:20529)
    at checkNoChangesNodeDynamic (core.js:23422)
    at checkNoChangesNode (core.js:23392)
    at debugCheckNoChangesNode (core.js:23993)
    at debugCheckRenderNodeFn (core.js:23947)
    at Object.eval [as updateRenderer] (InputFieldComponent.html:1)
    at Object.debugUpdateRenderer [as updateRenderer] (core.js:23936)
    at checkNoChangesView (core.js:23290)

**Comment by uNmAnNeR** [comment]
hi! According to your log i'm not sure if this relates to imask.

**Comment by Hiomma** [comment]
When the lazy field is true, the error is not triggered. When false, error is triggered

**Comment by uNmAnNeR** [comment]
Even though I still does not see any problems relating imask. Can you create some runnable fiddle to check?

**Comment by Hiomma** [comment]
StackBlitz. Thank you :D

https://stackblitz.com/edit/angular-hbakfv

**Comment by Hiomma** [comment]
I inserted value = "__: __: __" in the input and it worked. Does that interfere with something?

**Comment by uNmAnNeR** [comment]
@Hiomma Hi! did you solve it?

**Comment by eggp** [comment]
Fix:

 ngAfterViewInit() {
        setTimeout(()=>{if (this.imask)
          this.initMask();
          this._viewInitialized = true;},0)
    }

**Comment by eggp** [comment]
temp fix in main.ts

```
IMaskDirective.prototype.ngAfterViewInit = function() {
  setTimeout(() => {
    if (this.imask) {
      // @ts-ignore
      this.initMask();
    }
    // @ts-ignore
    this._viewInitialized = true;
  }, 0);
};
```

**Comment by goldmont** [comment]
Same issue here using Angular 20:

```js
{
		mask: 'amount %',
		lazy: false,
		expose: true,
		blocks: {
			amount: {
				mask: Number,
				scale: 2,
				signed: true,
				padFractionalZeros: true,
				normalizeZeros: true,
				thousandsSeparator: '.',
				radix: ','
			}
		}
	}
```
