### ISSUE TITLE
[Jest] Cannot read property 'createMask' of undefined

### ISSUE THREAD

**Issue by listepo-alterpost** [uNmAnNeR/imaskjs#225]
`Cannot read property 'createMask' of undefined` for `jest`, when import `import IMask from 'imask';`

**Comment by listepo-alterpost** [comment]
`const imask = require('imask');` works, but I really would not like to go to such extremes

**Comment by listepo-alterpost** [comment]
I think a problem with UMD and node support

**Comment by listepo-alterpost** [comment]
maybe around here https://github.com/uNmAnNeR/imaskjs/blob/master/packages/imask/rollup.config.js#L32 @uNmAnNeR what do you think?

**Comment by listepo-alterpost** [comment]
Also works like import * as IMask from 'imask'; but without `ts` typings

**Comment by uNmAnNeR** [comment]
I think adding `esm` build (`module` in `package.json`) should help.

**Comment by uNmAnNeR** [comment]
@listepo-alterpost can you please check #226

**Comment by listepo-alterpost** [comment]
still failed, jest using `dist/imask.js`

**Comment by listepo-alterpost** [comment]
I think dist/imask.js should contain `export default` polyfill for node

**Comment by listepo-alterpost** [comment]
https://stackoverflow.com/questions/40294870/module-exports-vs-export-default-in-node-js-and-es6

**Comment by uNmAnNeR** [comment]
Actually it is already done for `umd` build by `rollup`.

**Comment by listepo-alterpost** [comment]
but the problem remains

**Comment by uNmAnNeR** [comment]
Could you please check if `import { default as IMask } from 'imask'` is working or not?

**Comment by listepo-alterpost** [comment]
still failed

**Comment by uNmAnNeR** [comment]
No more ideas so far. If 'require' is working than probably issue relates to building jest tests. I have not used it so can not reason about.

**Comment by listepo-alterpost** [comment]
I will try to find a solution

**Comment by uNmAnNeR** [comment]
@listepo-alterpost hi! may be it will help #235

**Comment by uNmAnNeR** [comment]
should be fixed now

**Comment by listepo-alterpost** [comment]
@uNmAnNeR thanks

**Comment by tarmooo** [comment]
For me this still seems to fail as i import it like that

import IMask from 'imask'

and use it: 
this.imask = IMask<any>(inputElement, { mask: mask })

Then JEST screams at me: TypeError: Cannot read property 'Masked' of undefined

**Comment by uNmAnNeR** [comment]
@tarmooo try `import { default as IMask } from 'imask'`.

**Comment by tarmooo** [comment]
thank you for your reply @uNmAnNeR, but still same, also tried other import methods that are referenced in this issue
TypeError: Cannot read property 'Masked' of undefined

      at createMask (node_modules/imask/src/masked/factory.js:34:31)
      at new InputMask (node_modules/imask/src/controls/input.js:49:19)
      at Object.IMask [as default] (node_modules/imask/dist/imask.js:4591:11)

I use imask inside stenciljs if that matters at all.

**Comment by uNmAnNeR** [comment]
Ok, seems that problem is not in import.
Let me explain and you will be able to check. IMask uses global object to resolve circular dependencies. Global object varies depending on environment: https://github.com/uNmAnNeR/imaskjs/blob/master/packages/imask/src/core/utils.js#L123

So it seems that your globals has been changed from moment where scripts are imported and when tests are executing. So check if it's possible to keep globals.

**Comment by uNmAnNeR** [comment]
@tarmooo Hi! i've just commited https://github.com/uNmAnNeR/imaskjs/commit/db7a14d05aaad90c8b80362ee074418a872886bd new way to resolve globals inside mask. Can you please check if it solves your problem?

**Comment by tarmooo** [comment]
> @tarmooo Hi! i've just commited [db7a14d](https://github.com/uNmAnNeR/imaskjs/commit/db7a14d05aaad90c8b80362ee074418a872886bd) new way to resolve globals inside mask. Can you please check if it solves your problem?

Yes, that actually fixed it. At least my snapshot tests are running now. Good job :)
