### ISSUE TITLE
Incorrect Behavior for input in ngFor

### ISSUE THREAD

**Issue by ooigheehong** [uNmAnNeR/imaskjs#227]
**Issue 1 : Unable to enter any value behind the characters**

 Simulation : 
- Select any field and put the cursor at the end of the characters in the input.
- Press keyboard to enter valid input.
- Result: unable to enter any key.

*Note: able to type input if the cursor is anywhere other than at the end of the input (i.e. in front or between characters is ok).*

**Issue 2 : Backspace causes characters to be added not removed**

Simulation :
- Select any field and put the cursor between 2 characters.
- Press backspace.
- Result: characters added instead of removed.

Tools to simulate bugs - [Stackblitz](https://stackblitz.com/edit/angular-whjjhf)

**Comment by ooigheehong** [comment]
Found out that it only hit the bug is after version 4.1.4. Version 4.1.4 is working fine.

**Comment by uNmAnNeR** [comment]
Hi, thanks for reporting. It strange, but angular fires `ngOnChanges` before `input` event is handled by imask. So mask options is updated and value is replaced before input.

**Comment by uNmAnNeR** [comment]
For quick fix i suggest to generate imask options once at start for every field and then use it. I don't think it's a good way to fix it by adding timeouts or other stuff from dark side. And currently no ideas why this is happens and what to do with it. It also interesting to check if vue or react do the same or not.

**Comment by uNmAnNeR** [comment]
checked react, update is called after input as expected

**Comment by uNmAnNeR** [comment]
@ooigheehong can you please check it after fix?

**Comment by uNmAnNeR** [comment]
i also checked, should work

**Comment by ooigheehong** [comment]
Verified good. Thank you
