### ISSUE TITLE
Cannot use 'a' in mask pattern

### ISSUE THREAD

**Issue by Dohxis** [uNmAnNeR/imaskjs#228]
Hello, I have found a bug in a mask pattern. If the mask includes the letter `a` it will be converted to `_`. As patterns like `number $` and `number USD` works, I would assume that `number ha` also works, but instead, it renders as `1,000 h_`. Here is a reproduced [example](https://stackblitz.com/edit/imask-symbols?file=index.html).

And here is the example code 
```javascript
<input id="try" value="1000" />

<script src="https://unpkg.com/imask"></script>
<script>
  const element = document.getElementById('try');
  const maskOptions = {
    mask:'number ha',
    lazy: false,
    blocks: {
      number: {
        mask: Number,
        thousandsSeparator: ',',
        radix: '.'
      }
    }
  };

  IMask(element, maskOptions);
</script>
```

**Comment by uNmAnNeR** [comment]
hi! 'a', '0' and other definitions should be escaped: https://imask.js.org/guide.html#pattern

**Comment by Dohxis** [comment]
@uNmAnNeR Thanks!
