### ISSUE TITLE
How to updated dynamic inputs on append

### ISSUE THREAD

**Issue by hugofabricio** [uNmAnNeR/imaskjs#229]
I append new phone inputs to my form, but news inputs masks dont work, how to proceed to reload?

<img width="301" alt="Captura de Tela 2019-08-11 às 16 53 02" src="https://user-images.githubusercontent.com/425678/62838925-1449c180-bc59-11e9-8c3c-886e7b6b5b5b.png">

**Comment by uNmAnNeR** [comment]
hi! please provide some source, i am not able to help you by screenshots.

**Comment by hugofabricio** [comment]
`import IMask from '../../../node_modules/imask';

const setMask = (classname, settings) => {
  const inputs = document.querySelectorAll(classname)
  if (inputs) {
    inputs.forEach(input => {
      IMask(input, settings)
    })
  }
}

setMask('.js-mask-phone', {
  mask: [{ mask: '(00) 0000-0000' }, { mask: '(00) 00000-0000' }]
})`

**Comment by uNmAnNeR** [comment]
use `IMask(...)` only on initialization, then store masks somewhere and to update use `mask.updateOptions(...)`.

**Comment by uNmAnNeR** [comment]
please feel free to reopen. You are welcomed
