### ISSUE TITLE
date pattern

### ISSUE THREAD

**Issue by corsik** [uNmAnNeR/imaskjs#23]
Все круто, но не смог поменять в паттерне даты места год и день
https://jsfiddle.net/corsik/1o6en3Lt/

Последний символ у года не печатается. 
И еще подскажи пожалуйста, за что отвечает параметр Lazy?

**Comment by uNmAnNeR** [comment]
Насколько смог понять с телефона, ты парсишь дату неправильно. Год первым должен быть.
Lazy - плейсхолдер не отображать по возможности

**Comment by corsik** [comment]
А наоборот он не понимает? если я pattern выставляю как мне удобно т.е. d-m-Y?

**Comment by corsik** [comment]
Так это единственное, что я менял в твоем коде из simple и последняя цифра не печатается. Я как бы решил проблему сделать обычный patter 00-00-0000 
Но с датой так и не понял!

**Comment by uNmAnNeR** [comment]
Да у тебя и format неправильно работает. Смысл в том, что формат - это Date в строку - в ту самую строку, которую ты отображаешь в инпуте. А у тебя по прежнему было год-месяц-день, хотя маска другая.
Соответственно parse должен формировать Date из строки. И ты тут тоже делаешь split, а потом пихаешь в Date (день, месяц, год), хотя порядок должен быть наоборот.
Короче твой рабочий пример: https://jsfiddle.net/3qx4gjLm/2/

**Comment by corsik** [comment]
Все понял. Спасибо!
