### ISSUE TITLE
Postal mask with optional part

### ISSUE THREAD

**Issue by mattduffield** [uNmAnNeR/imaskjs#230]
Hello, I am trying to create a mask as follows: 00000[-0000]

However, I would like for the users to enter five (5) digits and not see the trailing dash (-) character. Only if the remaining four (4) digits are provided would I want to see the dash.

Is this possible?

**Comment by uNmAnNeR** [comment]
hi! sure it is.
Do you want to use it with `lazy: false`, right?
if yes, then you can use something like
```js
mask: [
  { mask: '00000', lazy: false },
  { mask: '00000-[0000]', lazy: false },
]
```
with `lazy: true` should work just as you wrote.

**Comment by mattduffield** [comment]
Thank you! That was exactly what I was looking for!
