### ISSUE TITLE
Creating typed mask with a block

### ISSUE THREAD

**Issue by Valdas3** [uNmAnNeR/imaskjs#233]
I want to create a mask which would allow to input numbers and would display a $ before the number and "/hr" after it. I defined the mask like this 
```
{
	mask: '$num/hr',
	lazy: false,
	blocks: {
		num: {
			mask: Number,
			thousandsSeparator: ',',
			scale: 2,
			radix: '.'
		}
	}
}
```
Here is how I currently implemented it https://codepen.io/Valdas/pen/vYBXOjB 

Since there is only a single block which is a Number I thought I could use typedValue property and get and set a number but it seems that it only works with strings. I want to avoid having to call toString on all of the numbers when I want to set the typedValue and parsing typedValue to a float when I want to do some logic on the values. Is there any way to rewrite the mask definition to achieve what I need or some other trick I could use?

**Comment by uNmAnNeR** [comment]
Hi!
I see 2 ways to get typed value from nested mask:
1) create separate `numberMask` and use it in block
2) access nested mask via private property `moneyMask.masked._blocks[1]`
here is demo https://codepen.io/uNmAnNeR/pen/XWrNMbr?editors=1111

Also there is a bug in 4.1.4 that when you delete number, then it's not possible to input again. Consider update to latest version.

**Comment by Valdas3** [comment]
Thanks for the reply. I like the first approach you suggested and it works well for my use case.

**Comment by antiold** [comment]
@uNmAnNeR why the first snippet does not work? And why creating an instance works?
Did not found anything in the docs.
