### ISSUE TITLE
import { createMask } from "imask" broken?

### ISSUE THREAD

**Issue by indrektamming** [uNmAnNeR/imaskjs#234]
Using "imask" in Nuxt project:
* Using createMask to define mask
* Manually resolving the created mask according the need

This was working all good. Updated to "imask": "^5.2.0" and cannot import the createMask function anymore.

Checked https://github.com/uNmAnNeR/imaskjs/issues/225 and tried different ways to import with no luck: "createMask is not a function"

If i revert back to "imask": "^5.1.7" it works as expected
`import { createMask } from "imask";`

Is there anything I could be missing?

**Comment by uNmAnNeR** [comment]
i supposed exports works same for umd and esm build, but no. Can you please check #235
