### ISSUE TITLE
Mask behavior 

### ISSUE THREAD

**Issue by fernandosoria** [uNmAnNeR/imaskjs#238]
Hoping to get some help here.

I have a form with a field that accepts a decimal value and IMask adds a percentage symbol at the end. It works, but only if I type an additional number. For example, to get **3.125%** to display I have to type **3.1255**. I would expect that the percentage symbol would appear immediately after typing the first digit or at minimum on field blur, but that's not the case.

Is there a way to have the mask applied immediately after the user begins typing ([JS Fiddle Example](https://jsfiddle.net/fernandosoria/tybnjmad/9/))?

Thanks in advance for your help.

**Comment by uNmAnNeR** [comment]
@fernandosoria hi!
