### ISSUE TITLE
Currency Mask with ($) formatting for negative values

### ISSUE THREAD

**Issue by efatima** [uNmAnNeR/imaskjs#239]
My requirement is that when user types - sign in the input field, the input field should display ($) and in the ngModel i need the negative value. If user does not type - sign and enters any digit, it should be a +ve currency value without brackets. The negative sign itself should not be displayed in the user input as this is communicated by the brackets.
My range is from **-9999999999 to 9999999999.**

**Is that possible using imaskjs? Any help would be greatly appreciated. I am using Angular 7, TypeScript 3 and the latest version of imask.**

I have catered another use case where the limit was from -99,000,000  to 0. But i was simply using positive values and converting them to -ve before any API calls. This solution cannot work for my new limits. It also does not allow entering any -ve signs.  (Please see code below) 

```
let numObjectNegative: any = { // 1 to 99,000,000 
    mask: Number,
    scale: 0,  // digits after point, 0 for integers
    signed: false,  // disallow negative
    thousandsSeparator: ',',
    normalizeZeros: false,  // appends or removes zeros at ends
    min: 1,
    max: 99000000,
}

   this.currencyMask = { 
      mask: [
        {
          mask: ''
        },
        {
          mask: '$#',
          lazy: true,
          placeholderChar: ' ',
          definitions: {
            '#': /[0]/
          }
        },
        {
          mask: '($num)',
          lazy: false,
          blocks: {
            num: numObjectNegative
          }
        }
      ]
    }
```

**Comment by uNmAnNeR** [comment]
I'm not sure i got your example exactly. But seems you need some complex mask.
First thing is there is no way to skip simbols if they are in unmasked value. So if you have negative value in model, then you will also have `minus` in input. That is done by default. If you want to change it some way, then probably you need to inherit from some of masked classes and implement your own convertion logic. May be later i will be able to add some absctraction layer on top of IMask to be able to get/set parts of mask in specific formats, but currently no time/ideas.

If you can do convertion on app side, then i can suggest you to use dynamic mask with custom `dispatch` callback to put your stuff. This way you are fully control mask selection.

**Comment by efatima** [comment]
Thank you for your help!
The` dispatch` function works perfectly for the mask selection but i couldn't find a way to remove the - sign using just the library features. Will have to implement a custom solution.
