### ISSUE TITLE
IE 11, bug

### ISSUE THREAD

**Issue by andalt** [uNmAnNeR/imaskjs#24]
http://joxi.ru/8An0lpqTqenMOm
http://joxi.ru/n2YzJZxUj8nKOA

**Comment by uNmAnNeR** [comment]
Please, provide some description and steps to reproduce.

**Comment by ramlmn** [comment]
This is not a problem with the library. You are using **default function params** on line `1132`, an ES6 feature which **doesn't work in Edge < 14**.

I see you are using Webpack, but not transpiling. If you are transpiling, then let me know about your Babel config.

**Comment by uNmAnNeR** [comment]
@ramlmn @andalt the line 1132 is from `imask`.
Probably `webpack` take `es` version of `imask` and does not transpile it properly.
@ramlmn thank you! if you could help, please kindly help him. I dont have time for that kind of issues.

**Comment by andalt** [comment]
@ramlmn  @uNmAnNeR Thank you very much for the answers. You are right.
config - 
module: {
                rules: [{
                    test: /\.js$/,
                    exclude: [/(node_modules)/],
                    loader: 'babel-loader',
                    options: {
                        presets: [
                            ['env', {
                                targets: {
                                    browsers
                                }
                            }]
                        ]
                    }
                }]
            }

babelrc - 
{
    "presets": ["env"]
}

**Comment by uNmAnNeR** [comment]
in short there is a problem in line
`exclude: [/(node_modules)/],`
which also excludes `imask` from transpiling.

Use appropriate regexp to avoid excluding `imask` from `node_modules`.
[This](https://github.com/babel/babel-loader/issues/171) and [that](https://github.com/webpack/webpack/issues/2031) could help.

**Comment by andalt** [comment]
@uNmAnNeR Thank you!
exclude: /node_modules(?!(\/|\\)imask)/, - worked

**Comment by uNmAnNeR** [comment]
nice

**Comment by ramlmn** [comment]
Glad the problem got solved!
