### ISSUE TITLE
Email mask

### ISSUE THREAD

**Issue by mattduffield** [uNmAnNeR/imaskjs#242]
Hi, 

Is it possible to have an email mask that shows the mask as well as well-known parts (e.g. '@' and '.')? I would like for the mask to fire valid only when the mask is satisfied so that I can enable a submit button.

Thanks in advanced,

Matt

**Comment by uNmAnNeR** [comment]
Hi! if not too late.
So you can use pattern with blocks feature, smthg like:
```js
imask({
  mask: 'w@w.w',
  blocks: {
    w: { mask: /\w*/g }  // but probably should be different for each part...
  }
})
```
I don't know how to check if it is valid except using required chars in each part (not regexp), or just you can just apply some regex on each change.
