### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by nassif7** [uNmAnNeR/imaskjs#243]
Can you please add an example how to use one of your guid examples with React.

**Comment by nassif7** [comment]
it would be great if it is the date one. 

Thank you

**Comment by uNmAnNeR** [comment]
@nassif7 here is an example of using react plugin:
https://github.com/uNmAnNeR/imaskjs/tree/master/packages/react-imask

As you can see the main idea is that all mask options are passed as react props instead of an object. That's no more difference.
