### ISSUE TITLE
How to use the pattern d/m/Y 

### ISSUE THREAD

**Issue by Jdeboysere** [uNmAnNeR/imaskjs#246]
Hi there,

I do not understand how to apply the pattern "d/m/Y" on an input, even after reading your documentation and yours examples. I have tried for 2-3 hours, without success.

Can you help please ?

**Comment by uNmAnNeR** [comment]
Hi!
here is an example of using custom patter: https://imask.js.org/guide.html#date
so you just have to provide your own `parse` and `format` props.

**Comment by parkotron** [comment]
also having this issue. The pattern

'm{/}`d{/}`Y' 

results in the input being blocked after xx/xx/xxx (note you can only put in 3 chars for the year and not the expected 4)

**Comment by uNmAnNeR** [comment]
@parkotron this means that you are trying to enter not existed date or date is not in specified min/max bounds

**Comment by luchn49** [comment]
As @parkotron mentions, I just put in 3 chars for the year.
https://codesandbox.io/s/flamboyant-curie-u0g08
