### ISSUE TITLE
Date Mask

### ISSUE THREAD

**Issue by albert9111** [uNmAnNeR/imaskjs#248]
Hi,

When I insert some number inside the day field bigger than 3 it always set 3 because the max number for a day would be 30 or 31. Is there a way to say that when the user insert for example 9 it will be converted to 09 instead of add a 3.

Thanks!

**Comment by uNmAnNeR** [comment]
Hi! currently no way, but looks reasonable to have.

**Comment by EddiDin** [comment]
Приветствую! Столкнулся с таким же вопросом. Во всех остальных случаях imask справился идеально. Не подскажете наиболее рациональный способ все же решить данную задачу? Или все таки нет возможности? Спасибо.

**Comment by uNmAnNeR** [comment]
fixed in 708d2c33097dc0d65f7a5f2260d189321c12b17b with new `autofix: 'pad'` option
