### ISSUE TITLE
Custom Vue Directive which Adds Event Listeners Cancels Out v-on Bound Event when Paired with imaskjs - Happens in Chrome Only

### ISSUE THREAD

**Issue by earnolmartin** [uNmAnNeR/imaskjs#250]
When using Vue custom directives mixed with imaskjs, it appears that the v-on Vue bound event is initially ignored by a change in the value of the imaskjs input.

Here is a complete fiddle example showing this incorrect behavior in Chrome:

http://jsfiddle.net/qrvd7h1g

Change the amount value by adding a number in front of its current value.  Notice how the value isn't updated, and the input field is reverted to its initial value?

Notice this problem doesn't happen in Firefox.

If we do not bind additional events in our custom directive code, it works fine in Chrome as illustrated below:

http://jsfiddle.net/njeorbqg

Is this being caused by imaskjs, Vue, or Chrome itself?

**Comment by g0ld3neag1e** [comment]
I think this issue is similar to the issue I was with the IMaskDirective and Vue. I was able to resolve this by adding `this.el.input.dispatchEvent(new Event('input'));` to the function `updateControl` in the `InputMask` class. See below:

```
key: "updateControl",
                    value: function updateControl() {
                    var newUnmaskedValue = this.masked.unmaskedValue;
                        var newValue = this.masked.value;
                    var isChanged = this.unmaskedValue !== newUnmaskedValue || this.value !== newValue;
                    this._unmaskedValue = newUnmaskedValue;
                        this._value = newValue;
                        if (this.el.value !== newValue) {
                            this.el.value = newValue;
                           ///***     NEW LINE ***///
                            this.el.input.dispatchEvent(new Event('input'));
                        }
                    if (isChanged) this._fireChangeEvents();
                }
```

This will trigger Vue to handle 'input' twice. Because of the way the Vue stack flows, the Vue's input event is handled before the value is changed. Also, there is a bug in Vue where any exernal input trigger is not bound, so we force it.

Hope that helps!

**Comment by uNmAnNeR** [comment]
i bet you know answer better than me. I am not active Vue user, so may be some one else can help. What i can say that what imask does inside is just `el.addEventListener("input", <processing value>);`.

**Comment by g0ld3neag1e** [comment]
Refer to #249 - Possible duplicate
