### ISSUE TITLE
Bug - Vue Model not updating

### ISSUE THREAD

**Issue by g0ld3neag1e** [uNmAnNeR/imaskjs#252]
Because Vue Model is not triggered with external value changes i.e. `element.value = "",` the bound value on Vue is no updated after a mask is complete and if values are entered still.

I found this when using a phone mask "(999) 999-9999". The mask would work fine, but if I hit an extra key after the last character the Vue data would be "(999) 999-9999X".

To solve this, I added updated `InputMask.updateControl` to :

```
function updateControl() {
                    var newUnmaskedValue = this.masked.unmaskedValue;
                        var newValue = this.masked.value;
                    var isChanged = this.unmaskedValue !== newUnmaskedValue || this.value !== newValue;
                    this._unmaskedValue = newUnmaskedValue;
                        this._value = newValue;
                        if (this.el.value !== newValue) {
                            this.el.value = newValue;
                            // If the mask has completed and keys are still entered, manually trigger Vue to update
                            if (this.masked.isComplete) this.el.input.dispatchEvent(new Event('input'));
                        }
                    if (isChanged) this._fireChangeEvents();
}
```

**Comment by chasegiunta** [comment]
@g0ld3neag1e also seeing this. Is the above a fix you can PR?

**Comment by g0ld3neag1e** [comment]
@chasegiunta My fix works as expected if using Directives only, but it creates a glitch if also using the Component side. I found that when using a number mask and deleting the value from the input this creates a loop that produces a max stack error. I mainly was putting this on the radar, as I don't have time to track that issue down. So, for now, I wouldn't want to add it to the main branch.

**Comment by chasegiunta** [comment]
@g0ld3neag1e Cool. I ended up ditching v-model helper for this case, listening input, and doing this as a workaround, with imask's `complete` event:
```
onInput(event) {
      if ((this.maskComplete) && (event.target.value.length > this.mask.mask.length))  {
          return
      }

      this.value = event.target.value
    }
```

**Comment by sem4phor** [comment]
@g0ld3neag1e Can you describe where/how you called this method? I am using the directive and struggeling to get this wokring.

**Comment by uNmAnNeR** [comment]
Hello guys, can you provide some fiddle to run?

**Comment by g0ld3neag1e** [comment]
Refer to "How to Use: 1"

https://jsfiddle.net/g0ld3neag1e/ev8k0goy/

**Comment by g0ld3neag1e** [comment]
@sem4phor I downloaded a local copy of the iMask JS and updated the function I have listed above at line, roughly, 3465.

Hope that helps.

P.S. This is not ideal fix as it causes an error on the component side, and it detaches your project from the cdn and future updates.

**Comment by chasegiunta** [comment]
Here's a codesandbox showing the issue
https://codesandbox.io/s/vue-template-h44nu?fontsize=14

**Comment by sem4phor** [comment]
@g0ld3neag1e thx for your reply :)

I ran into more issues when changing the unmasked value programatically...

So I created a workaround where you only have to add few lines in the directive instead of modifying the core library functions.

Tested for changing unamsked value programatically, normal user input and created hook which changes the input value:

https://codesandbox.io/embed/imask-test-2-tpfg7

But the root cause of the problem is in the function you mentioned (updateControl).

**Comment by g0ld3neag1e** [comment]
@sem4phor take a look at #249, i did pretty much the same thing, just using the InputMask library functions.

**Comment by sem4phor** [comment]
@uNmAnNeR Any idea when its possible for you to look into this and #249? Do you need more informations or how could we help?
