### ISSUE TITLE
Ignore overwrite/placeholder chars

### ISSUE THREAD

**Issue by alexcroox** [uNmAnNeR/imaskjs#253]
I have the following: 

```
mask: {
      mask: '000000000',
      lazy: false,
      overwrite: true,
      autofix: true
}
```

![ss](https://cl.ly/8db9ebda7c88/Screenshot%202019-09-27%20at%2015.31.50.png)

Is there anyway not to make the masked overwrite chars part of the value? If the user enters a character then deletes it the value is set to "_________" which is a pain when it comes to ignoring it in form validation as it's supposed to be empty.

**Comment by uNmAnNeR** [comment]
`unmaskedValue` is exactly for that
