### ISSUE TITLE
feat: Add support for an imask Angular pipe?

### ISSUE THREAD

**Issue by diosney** [uNmAnNeR/imaskjs#256]
That way we can reuse the masks to shown read only unidirectional values.

**Comment by uNmAnNeR** [comment]
can you give some example, not sure i understand this case.

**Comment by diosney** [comment]
Sure!

Look at https://jsdaddy.github.io/ngx-mask-page/main -> Other -> Pipe example, what I'm asking for is exactly like that, but to have it supported directly in this module.

Right now have now to use both of the modules to fulfill all my needs, `angular-imask` for the input fields (it is better than ngx-mask IMO), and the ngx-mask for displaying phones in the templates reusing the mask already set in `angular-imask`.

In the `angular-imask` case, I would expect to feed the `imask` pipe with the same options that are passed now to the input directive, so we can have it defined in only one place and reused everywhere.

Other reference: https://www.npmjs.com/package/ngx-mask

**Comment by diosney** [comment]
Ex:

```
{{ user.phoneNumber | imask:PHONE_MASK }}
```

where `PHONE_MASK` it is something like:

```
export const PHONE_MASK = {
  mask     : '{+1} (000)-000-0000',
  lazy     : false,
  overwrite: true
};
```

That will allow us to reuse masks for both:

- using it at the input fields
- displaying one-way properties in templates (which I think is a common use case too for masks)

**Comment by MatheusRich** [comment]
Up

**Comment by uNmAnNeR** [comment]
@diosney thanks for explanation. This is a nice feature to have i think.

**Comment by uNmAnNeR** [comment]
done in #277
