### ISSUE TITLE
Help Wanted: Date mask with unmasked format different from masked format

### ISSUE THREAD

**Issue by sem4phor** [uNmAnNeR/imaskjs#257]
Hello,

is it possible to have an output format which differs from the mask format.

I need to be able to pass in 'yyyy-dd-MM' dates, display and mask them as 'dd.MM.yyyy' and have the unmasked value in format ''yyyy-dd-MM'. Is this somehow possible?

**Comment by uNmAnNeR** [comment]
hi! `Date` mask has `parse` and `format` options. format is model->view convertion, and parse is view->model. Model is always type of `Date`. So currently it is not possible to get Date in string format that differs from view.

**Comment by sem4phor** [comment]
ok thank you!
