### ISSUE TITLE
Number: signed & min relation

### ISSUE THREAD

**Issue by antiold** [uNmAnNeR/imaskjs#260]
The option `signed` is ignored if `min` is negative. Just pointing, feel free to close.
e.g. https://imask.js.org/guide.html#number

**Comment by antiold** [comment]
Well, I found this https://github.com/uNmAnNeR/imaskjs/issues/213#issuecomment-509576508

**Comment by uNmAnNeR** [comment]
@antiold yep, this is exactly what i want to achieve: either `signed` or one of the bounds is less than zero.
