### ISSUE TITLE
imask.min.js does not work in Chrome 49 on Windows XP

### ISSUE THREAD

**Issue by TiGR** [uNmAnNeR/imaskjs#261]
I know, WinXP is dead. But Chrome 49 is pretty capable browser. Could we fix that?

The error is only in minified version (in `imask.min.js`). Original version (`imask.js`) works fine.

The error is this:

    Uncaught TypeError: Object.getOwnPropertyDescriptors is not a function

**Comment by uNmAnNeR** [comment]
As far as I know there should be no difference between minified and raw version. Anyway you can include any polyfills in your build from Babel or core.js directly, just like imask do.

**Comment by TiGR** [comment]
Seems to be fixed not due to packing, but due to newer version of you library. Sorry to bother.
