### ISSUE TITLE
How to validate a mask with out using event listener

### ISSUE THREAD

**Issue by MonkeyJumps** [uNmAnNeR/imaskjs#263]
Can we add this as an option?

**Comment by MonkeyJumps** [comment]
Do you have an example of usage, where i can call validate after pasting a value against a mask definition?

https://imask.js.org/guide.html#common

> Additionaly to mask option custom validator can be set as validate (value, masked) option for some complex checks on any mask types excluding Function and RegExp, because they are already validators themselves.

**Comment by uNmAnNeR** [comment]
Hi! in my vision validation is a thing that tells if value is correct or wrong with some details sometimes.
But `imask` is a different thing, it tells what parts of a value fits in mask, e.g. `mask('asd123') = 'ad2'`. Of course than we can check if it is exactly equals original value or not, but still that's quite different from conception of validation. If you want just to pass value through mask, then you can use `resolve` method of mask. Is it working for you?
`validate` option of mask is working deep internal in resolving process, not sure if this should be public.

PS may be i'll add something like `IMask.validate` method later which will just `return resolve(value) === value;`
