### ISSUE TITLE
"Mask in mask" case doesn't work for static text after sub-mask.

### ISSUE THREAD

**Issue by ArtemProkopenko** [uNmAnNeR/imaskjs#264]
Hi Alexey (@uNmAnNeR), 

**Expected Behavior:** 
1. Input is inited with an empty value
2. I enter 1100 and see 1,100 €
3. If I press and hold "backspace" I will again see empty value

**Current Behavior:** 
2. I enter 1100 and see 1,100 (without €)

This works great if the static text (currency) stands before the number. For example for "CHF 1,100". Unfortunately, currency quite often writes after the number.

I tried using the option "lazy: false", but the result does not match the behavior in points 1 and 3 (from Expected Behavior).

Example: https://codepen.io/bushart/pen/abbGqjQ

**Comment by uNmAnNeR** [comment]
hi Artem, check this one https://github.com/uNmAnNeR/imaskjs/issues/238

**Comment by ArtemProkopenko** [comment]
@uNmAnNeR , Thank you! It works nice.
