### ISSUE TITLE
Edge\IE bug - Cursor position does not change on focus

### ISSUE THREAD

**Issue by n1k1t0ss** [uNmAnNeR/imaskjs#265]
![Video_2019-11-21_140649](https://user-images.githubusercontent.com/1676900/69315662-9a6aa080-0c69-11ea-8c5e-5996b8b3fb9c.gif)
Tested only on Edge; Works on Chrome. I was able to reproduce it on https://imask.js.org/ 
If edit field was **not focused**, clicking on field doesn't change cursor position. Actually, it restores previous position (before unfocus). 
If edit field is focued - clicking on field changes cursor position correctly.

**Comment by uNmAnNeR** [comment]
Hi! thanks for reporting.
This was done due to https://github.com/uNmAnNeR/imaskjs/issues/162
Currently no ideas how to fix both issues.

**Comment by uNmAnNeR** [comment]
safari seems quite good, so reverted previous fix
