### ISSUE TITLE
Phone number field does not work in Safari

### ISSUE THREAD

**Issue by KelseyDH** [uNmAnNeR/imaskjs#266]
See attached screenshot when I tried to use this library from the demo website.

![Screen Shot 2019-11-26 at 2 07 22 PM](https://user-images.githubusercontent.com/6710303/69676727-31629e80-1056-11ea-973a-1237449d072a.png)

**Comment by uNmAnNeR** [comment]
h1! seems correct. What's wrong with it?

**Comment by uNmAnNeR** [comment]
feel free to reopen ...
