### ISSUE TITLE
Last character of a datetime remains blank/masked

### ISSUE THREAD

**Issue by samstarling** [uNmAnNeR/imaskjs#27]
I'm having an issue where the last character of a datetime is being masked like this, and I can't type into the field any more:

<img width="287" alt="screen shot 2018-01-02 at 13 34 47" src="https://user-images.githubusercontent.com/42478/34483920-bf13e05c-efc1-11e7-935a-4722b42dc546.png">

I've [created a JSFiddle](https://jsfiddle.net/h3au7bjz/) that shows this in action. There's probably something wrong with the way my pattern is set up, but I couldn't work out what it is. Thanks in advance for any help you can give!

**Comment by uNmAnNeR** [comment]
If you use your custom date format you also have to provide your custom `format` and `parse` methods as shown in [guide](https://unmanner.github.io/imaskjs/guide.html#date).

**Comment by samstarling** [comment]
Ah – OK, then it looks like the easiest option is to also use Moment.js, rather than roll my own datetime parsing code. Thanks for the quick reply!
