### ISSUE TITLE
Select date part

### ISSUE THREAD

**Issue by ejuo** [uNmAnNeR/imaskjs#272]
Hello.
Is it possible to implement this behavior? When clicked, automatically select part of the date.
![select_date_part](https://user-images.githubusercontent.com/1243837/69781101-efa93380-11ce-11ea-8929-4b82855ac0d8.gif)

**Comment by uNmAnNeR** [comment]
hi! i don't think this relates to mask.
in js you can track focus and click, then get cursor position and expand selection. So most likely yes, it's possible.
