### ISSUE TITLE
skips the value "0"

### ISSUE THREAD

**Issue by kigl** [uNmAnNeR/imaskjs#273]
Hi, why skips the value "0", although the parameter "min: 1"

`Imask(el, {
  mask: Number,
  min: 1,
  max: 365
});`

[https://codesandbox.io/s/peaceful-keller-v8blo](url)

**Comment by uNmAnNeR** [comment]
thats fine.
max and min bounds are applied on blur.
empty input is zero anyway.
imagine you have min=100 and you still can enter 0, then move cursor to left and enter 10. So on input mask restricts only incorrect number, but does NOT consider min bound. That's correct behavior.
