### ISSUE TITLE
Custom currency mask

### ISSUE THREAD

**Issue by waghcwb** [uNmAnNeR/imaskjs#274]
I need to make a brazillian currency mask, but I can't handle how to do that.

The currency is in the following format:

R$1,00
R$10,00
R$100,00
R$1.000,00
R$10.000,00

Can someone explain how can I achieve that?

I'm trying with the following code, but it doesn't add the cents separator
```js
iMask(this.$refs.value, {
  mask: 'R$num',
  blocks: {
    num: {
      mask: Number,
      thousandsSeparator: '.',
      radix: ',',
      scale: 2,
      signed: false,
      mapToRadix: ['.']
    }
  }
})
```

**Comment by uNmAnNeR** [comment]
seems fine https://jsfiddle.net/uNmAjs/fnojb2t0/

**Comment by waghcwb** [comment]
@uNmAnNeR 
That worked. Thank you!
