### ISSUE TITLE
bug in ie11

### ISSUE THREAD

**Issue by GBcrimson** [uNmAnNeR/imaskjs#28]
Doesn't fire change event in ie11 while length of input more than length of mask. For example,  mask: '+7 (000) 000-00-00' and I wrote 1 11+times

**Comment by uNmAnNeR** [comment]
Mask only fires custom `accept` and `complete` events.
What do you mean by "change" event?

**Comment by GBcrimson** [comment]
default change event

**Comment by uNmAnNeR** [comment]
[reproduce link](https://jsfiddle.net/cgd1vaLb/1/)
Edge is also affected. Probably not a bug with `imask`.

As a workaround use imask `complete` event or `blur` event.
