### ISSUE TITLE
Error with IE 11 on Windows 7

### ISSUE THREAD

**Issue by NibblyPig** [uNmAnNeR/imaskjs#283]
I'm running Windows 7, IE 11.0.9600.19230

When I do a <script> reference to imask.js, it doesn't work.

The error I get is:

> SCRIPT1010: Expected identifier
> File: imask.js, Line: 3754, Column: 23

When I click it, the line is this:

```
	        value: function _update(opts) {
	            // TODO type
>>>	            if (opts.enum) opts.mask = '*'.repeat(opts.enum[0].length);

	            _get(_getPrototypeOf(MaskedEnum.prototype), "_update", this).call(this, opts);
	        }
```

The IE11 debug tools are complete garbage, breakpoints do not work, adding console logs to the source js do not work either. I suspect the error is actually on a different line, but I am not sure. Since this is prior to trying to *use* the javascript - it's simply by referencing it - it must be something this version of IE doesn't support. Trying to use it results in IMask is undefined, presumably because of the error above.

It works fine in other browsers, such as Chrome.

I wonder if anyone has any ideas. I appreciate this is Windows 7 which is old, but unfortunately that's what we run our systems on (hurrah for public sector). Technically, IE11 is still supported.

**Comment by uNmAnNeR** [comment]
Hi! this fiddle with enums https://jsfiddle.net/uNmAjs/d90rgv6m/1/ does work on my IE 11.535.18362.0.
IMask ships with polyfills, `String.repeat` is included.
Try to turn off source maps (or just remove them locally) and check exact line with error.

**Comment by NibblyPig** [comment]
Thanks for your reply - I really appreciate your help. That fiddle does work for me as well. I thought maybe it was the jquery version, as I'm using 1.12.4, but changing your example to that, it still works.

I don't think I have source maps on, if I point to a local copy of the JS file, and remove the last line referencing source paths (I don't have the .map file anyway).

I'm not really sure how to debug this further because the developer tools in IE11 seem to be so bad, I can't put any breakpoints in.

**Comment by NibblyPig** [comment]
Ooh, I may have got it to show me:

`var n=Sys.Extended.UI.MaskedEditBehavior.prototype`

> Unable to get property 'prototype' of undefined or null reference

`MaskedEditBehavior` is undefined.  Could that mean something?

**Comment by uNmAnNeR** [comment]
> MaskedEditBehavior is undefined. Could that mean something?

seems not related to imask

**Comment by NibblyPig** [comment]
Thanks you've helped me to solve it.

Some joker had put this on the master page:

`<meta http-equiv="X-UA-Compatible" content="IE=8" /> <!-- force IE8 standards mode -->`

You can delete this issue if you want. Sorry and thanks for your help.

**Comment by uNmAnNeR** [comment]
Cool, you are welcomed
