### ISSUE TITLE
[Vue] "overwrite" option is not available in dynamic mask

### ISSUE THREAD

**Issue by zefexdeveloper** [uNmAnNeR/imaskjs#285]
In Brazil we have a phone number like this: `(00) 0000-0000` but we also have numbers that have one more number `(00) 00000-0000` so it would be something like `'(00) 0000-0000', '(00) 00000-0000'`.

I tried to `:mask="[{ mask: '(00) 0000-0000' }, { mask: '(00) 00000-0000' }]"` but it's returning this warning on the console: `"overwrite" option is not available in dynamic mask, use this option in siblings` and the masking is not working

**Comment by uNmAnNeR** [comment]
hi @zefexdeveloper! there were 2 bugs i found and fixed during investigation. thanks for reporting

**Comment by zefexdeveloper** [comment]
@uNmAnNeR Thank you very much. So I can just install again and it will be working?

**Comment by uNmAnNeR** [comment]
it will be in new release in a few days, i want to fix some more bugs before releasing. But fix already is in master branch.

**Comment by zefexdeveloper** [comment]
@uNmAnNeR Thank you very much, when it's released I will be upgrading.

**Comment by uNmAnNeR** [comment]
@zefexdeveloper check it out!

**Comment by zefexdeveloper** [comment]
@uNmAnNeR Thank you very much, you rock. It's working like a charm.

**Comment by fcandiani** [comment]
@uNmAnNeR I don't know if there was a breaking change but I tried with 6.0.1 ("vue-imask": "^6.0.1") and the mask does not change automatically

**Comment by fcandiani** [comment]
Nevermind, manage to get it working by using dispatch

**Comment by AlyonaPianykh** [comment]
@fcandiani Hello! Could you please share how did you fix this with dispatch?
