### ISSUE TITLE
Add TypeScript typings to the vue-imask package

### ISSUE THREAD

**Issue by mpaluchowski** [uNmAnNeR/imaskjs#286]
Could we also have TypeScript typings for the `vue-imask` package? The ones for `imask` don't cover elements like the `IMaskDirective`.

**Comment by uNmAnNeR** [comment]
nice to have. i'd even prefer to have sources in typescript rather than typings.

**Comment by sockenklaus** [comment]
Are there any news to this issue?

**Comment by antonreshetov** [comment]
Wow, that was a long time ago, and it looks like it's going to be a long time before that happens.

**Comment by vaban-ru** [comment]
Some news about this?

**Comment by uNmAnNeR** [comment]
fixed by https://github.com/uNmAnNeR/imaskjs/pull/858/commits/2c21f5a0fa761d13120c0c5ca4e5478f4b651107
but seems like the only thing that make sense in case of types for Vue is `Composable`. Component/Directive types are useless.
