### ISSUE TITLE
Angular 9, ivy support

### ISSUE THREAD

**Issue by glebmachine** [uNmAnNeR/imaskjs#288]
After install `angular-imask` on blank ng9rc8 project got this error:

```
...
Compiling angular-imask : module as esm5
Compiling @angular/forms : module as esm5
Compiling @angular/forms : main as umd
Compiling angular-imask : es2015 as esm2015
Compiling angular-imask : main as umd
Compiling angular-imask : module as esm5
Error: Error on worker #2: Error: Tried to overwrite .../node_modules/angular-imask/dist/fesm5/angular-imask.js.__ivy_ngcc_bak with an ngcc back up file, which is disallowed.
    at InPlaceFileWriter.writeFileAndBackup (...\node_modules\@angular\compiler-cli\ngcc\src\writing\in_place_file_writer.js:36:23)
    at ...\node_modules\@angular\compiler-cli\ngcc\src\writing\in_place_file_writer.js:30:69
    at Array.forEach (<anonymous>)
...
```

As you can see in log above it tries to compile library twice

Repro:
1. Generate empty repo with cli
2. ng update --next (to install latest deps)
3. add `angular-imask`
4. gotcha

**Comment by glebmachine** [comment]
This is because you've got 2 `package.json` files:
One in root, and another in `/dist` folder, and both points to same files. Which point ngcc to recompile each of them 2 times.

**Comment by glebmachine** [comment]
Could you please remove redundant dist/package.json file from `angular-imask`? @uNmAnNeR

**Comment by uNmAnNeR** [comment]
hi! in that case i completely rely on [ng-packagr](https://github.com/ng-packagr/ng-packagr)
what i can do is just update it. but i see they decided to go side by side with Angular versions. But 9 is still not released. So i can update `ng-packagr` from 5.3.0 to 5.7.0 if it solves the problem.

**Comment by glebmachine** [comment]
@uNmAnNeR To fix it - just distribute dist folder (not root folder, with dist inside)

**Comment by uNmAnNeR** [comment]
@glebmachine it does not work this way, because of using `lerna` https://github.com/lerna/lerna/issues/1282#issuecomment-387918197

**Comment by uNmAnNeR** [comment]
seems they added support https://github.com/lerna/lerna/tree/master/commands/publish#--contents-dir eventually
i need time to investigate

**Comment by glebmachine** [comment]
It will be awesome! Thank you)
