### ISSUE TITLE
[VUE] display masked as filter

### ISSUE THREAD

**Issue by zefexdeveloper** [uNmAnNeR/imaskjs#289]
I have the field with the mask, save this information on the database unmasked but now I need to display this masked in a `<p></p>`. I was wondering, is it possible to mask as a filter like: `{{ message | capitalize }}` but for the mask?

- https://vuejs.org/v2/guide/filters.html

**Comment by uNmAnNeR** [comment]
Vue filter is just a function, so you can wrap `IMask.pipe` : https://imask.js.org/guide.html#pipe

**Comment by zefexdeveloper** [comment]
@uNmAnNeR I'm not that advanced with Vue so I have no idea on how to do that, can you please help me out on this? Thank you

**Comment by uNmAnNeR** [comment]
@zefexdeveloper try this https://jsfiddle.net/uNmAjs/p7ub3zgv/
https://stackoverflow.com/ is a nice place to ask questions. I really have no time, because of fulltime job, family, children, etc...
I think definitely wil add an example to readme for Vue-IMask.
thanks

**Comment by zefexdeveloper** [comment]
@uNmAnNeR Thank you very much, it helped a lot.
