### ISSUE TITLE
Way of getting raw input value

### ISSUE THREAD

**Issue by mungurs** [uNmAnNeR/imaskjs#29]
Is there a way to get inputs value (raw) that was entered before formatting?

**Comment by uNmAnNeR** [comment]
[Just use](https://jsfiddle.net/Lm7f9zao/) regular `input` event.
Also you can get raw input value in `prepare` mask callback.
Of course there is no accumulated history inside mask.
If you want to get input during masking process you could also inherit from Masked.

**Comment by mungurs** [comment]
Thank you!
