### ISSUE TITLE
Missing last char with custom parse/format options

### ISSUE THREAD

**Issue by karlomikus** [uNmAnNeR/imaskjs#293]
I'm using date mask with moment formatting and parsing.
When I use this pattern: `'DD. MM. YYYY.'` the mask is always missing last char, but when I use `'DD. MM. YYYY'` or `'DD. MM. YYYY. HH:mm'` everything works fine.

Here's an example: https://codepen.io/eggzy/pen/QWwYMJV

**Comment by uNmAnNeR** [comment]
that's a bug! thanks for reporting

**Comment by cesarp** [comment]
I have the same problem with a custom mask, no moment.

https://jsfiddle.net/5jo03t2u/3/

**Comment by uNmAnNeR** [comment]
> I have the same problem with a custom mask, no moment.
> 
> https://jsfiddle.net/5jo03t2u/3/

no, you just have not read the guide. You have to provide parse/format if `pattern` is set

**Comment by kl3sk** [comment]
This looks not fixed
