### ISSUE TITLE
Callback on input wrong char

### ISSUE THREAD

**Issue by werty1001** [uNmAnNeR/imaskjs#294]
Привет, спасибо за плагин, в доках не нашел ответа, есть ли возможность вызывать cb при вводе недопустимого символа? Что-то типо:

`mask.on('wrong', char => alert('Вы ввели недопустимый символ ${char}'));`

**Comment by uNmAnNeR** [comment]
привет, потому что нету такого. Добавлять не планирую. Вроде и так понятно раз не добавился значит что-то не то))))
Но если очень надо, могу посоветовать добавить свое состояние и на onInput смотреть добавилось что-то или нет. Причем брать из mask.masked.rawInputValue - там все пользователь натыкал лежит.
