### ISSUE TITLE
React-imask don't work with InputGroup from blueprintjs

### ISSUE THREAD

**Issue by OliverWall** [uNmAnNeR/imaskjs#295]
Hi, im trying to use react-imask with component [InputGroup](https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/forms/inputGroup.tsx) from [blueprintjs](https://blueprintjs.com/) libriary but i get error.

TypeError: Cannot read property 'isContentEditable' of undefined
new InputMask
node_modules/imask/esm/controls/input.js:40
> 40 |   this.el = el instanceof MaskElement ? el : el.isContentEditable && el.tagName !== 'INPUT' && el.tagName !== 'TEXTAREA' ? new HTMLContenteditableMaskElement(el) : new HTMLMaskElement(el);

As I understand it react-imask wait only input or texarea, what can I do to get them started working together? It would be cool if there was a certain "rendererItem" property and you could pass a component to it . In fact, I'm trying to do it. I need to use your library in many places and I always have to use different components

Simplified code example 
```
import { IMaskMixin } from 'react-imask';
import { InputGroup } from '@blueprintjs/core';

const MaskedInput = IMaskMixin(({ inputRef, ...props }) => (
  <InputGroup {...props} innerRef={inputRef} />
));

<MaskedInput
      mask={masks}
      onAccept={(value: string, mask: any): void => console.log(value, mask)}
      placeholder="+7(909)302-00-00"
/>
```

Thanks for any help !

**Comment by uNmAnNeR** [comment]
hi, but why are you using `innerRef` instead of `inputRef`? seems like `blueprint` uses `inputRef`: https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/forms/inputGroup.tsx#L123

**Comment by OliverWall** [comment]
Ohhh, thank you very much. My bad. 
I was already starting to think that react-imask only accepts input or textarea, and InputGroup has a div wrapper over input.
Thank you again!
