### ISSUE TITLE
`TypeError: undefined is not an object (evaluating this.globalThis = this)` on Safari 11 and below

### ISSUE THREAD

**Issue by theVeid** [uNmAnNeR/imaskjs#296]
Related to https://github.com/uNmAnNeR/imaskjs/issues/290,
and this is **not** the [@ungap/global-this](https://github.com/ungap/global-this/) issue.
Please take a look at this [discussion](https://github.com/ungap/global-this/issues/7)

**Comment by uNmAnNeR** [comment]
I've seen it, but can't find something usefull. I followed the guide and done as described:
`ESM as import '@ungap/global-this'` in https://github.com/uNmAnNeR/imaskjs/blob/master/packages/imask/src/index.js#L1

I checked compiled (and minified) code and was not able to find any issues:
```js
function(t) {
    function e() {
        this.globalThis = this, delete t.prototype._T_
    }
    "object" != typeof globalThis && (this ? e() : (t.defineProperty(t.prototype, "_T_", {
        configurable: !0,
        get: e
    }), _T_))
}(Object);
```
So i also can't confirm that a bug is in IMask. Please let me know if i am wrong.

**Comment by cvaize** [comment]
@uNmAnNeR Please accept the pull request and rebuild dist for npm
