### ISSUE TITLE
Allow for empty string using field definitions

### ISSUE THREAD

**Issue by MonkeyJumps** [uNmAnNeR/imaskjs#299]
I have created some field definitions

```
export function getRegExInputMaskDefinitions(inputMask) {
  return {
    mask: inputMask,

    definitions: {
      "#": /[0-9]/,
      A: /^[a-z0-9]+$/i,
      a: /^[a-z0-9]*$/i,
      "9": /^[\d ]*$/,
      "&": /[ -~]/,
      C: /^[\s\d]*$/,
      "?": /^[a-z]+$/
    }
  };
```
```
then i create a mask using the field defintions.
`      masked = IMask.createMask(
        getRegExInputMaskDefinitions(fieldDefinition.InputMask)
      );
 masked.value = field.Value || "";
  const isInputMaskValid = masked.isComplete;

`
```
When inputMask = C 
which allows for empty string, masked.isComplete is always false when masked.value =""
How do I allow for it to accept empty string in this case using field definitions?

This seems to be related to issue #21  however even after i type a valid value then remove it leaving just an empty string the regex is still invalid.

**Comment by uNmAnNeR** [comment]
definition should always match single character, no matter is it optional or not.
Optional characters inside mask should be inside brackets `[` `]`.
