### ISSUE TITLE
Angular ImaskJs

### ISSUE THREAD

**Issue by howtomake** [uNmAnNeR/imaskjs#30]
Привет
```
public ngOnInit() {
this.phoneMask = [
            {
                mask: '+{380} (00) 000-00-00',
                startsWith: '38',
                country: 'Украина',
            },
            {
                mask: '+{7} (000) 000-00-00',
                startsWith: '7',
                country: 'Россия',
            },
            {
                mask: '00000000000',
                startsWith: '',
                country: 'undefined'
            }
];
        this.superPhone = new IMask(document.getElementById('last_phone'), {
            mask: this.phoneMask,
            lazy: false,
            placeholderChar: '_',
            dispatch(appended, dynamicMasked) {
                let numbers = (dynamicMasked.value + appended).replace(/\D/g, '');
                return dynamicMasked.compiledMasks.find(function (m) {
                    return numbers.indexOf(m.startsWith) === 0;
                });
            }
        });
}
```

маска работает
и placeholder не отображается...(

если вывожу в разметке

```
<input type="text" name="phone" id="last_phone"
       formControlName="userPhone"
       [imask]="{
            mask: [
                {
                    mask: '+{380} (00) 000-00-00',
                    startsWith: '38',
                    country: 'Украина'
                },
                {
                    mask: '+{7} (000) 000-00-00',
                    startsWith: '7',
                    country: 'Россия'
                },
                {
                    mask: '00000000000',
                    startsWith: '',
                    country: 'undefined'
                }
            ],
            placeholderChar: '_',
            lazy: false
       }"
       class="ff-input"
       (focus)="focusTempString = 'userPhone'"
       (blur)="focusTempString = ''"
>
```

та же штука, тока маска странно работает

подскажите, что я делаю не так?

**Comment by uNmAnNeR** [comment]
сделай плз на `jsfiddle` или форматни хотя бы, старый стал, не разберу

**Comment by howtomake** [comment]
да так ок работает, тока если в разметке)
а после обновлений сегодняшних перестало вобще работать))
можете добавить демку для angular'a ?? очень хочется Ваш скрипт использовать, круче нету пока
пс. могу задонатить напишите тока куда)

**Comment by uNmAnNeR** [comment]
Погоди, давай разбираться.
Первое. Сегодняшние обновления были про Vue и немного про React, плюс версию я не обновлял. Вообще не представляю как тебя могло зацепить.
Для Angular есть [плагин](https://github.com/uNmAnNeR/imaskjs/tree/gh-pages/plugins/angular). Посмотри, даже если тебе в чистом виде не подойдет, то можешь взять за основу. Я сам использую его в своих проектах.
Про донат нечего сказать, дело добровольное. Я помогаю чем могу, но на работу меня взять не получится, обещать не буду.

**Comment by howtomake** [comment]
Подразобрался слегка.. работает
_короче placeholder не отображается в динамической маске_
_и нельзя нажать "+" если не в разметке указывать маску_
если в первой маске массива выбирать **startsWith: ''** то placeholder отображается только ничего ввести не получается поэтому от динамики временно отказался [добавьте параметр плз - эта маска prefer и ее показывать в начальном состоянии]
без динамики все круто
в идеале хотелось чтобы в начальном состоянии было вот так например 
[http://andr-04.github.io/inputmask-multi/en.html](url)
и по мере ввода подстраивалась нужная маска

**Comment by uNmAnNeR** [comment]
@howtomake  Про placeholder походу баг.
На счет `prefer` - уже есть колбек `dispatch`, где можно вернуть любую маску, которая будет использована. Еще один атрибут `prefer` на эту же тему излишен.

**Comment by howtomake** [comment]
@uNmAnNeR да dispath работает на ура
placeholder нет(

**Comment by uNmAnNeR** [comment]
@howtomake я запилил сборку, она сырая, выкладывать пока не буду. Если есть желание - могу скинуть - посмотришь.

**Comment by howtomake** [comment]
круто! Спасибо большое!

**Comment by ivan-kocherga** [comment]
I have this problem now too
![image](https://user-images.githubusercontent.com/55404560/97573651-2ac56f80-19fb-11eb-9df1-1afbd2a92bb5.png)
