### ISSUE TITLE
Append a symbol € after the masked number value

### ISSUE THREAD

**Issue by raphaelbadia** [uNmAnNeR/imaskjs#302]
Hello,

First thanks for this library, it's amazing !

I want to do a curreny input and I saw the example, but in my country the currency tag goes after the price.

![CleanShot 2020-02-13 at 19 55 41](https://user-images.githubusercontent.com/1901628/74468267-d729ea80-4e9a-11ea-9e89-bd9882ad9cd6.png)

So instead of `mask: '$num'`, I tried to do `mask:num€` but when typing, the € sign won't show up as we're in the Number block.

Putting the ` lazy` option to false makes the € appear, but then I don't have the placeholder anymore.

In an ideal world, the € sign should appear only on focus. Would that be possible ?

I could write a workaround to put the `lazy` option dynamically, but it doesn't feels right...

Thanks !

**Comment by uNmAnNeR** [comment]
Hi! you are welcome :)

your case is here:
https://jsfiddle.net/uNmAjs/ayq9u631/

**Comment by raphaelbadia** [comment]
Thank you, it's perfect !

**Comment by grantiverson** [comment]
I am running into a similar issue, but it cannot be resolved with the solution above. I am trying to make inputs with masks for various currency settings. I need to have combinations of the following settings:
1) `thousandsSeparator`
    a) `,`
    b) `.`
    c) `'`
    d) ` ` (space)
2) `radix`
    a) `.`
    b) `,`
3) Currency symbol: unrestricted string (e.g. `$`, `€`, or `AUS`)
4) Ability to place currency symbol before or after the amount.

Here is the function I am using to generate the config options.
```
/**
 * @function currency
 * @param {object} currency formSettings.currency object
 * @param {string} currency.format Correlates to currency format in form settings (e.g. US Standard: 1,234,567.89)
 * @param {string} currency.symbolLocation Indicates whether currency symbol should go before or after amount
 * @param {string} currency.symbol Currency symbol string
 * @returns {object} imask config object for currency inputs
 * @description Gets imask config based on form settings
 */
currency: (currency) => {
    const { format, symbolLocation, symbol } = currency;
    const symbolBefore = symbolLocation === "0";
    let mask;
    let thousandsSeparator;
    let decimalSymbol;

    switch (format) {
        case "1": {
            thousandsSeparator = ".";
            decimalSymbol = ",";
            break;
        }
        case "2": {
            thousandsSeparator = "'";
            decimalSymbol = ",";
            break;
        }
        case "3": {
            thousandsSeparator = " ";
            decimalSymbol = ",";
            break;
        }
        default: {
            thousandsSeparator = ",";
            decimalSymbol = ".";
        }
    }

    mask = `${symbolBefore ? symbol : ""}dollars[{${decimalSymbol}}cents]${
        !symbolBefore ? " " + symbol : ""
    }`;

    return {
        inputMode: "decimal",
        mask,
        blocks: {
            // E.g. "$9,876,543.21"
            dollars: {
                mask: Number,
                signed: false,
                thousandsSeparator,
            },
            cents: {
                mask: "00",
                signed: false,
            },
        },
    };
}
```

**Comment by bfeister** [comment]
@grantiverson  did you ever get this working? I have the same use case you do
