### ISSUE TITLE
value should be string

### ISSUE THREAD

**Issue by odione** [uNmAnNeR/imaskjs#304]
"value should be string" still occours, if set number value to input with imask (angular)

**Comment by uNmAnNeR** [comment]
just use unmask="typed"

**Comment by odione** [comment]
> just use unmask="typed"

not working for number values. If set number value (without quote) to model error still occours

**Comment by GitNomster** [comment]
Same problem to me. Tried to set number to value. Unmask="typed" does not help.

**Comment by uNmAnNeR** [comment]
@GitNomster check https://jsfiddle.net/uNmAjs/cxzqhrbg/
what the problem did you get exactly?
can you also please provide some fiddle with problem scenario?

**Comment by odione** [comment]
[angular] check https://stackblitz.com/edit/angular-gqzf8z?file=src%2Fapp%2Fapp.component.html

error occours when mask has blocks with 'Number', even [unmask]=" 'typed' "

**Comment by uNmAnNeR** [comment]
@odione i've already answered about it here https://github.com/uNmAnNeR/imaskjs/issues/236#issuecomment-559705443
Parent mask knows nothing about nested blocks, so it can't work with typed value out of box.
In the link is working example how to achieve it. Currently no more plans to fix it other way.
