### ISSUE TITLE
I can't type the last character of the date mask

### ISSUE THREAD

**Issue by emanuellucascomp** [uNmAnNeR/imaskjs#306]
In the example available in the documentation, in the date mask demo (https://imask.js.org/guide.html#masked-date), I cannot type the last character. I tested it on a CodePen (https://codepen.io/emanuellucascomp/pen/gOpMRaX) and noticed the same error. Tested on Firefox (version 72.0.2) and Chrome (version 74.0.3729.157)

![image](https://user-images.githubusercontent.com/24272264/74746858-d3081f00-5244-11ea-9fc4-9d07d83cc05e.png)

**Comment by uNmAnNeR** [comment]
In a guide, there is `max` option on date: `max: new Date(2020, 0, 1), `, which is less then november.
Please read the note https://imask.js.org/guide.html#masked-date before using date mask with custom patterns.
