### ISSUE TITLE
patch 6.0.3, ie 11, "globalThis"

### ISSUE THREAD

**Issue by zavod008** [uNmAnNeR/imaskjs#307]
![image](https://user-images.githubusercontent.com/20419214/74827765-64e85880-5327-11ea-8fa7-33d4be68ef66.png)

![image](https://user-images.githubusercontent.com/20419214/74827902-9a8d4180-5327-11ea-8823-7cac54246965.png)

I rolled back to version 6.0.1, everything worked there.

**Comment by uNmAnNeR** [comment]
only umd builds contains polyfills,
if you are using bundlers you have to provide polyfills by your own. You can find all required polyfills to work with IE here: https://github.com/uNmAnNeR/imaskjs/blob/master/packages/imask/src/polyfills.js

**Comment by mises543** [comment]
You need to update Node.js to v12+ answear is here: https://stackoverflow.com/questions/64917442/angular-11-run-on-ssr-nguniversal-express-engine-referenceerror-globalthis-is/64932085#64932085
