### ISSUE TITLE
If using mapToRadix creates bug

### ISSUE THREAD

**Issue by SemmelJochen** [uNmAnNeR/imaskjs#309]
Hi again,
I found another problem where I can not use a thousand separator and a radix combined with mapToRadix.
For the value I am using the toLocaleString() method because otherwise the default input values decimal separator would be recognized as a thousands separator in the mask.

Steps to reproduce the problem:
1. go to: https://codesandbox.io/s/imaskinputbugexample-3wqcp?fontsize=14&hidenavigation=1&theme=dark

2. backspace the default input value and type another value longer than 3 digits (that you see a thousands separator (otherwise it will work))

3. try to enter a radix and decimal separator. (It wont work) <--

I hope someone can fix this.

**Comment by uNmAnNeR** [comment]
@SemmelJochen hi! sorry cant reproduce your example.
Even if i uncomment imask usage still seems to work correctly.
Please provide some more details/examples, better if unnecessary details will be skipped. And feel free to reopen this issue.
