### ISSUE TITLE
Styles for date placeholder

### ISSUE THREAD

**Issue by Qunkero** [uNmAnNeR/imaskjs#310]
Hi. Could you please help, if it is possible to change styles for mask's placeholder(delimiters).

![image](https://user-images.githubusercontent.com/15861798/75155406-aa869600-5718-11ea-8efe-35f5bcaa6b8e.png)

**Comment by uNmAnNeR** [comment]
Hi! mask placeholder is just input text. So i don't think it's possible. But this is not a subject of this library.  If you are really need it, then probably could use custom span over input with styling.
