### ISSUE TITLE
Angular 9 + Microsoft Edge throwing error 'globalThis' is not defined 

### ISSUE THREAD

**Issue by raygig** [uNmAnNeR/imaskjs#312]
In Angular 9 and in Microsoft Edge 44.18362.449.0 getting the error:

 `'globalThis' is not defined `

Which comes from:

`globalThis.IMask = _imask_js__WEBPACK_IMPORTED_MODULE_18__["default"];`

**Comment by uNmAnNeR** [comment]
answer is here: https://github.com/uNmAnNeR/imaskjs/issues/307#issuecomment-588173187
