### ISSUE TITLE
Hide mask characters, which not in curly brackets

### ISSUE THREAD

**Issue by qramilq** [uNmAnNeR/imaskjs#317]
Hi, thanks for your beautiful component `react-imask`
I want to hide mask characters, which not in curly brackets in Pattern mask.
In demo https://imask.js.org/guide.html#masked-pattern if you check 'lazy placeholder' checkbox and Apply, you can erase all input's value, except # symbol, because it in curly brackets in `mask`.
But when using `<Imask/>` component. the mask shown full, no matter, in curly brackets text or not. (expected: 'NIC' string is hide, reality: 'NIC' string shown
[Sandbox](https://codesandbox.io/s/boring-river-0iexy)
Thank's

**Comment by uNmAnNeR** [comment]
hi! You are welcome.
In a guide toggling 'lazy placeholder' also allows to delete "#" symbol as well.
In react sandbox i set `lazy={true}` and get exactly the same behaviour as in a guide.
Symbols in curly brackets are included in unmasked value, but it should not affect appearing in input.
