### ISSUE TITLE
React IMaskInput's onChange listener called inconsistently

### ISSUE THREAD

**Issue by grantiverson** [uNmAnNeR/imaskjs#318]
I am building an app using `react-imask` and the `<IMaskInput>` component. With the following props being passed:
```
<IMaskInput
    id={id}
    name={name}
    className={className}
    value={value}
    onChange={onChange}
    onBlur={onBlur}
    onFocus={onFocus}
    type="text"
    ref={ref}
    masktype={type}
    mask={Number}
    thousandsSeparator=","
/>
```

When typing into the input, the first character _does not_ trigger the `onChange` listener to be called. The second and third characters _do_ trigger `onChange`. And then any other characters input again _do not_ trigger the listener. (Once there is a `thousandsSeparator` `onChange` doesn't get called anymore.)

If I remove `thousandsSeparator: ','` the first character still _does not_ trigger the `onChange` listener to be called. However, all subsequent characters _do_ trigger `onChange`.

**Comment by uNmAnNeR** [comment]
please provide full example which i can run and help you then. You can use something like https://jsfiddle.net/

**Comment by grantiverson** [comment]
Here is an example of the behavior I'm seeing: https://codesandbox.io/s/tender-hawking-h7cb3

**Comment by uNmAnNeR** [comment]
thanks. `onChange` does not work in case of mask, so you have to use `onAccept`:
https://codesandbox.io/s/affectionate-lamarr-puqnt

**Comment by grantiverson** [comment]
Thanks for getting back to me so quickly. I have some unmasked inputs and was trying to use the same function to handle both the masked and unmasked with the same onChange function. Since onAccept doesn't return a SyntheticEvent I guess I'll just have to handle the inputs separately.

**Comment by uNmAnNeR** [comment]
Yes, unfortunately. React `onChange` is not fired when value in input is manually changed.

**Comment by uNmAnNeR** [comment]
Hm, but i can call `onChange` side by side with `onAccept`. Let me do this in next release.

**Comment by uNmAnNeR** [comment]
Hm, i tried to simulate `onChange` event and run into some problems.
Unlike `onAccept` `onChange` callback has SyntheticEvent parameter as you mentioned.
So there should be some way to pass this event, but react-imask is just a wrapper around imask core, which does not know about React SyntheticEvents. Actually input event is not poped up from imask core at all. Ok, i can make it work, but it will not be SyntheticEvent, it will be just vanilla Event.
@grantiverson **Does this really work in your case?**
Second thing is that `onAccept` fires not only on input event, but also when value prop is changed. Probably i can just remove this stuff... After all `onChange` event is not fired on prop changed, so it is acceptable.

**Comment by Allegathor** [comment]
@uNmAnNeR 
Hello! I've faced the same issue as TS. I think it would be perfect solution to have synthetic event passed to `onChange`. Plain JS event is a little bit worse, but it's still better than nothing.

What are the cases with undefined?

**Comment by uNmAnNeR** [comment]
@Allegathor there is no legal way to create SyntheticEvent manually, so no ideas how it can be done.

> What are the cases with undefined?

value is changed on app side and passed to component with mask, but value does not satisfy mask, so mask changes value, and fires `onAccept`

**Comment by Allegathor** [comment]
@uNmAnNeR I guess, in my case it won't be a problem. Maybe it should be discussed with others

**Comment by grantiverson** [comment]
@uNmAnNeR I was able to get my situation to work using onAccept. It's not the cleanest solution, but it is working for now. I need the element to update when props are changed, so this may be the only way to get it working for my situation.

On accept I am calling the `onChange` function passed to my element.
```
<IMaskInput ... onAccept={(val, QMask) => props.onChange(val, QMask)} ... />
```

The change function is being reused for this and several other non-masked inputs. I just have to do a bit of an awkward check to get the correct "target" element. I say awkward because in cases with a non-masked input, `e` is a SyntheticEvent, but when the input uses IMask, `e` is the input's value and doesn't have a `target`, so we fall back to the mask object. Here is a simplified version of what I'm doing.
```
const handleChange = (e, IMask) => {
    const target = e.target || IMask.el.input;
    setState({
        ...state,
        [target.name]: target.value
    });
};
```

**Comment by icaroponce** [comment]
@uNmAnNeR @grantiverson the problem with the solution provided above is that `onAccept` will be triggered even when the input wasn't manually changed but received a prop `value`, which will then trigger `onChange` as well. (What doesn't happen with `onChange`, because well, the input wasn't really changed).

In many cases this isn't a problem, in situations like me though, the `onChange` triggers also other events like `form.onFieldChanges` (when using it within a form component), which is giving me some headaches.

It'd be great to have something similar to onChange, like an `onAccept` but that's only triggered when the field is manually changed, not when the component was initialized with a value different than `undefined`.

**Comment by bfeister** [comment]
I'm suspecting that there's a bug in here somewhere, beyond just the issue with React synthetic events, etc. That inconsistency I don't think would explain why `mask: '$num'` would work while `mask: 'num%'` does not in this example:

https://github.com/uNmAnNeR/imaskjs/issues/486

**Comment by francosalcedo** [comment]
Hi, I managed to somehow get the onChange to work. here my example using react-datepicker

I run the onChange I receive from Props and pass a mock onchange event to it.

`
  return <>
    <IMaskInput
      mask={`d/m/Y`}
      autofix={true}
      lazy={false}
      blocks={{
        d: {mask: IMask.MaskedRange, placeholderChar: 'D', from: 1, to: 31, maxLength: 2},
        m: {mask: IMask.MaskedRange, placeholderChar: 'M', from: 1, to: 12, maxLength: 2},
        Y: {mask: IMask.MaskedRange, placeholderChar: 'Y', from: 1900, to: 2022, maxLength: 4}
      }}
      ref={ref}
      onAccept={
        (value: any) => {
          if (!name) return

          let dateSplit = value.split('/')
          let date = new Date(+dateSplit[2], dateSplit[1] - 1, +dateSplit[0])

          if (!isValidDate(date)) return
          if (!rest.onChange) return

          rest.onChange({
              target: {
                value: date
              }
            } as unknown as ChangeEvent<HTMLInputElement>
          )

          return true
        }
      }
      name={name}
      {...rest}
    />
  </>`

**Comment by felicandalc** [comment]
How does that solve the problem of initial value not manually setted but still triggerring onChange?

**Comment by uNmAnNeR** [comment]
@icaroponce @felicandalc a bit outdated but seems like it's possible to determine if the change was triggered by user or not by checking the last parameter of `onAccept(value, ref, event)` the last parameter `event` is not null if the change was triggered by user input. I will close this issue for now but you can reopen it again if more things are still need to be clarified/fixed.

**Comment by kneczaj** [comment]
The problem with `onAccept` is that it is not triggered on backspace button. In case the user removes one character the form should be informed about it e.g. to show validation error, but I see no way to do it.
