### ISSUE TITLE
React Native IMaskTextInput not working in the Expo

### ISSUE THREAD

**Issue by Kladislav** [uNmAnNeR/imaskjs#319]
I used code samples from your examples, app gets the error:
``setSpan(4 .. 4) end beyond length 3``
any idea how can i fix this? 
Thank you.

**Comment by uNmAnNeR** [comment]
hm, i definetely do not use `setSpan` in plugin. Actually, i have no idea.
I even can say that react native plugin is not production ready. And probably will never be until either react native will have consistent input events or somebody will write native bridge to plugin. So don't count on it now.

**Comment by samuelpetroline** [comment]
The error actually comes from expo (https://github.com/expo/expo/issues/8071) but the cause seems to be the delayed selection.

https://github.com/uNmAnNeR/imaskjs/blob/6adc0901e18789f5fec00fcf4bec7011b87943f5/packages/react-native-imask/src/native-mask-element.js#L41-L49

Just a guess, though.
