### ISSUE TITLE
BAG VueJS SyntaxError Unexpected string

### ISSUE THREAD

**Issue by chelkaz** [uNmAnNeR/imaskjs#320]
node_modules/vue-imask/dist/vue-imask.js:2:83
node_modules/vue-imask/dist/vue-imask.js:5:2

**Comment by uNmAnNeR** [comment]
hi. just have checked on latest chrome and ff and it does work. Provide more details, and also the cause could be https://github.com/uNmAnNeR/imaskjs/issues/313
