### ISSUE TITLE
React Material-UI after setState this.el is undefined.

### ISSUE THREAD

**Issue by fluflo** [uNmAnNeR/imaskjs#321]
I try to integrate the react-imask plugin into my material-ui input component. When I try to set the value of my state, the control loses the position of the cursor and I get an error this.el is undefined. Following an example on [codesandbox](https://codesandbox.io/s/pedantic-bohr-47cj4)

**Comment by uNmAnNeR** [comment]
you have to move your components outside of App otherwise they are recreated on every render.
https://codesandbox.io/s/dreamy-bell-2clie
