### ISSUE TITLE
Vue directive should find inner input

### ISSUE THREAD

**Issue by Glandos** [uNmAnNeR/imaskjs#323]
Some custom components wrap an input, but it is not available for the directive. The solution should be trying to find a child input like [vue-the-mask](https://github.com/vuejs-tips/vue-the-mask/blob/c13bbeec24c98f2413fc316a524c32381a335fb1/src/directive.js#L20). The logic seems quite simple.

It can also be a fix for #130 since Vuetify 2.0 removed support for mask.

**Comment by uNmAnNeR** [comment]
Hi! Thanks! but i don't think so. This is very error prone and i don't want to support this.
I think that vue directive/component/examples are quite enough to provide from my side. If you want some more customization you can fork it and customize as you like. Or just use vanilla `IMask`. This is also quite straightforward.
