### ISSUE TITLE
Input's change event doesn't work with type Number in Safari and Edge

### ISSUE THREAD

**Issue by yournatalita** [uNmAnNeR/imaskjs#324]
Sandbox to reproduce issue: http://jsfiddle.net/8xjcf53p/2/
Similar to: https://github.com/uNmAnNeR/imaskjs/issues/28

Issue: Input native change event doesn't fire with iMask type Number in Safari (tested on 13) and Egde (16). But other types (phone or regex) works fine with it.

All types works fine in Chrome and Firefox. Issue reproduced at https://imask.js.org/ too.

Tested with 6.0.3, 6.0.0, 5.2.0 versions.

If it is designed behaviour would be nice to know why.

**Comment by uNmAnNeR** [comment]
Probably this is designed by browsers, i don't know why.
`imask` does not prevent/stop any events, the only thing that `imask` does is subscribe on input event and change input value in event handler syncronously.
Number mask does work in case when `thousandSeparators` is not empty.
So the issue actually appears when value was somehow replaced by imask (while adding separators during input for instance). I don't see any reason why browsers work this way.
So from my side i don't think i have to try fixing it, i just can suggest using `blur` event instead.

**Comment by Mykola-Veryha** [comment]
Bug in Safari when using oninput and onchange
https://developer.apple.com/forums/thread/698078
