### ISSUE TITLE
Escape '0' character wrong result

### ISSUE THREAD

**Issue by daccess1** [uNmAnNeR/imaskjs#325]
Escaping 0 with `'\\0'` in mask results with � instead of zero in value. 
![2020-03-13_17-21-39](https://user-images.githubusercontent.com/19934534/76629328-283b0600-654f-11ea-951e-0b7cd002099a.png)
![2020-03-13_17-19-06](https://user-images.githubusercontent.com/19934534/76629143-e4e09780-654e-11ea-88f6-f1cf0b901ced.png)

**Comment by uNmAnNeR** [comment]
hi! https://jsfiddle.net/uNmAjs/sho2vkx5/ - works
so can not confirm, may be an issue in your editor?

**Comment by daccess1** [comment]
Sure, the issue is with generating JS code from PHP. Thanks for rapid response.
