### ISSUE TITLE
Date demo not working, unable to enter the last digit of the year.

### ISSUE THREAD

**Issue by alanzhaonys** [uNmAnNeR/imaskjs#327]
Date demo not working, unable to enter the last digit of the year.

![imaskbug](https://user-images.githubusercontent.com/7269586/76706421-ba611c80-66bd-11ea-89e1-acaa2391f189.jpeg)

**Comment by uNmAnNeR** [comment]
dup of https://github.com/uNmAnNeR/imaskjs/issues/306
