### ISSUE TITLE
Feature: Negative value before the currency symbol $

### ISSUE THREAD

**Issue by hassanasad** [uNmAnNeR/imaskjs#328]
I just started using imaskJS to convert some of the masks from TextMask package that we were using earlier. I pulled the example from the demos provided to come up with the currency mask:

```
export const NewCurrencyTextMask = IMask.createMask({
	mask: '$num',
	blocks: {
		num: {
			mask              : Number,
			thousandsSeparator: ',',
			scale             : 2,	// digits after decimal
			signed            : true, // allow negative
			normalizeZeros    : true,  // appends or removes zeros at ends
			radix             : '.',  // fractional delimiter
			padFractionalZeros: true,  // if true, then pads zeros at end to the length of scale
		}
	}
});
```

The only issue i am facing is with negative currency values. The mask applied converts it to `$-123.00`. I am trying to make it so that it appears as `-$123.00`, any help in this regard? :)

**Comment by uNmAnNeR** [comment]
i don't see an easy way, because minus is part of number, but you want to divide it.
1) you can inherit from `MaskedNumber` class and override some props/methods - requires to understand sources a lot
2) you can turn off `signed` for number mask, manually add optional minus part before `$` and invert your number model form mask manually if there is a minus sign

**Comment by hassanasad** [comment]
oh okay - seems quite complex :) - Will try to play with it. Feels like its a not a very uncommon case isn't it ?

**Comment by uNmAnNeR** [comment]
may be, but you are the first asking it

**Comment by uNmAnNeR** [comment]
btw, how do you solve it with textmask?

**Comment by hassanasad** [comment]
It does it by default. Here is the settings i use:
```
export const CurrencyTextMask = createNumberMask({
	prefix                   : '$',
	includeThousandsSeparator: true,
	thousandsSeparatorSymbol : ',',
	allowDecimal             : true,
	allowNegative            : true,
});
```

**Comment by hassanasad** [comment]
I believe they do it by pulling minus at the start ([0] index) if it exists in the number part.

This is a link to their implementation
https://github.com/text-mask/text-mask/blob/master/addons/src/createNumberMask.js

**Comment by axcairns** [comment]
> 2. you can turn off `signed` for number mask, manually add optional minus part before `$` and invert your number model form mask manually if there is a minus sign

Hi, would you be able to provide more detail on how to do this?

**Comment by hassanasad** [comment]
@axcairns I haven't moved those masks from TextMask to iMask as yet so am running with two libraries. Would love it if i can get rid of TextMask and just use iMask for every mask.

**Comment by axcairns** [comment]
@hassanasad @uNmAnNeR  I figured out how to do it with this library. 

1. create a dynamic mask array with two pattern masks - one with a hard-coded minus sign before the currency symbol and one without. Both would use an unsigned number mask for the numeric portion of the pattern
2. create a dispatch function to select the appropriate mask based on whether the value starts with a minus sign - 

      dispatch: function (appended: string, dynamicMasked: IMask.MaskedDynamic) {  // determine which mask to apply
        return dynamicMasked.compiledMasks[/^-/.test(dynamicMasked.value + appended) ? 1 : 0];
      }

**Comment by hassanasad** [comment]
Thanks @axcairns for this great solution. Could you however please share the complete mask so its more beneficial for everyone who finds this thread even later on :)

**Comment by hassanasad** [comment]
@axcairns I was looking into this again, I am able to get the correct mask applied but the unmasked value doesn't have the minus sign in it. It's always a positive value for both cases. Any pointers?

**Comment by axcairns** [comment]
```

public buildCurrencyMask(min: number = 0, max: number = 999999999999): any {
    return {
      mask: [
        { // positive currency
          mask: '$num',
          blocks: {
            num: this.buildIntegerMask(true, min < 0 ? 0 : min, max) // inner mask - formatted whole numbers no sign
          }
        },
        { // negative currency
          mask: '-$num',
          blocks: {
            num: this.buildIntegerMask(true, min < 0 ? 0 : min, max) // inner mask - formatted whole numbers no sign
          }
        }
      ],
      dispatch: function (appended: string, dynamicMasked: IMask.MaskedDynamic) {  // determine which mask to apply
        if (min >= 0) { // if < 0 not permitted always return positive mask
          return dynamicMasked.compiledMasks[0];
        }
        return dynamicMasked.compiledMasks[/^-/.test(dynamicMasked.value + appended) ? 1 : 0]; // return negative mask if starts with minus sign and minus allowed
      }
    };
  }

  public buildIntegerMask(formatted: boolean, min: number, max: number): any {
    return {
      mask: Number,
      scale: 0,  // digits after point, 0 for integers
      signed: min < 0 ? true : false,
      thousandsSeparator: formatted ? ',' : '',
      padFractionalZeros: false, // if true, then pads zeros at end to the length of scale
      normalizeZeros: false,  // appends or removes zeros at end of decimals
      radix: '.',  // fractional delimiter
      min: min,
      max: max
    };
  }

```

**Comment by hassanasad** [comment]
@axcairns Thanks for the mask. I have created a stackblitz with your mask code. I am not sure what i am doing wrong but its not working for me :(
Here is a link: https://stackblitz.com/edit/angular-imask-currency

**Comment by hassanasad** [comment]
@uNmAnNeR I have the dispatch method working as intended. However i am unable to find a way to extract the numeric value including `-` (minus) in case the minus mask is used with `[unmask]="true"` - Can you please provide any insiders? Here is my code:

```
maskProps = {
    mask: Number,
    thousandsSeparator: ",",
    scale: 2, // digits after decimal
    signed: false, // allow negative
    normalizeZeros: true, // appends or removes zeros at ends
    radix: ".", // fractional delimiter
    padFractionalZeros: true // if true, then pads zeros at end to the length of scale
  };

  currencyMask = {
    mask: [
      {
        mask: "", // To hide $ if field is empty
      },
      {
        mask: "$num",
        blocks: {
          num: this.maskProps
        }
      },
      {
        mask: "-$num",
        blocks: {
          num: this.maskProps
        }
      }
    ],
    dispatch: ( appended: string, dynamicMasked: IMask.MaskedDynamic, flags: any ) => {
      let index = /[-]/i.test(dynamicMasked.value) ? 2 : 1;
      if (appended === '-'  && !dynamicMasked.value) {
        index = 2;
      } else if ( appended !== '-' && flags?.input &&  !/[-]/i.test(dynamicMasked.value) ) {
        index = 1;
      }
      // Switch to no 'CURRENCY SIGN' mask if no numerical digit in the value
      if (/^[-]?\$$/.test(dynamicMasked.value + appended)) {
        index = 0;
      }
      return dynamicMasked.compiledMasks[index];
    }
  };
```

P.S: I have tried playing with `commit` method and `prepare` methods but they dont help much in this regard either.

**Comment by brockklein** [comment]
@hassanasad 2 years later and I'm facing the same problem. I tried getting @axcairns's solution working with no luck. Were you ever able to accomplish your goal using `iMask`?

**Comment by hassanasad** [comment]
@brockklein No, I gave up on the spec. It was a hacky solution and would keep giving issues in different scenarios unfortunately.

**Comment by brockklein** [comment]
@hassanasad ahh, sad day. Thanks for the quick response. I guess I'll have to evaluate whether I want to learn from those who have gone before me or experience the pain myself. I'll post back here if I end up finding a solution. Thanks!

**Comment by hassanasad** [comment]
@brockklein I hope you find a good solution.
For me we had to support other currencies as well so its was quite painful.
Also i showed my client that most financial tools like Google sheets etc handle it little differently. When editing an amount they strip off the symbols and you are just editing the number and then when you blur out, it formats it back properly. They have kept editing simple so i thought maybe that makes more sense.

**Comment by brockklein** [comment]
@hassanasad oh, good call, that's helpful insight. Thank you!

**Comment by uNmAnNeR** [comment]
this should work with current version in master:

```js
const numberOpts = {
  mask: Number,
  thousandsSeparator: ' ',
  scale: 2,
  radix: '.',
  expose: true,
};

class NegativeNumberMask extends IMask.MaskedNumber {
  get typedValue () {
    return -Math.abs(super.typedValue);
  }
  set typedValue (value) {
    super.typedValue = Math.abs(value);
  }
}

function dispatchMaskIndex (value) {
  if (!value) return 0;
  else if (value.indexOf('-') === 0 || value.indexOf('-') === 1) return 2;
  else return 1;
}

const mask = IMask(el, {
  mask: [
    numberOpts,
    {
      mask: '$num',
      blocks: {
        num: numberOpts,
      }
    },
    {
      mask: '{-}$num',
      blocks: {
        num: {
          ...numberOpts,
          mask: NegativeNumberMask,
          min: 0,
        }
      }
    }
  ],
  dispatch: (appended, dynamicMasked, flags, tail) => {
    const value = dynamicMasked.rawInputValue + appended + String(tail);
    const masked = dynamicMasked.compiledMasks[dispatchMaskIndex(value)];
    dynamicMasked.exposeMask = masked;
    return masked;
  }
});

// use mask.typedValue to get number
```

**Comment by brockklein** [comment]
@uNmAnNeR oh sweet! Thanks for the followup here. Is supporting the mask class the changes that make this possible or was that already supported and we just didn't realize this solution would work? Seems like a powerful/helpful pattern.

Any chance you have time elaborate on why the `dispatch` section is necessary?

**Comment by uNmAnNeR** [comment]
@brockklein well it's also possible to get rid of `dispatch` and simplify it a bit more:

```js
const numberOpts = {
  mask: Number,
  thousandsSeparator: ' ',
  scale: 2,
  radix: '.',
  min: 0,
};

class CurrencyMaskedDynamic extends IMask.MaskedDynamic {
  get typedValue () {
    return Number(this.unmaskedValue);
  }

  set typedValue (typedValue) {
    this.unmaskedValue = String(unmaskedValue);
  }
}

const opts = new CurrencyMaskedDynamic({
  mask: [
    {
      mask: '',
    },
    {
      mask: '$num',
      blocks: {
        num: numberOpts,
      }
    },
    {
      mask: '{-}$num',
      blocks: {
        num: numberOpts,
      }
    }
  ],
});
```
this should already work on v7.2.1

the `dispatch` was needed to 1) manually pick appropriate mask, otherwise the first one is always picked up 2) set `exposeMask` to make `typedValue` work transparently, otherwise need to define getters for parent mask as it's done in the second approach.

There is nothing new, it has been working for a couple of years already. The docs are quite poor and i am a little disappointed that people cannot use lib to its full potential. I am still trying to get myself to write these docs and examples somewhere.

**Comment by brockklein** [comment]
@uNmAnNeR man, I feel ya there. No worries at all. It's definitely a little sad that the library can't be maximally used by those of us who are less familiar with it, but at the same time I know what a bear it is to write documentation in general, let alone public facing documentation that is ready for randos to read and understand. The library is great, keep up the awesome work!

And sweet, thanks for the extra example. Super helpful. Looking forward to using this for my specific use case but also diving more into the concept of the class overrides. Seems like that could unlock a ton of behavior.
