### ISSUE TITLE
Trigger elements with IMask

### ISSUE THREAD

**Issue by satyakresna** [uNmAnNeR/imaskjs#33]
Hi, thanks for providing this cool plugin to make us easy for masking. I would like to ask, can I trigger elements with IMask. Example, in a page I have a form which contain 2 text field with behavior as year.

```html
<form>
<label for="year"></label>
<input type="text" class="year" name="year" id="year">
<label for="taxYear"></label>
<input type="text" class="year" name="tax_year" id="taxYear">
</form>
````

When I initialize with IMask with the syntax below:

```js
var yearMask = new IMask(document.getElementsByClassName("year"), options);
```

It doesn't work. Is that Imask doesn't support for multi elements? Thanks a lot

**Comment by uNmAnNeR** [comment]
Hi!
In this case - No, IMask takes only single element.
If you want to apply mask on many elements use mask in loop on them.

**Comment by satyakresna** [comment]
Noted. Thanks for your advice.

**Comment by monaye** [comment]
I think this need to be in the documentation.
