### ISSUE TITLE
increment/decrement numerical values with up/down arrows?

### ISSUE THREAD

**Issue by jedierikb** [uNmAnNeR/imaskjs#330]
Could you point me in the right direction if I want to be able to increment/decrement numerical values in my mask with up/down arrow keys?

**Comment by uNmAnNeR** [comment]
just listen to events and change the value.
smthg like (did not check it)
```js
const m = IMask(el, {...});
const UP_KEY = 38;
el.addEventListener('keydown', e => {
  if (e.keyCode == UP_KEY) m.typedValue += 1;
}
```
