### ISSUE TITLE
react readme css color invalid

### ISSUE THREAD

**Issue by jedierikb** [uNmAnNeR/imaskjs#332]
https://github.com/uNmAnNeR/imaskjs/blob/master/packages/react-imask/README.md
```
const StyledInput = styled.input`
  color: paleviolet;
`;
```

`paleviolet` is not a css named color (at least not for chrome), so styled component does not render differently.  Took me a while to realize it was the css color in your readme example, not the mixin, which was the problem.

**Comment by uNmAnNeR** [comment]
:) thanks
