### ISSUE TITLE
Unable to type last digit of the date even with no min and max date

### ISSUE THREAD

**Issue by sibijohn72** [uNmAnNeR/imaskjs#333]
I am unable to type the last digit of the year. I am not sure what's wrong, i have tried a few different things but this is the closest i got to getting it right

![image](https://user-images.githubusercontent.com/7763098/77669021-81aa2880-6f84-11ea-99a7-b9581a7380ab.png)

![Uploading image.png…]()

I have shared a minimal example on stackblitz in the link. It is basically the example with a different pattern, without min and max option.
https://angular-imask-yl4bj2.stackblitz.io

**Comment by sibijohn72** [comment]
I have shared a minimal example on stackblitz in the link. It is basically the example with a different pattern, without min and max option.

**Comment by uNmAnNeR** [comment]
hi! i am getting endless loading by this link (https://angular-imask-yl4bj2.stackblitz.io/)
Basic rules are: provide `format` and `parse` callbacks and make sure that `format(parse(yourDateString)) === yourDateString`

**Comment by sibijohn72** [comment]
Thank you, this helped.
