### ISSUE TITLE
Need to double press '.' to get the radix - Vue Plugin

### ISSUE THREAD

**Issue by sunil-uam** [uNmAnNeR/imaskjs#335]
I am using vue plugin as the directive with following mask variables:
```
mask: {
        mapToRadix: ['.'],
        mask: Number,
        max: 9999999.99,
        min: 0,
        normalizeZeros: true,
        padFractionalZeros: false,
        radix: '.',
        scale: 2,
        signed: false,
        thousandsSeparator: ','
      }
```
My component is simple input field
```
<input
  v-imask="mask"
  v-value="model"
>
```

All the variables work except I need to double press '.' to get the radix. Is it the expected behaviour?

**Comment by uNmAnNeR** [comment]
value bindings do not work for directive, you have to use `@accept` or `@complete` events to update value

**Comment by diegovfeder** [comment]
I'm actually seeing a similar issue on a project I just joined.
I need to press the (dot-key `'.'`)  two times for it to appear on the input.
