### ISSUE TITLE
Error "Mask not found for mask" when using custom mask

### ISSUE THREAD

**Issue by raphaelbadia** [uNmAnNeR/imaskjs#336]
Hello,

I have a recurring warning message in my application : whenever I use a custom mask, it throws this warning : `Mask not found for mask `

To reproduce it, go to this sandbox https://codesandbox.io/s/confident-mendel-3k51m and open the console, then type things in it.

Do you see why it's happening? Am I doing something wrong when creating the mask ?

Thanks!

**Comment by colacoashley12** [comment]
<img width="984" height="802" alt="Image" src="https://github.com/user-attachments/assets/e1b12ee9-067f-4952-a3f9-490d6e8cefa4" />

In my library the mask gets assigned correctly but in the application that uses this library , the mask is not correctly assigned and it throws "mask not found error"  ( application uses strict typescript compilation option ) -> Application uses imask: '6.4.2' and library uses "6.4.2"

**Comment by raphaelbadia** [comment]
you should open a new issue bro this one is quite old and closed
