### ISSUE TITLE
Last digit of mask is not available for edit after setup pattern contain dash (date mask)

### ISSUE THREAD

**Issue by v1kee** [uNmAnNeR/imaskjs#338]
Hello, when i try set **pattern** of Date mask like `'Y-m-d'` or `'m-d-Y'`, input showing: 20-02-202_ <- last digit not available. What i do wrong?
my code:
`
var dateMask = IMask(
        document.querySelector('.datemask'),
        {
            mask: Date,
            pattern: 'd-m-Y',
            min: new Date(2010, 0, 1),
            max: new Date(2030, 0, 1),
            lazy: false
        });
`
when mask pattern contain dots: `m.d.Y` all works fine.
Chrome 80.0.3987.149

**Comment by anisha-rohra** [comment]
Running into the same problem, even after creating my own format and parse functions - noticing on the format function that the year on the date is correct but the `getFullYear` function is interpreting the year incorrectly (2020 turns into 1917 somehow)

**Comment by anisha-rohra** [comment]
Running into the same problem, even after providing my own format and parse functions!

**Comment by uNmAnNeR** [comment]
Guys, there are a lot of similar issues here, just use search and read the guide. All examples in guide are working correctly.
So you have to provide `format` and `parse` callbacks, and just make sure that `format(parse(yourInputDateString) === yourInputDateString`

Please provide some runnable examples if you want more help.
