### ISSUE TITLE
Value is not properly being update when `thousandSeparator` is present

### ISSUE THREAD

**Issue by matheusml** [uNmAnNeR/imaskjs#339]
This is my configuration for a decimal number mask:

```js
{
      mask: Number,
      thousandsSeparator: ",",
      radix: "."
}
```
_the important part here is the **thousandsSeparator**, if I remove this line, the error goes away_

I recorded the error:

![ezgif-7-3cff5178cdbb](https://user-images.githubusercontent.com/444202/78186201-af8ae380-7442-11ea-8280-22acc29bbc0a.gif)

Here's where you can reproduce this: https://codesandbox.io/s/relaxed-easley-xm4wg

**Comment by uNmAnNeR** [comment]
hi!
`onChange` event does not work in case when imask is changing value internally in input.
Without `React` this thing reproduces only in IE/Edge, but seems like react team decided to "normalize" it accross all browsers.
So, i can suppose to use `onAccept` event on imask.
