### ISSUE TITLE
Same mask applied on multiple fields is causing issue

### ISSUE THREAD

**Issue by hassanasad** [uNmAnNeR/imaskjs#343]
If a same mask is applied on multiple input fields, once you type in the first one and click on second field and type - it copies data from first field.

Here is a stackBlitz to demonstrate the issue

https://stackblitz.com/edit/angular-kdb4wp

**Comment by uNmAnNeR** [comment]
hi! mask contains model data. So it supposed to share value.
If you want to have independent mask, then you might generate it with some function.
Or you can use object properties instead of mask instance - this way new mask instance will be created every time.

**Comment by hassanasad** [comment]
Would it make sense to have an option when it doesn't share model data ? 

Maybe something like:
```
export const FreeNumberMask: IMask.AnyMaskedOptions = {
	mask        : '0000',
	signed      : false,
	shareData   : false,  <-----
};
```
P.S: Is sharing data a very common use case?

**Comment by uNmAnNeR** [comment]
@hassanasad  for me sharing works as expected already.
`Masked` instance shares state (like in your demo), but if mask options is used then state is not shared (like in your latest comment).
So if you want to share state - use Masked instances,
If not - use raw options or factories of Masked instances. Factories is also a common pattern, i don't see any issues here.

**Comment by hassanasad** [comment]
You mean like this right:
```
export const FreeNumberMask: IMask.AnyMaskedOptions = {
	mask  : Number,
	signed: false,
	scale : 0,
});

export function generateMask( maskSettings: IMask.AnyMaskedOptions ): IMask.DeduceMasked<IMask.AnyMaskedOptions> {
	return IMask.createMask( maskSettings );
}

export class AppComponent  {
  ...
  readonly freeNumberMask = generateMask( FreeNumberMask );
  readonly freeNumberMask2 = generateMask( FreeNumberMask );
}
```
Then use it like this:
```
<div class="field-container">
	<input type="text" placeholder="Routing #"
		[formControlName] = "'routingNumber'"
		[imask]  = "freeNumberMask"
		[unmask] = "true"
	/>
</div>
<div class="field-container">
	<input type="text" placeholder="Account #"
		[formControlName] = "'accountNumber'"
		[imask]  = "freeNumberMask2"
		[unmask] = "true"
	/>
</div>
```

**Comment by hassanasad** [comment]
OH - Now i understand what you mean.

So you mean it like this:
```
export const FreeNumberMask: IMask.AnyMaskedOptions = {
	mask  : Number,
	signed: false,
	scale : 0,
});

export class AppComponent  {
  ...
  readonly freeNumberMask = generateMask( FreeNumberMask );
}
```
Template file
```
<div class="field-container">
	<input type="text" placeholder="Routing #"
		[formControlName] = "'routingNumber'"
		[imask]  = "freeNumberMask"
		[unmask] = "true"
	/>
</div>
<div class="field-container">
	<input type="text" placeholder="Account #"
		[formControlName] = "'accountNumber'"
		[imask]  = "freeNumberMask"
		[unmask] = "true"
	/>
</div>
```
I am not sure how i missed this. Yeah it works fine now!
Maybe i was using `[imask] = {mask: freeNumberMask}` earlier and it was sharing data.

Sorry to bother you again but can you please tell me the proper type of this mask:
```
export const ExpiryMask: any = {	// type IMask.AnyMaskedOptions has issues with blocks
	mask     : 'MM/YY',
	overwrite: true,
	autofix  : true,
	lazy     : true,
	blocks   : {
		MM: { mask: IMask.MaskedRange, placeholderChar: 'M', from: 1, to: 12, maxLength: 2 },
		YY: { mask: IMask.MaskedRange, placeholderChar: 'Y', from: 20, to: 99, maxLength: 2 },
	}
};
```
^ I cant seem to type case it properly so have to use `any` instead.
