### ISSUE TITLE
mask:Date vs mask:'blockname' when blockname.mask = Date => unexpected input behavior

### ISSUE THREAD

**Issue by voskresla** [uNmAnNeR/imaskjs#344]
Example: https://codesandbox.io/s/compassionate-violet-hrccp?file=/src/index.js

If u type '12.11.1999' in first input, then try to change 11 => all will be fine. We get `11.1_.1999`
If try the same in second input we get `12.11.999_`

(

**Comment by uNmAnNeR** [comment]
thanks, i'll check it

**Comment by papiliond** [comment]
Dear @uNmAnNeR !

I experience (i guess) the same problem. I use the recommended setting for moment.js (https://imask.js.org/guide.html#masked-date). The "YYYY-MM-DD HH:mm" formatted parse method parses the date right, but is displayed in the input with an **underscore in the place of the last character**, for example: "2020-04-28 20:0_". 

If you cannot reproduce, i will provide a codesandbox. Thank you!

**Comment by voskresla** [comment]
> "YYYY-MM-DD HH:mm"

try use "\`" symbol - https://imask.js.org/guide.html#masked-pattern
```
mask: "YYYY-`MM-`DD, `HH:`mm"
```
