### ISSUE TITLE
IMask Date

### ISSUE THREAD

**Issue by henriquepalato** [uNmAnNeR/imaskjs#345]
I am not able to format data, when I put the pattern 'd / `m /` Y', the last digit is not returning, I put 01/01/1999, and it returns 01/01/199.

I made a model in:
https://stackblitz.com/edit/angular-et3zk9

I am very grateful to help me.

**Comment by uNmAnNeR** [comment]
just debug what you are getting:
`return new Date(yearMonthDay[0], yearMonthDay[1] - 1, yearMonthDay[2]);`
you have dayMonthYear not yearMonthDay

**Comment by henriquepalato** [comment]
Dear friend,

Of all the plugins I researched, Angular IMask is the best I found, because I have two difficulties that I am not able to solve, because I have been trying for more than 3 weeks, I believe it is because I am a beginner in the angular, so I would be very grateful to help me.

The first is the formatting of the date, as I would like it to be in dd / MM / yyyy format, but I am not able to put it in this format, could you help me on how to do this?

The second is in relation to the currency mask, as it is going to the right api, only when it comes time to get it to show, it presents this error.

In Component
imaskDate = {
    mask: Date,
    // pattern: 'd {/} `m {/}` Y',
    pattern: 'd {.} `m {.}` Y',
    blocks: {
      d: {
        mask: IMask.MaskedRange,
        from: 1,
        to: 31,
        maxLength: 2,
      },
      m: {
        mask: IMask.MaskedRange,
        from: 1,
        to: 12,
        maxLength: 2,
      },
      Y: {
        mask: IMask.MaskedRange,
        from: 1900,
        to: 9999,
        maxLength: 4,
      }
    },

    format (date: any) {
      console.log (date);
      let day = date.getdate ();
      let month = date.getmonth () + 1;
      const year = date.getfullyear ();

      if (day <10) {day = '0' + day; }
      if (month <10) {month = '0' + month; }
      return [year, month, day] .join ('.');
    },
    parse (str: any) {
      const daymonthyear = str.split ('.');
      return new Date (daymonthyear [0], daymonthyear [1] - 1, daymonthyear [2]);
    },
    min: new Date (1900, 0, 1),
    max: new Date (2099, 12, 31),

    autofix: true,
    lazy: true,
    overwrite: true
  };

In HTML
<input [imask] = "imaskDate" [unmask] = "true" type = "text" class = "form-control text-right" id = "expiryDate" formControlName = "expiryDate"

ERROR Error: value should be string
    at MaskedNumber.append (base.js: 187)
    at MaskedNumber.resolve (base.js: 78)
    at MaskedNumber.set (base.js: 324)
    at InputMask.set (admitjs: 368)
    at IMaskDirective.set maskValue [as maskValue] (angular-imask.js: 98)
    at IMaskDirective.writeValue (angular-imask.js: 178)
    at forms.js: 3438
    at forms.js: 4822
    at Array.forEach (<anonymous>)
    at FormControl.setValue (forms.js: 4818)

In Component
  imaskMoney = {
    mask: Number,
    overwrite: true,
    scale: 2,
    thousandsSeparator: '.',
    padFractionalZeros: true,
    normalizeZeros: true,
    radix: ',',
    signed: false,
    min: 0,
  };

In HTML
<input [imask] = "imaskMoney" [unmask] = "true" type = "text" class = "form-control text-right" id = "aliquotIpi" formControlName = "aliquotIpi">

Both codes are in
https://stackblitz.com/edit/angular-et3zk9

I believe you can change it.

I thank you very much for helping me.

**Comment by uNmAnNeR** [comment]
@henriquepalato https://stackblitz.com/edit/angular-x9ptsb check this out for date
for number - probably you are trying to put value of number type to imask. if yes, then use `unmask="typed"` instead of `true`.

**Comment by henriquepalato** [comment]
Dear Alexey,
Now I can put the date right, but I need your help again... I believe the problem is on the parse method, because when it sends to API, the format needs to be "yyyy-MM-dd", is there a way to do that? Or should I send yhe way it is "dd/MM/yyyy".

How do I the unmask="typed"? Because when I put that it says "Identifier 'typed' is not defined. The component declaration, template variable declarations, and element references do not contain such a member" Can you identify the problem?
(for number - probably you are trying to put value of number type to imask. if yes, then use unmask="typed" instead of true.)

Forgive me for giving you so much trouble.

**Comment by la-costa** [comment]
Hi @henriquepalato,

I have the same problem.

Please, check my solution in the discussion #100

**Comment by cesartalves** [comment]
For anybody having trouble with this, managed to make the mask work with dd/mm/yyyy using the following:
@henriquepalato 

```
{
  mask: Date,
  pattern: 'd{/}`m{/}`Y', // default is 'd{.}`m{.}`Y'
  format: function (date) {
    var day = date.getDate();
    var month = date.getMonth() + 1;
    var year = date.getFullYear();

    if (day < 10) day = "0" + day;
    if (month < 10) month = "0" + month;

    return [day, month, year].join('/');
  },
  parse: function (str) {
    var yearMonthDay = str.split('/');
    var date = new Date(yearMonthDay[2], yearMonthDay[1] - 1, yearMonthDay[0])
    return date;
  },
  lazy: false,
}
```

**Comment by JoaoHamerski** [comment]
> For anybody having trouble with this, managed to make the mask work with dd/mm/yyyy using the following: @henriquepalato
> 
> ```js
> {
>   mask: Date,
>   pattern: 'd{/}`m{/}`Y', // default is 'd{.}`m{.}`Y'
>   format: function (date) {
>     var day = date.getDate();
>     var month = date.getMonth() + 1;
>     var year = date.getFullYear();
> 
>     if (day < 10) day = "0" + day;
>     if (month < 10) month = "0" + month;
> 
>     return [day, month, year].join('/');
>   },
>   parse: function (str) {
>     var yearMonthDay = str.split('/');
>     var date = new Date(yearMonthDay[2], yearMonthDay[1] - 1, yearMonthDay[0])
>     return date;
>   },
>   lazy: false,
> }
> ```

This should be in the documentation, just a contribution:

Using luxon js you can do it in one line:

```js
import { DateTime } from 'luxon'

export const DATE_MASK = {
  mask: Date,
  pattern: 'd{/}`m{/}`Y',
  eager: true,
  format: date => DateTime.fromJSDate(date).toFormat('dd/MM/y'),
  parse: str => DateTime.fromFormat(str, 'dd/MM/y').toJSDate()
}
```

**Comment by francofer7** [comment]
> ```js
> mask: Date,
>   pattern: 'd{/}`m{/}`Y', // default is 'd{.}`m{.}`Y'
>   format: function (date) {
>     var day = date.getDate();
>     var month = date.getMonth() + 1;
>     var year = date.getFullYear();
> 
>     if (day < 10) day = "0" + day;
>     if (month < 10) month = "0" + month;
> 
>     return [day, month, year].join('/');
>   },
>   parse: function (str) {
>     var yearMonthDay = str.split('/');
>     var date = new Date(yearMonthDay[2], yearMonthDay[1] - 1, yearMonthDay[0])
>     return date;
>   },
>   lazy: false,
> ```

NEcesito lo mismo pero con el formato de fecha `pattern: 'm{/}`d{/}`Y'`, cuando lo coloco asi no me deja ingresar el ultimo caracter tampoco
