### ISSUE TITLE
[angular-imask] radix show unexpected format in pipe

### ISSUE THREAD

**Issue by superman-lopez** [uNmAnNeR/imaskjs#347]
When a number value (as string) includes a `.` as a decimal separator, the attribute `imask` masks it correctly (even without parameters on the radix value).  When I map the radix value from `.` to `,` the attribute based functionality continues to work as expected.
However for the pipe `imask` I don't see the same results.  Without any parameters on the radix value, the masked value is wrongly formatting the value.  If I explicitly set the parameters to read and map the radix to `.`, it works.  If I map it from `.` to `,` it continues to incorrectly format it.

Outcome: I have a value of `"5000000.50" `, when I pipe this value with `imask` it becomes `5,00`
Parameters: 
```
  {mask: Number,
    scale: 2,
    padFractionalZeros: true,
    signed: true,
    radix: ',',  
    mapToRadix: ['.'] 
  }
```
https://stackblitz.com/edit/angular-imask-string?embed=1&file=src/app/app.component.ts&hideExplorer=1&hideNavigation=1

**Comment by uNmAnNeR** [comment]
you have `number` pipe before `imask`. When i removed it, imask pipe works well. Seems like a problem not it `imask`.
