### ISSUE TITLE
Custom "typed" unmask?

### ISSUE THREAD

**Issue by lunaboona** [uNmAnNeR/imaskjs#348]
Currently I have a mask that looks like this:

```
// ...
    mask: [
      {
        mask: 'prefixnum',
        blocks: {
          num: {
            mask: Number,
            scale: 2,
            thousandsSeparator: '.',
            padFractionalZeros: true,
            normalizeZeros: true,
            radix: ',',
            mapToRadix: ['.', ','],
            min: undefined,
            max: undefined
          },
          prefix: {
            mask: ''
          }
        }
      }
    ]
// ...
```

and in `dispatch()` I do some additional processing (setting the prefix and changing a few options). The problem is that when I set `unmask` to "typed", the value isn't unmasked at all. How can I make a custom "unmask" so that I can define logic to return a number? Also, this is using the Angular plugin.

**Comment by uNmAnNeR** [comment]
the only thing i can suggest now is: https://jsfiddle.net/uNmAjs/49ap8v25/
but still in search for better solution...

**Comment by lunaboona** [comment]
> 
> 
> the only thing i can suggest now is: https://jsfiddle.net/uNmAjs/49ap8v25/
> but still in search for better solution...

Thanks, good to know it's possible even though it's not the cleanest. Any idea how I would go about implementing this in Angular?
