### ISSUE TITLE
Input value is longer than masked value

### ISSUE THREAD

**Issue by vlaca99** [uNmAnNeR/imaskjs#350]
Hi!
I've encountered a problem with validation during development.
I have a input type number and max set to 1000. I have also set max to 1000 to mask but the mask value and input value are different when typing.

e.g. If I try to enter 1234 the masked value in input will show 123 but the error message will trigger since the input value will actually be 1234.

This is the link to stackblitz where you can see the input value logged next to an input element.
https://stackblitz.com/edit/angular-eenmlz?file=src%2Fapp%2Fapp.component.ts

**Comment by uNmAnNeR** [comment]
hi, this is known browser problem (not imask i am still sure), you can search for details in issues. The only thing i can suggest is to use `accept` instead of `input`. imask does not prevent any native events.
