### ISSUE TITLE
Setting a value with calculation crash the application

### ISSUE THREAD

**Issue by Flakelf** [uNmAnNeR/imaskjs#351]
Hi there, i am building an app using `react-imask`, i have a problem, when i setting value at input with calculation, app crashes, because it's triggered infinite loop.

Here a reproduction - [CodeSandbox](https://codesandbox.io/s/onchange-loop-triggers-vu5wy?file=/src/App.js)

Help me pls...

**Comment by uNmAnNeR** [comment]
hi. you made a recursion without exit and got infinite loop. Works quite obvious, what help do you need?

**Comment by Flakelf** [comment]
@uNmAnNeR how can i improve this code for work correct? I need to recalculate the values based on other values

**Comment by uNmAnNeR** [comment]
currently it does not include exit point. You have to add a condition when your values will stop changing.

**Comment by Flakelf** [comment]
@uNmAnNeR can u explain, pls, or fork my sandbox, i don't understand, i have a switch/case block, i check "name" on value and recalculate what i need, where i need add a condition

**Comment by uNmAnNeR** [comment]
you have 1-2-3-4-1 updates, just break this loop in any place

**Comment by Flakelf** [comment]
@uNmAnNeR doe's setting value triggers onAccept ?

**Comment by uNmAnNeR** [comment]
@Flakelf yes, it does
