### ISSUE TITLE
how to setup tree shaking imports with 'Date'?

### ISSUE THREAD

**Issue by mashpie** [uNmAnNeR/imaskjs#356]
Thanks for this lib... good Job!

Now... as I wanted to setup tree shaking for my use case I started with examples from docs, ok fine, just works... for numbers, not for dates?

Example from the docs with `number` works fine:

```js
import IMask from 'imask/esm/imask' 
import 'imask/esm/masked/number'
```

next I tried with `date`

```js
import IMask from 'imask/esm/imask' 
import 'imask/esm/masked/date'
```

which breaks with Error: "Masked class is not found for provided mask, appropriate module needs to be import manually before creating mask."

Ok, double checked my setup by `import IMask from 'imask'` which works perfectly.

And as a last try (date is extending pattern:

```js
import IMask from 'imask/esm/imask' 
import 'imask/esm/masked/pattern'
import 'imask/esm/masked/date'
```

same issue. Any hint on what I am missing?

**Comment by jbanety** [comment]
Hi @mashpie,
The workaround is to add the missing regexp import.
```js
import IMask from 'imask/esm/imask' 
import 'imask/esm/masked/regexp'
import 'imask/esm/masked/date'
```

**Comment by mashpie** [comment]
Ah nice- thanks for support! I'll report as soon this was implemented on our side
