### ISSUE TITLE
how to update mask for an element

### ISSUE THREAD

**Issue by FatehDzIt** [uNmAnNeR/imaskjs#357]
how i can change the mask for an input when changing like phone number type ?

this function fires when changing the type
i tried before and i got this err 
**Element** value was changed outside of mask. Syncronize mask using `mask.updateValue()` to work properly**

```function update_mask(e) {
   type = e.target.previousElementSibling.value
   element = e.target
   let maskOptions = { mask : "000-00-00-00"}
   var mask = IMask(element, maskOptions);
  
   if(type == 'mobile') {
     //update maske
   }

**Comment by uNmAnNeR** [comment]
you can use `mask.updateOptions(...)`. Please provide some fiddle to run for more info
