### ISSUE TITLE
Angular unmaskedValue.replace is not a function 

### ISSUE THREAD

**Issue by ryanbuening** [uNmAnNeR/imaskjs#36]
I'm using Angular `5.2.2` and angular-imask `1.0.2`. I have the following service with various masks defined:

### mask.service.ts

```
import { Injectable } from '@angular/core';

@Injectable()
export class MaskService {

    public alpha = {
        mask: /^[a-zA-Z]*$/
    };

    public alphaAllowSpaces = {
        mask: /^[a-zA-Z ]*$/
    };

    public alphaNumeric = {
        mask: /^[a-zA-Z0-9]*$/
    };

    public alphaNumericAllowSpaces = {
        mask: /^[a-zA-Z0-9 ]*$/
    };

    public numeric = {
        mask: /^[0-9]*$/
    };

    public phone = {
        mask: '(000) 000-0000',
    };

    public socialSecurity = {
        mask: '000-00-0000',
    };

    public fourDigitYear = {
        mask: Number,
        scale: 0,
        signed: false,
        thousandsSeparator: "",
        padFractionalZeros: false,
        normalizeZeros: false,
        max: (new Date()).getFullYear(),
        min: 0,
    };

    public numericWithThousandsSeparator(max: number): {} {
        return {
            mask: Number,
            scale: 0,
            signed: false,
            thousandsSeparator: ",",
            padFractionalZeros: false,
            normalizeZeros: false,
            max,
            min: 0,
        };
    }
}
```

and they are used in my HTML template:

```
<input class="form-control" name="constructionYear" [(ngModel)]="vm?.constructionYear" #constructionYear="ngModel"
                    required [imask]="this.maskService.fourDigitYear" minlength="4" />
```

All of the masks are working correctly when inputting values. However, when I save values and return back to my component to display the values I'm getting the following error(s):

`ERROR Error: Uncaught (in promise): TypeError: unmaskedValue.replace is not a function
TypeError: unmaskedValue.replace is not a function`

None of the values get displayed in the inputs. Any ideas of what I could try?

### Edit: I created an Angular CLI project that reproduces these examples here: https://github.com/ryanbuening/imaskexample

**Comment by ryanbuening** [comment]
In further testing, the `numeric` mask works correctly when values are being input, but the value does not get set in the input if an existing value exists and I reload my page. I do not get any errors.

```
public numeric = {
	mask: /^[0-9]*$/
};
```

```
<input class="form-control" name="constructionYear" [(ngModel)]="vm?.constructionYear" #constructionYear="ngModel"
                    required [imask]="this.maskService.numeric" minlength="4" />
```

The `fourDigitYear`  mask throws an error message `Error: Uncaught (in promise): TypeError: str.replace is not a function TypeError: str.replace is not a function`.

```
public fourDigitYear = {
	mask: Number,
	scale: 0,
	signed: false,
	thousandsSeparator: "",
	padFractionalZeros: false,
	normalizeZeros: false,
	max: (new Date()).getFullYear(),
	min: 0,
};
```

**Comment by ryanbuening** [comment]
I created an Angular CLI project that reproduces these examples here: https://github.com/ryanbuening/imaskexample

**Comment by uNmAnNeR** [comment]
Hi! sorry for delay.
Imask model is always of string type which is universal for text input. But in your example `Number` is passed.
Any type convertions could be done on application side, or get obtained from internal mask, e.g. for number mask: `imask.maskRef.number`

**Comment by ryanbuening** [comment]
@uNmAnNeR No problem. I'm not quite following how I would use `imask.maskRef.number` in my case. Could you give me an example?

I understand where you are coming from the thought that text is "universal" for input. In my case, I'm getting a lot of data back from our API that is stored as an integer/number. I would rather not do conversions everywhere in my application if it can be avoided.

`ng2-currency-mask` (https://github.com/cesarrew/ng2-currency-mask) currently handles `Number` type masking. I'm not looking for all the currency type options, but is something like that feasible for this project or is that out of scope?

Thanks.

**Comment by uNmAnNeR** [comment]
Currently there is no way to cast types for `ng-model`.
`Number` value for number mask can only be received by `imask.maskRef.number`, where `imask` is reference for directive.
Probably it takes sense to access typed value. I need to think more on it.

**Comment by uNmAnNeR** [comment]
@ryanbuening try using `unmask='typed'` since v3.3.0
