### ISSUE TITLE
Digits after fractional delimiter aren't removed when scale is set to `0`

### ISSUE THREAD

**Issue by mr-winter** [uNmAnNeR/imaskjs#360]
I just gave imaskjs a try and found this behaviour which doesn't feel right.

Given a `Number` mask:

```
    IMask.pipe(
        '123.45',
        {
            mask: Number,
            scale: 0 // format to integer 
        },
        IMask.PIPE_TYPE.UNMASKED,
        IMask.PIPE_TYPE.MASKED
    )
```

Output:
`12345`

Expected output:
`123`

**Comment by uNmAnNeR** [comment]
from my point of view it works as expected.
Pipe options relates to output, and input is just raw string. Pipe works same way as user copies and pastes in input field. So what you want is dot to be processed in a special way, but it should not.
User can have various format, for instance `1.000.000,20`, `1,133.00` etc. So i don't think it's a good idea to try processing all this combinations. What mask does is just trying to get all acceptable chars from input string without any knowledge of it's format. It's very generic and works quite well. I'm going stay with it, and can suggest you to prepare such numbers on your app side.
