### ISSUE TITLE
Extra value is getting appended despite its configuration 

### ISSUE THREAD

**Issue by monis001** [uNmAnNeR/imaskjs#362]
Hi,
First of thanks for this awesome library. I have observed some random behavior : consider this configuration 
```
 private durationFormat() {
    return {
      overwrite: true,
      autofix: true,
      mask: "HH:MM:SS",
      blocks: {
        HH: {
          mask: IMask.MaskedRange,
          placeholderChar: "H",
          from: 0,
          to: 23,
          maxLength: 2,
        },
        MM: {
          mask: IMask.MaskedRange,
          placeholderChar: "M",
          from: 0,
          to: 59,
          maxLength: 2,
        },
        SS: {
          mask: IMask.MaskedRange,
          placeholderChar: "S",
          from: 0,
          to: 59,
          maxLength: 2,
        }
      },
    };
  }
```
and it is supposed to show output like  : `00:43:44` BUT after typing second part i.e. `... : ... :43` If I again press any key or same key (i.e. in above case it is 4) It wil restrict in the input box but it will show `00:43:444` in the output 
[images]
![image](https://user-images.githubusercontent.com/46885793/83046458-ae51ed80-a064-11ea-92d1-75368cdd05d4.png)
and 

![image](https://user-images.githubusercontent.com/46885793/83046553-cfb2d980-a064-11ea-9918-6a216b1ac454.png)

![image](https://user-images.githubusercontent.com/46885793/83046889-45b74080-a065-11ea-84fa-8d4d84ba259a.png)

I tried to format the output, but not able to capture that in any callback.

Thanks

**Comment by uNmAnNeR** [comment]
Hi, you are welcome. Do you use imask `accept` event or native `change` event?

**Comment by monis001** [comment]
Actually, this is an angular project so I decided to use `Imask` JS instead of angular plugin
![image](https://user-images.githubusercontent.com/46885793/83142523-3c35e300-a10e-11ea-8bf6-2bb213bb7174.png)
and
![image](https://user-images.githubusercontent.com/46885793/83142696-7acb9d80-a10e-11ea-98e5-92121540ea58.png)
[Images for just hint purposes]

but somehow it is interfering with the `model`, it shows `input value` to be empty but `model` is getting updated, and same behaviour can be observed with `number`  when we type string it do not accept but `model` shows the value

**Comment by uNmAnNeR** [comment]
anyway it will be solved if you use imask `accept` event instead of native `input` or `ngOnChanges` which also is using `input` under the hood.

**Comment by monis001** [comment]
If I am not wrong, You meant to update `ng-model` value from `accept` event ?

**Comment by uNmAnNeR** [comment]
yep, that what i meant :)

**Comment by monis001** [comment]
Thanks for your support, it worked me with  `commit` event once I am done with the values and when it focuses out than I update my model.
But still, it brings me back to the question, **why does it happening so?** I find plain JS library helpful rather going for angular-plugin and don't know if the same case is handled over there as well..
P.S. : If anyone falls fo same issue this helps me out  [ng-model update](https://stackoverflow.com/questions/37598895/change-an-inputs-ngmodel-value-using-a-directive-angular-2)
