### ISSUE TITLE
Clear invalid values on blur

### ISSUE THREAD

**Issue by julianomqs** [uNmAnNeR/imaskjs#363]
Hello,

I noticed your component doesn't clear invalid values on blur like other mask components.

For example, I have a component with the mask `(00) 0000-0000`.

If the user types `48` and tabs or clicks away the component stays with the value `(48)`.

In my opinion this behavior is quite undesirable, because keeping the invalid value would demand extra validations and wouldn't make much sense after all.

Is there a option to do this? If not, could be implemented?

**Comment by uNmAnNeR** [comment]
hi. it is more like incomplete then invalid. So from my point of view it works as it should.
You can clear value on blur if value is not filled (see `isComplete` flag)
