### ISSUE TITLE
MaskedNumber doesn't accept any numbers after '0'

### ISSUE THREAD

**Issue by canerelci** [uNmAnNeR/imaskjs#364]
I'm looking for a stable text-mask solution and I'm surprised to fail on this in my first try. You may also try the following scenario on the documentation at: https://imask.js.org/guide.html#masked-number

This is the case: 

When I put 0 as the initial value for MaskedNumber element and click right of this '0' character, it doesn't accept any number. 

Expected behavior:

It should let the user add any numbers after '0', like 0132 and mask it as it's supposed to. In fact, it should also remove '0' character and continue accepting numbers. Because it's nonsense '01' as a number. Instead, it is simply '1'.

**Comment by tarmooo** [comment]
This is described here #205 

If anyone has a solution for that i would like to hear that too.

**Comment by uNmAnNeR** [comment]
i consider mask strategy as `restriction` rather then `correction`. So no plans to implement any 'fixing' behaviours, i think it should be implemented on app side. From myside i tried to make imask to be extendable as possible to simplify this. this case is quite specific, for instance in our apps i'd prefer current behaviour.
