### ISSUE TITLE
More documentation how to use with RegExpre in Angular2+

### ISSUE THREAD

**Issue by anjopater** [uNmAnNeR/imaskjs#366]
Hi, great library!

Do you have more doc of how to work with regular expression in angular 2+
for example, I'm trying to validate a field with x expression, but I don´t know if a need to pass the expression directly. for example.

`let mask = { mask:  /^\-?(\d+\d*|\d*\d+)$/ } ` or` let mask = { mask: (value)=>  /^\-?(\d+\d*|\d*\d+)$/.test(value) }`
`<input  [mask]="mask" />`

I tried the two ways but, it not work,  how is the correct way,?

I reviewed this also and not work for me https://imask.js.org/guide.html#masked-base

**Comment by lhalver1** [comment]
Then angular documentation could definitely use improved documentation and more examples of how to use some of the features.

**Comment by franbueno** [comment]
Is there any update here? Thanks!

**Comment by uNmAnNeR** [comment]
it's already in the guide: regexp need to cover all intermediate values, not only the complete one
