### ISSUE TITLE
Multiple phone numbers masks for one input

### ISSUE THREAD

**Issue by ravtakhar** [uNmAnNeR/imaskjs#367]
Hey guys,

I am attempting to apply an array of masks to one input (phone numbers). For example if I enter more than 10 digits I want it to shift to my 11 digit mask and if 11 digits are exceeded I want it to shift to my 13 char mask.

(000) 000-0000
+0 (000) 000-0000
+000 (000) 000-0000

**Comment by ravtakhar** [comment]
Solved my own issue. Was creating the array incorrectly:

[imask]="{mask: [{mask: '(000) 000-0000'}, {mask: '+0 (000) 000-000'}]}"

**Comment by renerlemes** [comment]
In any case, there is wrong behavior.
If I enter the value 6492176420 it should resolve to (64) 9217-6420.
If I enter the value 64921764209 it should resolve to (64) 92176-4209.

It should meet one of the masks.

I'm using it like this:

 IMask.createMask({ mask: [{ mask: "(00) 0000-0000" }, { mask: "(00) 00000-000" }] })
