### ISSUE TITLE
Phone mask with static prefix (+48) is rendered without first digit if current value has that digit first

### ISSUE THREAD

**Issue by lsurma** [uNmAnNeR/imaskjs#368]
Hi,

I need phone mask with static prefix +48, which will be not included in unmasked value.
Code below is working fine, but when input already has value, and that value is starting with first digit of my mask (in my example is digit "4") the initial rendering of masked input is missing my first digit from value.

So when current value is for eg. 422422422, the initial rendering will be +48 224-224-22_ and expected result is +48 422-422-422

```js
phoneMask = IMask(document.getElementById('test'), {
  mask: '+48 000-000-000',
  lazy: false,
  overwrite : true
});
```

Fiddle with working example of problem: https://jsfiddle.net/ukp1s5fm/

Any ideas?

**Comment by drMonro** [comment]
Try to check my example:
https://github.com/uNmAnNeR/imaskjs/issues/370

**Comment by lsurma** [comment]
Hi,

Thanks for the response @drMonro , i modified your example to show what the problem is.
https://codepen.io/lukasz-surma/pen/xxZGOWX

I added static/initial value "7774441212" to the input, and the rendered mask is "+7 (774) 441-21-2", but should be +7 (777) 444-12-12.
Everyting is working when new value is typed into input, mask is working properly. Problem is when initial value is set, then mask is rendered without first digit (if first digit from mask is same as first digit from value).

I overcome this problem by adding excessive digit to value. 
Example: https://codepen.io/lukasz-surma/pen/zYrGBmd

But is rather "hacky" solution.

**Comment by drMonro** [comment]
Did you solve problem with minlength validation on submit?

**Comment by lsurma** [comment]
@drMonro Thanks :) Kind of - yes, but i store phone number in database in raw, unmasked form. So i do not wan't convert my raw DB value to masked form, so lib can display it correctly. It should be job of this library.  

But don't waste more of your time here :) I already got "hacky" solution which works for me, but i just wanted to know if there is bug in this library or if i'm doing something wrong. 

I will take a look at your problem, if i'll find some solution i just write in your issue.
