### ISSUE TITLE
Third placeholder option

### ISSUE THREAD

**Issue by kakawajazz** [uNmAnNeR/imaskjs#37]
I think it might be useful to have an option to display mask placeholder only on focus.
Here an example:
![asdadad](https://user-images.githubusercontent.com/2721607/36303002-9879b250-131b-11e8-9b87-ef09ea2f61a4.png)

**Comment by uNmAnNeR** [comment]
Mask is ready to work like you described.
It is easy to do it with `focus` and `blur` events and mask `lazy` option.
But no plans to include this in library.

**Comment by kakawajazz** [comment]
Yes, I've just figured it out by myself. Thanks for your help.
