### ISSUE TITLE
Validation masked input

### ISSUE THREAD

**Issue by drMonro** [uNmAnNeR/imaskjs#370]
Hi, everyone!

How i can setup masked input?
Unfortunately, input's minlenght attribute  doesn't work correct - if, i just focus in input and try to submit form it will pass validate check, but it have't to. Also, if i'll type one more digit - validation starting working correct.

Here is my example: https://codepen.io/rapman477/pen/ZEQGzOw

Please, help

**Comment by lsurma** [comment]
Hi,

This might be answer: https://stackoverflow.com/questions/45929862/why-doesnt-input-minlength-check-work-with-initial-value

> This is by design. The minlength attribute only validates a field once it has been edited by the user. It doesn't validate the field if its value hasn't been changed, even if that value doesn't meet the constraint.

Solution would be some custom validation via JS, but not HTML native one, and of course server side validation which always should be used.
