### ISSUE TITLE
Custom separating length

### ISSUE THREAD

**Issue by dreit-p** [uNmAnNeR/imaskjs#377]
The `thousandsSeparator` separates by thousands but how can I change the length of separating? 
For example, for a card number 0000 0000 0000 0000.

**Comment by umairhm** [comment]
You can use this object for opts => { mask: '0000 0000 0000 0000' } and it should work for you.

**Comment by uNmAnNeR** [comment]
thanks for @umairhm , yes, only by using pattern mask
