### ISSUE TITLE
Angular plugin: cannot access mask.updateValue() 

### ISSUE THREAD

**Issue by shateeshb** [uNmAnNeR/imaskjs#378]
I'm using the Angular plugin as part of a custom date picker, so the element's value can be changed by typing into the input field or by clicking on a calendar pop up. 

If I change the date by clicking on the calendar, I get this warning message: 
```
input.js:132 Element value was changed outside of mask. Syncronize mask using `mask.updateValue()` to work properly.
```

Is there a way to access mask.updateValue through the angular plugin? Thanks.

**Comment by mustordont** [comment]
@shateeshb, i used this approach:
`
    @ViewChild('imask', {read: IMaskDirective}) imask: IMaskDirective<MaskedOptions<MaskedNumber>>;

    public clear(): void {
        this.imask.maskValue = '';
    }
`
but definitely need the exportAs on imaskDirective.

**Comment by shateeshb** [comment]
ah, thanks for the suggestion @mustordont. Where do you get the `IMaskDirective ` from?

**Comment by shateeshb** [comment]
Where do you get `MaskedPattern` from? @mustordont
