### ISSUE TITLE
toggle lazy:true/false on focus/blur using Angular plugin

### ISSUE THREAD

**Issue by shateeshb** [uNmAnNeR/imaskjs#380]
hi all, is there a way to toggle the `lazy` option for the mask on focus/blur using the angular plugin? 

this is how I am currently using imask. I am a newbie to angular and am not sure how when blur and focus methods are called, but it this is not updating the lazy option the way I'd expect: 

```tsx
// template
<input 
  [imask]="imaskOptions"
  [unmask]="false"
  (blur)="onBlur($event)"
  (focus)="onFocus($event)"
  (accept)="onAccept($event)"
  (complete)="onComplete($event)"
/>

// class 
imaskOptions = {
  mask: "00/00/0000", 
  lazy: this.isLazy, 
}

isLazy = false

onBlur() {
  this.isLazy = true
}

onFocus() {
  this.isLazy = false
}
```

is there a recommendation to achieve something like this?

**Comment by danielreiser** [comment]
You can get hold of the imask instance via the directive and then use the mask.updateOptions({}) method.
```
@ViewChild('imask', { read: IMaskDirective }) imask: IMaskDirective<MaskedPattern>;

public clear(): void {
  this.imask.updateOptions({...});
}
```

**Comment by shateeshb** [comment]
thanks!

**Comment by shateeshb** [comment]
thanks!

**Comment by dstj** [comment]
Isn't there a `maskRef` missing in there? The correct syntax seems to be (w/ v6.0.7):

```
this.imask.maskRef.updateOptions({...});
```
