### ISSUE TITLE
Element value was changed outside of mask. Syncronize mask using `mask.updateValue()` to work properly.

### ISSUE THREAD

**Issue by JuJoGuAl** [uNmAnNeR/imaskjs#386]
Have Inputs with date mask, but also with Boostrap datepicker, so when the user clic on the Input it shows "Element value was changed outside of mask. Syncronize mask using `mask.updateValue()` to work properly." but it only open de picker.

Why this happend?

The code
```
var momentDates = 'DD/MM/YYYY';
var mask_dates = {
        mask: Date, //Habilita la Mascara de fechas
        pattern: momentDates,
        lazy: true,
        format: function (date) {
            return moment(date).format(momentDates);
        },
        parse: function (str) {
            return moment(str, momentDates);
        },
        blocks: {
            YYYY: {
                mask: IMask.MaskedRange,
                from: 1500,
                to: 9999,
            },
            MM: {
                mask: IMask.MaskedRange,
                from: 1,
                to: 12
            },
            DD: {
                mask: IMask.MaskedRange,
                from: 1,
                to: 31
            },
        },
    }
$obj = jQuery('.dates'); (that is a each, but for the example)
$obj.datepicker();
$obj[0]["mask"] = new IMask(document.getElementById($obj.prop('id')),mask_dates).on("accept", function() {
    $obj[0]["mask"]["_unmaskedValue"] = moment(($obj[0]["mask"].value)+" 00:00", "DD/MM/YYYY HH:mm").unix();
});
```

**Comment by uNmAnNeR** [comment]
hi, probably this question should be addressed to bootstrap team. imask does not fire any change events on focus

**Comment by JuJoGuAl** [comment]
Whas the datePicker, Because somethimes u can choose the date from a Picker (boostrap picker) and somethimes you cann writte the date, so, when the user choose the date from Picker? how i can update the input?

**Comment by Dmitrevicz** [comment]
> so, when the user choose the date from Picker? how i can update the input?

@JuJoGuAl hi, I found out useful to call this two functions to update mask object (when input was changed somewhere else in js): 
```
mask.updateValue();     // update model from view
mask.updateControl();   // update view from new model
```

**Comment by JuJoGuAl** [comment]
> > so, when the user choose the date from Picker? how i can update the input?
> 
> @JuJoGuAl hi, I found out useful to call this two functions to update mask object (when input was changed somewhere else in js):
> 
> ```
> mask.updateValue();     // update model from view
> mask.updateControl();   // update view from new model
> ```

But it doesn't work for me, can you add some example?

**Comment by Dmitrevicz** [comment]
@JuJoGuAl, sorry, I don't have experience working with date. Don't really think it may help a lot now, but here is my case with phone input

```
var phoneMask = new IMask(
    document.getElementById('phone-mask'), {
    mask: '+{375}(00)000-00-00'
});
$("#phone-mask").val("+375112223344");
phoneMask.updateValue();   // update model from view
phoneMask.updateControl(); // update view from new model
```
