### ISSUE TITLE
[Question] Validating specific string "at once" with multiple mask selection

### ISSUE THREAD

**Issue by icaroscherma** [uNmAnNeR/imaskjs#389]
Hey guys,

I was kind of unhappy with the input wrapper so I did my own, but instead of using it only for the input, I'm also using it to standardize old phone numbers on the database. So as I pull them off the DB, I apply the mask as the code below:

### Example code
```JS
const phoneMask = IMask.createMask({
  mask: [
    {mask: '+61 - 0 - 0000 - 0000', startsWith: '61'},
    {mask: '+1 (000) 000 - 0000', startsWith: ''}, // fallback one ;)
  ],
  dispatch: (appended, dynamicMasked) => {
    const number = (dynamicMasked.value + appended).replace(/\D/g,'');
    console.log(number);
    return dynamicMasked.compiledMasks.find(m => number.indexOf(m.startsWith.substr(0, number.length)) === 0);
  },
};

const valueFromDb = '2500000000';
const maskedValue = phoneMask.resolve(valueFromDb);
```

### `console.log()` output
```
2
25
250
2500
25000
250000
2500000
25000000
250000000
2500000000
```

Is there another option to apply the mask `at once` without looping it through the string?

**Comment by uNmAnNeR** [comment]
hi, hope not being too late.
But yes, dispatch is applied for each char one by one. What do you mean saying `at once`? mask should look at every char to check.

**Comment by icaroscherma** [comment]
If I already have the whole number stored in one string, why bother looping it through the same function?
PS.: I'm talking when I just want to `sanitize` a number, nothing related to a bi-directional input handling.

**Comment by uNmAnNeR** [comment]
sanitize internally uses same logic as mask on input. So if you want to just sanitize probably it's better to handle this case manually with some regex  for instance

**Comment by icaroscherma** [comment]
It's how I'm handling it after I checked this behaviour, it was lagging to sanitize a long list of items.
But it would be nice to use the same library to keep "a single source of truth" (a single mask array for every component) to both sanitize and resolve the input.

I think maybe a quick change and add a method like `resolve()` that doesn't loop each character on the dispatch method, it only dispatches once.
