### ISSUE TITLE
Reactjs onAccept have lag

### ISSUE THREAD

**Issue by Mrezagolbaba** [uNmAnNeR/imaskjs#391]
I used this input in react like below 

``` 
       <IMaskInput
        spellCheck={false}
        value={inputValue}
        defaultValue={inputValue}
        blocks={maskTypes}
        mask={maskType}
        type="text"
        onAccept={
          (value, mask) => onChangeHelper(value)}
        {...{
          name,
          ref: (r) => onRef && onRef(r),
          className: `form-control mask-input ${inputClassName}`
        }}
      />
```

but its have lag when user getting typing something.is it normal behavior or bug?
for mask type, I used regex like below 

```
    noneDashedCode: {
      mask: "noneDashedCode",
      lazy: false,
      overwrite: true,
      autofix: true,
      blocks: {
        noneDashedCode: {
          mask: /^[a-zA-Z0-9]{0,10}$/,
        },
      },
    },
```
is tis true? thanks for you help

**Comment by uNmAnNeR** [comment]
Hi. `onAccept` method is bound directly to native `input` event and it is synchronous. So i suppose there should be no lag from imask side. But if mask is quite complex then i think it can be laggy. BTW I did not do perfomance tests. But in your mask looks simple, so no ideas why it has lag
