### ISSUE TITLE
Date masks not accepting all chars!

### ISSUE THREAD

**Issue by xeroxstar** [uNmAnNeR/imaskjs#392]
I am trying to achieve something simple but ended up here, i need the input will display a date in this format 'YYYY/MM/DD',  here is the code:

```
 IMask(input, {
                                mask: Date,
                                lazy: false,
                                overwrite: true,
                                autofix: false,
                                pattern: 'Y/`m/`d',
                                blocks: {
                                    d: { mask: IMask.MaskedRange, placeholderChar: 'D', from: 1, to: 31, maxLength: 2},
                                    m: { mask: IMask.MaskedRange, placeholderChar: 'M', from: 1, to: 12, maxLength: 2},
                                    Y: {
                                        mask : IMask.MaskedRange,
                                        placeholderChar: 'Y',
                                        from : 1900,
                                        to   : 5999,
                                        maxLength: 4
                                    }
                                }
})
```

the mask is working but i can't type the full date in the input, the input accepts all chars except the last one, so from  'YYYY/MM/DD' i can write in the input only to  '2020/08/0D' ( where is D it where the filed stops accepting the user input)

**Comment by uNmAnNeR** [comment]
Hi, please read the guide for date mask. For custom pattern you have to provide `parse` and `format` callbacks.

**Comment by jimyhdolores** [comment]
@uNmAnNeR  I did what the documentation indicates, but I still have the same problem, do you have an example?

**Comment by uNmAnNeR** [comment]
@jimyhdolores there is an example https://imask.js.org/guide.html#masked-date which is working fine
