### ISSUE TITLE
Titlecase mask

### ISSUE THREAD

**Issue by addun** [uNmAnNeR/imaskjs#393]
Hi,
how can I create a **titlecase** mask? I tried to do it by **prepare** function but is doesn't work like I expected.

<s>Demo: https://stackblitz.com/edit/angular-imask-sraqwy?file=app%2Fapp.component.html</s>

Is any eazy way to do it?

Edit: **What is wrong with this solution?** Try edit something in the input. Something in the middle. All values are mixed.

I prepared another example where I show how it works in better way (the second input):
https://stackblitz.com/edit/angular-imask-3jcyat?file=app%2Fapp.component.ts

I tried to use this regex with IMask but i dont have idea how to do it.

**Comment by uNmAnNeR** [comment]
Hi! For Me It Seems Working As Expected :)
What is not working exactly?

**Comment by addun** [comment]
> Hi! For Me It Seems Working As Expected :)
> What is not working exactly?

Thanks For Your Time! I Edited My Question. Take A Look If You Have Got Time.

**Comment by uNmAnNeR** [comment]
https://stackblitz.com/edit/angular-imask-dht4kf?file=app/app.component.ts
You Are Welcomed

**Comment by addun** [comment]
I tried to use your idea in my app but it doesn't work.
In my demo is installed _angular-imask@**3.4.0**_, but in my project i use _angular-imask@**6.0.5**_. I didn't check that before. Sorry for that 😞 

I created new demo with angular@10 and angular-imask@6.0.5. In comments I have written what is wrong.

- App broke if text is very long and you edit text at beginning
- IMask block me to write if you edit before upper case


New demo: https://stackblitz.com/edit/angular-ivy-suncwg?file=src%2Fapp%2Fapp.component.ts
