### ISSUE TITLE
Email mask

### ISSUE THREAD

**Issue by olegKusov** [uNmAnNeR/imaskjs#396]
Can you add email mask example to official docs?

I wanna have something like this 
![image](https://user-images.githubusercontent.com/28058268/90978406-643eb200-e556-11ea-8e1b-1f8fef1bffc2.png)
so text before @ must be with dynamic length. and if user type '@' then mask must understand it and automatically shift left side '___' to '@'. Same logic must be for text after '@' and before dot (dynamic text input with smart adjustments).

example.

![image](https://user-images.githubusercontent.com/28058268/90978457-c5ff1c00-e556-11ea-9798-5795190c9afa.png)

**Comment by uNmAnNeR** [comment]
i don't see any example to add :) nice exercise, but not for me ;)
PR's are welcomed
