### ISSUE TITLE
Using latin characters with iOS Pinyin keyboard bounces input

### ISSUE THREAD

**Issue by jgriffin316** [uNmAnNeR/imaskjs#397]
This is reproducible on https://imask.js.org/. To reproduce do the following:

1. With an iPhone 8, 9, 10 or XR go to Settings > General > Keyboard > Keybords > Add New Keyboard and add "Chinese, Simplified - Pinyin".
2. Using the Pinyin keyboard open up the default iPhone browser and navigate to https://imask.js.org/.
3. In the first example (Russian postal code) type "a", then type a number.

The result is that you will see the number repeated. If you type another number you will see both numbers repeated.

**Comment by jgriffin316** [comment]
There are also issues with the "Japanese - Kana" keyboard.

**Comment by uNmAnNeR** [comment]
Sorry guys, no idea how to handle this. Any help are very welcome

**Comment by daniellizik** [comment]
@uNmAnNeR i will take a look, i also need to handle double byte character input for japanese clients at my company

**Comment by uNmAnNeR** [comment]
should be fixed in v7.3.0 (https://github.com/uNmAnNeR/imaskjs/commit/3a390bb1889f660bc12d9c233a993a23e750aea9)
