### ISSUE TITLE
If both min and max dates present, imask.resolve bugs out

### ISSUE THREAD

**Issue by sylenien** [uNmAnNeR/imaskjs#398]
Версия **6.0.5**

Если в маске присутствуют одновременно min и max параметры как даты, то последние 4 символа даты не вводятся вообще.
Возможно, тоже самое что и в #314 
```javascript
const testComponent = () => { 
      const [value, setValue] = useState('')

   const inputMask = IMask.createMask({
          mask: Date,
          min: new Date('2020-09-04'),
          max: new Date('2020-09-06'),
      });

   const onChange = (e) => {
    
      const resolved = inputMask.resolve(e.target.value);

      console.log(e.target.value, resolved)  // <=== 04.09.2, 04.09.
      setValue(resolved)
  }
  return (
      <input id="test" type="text" onChange={onChange} value={value}>
  )
}
```

Ломается даже если вводимая дата больше минимальной, но меньше максимальной

**Comment by sylenien** [comment]
UPD: проблема связана с тем, что min: new Date пересоздавался на инпут и маска спешит сравнить учитывая часы, минуты и секунды

**Comment by uNmAnNeR** [comment]
ну я же для тебя написал в доке

> Please note
> if you set pattern option, then you also have to provide format and parse options.
