### ISSUE TITLE
Example of how to use IMask without element

### ISSUE THREAD

**Issue by plashenkov** [uNmAnNeR/imaskjs#40]
Some example of how to use IMask without DOM element is needed

Often we may need to convert some value to a formatted one. For example, a phone number. I get it from a DB and want to display to a user in a formatted style. How to do that by not involving real DOM input elements?

**Comment by plashenkov** [comment]
Is this the right way to do that?

```
const phoneMasker = IMask.createMask({
  mask: '+7 (000) 000-00-00'
});

const formattedPhone = phoneMasker.resolve('71234567890');
```

**Comment by uNmAnNeR** [comment]
exactly.
Also mask keeps state after calling `resolve` and `unmaskedValue`, `value`, `rawInputValue` properties are available.

**Comment by plashenkov** [comment]
When using a real DOM element, the unmask option defines how input value will be interpreted. For example:

mask is `'+7 (000) 000-00-00'`  
value is `'71234567890'`

when `unmask=false`, we get the correct result: `+7 (123) 456-78-90`  
when `unmask=true`, we get `+7 (712) 345-67-89`

This is in the case of real DOM element. When I use `IMask.createMask(...)` and pass `unmask` option to it, I do not have this behavior. How to get the same behavior in both cases?

**Comment by plashenkov** [comment]
Sure I can use `+{7}` instead of `+7` and it works, but why behavior differs?

**Comment by uNmAnNeR** [comment]
There is no `unmask` option in a guide. It relates only to plugins.
Use `unmaskedValue` property to do unmasking.

```javascript
const phoneMasker = IMask.createMask({
  mask: '+7 (000) 000-00-00'
});

const formattedPhone = phoneMasker.resolve('71234567890');
console.log(phoneMasker.value);  // same as formattedPhone
console.log(phoneMasker.unmaskedValue);
```

**Comment by plashenkov** [comment]
Oh, now I understand. Thank you (I use Vue plugin). Some example (even small) in the guide would be very helpful for others though.

P.S. Thanks for the great lib!

**Comment by uNmAnNeR** [comment]
Totally agree. Guide could be done much better. Hope for english speaking community will help.
Thanks :)

**Comment by plashenkov** [comment]
That's great.
