### ISSUE TITLE
thousandsSeperator issue in Safari browser

### ISSUE THREAD

**Issue by xiongdg** [uNmAnNeR/imaskjs#400]
Hi guys!
Once contains thousandsSeperator, the input change event does not fire in Safari browser.
below works fine in chrome, but in Safari
![image](https://user-images.githubusercontent.com/6868812/92385473-89c9df00-f144-11ea-99b8-a73afdcd09e6.png)

[https://stackblitz.com/edit/angular-ivy-b3u5ez](https://stackblitz.com/edit/angular-ivy-b3u5ez)

**Comment by uNmAnNeR** [comment]
see https://github.com/uNmAnNeR/imaskjs/issues/324
