### ISSUE TITLE
How to mask IP Address

### ISSUE THREAD

**Issue by nkovacic** [uNmAnNeR/imaskjs#401]
Hi,

How to mask IP Address, because IP address may be 111.111.111.111 or 11.11.11.11 or 121.11.1.111,

is there any example for this use case?

**Comment by WestBonner** [comment]
Use a regex, like this: /((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\.|$)){4}/i

**Comment by WestBonner** [comment]
A more complete example is:
`
var ipNumber 		= document.getElementById('ipNumber');
var ipNumbe_Mask = new IMask(ipNumber, {
	    mask: [
    {
      mask: 'IP.IP.IP.IP',
      blocks: {
        IP: {
          mask: IMask.MaskedRange,
          from: 0,
          to: 255
        }
      }
    },
    {
      mask: /((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\.|$)){4}/i
    }
  ]
	});
`

See a live example here: [jsfiddle](https://jsfiddle.net/x6vwe8qj/6/)

**Comment by nkovacic** [comment]
It somewhat works, but 10.0.0.0 is not recognized, unfortunately. It should work with 3 or fewer numbers.

**Comment by mint-dev** [comment]
> It somewhat works, but 10.0.0.0 is not recognized, unfortunately. It should work with 3 or fewer numbers.

You can try this [https://ipregex.com/](https://ipregex.com/)

**Comment by avrahamcool** [comment]
I think this is a far better solution:
it gives you the ability to put `0` in each block etc.
if you have a strict restriction for each part of the IP, just add more blocks and configure them accordingly.

```typescript
public options: IMask.AnyMaskedOptions = {
    mask: 'IP.IP.IP.IP',
    blocks: {
      IP: {
        mask: Number,
        scale: 0,
        min: 0,
        max: 255
      }
    }
  };
```

**Comment by tech-meppem** [comment]
> I think this is a far better solution: it gives you the ability to put `0` in each block etc. if you have a strict restriction for each part of the IP, just add more blocks and configure them accordingly.
> 
> ```ts
> public options: IMask.AnyMaskedOptions = {
>     mask: 'IP.IP.IP.IP',
>     blocks: {
>       IP: {
>         mask: Number,
>         scale: 0,
>         min: 0,
>         max: 255
>       }
>     }
>   };
> ```
> 
> Here is an updated fiddle - https://jsfiddle.net/avrahamcool/u2pcbtna/

This works great for input, as the MaskedRange just doesn't 'feel' good when typing with it.
I have 2 questions for more capabilities if possible.

1) Are you able to space out the Number blocks? I did see that Masked Range specifies "but can use placeholder", so I assume Number cannot use placeholders. However, are you able to have lazy=false, which shows the three '.' characters, but have them spaced out a bit, even if only a character apart?

2) Are you able to default a block to 0 when skipped? With what you posted, if you just type '.', it will skip a block. Is it possible that when this occurs, you can default it to 0? I tried using prepare in the block:
```
prepare: (str, masked) => {
    return str === "." ? "0." : str;
},
```
however that only works if the return string is a single character (so 0 not 0.).
I also tried something like:
```
prepare: (str, masked) => {
    if(str === "." && masked.value === "")
        masked.value = "0"
    return str
},
```
but that doesn't work, and you advise against it in https://imask.js.org/guide.html#masked-base anyways.

Any help would be greatly appreciated.



My settings for reference:
```
        radix="."
        mask="IP.`IP.`IP.`IP"
        blocks={{
            IP: {
                mask: Number,
                scale: 0,
                min: 0,
                max: 255,
                radix: '.',
            }
        }}
```

```

**Comment by avrahamcool** [comment]
1. you can use `letter-spacing` in css. but it will get very ugly - because this will also affect the numbers.
I don't think there is a method of seperaing only the dots without breaking the whole things into multiple inputs.
2. I've made some changes based on your configuration - and got it to work.
see it in action here: https://jsfiddle.net/avrahamcool/0vozgcy5/2/

* I've use backtics in the main mask. although I'm not sure what they are really doing. didn't notice any change with or without them, and didn't understand their meaning from the docs.
* the dots are now surrounded with `{}` so they appear in the unmasked value as well. (because they should be part of the final IP)
* I've used `setTimeout` to manually fix the cursor position after tweaking with the value. the whole thing works also without this part - but it looks wierd. I didn't find a better way to change the value and the position. if you find a better way to do that - please share.

final solution looks like this:
 
```javascript
const ipNumber = document.getElementById('ipNumber');
const ipNumber_Mask = new IMask(ipNumber, {
    mask: 'IP{.}`IP{.}`IP{.}`IP',
    blocks: {
        IP: {
            mask: Number,
            scale: 0,
            min: 0,
            max: 255
        }
    },
    prepare: (value, masked) => {
        if(!masked.isFilled && value === '.' && (masked.value === '' || masked.value.endsWith('.')))
        {
            masked.appendTail('0');
            setTimeout(() => ipNumber.setSelectionRange(12, 12), 50);
        }
        return value;
    }
});
```

**Comment by avrahamcool** [comment]
I found a clean way to fill the zeroes without tweking the library.
but for some reason. the library keeps complaining about me trying to set 'eager' and 'overwrite' option.
you can see it in action here: https://jsfiddle.net/avrahamcool/0vozgcy5/6/

I'm using a combination of dynamic mask, and blocks.
each block can be the litteral '0', or a number between 0-255.

```javascript
const ipNumber = document.getElementById('ipNumber');
const ipNumber_Mask = new IMask(ipNumber, {
    mask: 'IP{.}`IP{.}`IP{.}`IP',
    blocks: {
        IP: {
            mask: [
                {
                    mask: "\\0"
                },
                {
                    mask: Number,
                    scale: 0,
                    min: 0,
                    max: 255
                }
            ]
        }
    }
});
```

**Comment by tech-meppem** [comment]
> 1. you can use `letter-spacing` in css. but it will get very ugly - because this will also affect the numbers.
>    I don't think there is a method of seperaing only the dots without breaking the whole things into multiple inputs.
I'm using the react version, so I think I can just change the style based on the value.

> * I've use backtics in the main mask. although I'm not sure what they are really doing. didn't notice any change with or without them, and didn't understand their meaning from the docs.
I believe they prevent shifting the numbers on deletion between blocks. So if you have the ip '222.111.111.0', and then deleted part of the '222', then it prevents the 1s from being shifted backwards into the first section.

> I found a clean way to fill the zeroes without tweaking the library. but for some reason. the library keeps complaining about me trying to set 'eager' and 'overwrite' option. you can see it in action here: https://jsfiddle.net/avrahamcool/0vozgcy5/6/
> 
> I'm using a combination of dynamic mask, and blocks. each block can be the litteral '0', or a number between 0-255.
This works pretty much perfectly, thank you for your help.

**Comment by swb21** [comment]
On version 7.6.1 works perfectly:
```
const ipMaskOptions = {
	mask: "IP{.}`IP{.}`IP{.}`IP",
	blocks: {
		IP: {
			mask: Number,
			min: 0,
			max: 255,
			scale: 0, // digits after point, 0 for integers
			signed: false // disallow negative
		}
	},
	prepare: (typedChar) => {
		return typedChar.match(/[\d.]/) ? typedChar : "";
	},
};
```

**Comment by Harted** [comment]
Thanks, this helped me a lot as a starting point. 

I was however annoyed by the ability to enter an infinite amount of zero's, and zero's leading zero and other numbers. I saw the 0's disappear 'onBlur' but I wanted it formatted while inputting the numbers. 

```tsx
    <IMaskInput
      mask="IP.IP.IP.IP"
      blocks={{
        IP: {
          mask: IMask.MaskedNumber,
          min: 0,
          max: 255,
          scale: 0
        }
      }}
      prepare={(char, mask) => {
        // Only accept numbers and dots. 
        // When entering an invalid character it would fill the input with the remaining dots
        // without any numbers inbetween them.
        const isValidChar = /[\d\.]/.test(char)
        if (!isValidChar) return ''

        // No number can lead with a zero
        const parts = mask.displayValue.split('.')
        const lastPart = parts.at(-1)
        if (lastPart && lastPart.length === 1 && lastPart === '0') {
          // Only add the character after the . when not entering the last number "0.0.0.<last_number>"
          return parts.length < 4 ? `.${char}` : ''
        }

        return char
      }}
      onAccept={(value, mask) => ... }
    />
```
