### ISSUE TITLE
[angular-imask] Handle null value in imask pipe

### ISSUE THREAD

**Issue by ivarorn85** [uNmAnNeR/imaskjs#406]
imask pipe should be able to handle null.  It could return empty sting or null in that case. 

It throws this error:
![image](https://user-images.githubusercontent.com/6479793/95473465-a8a1d800-0973-11eb-826d-f377e182ed14.png)

It's possible to fix it here : [https://github.com/uNmAnNeR/imaskjs/blob/master/packages/angular-imask/src/imask.pipe.ts](url)
![image](https://user-images.githubusercontent.com/6479793/95474064-3bdb0d80-0974-11eb-98b4-e1a7be98ae6b.png)

or here: [https://github.com/uNmAnNeR/imaskjs/blob/master/packages/imask/src/masked/pipe.js](url)
![image](https://user-images.githubusercontent.com/6479793/95474255-704ec980-0974-11eb-98d5-891c00b817cf.png)

**Comment by uNmAnNeR** [comment]
why it should? SOME of masks can handle null in `typed` mode, but in general i don't think so.
