### ISSUE TITLE
Can't run Jest in Angular 8 when using manual imports

### ISSUE THREAD

**Issue by gamesgil** [uNmAnNeR/imaskjs#407]
When importing IMask into an Angular component, i.e.
`import IMask from 'imask/esm/imask';`

and running a test on an auto-generated spec file, I'm getting the following error:

```
Test suite failed to run

    C:\Users\gs1109\WebstormProjects\ocp-ui-fe\node_modules\imask\esm\imask.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import './_rollupPluginBabelHelpers-3c58f0e3.js';
                                                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    SyntaxError: Unexpected string

      2 | import {FormBuilder, Validators} from '@angular/forms';
      3 | // tslint:disable-next-line:no-implicit-dependencies
    > 4 | import IMask from 'imask/esm/imask'; // NOSONAR
```

Any suggestions on how to overcome? TIA.

**Comment by cgatian** [comment]
@gamesgil did you ever find a solution?

**Comment by voskresla** [comment]
@gamesgil did u try `transformIgnorePatterns: ['/node_modules/imask)']`

**Comment by gamesgil** [comment]
> @gamesgil did you ever find a solution?

I did. Not sure what made it work eventually, but this code runs:
`TestBed.configureTestingModule({
            declarations: [VatComponent],
            imports: [ReactiveFormsModule],
            schemas: [NO_ERRORS_SCHEMA]
        })
            .compileComponents();`
