### ISSUE TITLE
How can I set a Mask with Placeholder 

### ISSUE THREAD

**Issue by jalopez526** [uNmAnNeR/imaskjs#409]
Im trying to archive something like this in React: http://archive.conductiva.com/files/demos/maskedin/index.html

It's a mask that remains the placeholder while typing. Is there a way of getting this done with imaskjs?

**Comment by guilhermewaess** [comment]
What error are you getting? I think there are a bunch of examples on the docs about how to do it

**Comment by jalopez526** [comment]
> What error are you getting? I think there are a bunch of examples on the docs about how to do it

Could you please show me one? I'm quite new to the lib, haven't touched everything

**Comment by cgatian** [comment]
@jalopez526 isnt this [Overwrite mode](https://imask.js.org/guide.html#overwrite)?
