### ISSUE TITLE
Issue with regex

### ISSUE THREAD

**Issue by cmnstmntmn** [uNmAnNeR/imaskjs#410]
hey, i'm trying to add a condition to an input to accept only valid version numbers.

i found this regex on [semver.org](https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string)

```
/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
```

and i'm trying to use it like

```js
{
  mask: /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
}
```

for whatever reason i can't input anything, i have tried using a function

```js
        mask: function (value) {
            return /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/.test(value) &&
              value.split('').every(function(ch, i) {
                var prevCh = value[i-1];
                return !prevCh || prevCh < ch;
              });
          }
```

but withoud any luck.
any ideeas?

thank you.

**Comment by polianomartini** [comment]
@cmnstmntmn something progressed? I have the same question.

**Comment by cmnstmntmn** [comment]
@polianomartini, nope

**Comment by FckYeah** [comment]
@cmnstmntmn @polianomartini It won't work, guys. The mask function verifies typed or pasted value character by character. So, you should make a regex that will return `true` for every possible valid character either use a pattern mask with well-defined blocks either use a function mask. I see no other way how to deal with it instead. 🤷‍♂️
