### ISSUE TITLE
imask should be a peer dependency in plugin libs

### ISSUE THREAD

**Issue by cgatian** [uNmAnNeR/imaskjs#411]
Forgive me if I'm totally wrong on this... But shouldn't imask be listed as a peer dependency in the plugin lib's package.json?

If I use the angular-mask plugin and also want to make use of imask's core features I must install both packages (imask and angular-mask). This is because angular-mask does not expose the imask API. Now I have to make sure to keep those versions in lock step, otherwise I could potentially import duplicated code.

**Comment by uNmAnNeR** [comment]
already tried this, just believe me better to go in sync.
plugins installs `imask` dependency as well but implicitly
