### ISSUE TITLE
Remove placeholders on backspace

### ISSUE THREAD

**Issue by cgatian** [uNmAnNeR/imaskjs#414]
Given a simple mask
```
mask = {
    mask: '0-0',
    placeholderChar: '-',
};
```
User input:
"0" => "0"
"0" => "0-0"
Backspace => "0-"

Is it possible for the masked value to be "0" without the placeholder?

**Comment by frkntplglu** [comment]
Could you solve this problem? I also want to remove all letters when pushing backspace but I couldn't.

**Comment by uNmAnNeR** [comment]
fixed in 165c1a8d29955fa8e7cfa05029fdcd6b97930fdd with `eager` option
