### ISSUE TITLE
Weird behavior when typing first number by pattern mask with fixed value 

### ISSUE THREAD

**Issue by zhaseo1** [uNmAnNeR/imaskjs#416]
**Configuration**
mask: {34567}-000-000
lazy: true

**Use Case scenario:**
The first number when i key in, 1 for example, i am expecting the field to be 34567-1 where the fixed value will be automatically append in front of the first value that keyed in. The result is as expected in this case.

However, when I try to key in the first number with any number that is part of the fixed part, it will not works as expected.
For example, typing 3 as the first number. It it showing 3 instead of 34567-3.

**Expected result: 34567-3
Actual result: 3**

I know I can set lazy as false then the fixed part will be there, but I do not want to show the value until the user first key in as that is an optional field.

**Comment by uNmAnNeR** [comment]
fixed in 165c1a8d29955fa8e7cfa05029fdcd6b97930fdd with `eager` option

**Comment by gterras** [comment]
Great news do you plan to make a release soon ?

**Comment by uNmAnNeR** [comment]
@gterras give a try 6.3.0-alpha.0
