### ISSUE TITLE
minification error caused by regular expression

### ISSUE THREAD

**Issue by DRiFTy17** [uNmAnNeR/imaskjs#417]
We're running into an issue using this library with ASP.NET MVC bundling/minification (specifically in System.Web.Optimization). While I do think the proper thing to do is fix the minifier in that .NET package to support this (since the regex you're using is valid JavaScript), it appears support for it is lacking which isn't promising, and a small change to a regular expression in `imask` would solve it for us.

The error is occurring due to the syntax used in the regular expression here (which again, is valid JavaScript):
https://github.com/uNmAnNeR/imaskjs/blob/db7a14d05aaad90c8b80362ee074418a872886bd/packages/imask/src/core/utils.js#L71

The output we get after MVC takes over on the minification during its bundling process is the following:
```
function escapeRegExp(str) {
  return str.replace(/([.*+?^=!:${}()|[\]/\\])/g, '\\$1');
} // cloned from https://github.com/epoberezkin/fast-deep-equal with small changes

function
(72825,22-43): run-time error JS5017: Syntax error in regular expression: /([.*+?^=!:${}()|[\]/
(15775,3-15): run-time error JS1018: 'return' statement outside of function: return false
(15770,5-16): run-time error JS1018: 'return' statement outside of function: return true
(15767,52-64): run-time error JS1018: 'return' statement outside of function: return false
(15763,62-74): run-time error JS1018: 'return' statement outside of function: return false
(15759,29-41): run-time error JS1018: 'return' statement outside of function: return false
(15758,29-64): run-time error JS1018: 'return' statement outside of function: return a.toString() == b.toString()
(15755,25-37): run-time error JS1018: 'return' statement outside of function: return false
(15754,25-58): run-time error JS1018: 'return' statement outside of function: return a.getTime() == b.getTime()
(15772,5-41): run-time error JS1018: 'return' statement outside of function: return a.toString() === b.toString()
(15749,21-33): run-time error JS1018: 'return' statement outside of function: return false
(15746,5-16): run-time error JS1018: 'return' statement outside of function: return true
(15743,40-52): run-time error JS1018: 'return' statement outside of function: return false
(15740,31-43): run-time error JS1018: 'return' statement outside of function: return false
(15734,16-27): run-time error JS1018: 'return' statement outside of function: return true
(15730,22-43): run-time error JS5017: Syntax error in regular expression: /([.*+?^=!:${}()|[\]/
```

Which causes this error at runtime (due to the bad output):
```
Uncaught SyntaxError: Function statements require a function name
```

We believe the simple fix is to escape the forward slash in the regex:
```
function escapeRegExp(str) {
    return str.replace(/([.*+?^=!:${}()|[\]\/\\])/g, '\\$1');
}
```

This does fix the issue for us, and I don't believe it will cause any adverse side effects. I can submit a PR for this, but I wanted to get some thoughts on it first. Thanks!

**Comment by uNmAnNeR** [comment]
@DRiFTy17 hi, no prob, no idea, go PR and thanks
