### ISSUE TITLE
Remove mask prefix

### ISSUE THREAD

**Issue by bloodhawk** [uNmAnNeR/imaskjs#418]
Taken from one of the examples at https://imask.js.org/:

![Screen Shot 2020-11-23 at 4 31 32 PM](https://user-images.githubusercontent.com/7389373/100017753-6872a980-2da9-11eb-9bed-06f6279d21ae.png)
![Screen Shot 2020-11-23 at 4 31 26 PM](https://user-images.githubusercontent.com/7389373/100017757-6872a980-2da9-11eb-9774-4426681c1025.png)

When hitting backspace with all chars selected in the input, I would expect everything to be cleared out and leave a blank input. However this is not the case. Is there a setting to allow this? Same issue occurs with `mask: '(000) 000-0000'` which I'm attempting to use.

**Comment by trazek** [comment]
I am also having this exact issue

**Comment by trazek** [comment]
I am going to experiment with comparing the unmasked and masked value to know when to delete

**Comment by hassanasad** [comment]
I used to do it like this previously:
```
mask: [{ mask: '' }, { mask: '(000) 000-0000' }]
```
It switches to blank mask when nothing was in the field. However lately i started having issues with this method in Angular 11.2+
If you do not use Angular you can try it.

**Comment by sumegha26** [comment]
I am also facing same issue, when I hit backspace last char or mask remains in Input, any workaround or config for Angular latest on this ?

**Comment by uNmAnNeR** [comment]
fixed in #606
