### ISSUE TITLE
Unmask field based on select onChange event

### ISSUE THREAD

**Issue by cbartellds** [uNmAnNeR/imaskjs#42]
I am using this plugin to mask a phone field. 

What I am hoping to do is only have the mask apply if a user's country is the US. So if a user selects a country, which is not the US, in the dropdown, the mask will go away.

I am not exactly sure if using destroy() is the correct method or if I am even using it correctly, or if there is a better way to do this ... 

This is my code:

`<script src="https://unpkg.com/imask"></script>
<script type="text/javascript">
    document.addEventListener("DOMContentLoaded", function () {
        var phoneMask = new IMask(document.getElementById('billing:telephone'), {
          mask: '0000000000',
          lazy: false
        });
    });

    function resetPhone(CountryCode) {
        if(CountryCode !== "US") {
            var phoneMask = new IMask(document.getElementById('billing:telephone'), { mask: Number });
            phoneMask.destroy();
        }
    }
</script>`

After I change the country and click in the phone field, when I start to type, I get this warning in Chrome: 

input.js:181 Uncontrolled input change, refresh mask manually!
_saveSelection @ input.js:181
(anonymous) @ prototype.js?q=2018021301:391

Any suggestions would be great. Thanks for your help!

**Comment by uNmAnNeR** [comment]
In this case you could use dynamic mask with custom `dispatch` option.
Did not get why in `resetPhone` you create mask and destroy it immediately.
Btw in complex cases it should not be a problem to destroy and reapply mask.
Please format your code.
