### ISSUE TITLE
Mask with RegEx

### ISSUE THREAD

**Issue by polianomartini** [uNmAnNeR/imaskjs#420]
I'm trying to create a mask for a Brazilian document (RG) in the following format:

12.123.123-1

The last digit can be a number between 0-9 or the character X.

I did it this way:

`IMask(element, {
    mask: /^[0-9]{2}\.[0-9]{3}\.[0-9]{3}\-[0-9]|X{1}$/,
    lazy: false
})`

However, the element input does not receive any characters.

What am I doing wrong?

**Comment by guillaumebras** [comment]
Hi ! 
As stated in the other ticket, the Regexp should 'always' be respected (also while typing).
The following mask would do: 
>   mask: /^[0-9]{0,2}\.?[0-9]{0,3}\.?[0-9]{0,3}-?[0-9X]{0,1}$/, 
(but not enforcing the dots and dash, that being said, other input masks methods might do the job better)
Updated exemple: 
https://jsfiddle.net/Lu0nh19f/
