### ISSUE TITLE
react-imask / pass mask as second argument to onFocus/onBlur

### ISSUE THREAD

**Issue by khanilov** [uNmAnNeR/imaskjs#421]
Hello,

I am using `react-imask` to create reusable `InputMasked` component very similar to one in docs. This `InputMasked` component used in several _implementation details_ components like `InputNumber`, `InputPhone` & etc.

In order to improve UX on my `InputNumber` component I need to clear input on focus, if current value is `0`.

I've tried next approach:
```
<InputNumber
  innerRef={inputElRef}
  value={inputValue}
  onChange={value => onChange(value))}
  ...
  onFocus={event => {
    if (!inputValue) {
      inputElRef.current.value = '';
    }

    onFocus && onFocus(event);
  }}
/>
```

But this is working incorrectly - no matter what I type in cleared input, 0 would appear.

It's happen because the inner `IMaskMixin` state value become out of sync and I receive warning in console:
`Element value was changed outside of mask. Syncronize mask using mask.updateValue() to work properly.`

But I have no access to `mask` object since it buried inside `IMaskMixin` instance.
As a workaround, to gain control over mask instance, I could create it on myself in my component and pass it through to `InputMasked`, but this would cross all the beauty of logic delegation between components.

In order to preserve mask logic on IMaskMixin layer and give some control over it on implementation layer, I think, it can be passed as second argument to onFocus/onBlur handlers. Then the solution for my case should be:
```
<InputNumber
  innerRef={inputElRef}
  value={inputValue}
  onChange={value => onChange(value))}
  ...
  onFocus={(event, mask) => {
    if (!inputValue) {
      inputElRef.current.value = '';
      mask.updateValue();
    }

    onFocus && onFocus(event);
  }}
/>
```

What do you think?

**Comment by khanilov** [comment]
I've made a workaround by accessing `maskRef` from class component using ref and passing as second argument to a handlers. But I believe that making this in `IMaskMixin` would be cleaner.

**Comment by uNmAnNeR** [comment]
Hey :) it's too late i know, sorry.

1) there is `maskRef` prop on wrapped component.
2) why not to update state on focus?
