### ISSUE TITLE
How to prevent remove require part of value?

### ISSUE THREAD

**Issue by krutoo** [uNmAnNeR/imaskjs#426]
Hi. First of all thanks for great library. 

How can i prevent remove for example `+7` from value with pattern mask `+{7} (000) 000 00 00`?

**Comment by uNmAnNeR** [comment]
nice question. it could work like to make first part (+7) with `lazy: false`, and second part with `lazy:true`, but that is not working now. But i think you might want to use `prepare` or `complete` callbacks.
