### ISSUE TITLE
[help] Currency mask

### ISSUE THREAD

**Issue by benjamincharity** [uNmAnNeR/imaskjs#43]
I've been trying to implement a currency filter for a bit now with no luck. Hoping that someone can direct me as I'm sure that I am missing something simple..

#### Need

I basically need the built in number mask with a prefixed `$`. And I would like it to work like a normal text mask ie user can type `$32` and it's valid, but if they type just `32` the `$` would be added automatically.

A string mask won't work as it's not flexible enough so I'm looking into the regex or function mask but haven't had much luck.

This regex will check for a valid currency:

```
// 1. '$' is optional
// 2. non-decimal currency is separated by commas ','
// 3. decimal is optional
// 4. if decimal exists, only two trailing numbers are allowed
// 5. leading zeros are not allowed

/(?=.)^\$?(([1-9][0-9]{0,2}(,[0-9]{3})*)|0)?(\.[0-9]{1,2})?$/

Note: using the above regex as my mask will allow `123` and `$123` but will not 
allow any more numbers, a comma or a decimal despite those being valid in the regex.
```

#### Implementation

I am building this in Angular but cannot use the provided Angular directive due to constraints I have for this project. To begin I have basically just copied the `imaskjs` Angular directive in my project (trying to get it working before adding my custom requirements).

I can't seem to find good examples of using a function mask. The only example in the guide shows a function just returning true/false. I was originally thinking that passing a Function to `mask` meant that the function should return a valid mask string. But as it's just returning a boolean, should I be adding my comma separators and `$` in the `prepare` method I pass when creating the mask?

Can someone point me in a direction for this? 🙏

**Comment by uNmAnNeR** [comment]
> A string mask won't work as it's not flexible enough

Yes, because it has fixed length.

> `/(?=.)^\$?(([1-9][0-9]{0,2}(,[0-9]{3})*)|0)?(\.[0-9]{1,2})?$/`

does not work, because for ex. `123.` is not valid. From guide:
> Also make sure that mask or validator works with any of intermediate states, not just final value.

> But as it's just returning a boolean, should I be adding my comma separators and $ in the prepare method I pass when creating the mask?

Probably yes. I dont see other ways now.

**Comment by benjamincharity** [comment]
Thanks for the quick response!

> Also make sure that mask or validator works with any of intermediate states, not just final value.

hmm so maybe I am miss-understanding how the regex match works.. If you take the referenced regex and drop it into https://regex101.com/, both `123` and `$1,123.12` are 'matches' which is why I was thinking it could work.

---

I will try to go down the `prepare()` path. Thanks!
