### ISSUE TITLE
Bug with option lazy: true

### ISSUE THREAD

**Issue by nflorentin** [uNmAnNeR/imaskjs#433]
Hi,

In version 6.0.5, with the option `lazy: true`, when the input is focused, the dom placeholder disappears but the mask is not shown.

If anyone has a workaround for this problem, I would be very grateful :) 

Thanks

**Comment by uNmAnNeR** [comment]
lazy means that you don't want mask placeholder and it does not depend on focus. Toggle `lazy` option on focus if you want to show mask placeholder
