### ISSUE TITLE
Uppercasing part of a value

### ISSUE THREAD

**Issue by cutterbl** [uNmAnNeR/imaskjs#435]
I was able to use the following to mask a Date Time value

```
let mask = 'MM/DD/YYYY hh:mm A'; //[/\d/, /\d/, /\d/, '-', /\d/, /\d/, '-', /\d/, /\d/, /\d/, /\d/];
  let blocks = {
    MM: {
      mask: IMask.MaskedRange,
      from: 1,
      to: 12,
    },
    DD: {
      mask: IMask.MaskedRange,
      from: 1,
      to: 31,
    },
    YYYY: {
      mask: IMask.MaskedRange,
      from: 1850,
      to: 9999,
    },
    hh: {
      mask: IMask.MaskedRange,
      from: 1,
      to: 12,
    },
    mm: {
      mask: IMask.MaskedRange,
      from: 0,
      to: 59,
    },
    A: {
      mask: IMask.MaskedEnum,
      enum: ['AM', 'PM'],
    },
  };
```
And this works fantastic. However, I'd like to allow the user to type upper or lower cased am/pm (which I could allow in the enum), and have it auto convert to uppercase. Is this possible? I thought maybe with a pipe, but no clue how to start that. I'm doing all of this in the React component, using the IMaskMixin.

**Comment by uNmAnNeR** [comment]
hi! not a pipe :) you can use `prepare` callback for such things

**Comment by timneyens** [comment]
@uNmAnNeR Is it possible that this doesn't work in react-imask?
