### ISSUE TITLE
TypeError when creating a pipe

### ISSUE THREAD

**Issue by gustavofabro** [uNmAnNeR/imaskjs#438]
When I try to create a pipe like the documentation says, for instance:

```js
const numberPipe = IMask.createPipe({
  mask: Number,
  scale: 2,
  thousandsSeparator: ' ',
  normalizeZeros: true,
  padFractionalZeros: true
});
```

I got this TypeError:

![image](https://user-images.githubusercontent.com/14109186/107119872-1b12be00-6869-11eb-89bd-fadf4e8e205d.png)

This is just an example, I have also had similar problems with other functions. I'm using IMask 6.0.5 with typescript

**Comment by johanjmoncada** [comment]
Hi guys, are there any news on this? I'm facing the same issue :(

**Comment by uNmAnNeR** [comment]
works on v6.3.0
