### ISSUE TITLE
Testing react-imask

### ISSUE THREAD

**Issue by cutterbl** [uNmAnNeR/imaskjs#439]
So, I noticed a lot of issues writing unit testing against react-imask, specifically when changing the value on the fly

```
fireEvent.change(field, {target: {value: '08/03/2001 11:35 AM'}});
```
When doing this, I could see that the field value had changed
```
expect(field.value).toEqual('08/03/2001 11:35 AM');
```
But noticed that none of my event handlers fired (`onAccept`, `onComplete`, `validate`...).

So, wrote a basic example in [codesandbox](https://codesandbox.io/s/react-imask-change-test-uyb8u), to test this out. Sure enough, if I programmatically set the input value (as React Testing Library does), I could see the change in the field, but my events never fired.

And then I found Issue #318 , which confirmed that it (unfortunately) wouldn't.

Now, I control field 'value' with state, so this is rarely an issue in app, but it is a big problem when testing scenarios where changing the field value should fire some after effect (say, a date comparison to give a notification to the user). It also makes it nearly impossible to test my error validation methods. As in, change to the input should fire `onAccept` and `validate` and (if it's correct) `onComplete`.

How does everyone else handle this? And, what is the barrier? You would expect that an input change (however it was changed) would fire all of the appropriate events.

**Comment by cutterbl** [comment]
As in, a change to the input (regardless of how it was received), should call the `onAccept`, `validate` and (if correct) `onComplete` event handlers.

**Comment by uNmAnNeR** [comment]
@cutterbl  try using `input` event instead. I have no idea when mask needs to handle `change` event besides tests

**Comment by cutterbl** [comment]
Putting this here, unless someone else has issues with testing with react-testing-library.

I was able to handle my testing scenarios by providing a helper function

```
import userEvent from '@testing-library/user-event';
import TestUtils from 'react-dom/test-utils';

function changeInputMaskValue(element, value = '') {
  element.value = value;
  element.selectionStart = element.selectionEnd = value?.length ?? 0;
  TestUtils.Simulate.change(element);
}

export default function changeMaskFieldValue(field, value) {
  userEvent.type(field, value);
  changeInputMaskValue(field, value);
}
```
And then using that function from within my tests
```
it('should change the field', async () => {
    const { getField, queryByText } = await renderTest({
      mask: '000-00-0000',
      id: 'gov-id',
    });
    const field = getField();

    changeMaskFieldValue(field, '456789012');
    const val = await queryByText('456-78-9012');

    expect(val).toBeInTheDocument();
  });
```
I do have to have an 'empty' field to begin with, for some reason, but I can work with this.

**Comment by Patrascu-Lucian** [comment]
The above solution didn't work for me, but I'll leave here a workaround I found: trigger a `blur` event after the `change` event
```
fireEvent.change(field, {target: {value: '08/03/2001 11:35 AM'}});
fireEvent.blur(field);
```

**Comment by BrianBusby** [comment]
The solution that @cutterbl proposed no longer seems to work. This is very problematic for individuals who need to test that typing into a masked input effects change elsewhere in the app.

**Comment by pgruetznergridx** [comment]
@BrianBusby the solution of @Patrascu-Lucian worked for me, can you confirm?

**Comment by evgen-kent** [comment]
does not work any of this for me

**Comment by vbarinov** [comment]
Following code works for me (React@18 imask@7.3.0)

```javascript
fireEvent.focus(fieldInput);
fireEvent.input(fieldInput, { target: { value: newValue } });
fireEvent.blur(fieldInput);
```
