### ISSUE TITLE
bug with Date mask

### ISSUE THREAD

**Issue by SilencerWeb** [uNmAnNeR/imaskjs#44]
There is a bug with Date mask even in [your example](https://jsfiddle.net/corsik/1o6en3Lt/). I can't fill all numbers in the year field(nope, it is not because the year is less than min or more than max)

**Comment by uNmAnNeR** [comment]
My example is fine but this is not because `parse` and `format` callbacks (Y-m-d) dont correspond to `pattern` option (d-m-Y).

**Comment by SilencerWeb** [comment]
@uNmAnNeR well, but I still can't get what is the reason I can't fill all fields, here is a screen with max filled fields http://prntscr.com/ivamp3

**Comment by ryanbuening** [comment]
@uNmAnNeR - I'm having the same issue with the following mask:

```
public dateMask = {
	mask: Date,
	pattern: 'm/`d/`Y'
};
```
It will not let me enter all four digits of the year. I enter `01/01/200`, but the mask will not let me enter the fourth digit of the year.

Also, is the Date mask able to limit the the valid days based on the month? For instance, only allowing 31 days in January, 28 days in February, 30 days in April...etc.

**Comment by uNmAnNeR** [comment]
@SilencerWeb @ryanbuening please provide sources

> Also, is the Date mask able to limit the the valid days based on the month? For instance, only allowing 31 days in January, 28 days in February, 30 days in April...etc.

@ryanbuening answered in #18

**Comment by ryanbuening** [comment]
@uNmAnNeR here is a repo that reproduces the issue: https://github.com/ryanbuening/datemask

**Comment by SilencerWeb** [comment]
@uNmAnNeR I provided an example already https://jsfiddle.net/corsik/1o6en3Lt/

**Comment by uNmAnNeR** [comment]
@SilencerWeb About your example i've already answered [above](https://github.com/uNmAnNeR/imaskjs/issues/44#issuecomment-375644722). It has mistakes in `parse` and `format`.
@ryanbuening custom `pattern` is insufficient and you have to provide your custom `parse` and `format` options. Why this is required in #18

**Comment by ryanbuening** [comment]
@uNmAnNeR I tried the following:

```
public dateMask = {
	mask: Date,
	pattern: 'm/`d/`Y',
	// define date -> str convertion
	format: function (date) {
		let day = date.getDate();
		let month = date.getMonth() + 1;
		let year = date.getFullYear();

		if (day < 10) day = "0" + day;
		if (month < 10) month = "0" + month;

		return [month, day, year].join('/');
	},
	// define str -> date convertion
	parse: function (str) {
		const monthDayYear = str.split('/');
		return new Date(monthDayYear[0] - 1, monthDayYear[1], monthDayYear[2]);
	},
}
```
but I'm still unable to type a four digit year using a `m/d/Y` format. Any ideas what I'm doing wrong?

**Comment by uNmAnNeR** [comment]
@ryanbuening Date constructor [takes year, month, day](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date), not month, day, year

**Comment by uNmAnNeR** [comment]
hope i helped. fill free to reopen

**Comment by svetandrei** [comment]
Hi, pleae help me
```
IMask(el, {
          mask: Date,
          pattern: 'm/`Y',
          blocks: {
            m: {
              mask: IMask.MaskedRange,
              from: 1,
              to: 12,
              maxLength: 2,
            },
            Y: {
              mask: IMask.MaskedRange,
              from: new Date().toLocaleDateString('en', {year: '2-digit'}),
              to: 99,
              maxLength: 2
            }
          },
          lazy: false,
        });
```
I can't enter last digit year 
![image](https://github.com/uNmAnNeR/imaskjs/assets/16918767/a068111c-6fac-4837-a49c-da4cda3eba8c)

What a bug?

**Comment by iankduffy** [comment]
Still seeing this issue event when updating the config to use the one in https://imask.js.org/guide.html#masked-date 

This is my code: 
```javascript
import { useState } from "react";
import { IMask, IMaskMixin } from "react-imask";
import { TextInput } from "ui-library/components/text-input";

const MaskedInput = IMaskMixin(({ inputRef, ...props }) => (
  <TextInput
    {...props}
    ref={inputRef}
  />
));

const formateDate = (date: Date) => {
    return date.toLocaleString('en-GB', { day: '2-digit', month: '2-digit', year: 'numeric' })
}

const MASK = [
    // {mask: ''}, 
    {
    mask: Date,
    lazy: true,
    pattern: 'Y-`m-`d',
    blocks: {
        d: {
            mask: IMask.MaskedRange,
            from: 1,
            to: 31,
            maxLength: 2, 
            placeholderChar: 'D'
        },
        m: {
            mask: IMask.MaskedRange,
            from: 1,
            to: 12,
            maxLength: 2, 
            placeholderChar: 'M'
        },
        Y: {
            mask: IMask.MaskedRange,
            from: 0,
            to: 9999,
            // maxLength: 4, 
            placeholderChar: 'Y'
        },
    },
    format: formateDate,
    parse: (str: string) => {
        const [day, month, year] = str.split('/');
        return new Date(`${year}-${month}-${day}`);
    },
    overwrite: true,
}]

export function NewDateInput({ onChange, defaultValue, ...rest }: any) {
    const [value, setValue] = useState(defaultValue);

    const handleChange = (v: any) => {
        console.log(v)
        setValue(v);
        onChange(v);
    };

    return <MaskedInput {...rest} mask={MASK} onAccept={handleChange} value={value} />;
}
```
