### ISSUE TITLE
Prepare not triggered in react-imask

### ISSUE THREAD

**Issue by timneyens** [uNmAnNeR/imaskjs#441]
Hello,

I am trying to create a mask for an IBAN input. The letters are always uppercase so I am trying to use the prepare option to put them to uppercase, but the prepare function is never called. Is this a known issue or am I missing something. I also noticed following post which says the prepare isn't triggered in tests: https://github.com/uNmAnNeR/imaskjs/issues/439

Is this related?

Kind regards

**Comment by uNmAnNeR** [comment]
please provide an example somewhere to run (js fiddle, etc..)

**Comment by timneyens** [comment]
Here you go: 
https://codesandbox.io/s/react-imask-prepare-tctel?fontsize=14&hidenavigation=1&theme=dark&file=/src/App.js

**Comment by cutterbl** [comment]
comment to follow this question
