### ISSUE TITLE
Random strings formatted

### ISSUE THREAD

**Issue by timneyens** [uNmAnNeR/imaskjs#445]
Hello,

When I use a mask for IBAN and paste a random string, it adapts the input to comply to the IBAN, f.e. if you paste 'BE6asdfasdf987asdfasdf654asdf8539007547034' in following example input it gets modified to be a BE iban. 

https://codesandbox.io/s/react-imask-prepare-tctel?fontsize=14&hidenavigation=1&theme=dark&file=/src/App.js

Is there some way to block this? I tried in the prepare but the `appended` value only gets 1 character at the time and all other params I can find in functions are the already formatted value.

Am I missing something or is blocking this not possible?

Kind regards

**Comment by uNmAnNeR** [comment]
hi! how do you decide what should be blocked?

**Comment by timneyens** [comment]
The expected behaviour for us would be that if (in this case) the 3rd character is not like the mask defines, it pastes nothing or only the first 3 valid characters

**Comment by uNmAnNeR** [comment]
So you want something like break fast after first incompatible symbol. Good idea i think
