### ISSUE TITLE
[question] allow for leading zeros in MaskedRange

### ISSUE THREAD

**Issue by DRiFTy17** [uNmAnNeR/imaskjs#447]
@uNmAnNeR This isn't necessarily an issue, but more of a support question that I'm hoping you could shine some light on. Sorry, I wouldn't normally open an issue for support, but I'm not exactly sure of the best solution.

I am working on a time input mask using `MaskedRange`. It works fairly well as-is (see below), but I'm trying to account for some edge cases in regards to adding leading zeros automatically.

Here is my mask configuration:
```javascript
    {
      mask: 'h:mm AM', // 12-hour time format with just minutes and meridian
      autofix: false,
      overwrite: true,
      lazy: true,
      prepare: (value: string) => value.toUpperCase(),
      blocks: {
        HH: {
          mask: MaskedRange,
          placeholderChar: 'h',
          from: 0,
          to: 23,
          maxLength: 2,
          autofix: true
        },
        h: {
          mask: MaskedRange,
          placeholderChar: 'h',
          from: 0,
          to: 12,
          maxLength: 2,
          autofix: true
        },
        mm: {
          mask: MaskedRange,
          placeholderChar: 'm',
          from: 0,
          to: 59,
          maxLength: 2,
          autofix: true
        },
        ss: {
          mask: MaskedRange,
          placeholderChar: 's',
          from: 0,
          to: 59,
          maxLength: 2,
          autofix: true
        },
        A: {
          mask: MaskedEnum,
          placeholderChar: 'A',
          enum: ['A', 'P']
        },
        M: {
          mask: MaskedEnum,
          placeholderChar: 'M',
          enum: ['M']
        }
      }
    };
```

This works really nicely for the most part, but due to my lack of understanding on the internals of imaskjs, I'm not quite sure the "best" way to automatically prepend a leading zero in the case where say you type a "6" as the first character. Currently, this automatically converts that to a "1" for hours, and "5" for minutes/seconds (due to the `doPrepare` method inside of `MaskedRange` and how its boundaries are set up). I am hoping to have all 1-9 digits automatically get prepended with a "0" so when you type "6", it changes to "06". Any thoughts?

**Comment by DRiFTy17** [comment]
As a last resort, I decided to copy the `MaskedRange` implementation into my project, and after fixing a few typings issues, I was able to replace the following line:
https://github.com/uNmAnNeR/imaskjs/blob/515fd72ee7e9fc700dc2f36eda8f7b39db253a80/packages/imask/src/masked/range.js#L88

With this:
```javascript
else if (Number(minstr) > this.to) prepStr += str[ci].padStart(this.maxLength, '0');
```

This gets me exactly what I need for now! I still wonder if there is a better way using `MaskedRange` directly still though...

Would you be interested in me created a PR to add a new option to the `MaskedRange` class called something like `padLeadingZeros` (defaulting to `false`) and allow for opting-in to this functionality?

**Comment by DRiFTy17** [comment]
Another note I'll add is that for the above to work, I was actually manually forcing a rebuild of the mask in the accept callback. If I don't do that, the above doesn't work properly. Is there a way to update the mask internally after padding the zero to avoid having to do that?

**Comment by uNmAnNeR** [comment]
@DRiFTy17 hi, sorry for being too late.
i think `prepare` callback could be used for that purpose. something like
```
// check if it's a first digit
// check if this digit can be used (1-2 probably can be, others are not)
// if yes then return just string
// if not then return padded string
```

**Comment by DRiFTy17** [comment]
Thank you, I ended up doing something very similar to what you describe here and it worked out great. Appreciate the help.

**Comment by luchn49** [comment]
Hi @DRiFTy17, do you have an example for this case?

**Comment by DRiFTy17** [comment]
@luchn49 I received your email, and provided an example of my implementation.

To recap, I ended up using a custom implementation of `MaskedRange` that extends `MaskedPattern`. I needed some flexibility that the `prepare` callback on `MaskedRange` alone wasn't providing unfortunately... I would like to circle back eventually and create a PR for this to help others create range masks where leading zeros are required.

**Comment by luchn49** [comment]
> @luchn49 I received your email, and provided an example of my implementation.
> 
> To recap, I ended up using a custom implementation of `MaskedRange` that extends `MaskedPattern`. I needed some flexibility that the `prepare` callback on `MaskedRange` alone wasn't providing unfortunately... I would like to circle back eventually and create a PR for this to help others create range masks where leading zeros are required.

@DRiFTy17 I received your help email. It is not entirely fit for our use cases. Anyway, thank you so much for helping. 

Now, I'm trying to handle logic outside the component and pass the value down to it.

Again, thank you so much!

**Comment by luchn49** [comment]
> @DRiFTy17 hi, sorry for being too late.
> i think `prepare` callback could be used for that purpose. something like
> 
> ```
> // check if it's a first digit
> // check if this digit can be used (1-2 probably can be, others are not)
> // if yes then return just string
> // if not then return padded string
> ```

I tried to follow these steps. But I have an issue. 

- Format date `DD/MM/YYYY` 
- Input `9` --> `prepare` checks and changes to `09` 
But I get the value like this: `09D/MM/YYYY`

[You can see here](https://codesandbox.io/s/react-imask-input-box-masks-forked-mmg3l?file=/src/index.js)

**Comment by DRiFTy17** [comment]
@luchn49 Based on your example, you can try something like the following to get the leading zero to work:
```
if (str > 1 && mask.value === "") {
  mask.unmaskedValue = str.padStart(2, '0'); // Pad zero to the value that was entered
  return '.'; // Assume the user entered the separator character since we changed the mask
}
```

You may want to do this based on cursor position so that you can also account for the second segment as well, but this is what I ended up doing and it's working well. One thing I did add to my implementation was to adjust the cursor position to move after separator as well.
