### ISSUE TITLE
Weird Visual Studio Code Error with angular-imask and iMask

### ISSUE THREAD

**Issue by tgfactor** [uNmAnNeR/imaskjs#449]
I don't know when this started but I've started getting this weird Visual Studio Code error in my Angular 11 projects:

"**This component uses a directive which requires an inline type constructor, which is not supported by the current environment. (-998901)**"

The error comes up in the .ts and .html files of the component in error, and I've pinpointed it down to the angular-imask/iMask plugin.  In my component I have a variable as such:

`public moneyMask = {
    mask: '$num',
    blocks: {
      num: {
        mask: 0,
        scale: 2,
        radix: '.',
        normalizeZeros: true,
        thousandsSeparator: ','
      }
    },
    lazy: false
  };`

In my component template I have the following:

`<input type="text"
              id="someId"
              name="someName"
              ....
              [imask]="moneyMask"
              [unmask]="true"
              >`

As soon as I remove the [imask] and [unmask] directives from the input tag, the error goes away, both for the .ts and .html files.  How can I bypass this error in Visual Studio Code, or is this a legit error that needs to be fixed?

**Comment by uNmAnNeR** [comment]
i don't use VS neither Angular, so may be someone else could help
