### ISSUE TITLE
React: Number mask not respecting max value

### ISSUE THREAD

**Issue by GuiRitter** [uNmAnNeR/imaskjs#45]
Hi everyone.

I'm trying to use this library, but I can't get an input field to respect the max value I'm setting. I have something like this:

    this.inputField = <IMaskInput
        className='maskedInputStyle'
        mask={Number}
        unmask={false}
        thousandsSeparator={'\u2009'}
        padFractionalZeros={true}
        min={0}
        max={99999999999999.99}
    />

I still can type much more digits than that. Is it a bug or am I using it wrong?

Thanks in advance.

**Comment by uNmAnNeR** [comment]
Hi, this is a BUG )

**Comment by GuiRitter** [comment]
Thanks for fixing!
