### ISSUE TITLE
Preventing the user from inserting incomplete date

### ISSUE THREAD

**Issue by pbrzosko** [uNmAnNeR/imaskjs#450]
Hi,

how can I make sure, that user always enters proper date?
For example, if only days are entered I would expect month and year to be set from the min value.
I thought that autofix feature is for this, but this seem not to work like that. I would use parse to fix the date, but apparently this method is called only when user enters the last character in the date.

Please give me some hint.

**Comment by uNmAnNeR** [comment]
you can use common `validate` callback to check if value satisfies you condition
