### ISSUE TITLE
Использование 0 в телефоном коде

### ISSUE THREAD

**Issue by blackfoxdeveloper** [uNmAnNeR/imaskjs#455]
Сейчас некорректно отрабатывает (точнее не отрабатывает) 0 при попытке задать его в коде телефона.
Пример:
`var phoneMask = IMask(
    document.querySelector('input[type="tel"]'), {
        mask: '+{380}(000) 000-00-00'
    });`
при попытке начать ввод с любой цифры он подменяет 0 в коде. К примеру, если нажать 1, то получится +381

**Comment by uNmAnNeR** [comment]
потому что 0 надо эспейпить

**Comment by blackfoxdeveloper** [comment]
Можно пример?

**Comment by blackfoxdeveloper** [comment]
Разобрался, спасибо!
