### ISSUE TITLE
Append a character to the end of the value

### ISSUE THREAD

**Issue by leon-lovett-rsi** [uNmAnNeR/imaskjs#456]
I have a use case where I need to append a % to the end of the value inside the input.

I have tried using prepare and commit with no luck.

I have also tried modifying the currency example as follows, but doesn't seem to be working.
The mask is connected to an input with the type of "tel".

`percentMaskOptions = {
    mask: 'num%',
    blocks: {
      num: {
        mask: Number,
        radix: '.',
        scale: 2
      }
  }`

Edit: I've noticed that this will prepend the percent sign:
`mask: '{%}00'`

but this will not append the percent sign to the end:
`mask: '00{%}'`

Is what I am trying to do possible with this library?

**Comment by bfeister** [comment]
For anyone else coming upon this issue, this might be helpful:

https://github.com/uNmAnNeR/imaskjs/issues/302

https://jsfiddle.net/uNmAjs/ayq9u631/
