### ISSUE TITLE
Angular IMask Plugin: [unmask]="true" input of IMaskDirective have no effect

### ISSUE THREAD

**Issue by mihailkuritsyn** [uNmAnNeR/imaskjs#457]
Looks like  [unmask]="true" input of IMaskDirective is not working - masked value returned.

my usage of directive
```
<input [value]="currentValue"
       [imask]="{mask: '000{ }000{ }0000'}"
       [unmask]="true"
       (accept)="onAccept($event)"
       (complete)="onComplete($event)"
/>
```
![image](https://user-images.githubusercontent.com/10944626/110103824-6f9d5080-7db7-11eb-80ca-1de772a76888.png)

Thank you

**Comment by uNmAnNeR** [comment]
hi, it's unmasked value as i see. what do you expect to return?

**Comment by mihailkuritsyn** [comment]
my mask is : '000{ }000{ }0000' 
so, masked value is: '112 312 412'
I expect unmasked value: '112312412' (no spaces)

**Comment by mihailkuritsyn** [comment]
JS API works correct. It reproduced in angular api only:
JS API proof:
![image](https://user-images.githubusercontent.com/10944626/110115004-81d2bb00-7dc6-11eb-92f0-2cddb7bd3cec.png)

**Comment by mihailkuritsyn** [comment]
@uNmAnNeR Hello. Is it possible to fix? Please provide some info.

**Comment by uNmAnNeR** [comment]
@mihailkuritsyn just one question to you. Why are you using curly braces in your mask?

**Comment by mihailkuritsyn** [comment]
according to docs I have to use it for fixed part in unmasked value (https://imask.js.org/guide.html#masked-pattern)

**Comment by uNmAnNeR** [comment]
@mihailkuritsyn but if you did it why then you are saying you don't want to include it in unmasked value?

**Comment by mihailkuritsyn** [comment]
@uNmAnNeR cause I want to pass unmasked value to server.  Unmasked value must not include mask symbols. Are you agree?

**Comment by uNmAnNeR** [comment]
@mihailkuritsyn no i don't. That's why i make it optionally. Remove curly braces and we are done

**Comment by mihailkuritsyn** [comment]
Yep, without curly braces it works as expected, thx.
