### ISSUE TITLE
NumberMask: padFractionalZeros with scale=0 results in showing the decimal separator without any decimal digits

### ISSUE THREAD

**Issue by Mario-Eis** [uNmAnNeR/imaskjs#458]
The title tells the whole tale. And here is a fiddle as well: https://jsfiddle.net/274fmy0q/1/

I think there should be no separator visible when scale is 0. I fixed this by doing 
`padFractionalZeros=padFractionalZeros && scale > 0`
But I guess it would be an easy fix in the codebase.

**Comment by uNmAnNeR** [comment]
thanks for reporting
