### ISSUE TITLE
Неверная позиция курсора на IOS

### ISSUE THREAD

**Issue by Wayfindertm** [uNmAnNeR/imaskjs#461]
Например на телефоне на сайте при фокусе поля (если заполнен телефон), курсор ставится после первой скобки.

Возможно ли сдвигать курсор на место клика или в конец?

**Comment by uNmAnNeR** [comment]
насколько я помню курсор при фокусе попадает в начало, после этого подгоняется маской.

да, я думал делать в конец. Но проблема в том, что на некоторых платформах нормально работает позиционирование в место клика, и сдвиг в конец будет выглядеть нелогично. Соответственно единственный вариант - это делить поведение по платформам, но этим я решил принципиально не заниматься. Поправь меня, если я не прав, но насколько я понял маска отрабатывает как надо, дело в платформе, а патчить платформу и обрастать костылями это путь в никуда.

Короче говоря, могу предложить делать позиционирование на стороне приложения. Определять айос там и прочее, а потом ставить курсор, допустим в конец, и травить маску (см `alignCursor`). Все вроде изи.

**Comment by Wayfindertm** [comment]
Курсор двигает сам плагин маски, разве я не прав? На других текстовых полях курсор становится ровно в место куда ткнул. Есть ли callback после того как отработала маска?

**Comment by uNmAnNeR** [comment]
@Wayfindertm курсор смещает позицию относительно той, в которой он оказался при фокусе. Колбеков нет, обработка синхронная на события. Маска работает на input, позиционирование на фокус
