### ISSUE TITLE
Element value was changed outside of mask. Syncronize mask using `mask.updateValue()` to work properly.

### ISSUE THREAD

**Issue by yabikusensei** [uNmAnNeR/imaskjs#463]
**Hello I am trying to add currency, this is the implemented code**

const maskOptions = {
        mask: `S/ num`,
        blocks: {
          num: {
            // nested masks are available!
            mask: MaskedNumber,
            scale: 2,
            signed: true,
            thousandsSeparator: ',',
            padFractionalZeros: true,
            normalizeZeros: true,
            radix: '.',
            mapToRadix: ['.'],
            min: 0,
            max: 50000,
          },
        },
      };
 this.refMask = IMask(this.refInput, maskOptions);

**but I get this error**

**ui-input-text.entry.js:3052 Element value was changed outside of mask. Syncronize mask using `mask.updateValue()` to work properly.**

**Comment by umairhm** [comment]
@yabikusensei It'll be great if you can set up a working example somewhere on codepen.io or StackBlitz may be.

Apparently, this error occurs when you directly change the value of the masked input using some script or binding. If you have the mask instance, you can use `mask.value` to update the value of the input.

If this doesn't solve, then it's best to please share a working code example.

**Comment by evildevilnova** [comment]
import { Form, } from "antd";
const [form, mask] = Form.useForm();
mask.updateValue()

**Comment by CatherineShemenkova** [comment]
> 

sorry but what is it? how to use? use Form returns only form instance, how you get "mask"?

**Comment by artknight** [comment]
I ended up doing this

```
imask.value = new_value;
imask._onChange(); //undocumented method to trigger the mask to be applied
```
this effectively updates the input field value

hope this helps somebody!

**Comment by aleksandr17051991** [comment]
In the part of the code where you use additional validation, you need to associate the new validation with iMask. Just specify - mask.updateValue().
For Example:

const phoneInput = document.getElementById('phoneInput');
const maskOptions = {
    mask: '+{38}(000) 000-00-00',
    lazy: false
} 
const phoneMask = new IMask(phoneInput, maskOptions);

submitBtn.addEventListener('submit', function() {
  const currentPhone = phoneInput.value

// the place where we apply additional validation

  const isValid = !currentPhone.includes('_') && currentPhone.length === 18;
  if (isValid) {
    do something...
  } else {
    do something...
  }

// in this scope we notify about a new validation

phoneMask.updateValue()
})

All my errors are gone)

**Comment by jonaswebdev** [comment]
> imask._onChange();

It worked for me 👍  thank you

**Comment by kossa** [comment]
I had the same issue, the issue was the type input was "number" but it should "text"
