### ISSUE TITLE
How To Deal With Dates

### ISSUE THREAD

**Issue by cutterbl** [uNmAnNeR/imaskjs#464]
I have a react-imask implementation dealing with Dates. It is very similar to the MomentJS version within the Guide

https://imask.js.org/guide.html#masked-date

But, getting a request to support two differing display formats, both `MM/DD/YYYY hh:mm A` and `MM/DD/YYYY HH:mm`. Basically, they would like if the user did type in the 24 hour format, the control should automatically convert it. The difficult part for me to figure out here is how I would define my `pattern` in this situation. Is it even possible to do this? I know my `format` and `parse` methods will have to change, so support Moment properly parsing the date strings, and it handles multiple formats fairly easily. Just not sure about the `pattern` part here.

**Comment by uNmAnNeR** [comment]
@cutterbl seems more like model level issue, not view responsibility. I think easiest way is always use one format and convert the value somewhere behind. If it should be converted by mask, then in what moment in time?
For different patterns dynamic mask suites well.

**Comment by cutterbl** [comment]
I was able to support this by changing my `pattern` to `MM/DD/YYYY KK:mm[ A]`, and by updating my `onAccept` to handle conversion to Meridiem prior to changing state.
