### ISSUE TITLE
[react-imask] Allow defaultValue props when using the component as "uncontrolled"

### ISSUE THREAD

**Issue by timwangdev** [uNmAnNeR/imaskjs#465]
Currently, there is no way to set the default value of an input element. According to [this line](https://github.com/uNmAnNeR/imaskjs/blob/master/packages/react-imask/src/mixin.js#L123), input `defaultValue` props reads from `this.props.value`. And in [uncontrolled](https://reactjs.org/docs/uncontrolled-components.html) use cases the `value` props is alway left empty, otherwise the `defaultValue` not needed.

Could you have a look at this behavior? Thanks.

**Comment by Aerophite** [comment]
I also have this issue. Does anyone have any suggestions on getting around it?

**Comment by jcdiprose** [comment]
I've managed to work out a solution.. We're using unix timestamps but any format would work once you've converted to Date object.

```
value={(() => {
                const drillDateUnix = 679273200000 // or your source

                if (!drillDateUnix) return ''
                if (drillDateUnix && drillDateUnix < 0) return ''

                const date = new Date(drillDateUnix || 0)

                let day: number | string = date.getDate()
                let month: number | string = date.getMonth() + 1
                const year = date.getFullYear()

                if (day < 10) day = '0' + day
                if (month < 10) month = '0' + month

                return [day, month, year].join('/')
              })()}
              ```
