### ISSUE TITLE
How prevent space behaviour

### ISSUE THREAD

**Issue by HrjSnz** [uNmAnNeR/imaskjs#466]
Hello,

i have question. Here is my code . [https://codepen.io/Dalaroth/pen/zYNqQmR](url)
I have problem and can not solve it. I need for 3 char only 329 or 330 . Behind space and next 2-3char mus be [A-Z] and again space and again need 3 integers...  

Result need to be this format : 329 JGK 254 or 330 KA 214 .  And i NEED this letters inside.

my problem is : Always when i hit after first 3 numbers something other than [A-Z] so it make space and now i can not write nothing. I need press spacebar and after it i can again write... 

can you help me please how i can write it better or something else ? 

Thank you !

**Comment by uNmAnNeR** [comment]
@HrjSnz hi, I think for the second block you have to use pattern mask with optional third char, like { mask: 'aa[a]' } and then you no more need to check it in third block.

**Comment by HrjSnz** [comment]
OOOOO THANK YOU !!!! It works pretty nice ! Can you please explain me how is possible its working ? I did not see this optional setting in doc. Now I know how it is meant in the documentation. Thank you very much!

**Comment by uNmAnNeR** [comment]
@HrjSnz you are welcome :) optional char can be skipped if letter is not matched
