### ISSUE TITLE
Prevent cursor position switching

### ISSUE THREAD

**Issue by LodewijkSioen** [uNmAnNeR/imaskjs#467]
I'm trying to build a timepicker using iMask:
![afbeelding](https://user-images.githubusercontent.com/122718/112820727-2ffc1880-9086-11eb-90fc-94623cade99b.png)
I want the hours or the minutes to increase/decrease by using the up/down arrows. If the cursor is before the colon, the hours will change. After the colon, the minutes will change.

 However, iMask has an earlier event that will put the cursor at the start or the end of the mask when up/down is pressed. So by the time my event is triggered, the current cursor prosition is no longer correct.

Is this something that can be controlled?

**Comment by uNmAnNeR** [comment]
imask does not handle any keyboard events besides 'input', may be you are using another library with same name

**Comment by LodewijkSioen** [comment]
You also handle keydown [here](https://github.com/uNmAnNeR/imaskjs/blob/6adc0901e18789f5fec00fcf4bec7011b87943f5/packages/imask/src/controls/html-mask-element.js#L108), which is the moment when the cursor moves to anonther location.

**Comment by uNmAnNeR** [comment]
@LodewijkSioen it's a readonly thing, just store cursor position, nothing is changing

**Comment by Hestre** [comment]
hi i want to prevent imask from reseting the cursor to the cursor positon 0 when i click on a section of the mask. you can see what i am referrring to if you click on m in the lazy mode example here.  https://imask.js.org/guide.html#masked-date
