### ISSUE TITLE
Redaction of entered value on blur

### ISSUE THREAD

**Issue by samuelhar** [uNmAnNeR/imaskjs#469]
Hello,

Is it possible to extend the functionality in some way to redact part of the user input when they move focus out of the field they entered it?

For example, suppose the field is SSN and a user types "123123123" it should show that until the field is blurred, and then it would show in the view as "XXXXX3123", replacing first 5 characters with X. The model value should stay the same though.

This is similar to https://github.com/uNmAnNeR/imaskjs/issues/291 and https://github.com/uNmAnNeR/imaskjs/issues/216, but I do not want to apply the redaction on input, just on blur/focus.

**Comment by uNmAnNeR** [comment]
nice case, currently not possible, but i am keeping an eye on it
