### ISSUE TITLE
Integration with Vue

### ISSUE THREAD

**Issue by indapublic** [uNmAnNeR/imaskjs#47]
Hi! First, thanks for your excellent plugin.
I have strange behaviour for using your mask with Vue

IMask version: 

> "imask": "^3.1.2"

My input is:
`<input type="text" class="form-control imask" data-mask="Date" data-mask-placeholder=" " required v-model="some-value" />`

Mask options are very simple:

```
const maskOptions = {
	mask: IMask.MaskedDate
}
```

And input mask is not working :(
My input looks like this after successive pressing of the buttons from **1** to **9**:

![screen shot 2018-04-02 at 09 09 57](https://user-images.githubusercontent.com/856260/38178400-a3a0c5e4-3655-11e8-9b25-71d2baf6fd26.png)

Many warnings in console with `Uncontrolled input change, refresh mask manually!` message

**Comment by indapublic** [comment]
Want to pay attention for fact: I'm using Vue just for mapping, without components, so cannot use your Vue plugin at the moment

**Comment by indapublic** [comment]
Same behaviour with phone mask too :(

**Comment by uNmAnNeR** [comment]
@indapublic Please provide some sources about how you bind mask to input.
Also you may take a look at Vue plugin source code which is pretty simple.

**Comment by uNmAnNeR** [comment]
Please reopen if more info appears

**Comment by shrpne** [comment]
@uNmAnNeR 
[Vue directive example](https://github.com/uNmAnNeR/imaskjs/tree/master/packages/vue-imask#mask-directive-example) not working properly.
I reproduced it in the [CodeSandbox](https://codesandbox.io/s/91jmn3o8o?hidenavigation=1&module=%2Fsrc%2Fcomponents%2FImaskInput.vue&view=preview)

If you try to enter something in the input, you will see in console `accept undefined` and `complete undefined` messages.

`console.log("accept", maskRef.detail._value);` should work instead.

**Comment by uNmAnNeR** [comment]
@shrpne thanks! will fix soon
