### ISSUE TITLE
Usage with React Formik?

### ISSUE THREAD

**Issue by JCMais** [uNmAnNeR/imaskjs#470]
Is anyone using this with [`formik`](https://formik.org/docs/api/formik)?

**Comment by uNmAnNeR** [comment]
close due to inactivity

**Comment by yevhen-logosha** [comment]
For anyone wondering, yes it is possible:
use <Field />'s `component` or `children` 
https://formik.org/docs/api/field
TIP: make sure to use `onAccept` when handling changes, otherwise middle of number changes wont be registered by formik

**Comment by badanator** [comment]
Any example with formik would will be much appreciated. Thanks!
