### ISSUE TITLE
iPhone change event [bug] vuejs

### ISSUE THREAD

**Issue by Eugene313** [uNmAnNeR/imaskjs#473]
In iPhone with thousandsSeparator space, not working change event

https://user-images.githubusercontent.com/44434783/115142965-2d6d5d00-a04d-11eb-9990-e48eb8304489.MP4

**Comment by Eugene313** [comment]
https://codesandbox.io/s/vue-examples-forked-d8pe4?file=/App.vue

**Comment by uNmAnNeR** [comment]
through the years i can say that
1. `accept` event should be used instead of `input` event
2. `blur` event should be used instead of `change` event
