### ISSUE TITLE
Number masks allow a single dot or comma to be entered

### ISSUE THREAD

**Issue by Juanpam** [uNmAnNeR/imaskjs#474]
When using the number mask, a single dot is allowed as valid input. Using: 

- padFractionalZeros: true,  // if true, then pads zeros
- normalizeZeros: true,  // appends or removes zeros at ends

won't help. Is there any way to restrict this so it adds the 0 before the decimal point or by restricting the input so a single dot is not acceptable?

**Comment by uNmAnNeR** [comment]
seems like dot is replaced with 0 on blur.
'.123' -> '0.123'

does not it work for you?
if not then you can inherit from number mask and add some additional rules.

**Comment by Juanpam** [comment]
@uNmAnNeR If possible, could you provide the required flags/configuration to make this work? I didn't find the example on the mentioned issue.
