### ISSUE TITLE
[Feature request] Export the main library from plugins

### ISSUE THREAD

**Issue by wujekbogdan** [uNmAnNeR/imaskjs#476]
I've just installed the Vue plugin and found that the main library is not exported. So, if I want to use classes like `IMask.MaskedEnum` I have to install the main library in order to import them.

I know that it's installed as a dependency of a vue plugin, but importing  implicitly installed dependences isn't a good practice.

**Comment by uNmAnNeR** [comment]
`import { IMask } from 'vue-imask'` will be available in next release
