### ISSUE TITLE
[react-plugin] [help wanted] Date mask validation

### ISSUE THREAD

**Issue by comertcimen** [uNmAnNeR/imaskjs#477]
I am trying to use React plugin with Date mask. I want to use the overwrite mode but I am having a problem. When I enter 01.08.2020 and try to change the 0 of month to 1, it does not allow me because there is no 18th month. But there is 11 and 12 so I want to be able to change that. Is there a prop that can allow me to do it and then fix the value for me when the cursor is at the end of month? I tried mask='00.00.0000' but if I do this I must control the dates by myself.

Example code: [CodeSandbox](https://codesandbox.io/s/lucid-silence-z6tsg?file=/src/App.js)

**Comment by uNmAnNeR** [comment]
autofix = true could help. If you want to fix it during typing then you can inherit from pattern mask and overwrite default behaviout

**Comment by enrico-waat** [comment]
`autofix` is not helping in our case. Do you have a concrete example on how to inherit from pattern mask and overwrite default behaviour?

Users are generally confused when they are not allowed to change values and go further while typing. They think is not working although is correct behavior.

To fix their perception it would be great to change the value while typing to 12 for example.

I am also seeing that in the parse function I am getting the right string with the month autofixed and set to 12, but then it is called again with the old str value :thinking: 

Any hint?
