### ISSUE TITLE
Support for  \p{L} 

### ISSUE THREAD

**Issue by itaymesh** [uNmAnNeR/imaskjs#48]
Hello,

I tried to use **\p{L}** expression that matches any kind of letter from any language.

It does seem to work with the following code:

`new IMask(element, {
    mask : /^\p{L}+$/
});`

I will appreciate some help here. 

Thanks
Itay

**Comment by itaymesh** [comment]
Ok, seems like javascript version prior to ECMAScript 2018 does not support this expression 
https://stackoverflow.com/questions/13210194/javascript-regex-equivalent-of-a-za-z-using-pl

Can I use a custom function instead of regex to validate the input using IMask class?

**Comment by uNmAnNeR** [comment]
Sure:
```js
new IMask(element, {
  mask : function (input) {
    // return true or false
  }
});
```

**Comment by itaymesh** [comment]
Great. I will try this approach.
