### ISSUE TITLE
Editing input with a masked value moves cursor to end of line

### ISSUE THREAD

**Issue by borisilic** [uNmAnNeR/imaskjs#487]
Reproducible example here:

https://codesandbox.io/s/trusting-bardeen-qqr1s?file=/src/App.js

When you type in a number, say `123 456`, and then decide you want to change `2` to `9`, pressing backspace on `2` shifts the cursor to the end of the line. Is this a bug or am I doing something incorrect?

**Comment by uNmAnNeR** [comment]
@borisilic if you are using vanilla version then you also need to take care of setting cursor position
