### ISSUE TITLE
Перевод каретки в Android, google Chrome

### ISSUE THREAD

**Issue by corsik** [uNmAnNeR/imaskjs#49]
Если заполнять с телефона и на клавиатуре нажать "Далее", то на следующем input каретка становится в конце, а не в начале.
Посмотреть можно вот тут
http://таксомотор24.рф/driver-form/

**Comment by uNmAnNeR** [comment]
привет!
Под мобилы есть много способов сломать маску, думаю остается только подхачивать.
В маске каретка позиционируется только на клик.
В браузере насколько я понимаю кнопке далее соответствует таб. В этом случае ставится выделение на все поле, что нормально для пользователя, поэтому на focus позиционирование курсора не завязано. В мобиле выделение не ставится, но и курсор тоже не позиционируется - получается не очень.
Что я могу предложить попробовать:
1) локально: <element>.addEventListener('focus', <mask>.alignCursorFriendly);
2) сделать и задокументировать адекватный хак, без анализов userAgent и пр., тогда можно залить в основную репу.

**Comment by uNmAnNeR** [comment]
исправлено
