### ISSUE TITLE
When input has "0" character, can't type numbers after the 0

### ISSUE THREAD

**Issue by LordZardeck** [uNmAnNeR/imaskjs#493]
I'm using react-imask, but I tested on the demo page for the number mask and it still happens. Basically, type 0, then type another number. Ideally, it would just replace the 0 with the next number, but even if it didn't, it should still at least add the next number. Then I could handle removing the preceding 0's in `onAccept`. Right now, `onAccept` doesn't even trigger.

**Comment by LordZardeck** [comment]
It appears to be a result of this regex: https://github.com/uNmAnNeR/imaskjs/blob/master/packages/imask/src/masked/number.js#L81

If it was `'(0|([0-9]+\\d*))?'` instead, it seems to validate/pass. Not sure why this doesn't allow 0's, so I'm hesitant to create a PR.

**Comment by prakhathi-m** [comment]
I think it is working as expected. I wouldn't want any leading zero.

**Comment by LordZardeck** [comment]
Ideally it would just replace the 0 with the number you typed. So 05 would just become 5

**Comment by uNmAnNeR** [comment]
i still would like to follow 'restrict' pattern instead of 'fix' one
