### ISSUE TITLE
data in InputEvent is null in Chrome on paste

### ISSUE THREAD

**Issue by someden** [uNmAnNeR/imaskjs#495]
There is some data in Safari on paste:
<img width="574" alt="Screenshot 2021-06-03 at 13 01 01" src="https://user-images.githubusercontent.com/7009699/120627695-9a597c80-c46c-11eb-8204-13dc192e1788.png">

Firefox is also have data.

But it's null in Chrome:
<img width="574" alt="Screenshot 2021-06-03 at 13 02 36" src="https://user-images.githubusercontent.com/7009699/120627823-bb21d200-c46c-11eb-97d7-07a17e9f0052.png">

Example: https://codesandbox.io/s/confident-mahavira-imck4?file=/src/index.js

Checked in Chrome versions 90.0.4430.212 and 91.0.4472.77
imask version: 6.0.7

**Comment by uNmAnNeR** [comment]
@someden  are you sure that it works properly without imask?

**Comment by someden** [comment]
So, I checked without imask and it's standard Chrome behaviour. Sorry to disturb.
