### ISSUE TITLE
Updating lazy option does not work with dynamic nested mask

### ISSUE THREAD

**Issue by Mokkapps** [uNmAnNeR/imaskjs#497]
Hi,

I want to toggle visibility of placeholders by calling `updateOptions` using dynamic nested masks but it does not work, the placeholders are always hidden. 

Example: https://stackblitz.com/edit/imask-nested-mask?file=index.js

Thanks in advance for your help!

**Comment by uNmAnNeR** [comment]
solution https://stackblitz.com/edit/imask-nested-mask-5p9kaz?file=index.js

**Comment by vinderman** [comment]
@uNmAnNeR In provided example, focusing input by tab navigation places caret at the end of the filed, but focusing it by mouse work as expected. What solution can you advice to fix it? thx
