### ISSUE TITLE
Critical and High Fortify Security Scan Findings

### ISSUE THREAD

**Issue by jstrong62** [uNmAnNeR/imaskjs#498]
The following "Critical" and "High" findings are reporting by a Fortify security scan and needs remediation to pass a standard security scan:

### **1. [CRITICAL] - Hardcoded Encryption Keys**

imask/dist/imask.js
```
3427: key: "_unsafeSelectionStart",
3437: key: "_unsafeSelectionEnd",
3550: key: "_unsafeSelectionEnd",
3533: key: "_unsafeSelectionStart",
```

Details from Fortify:

Hardcoded encryption keys can compromise security in a way that is not easy to remedy.

Encryption keys should never be hardcoded and should be obfuscated and managed in an external source. Storing encryption keys in plain text anywhere on the system allows anyone with sufficient permissions to read and potentially misuse the encryption key.

### **2. [HIGH] - Insecure Randomness**

imask/dist/imask.js

`238: var postfix = Math.random();`

**Details from Fortify:**

The random number generator implemented by random() cannot withstand a cryptographic attack.

In JavaScript, the typical recommendation is to use the window.crypto.random() function in the Mozilla API. However, this method does not work in many browsers, including more recent versions of Mozilla Firefox. There is currently no cross-browser solution for a robust cryptographic PRNG. In the meantime, consider handling any PRNG functionality outside of JavaScript.

**Comment by ynamite** [comment]
I may be wrong, but I don't think imask does what you think it does. 
These vulnerabilities don't seems like actual vulnerabilites to me, especially since imask isn't used to a) store encryption keys and b) secure anything at all.

**Comment by uNmAnNeR** [comment]
@ynamite exactly, thanks
