### ISSUE TITLE
Regex causes input to freeze

### ISSUE THREAD

**Issue by chrisschaub** [uNmAnNeR/imaskjs#50]
Using this regex
```
/^\+[0-9]\.\d{0,14}$/
```
causes the input to freeze. The example Russian postal code works fine. Is there something I'm missing in the regex for special chars? Thanks.

**Comment by uNmAnNeR** [comment]
There is no freeze, it just does not work:
https://jsfiddle.net/ymctL65x/

This case is described in a guide:

> Also make sure that mask or validator works with any of intermediate states, not just final value.

```js
/^\+[0-9]\.\d{0,14}$/.test('+')
false
```

There is no magic with RegExp, it just applies to input as is.

**Comment by uNmAnNeR** [comment]
@chrisschaub hope it helped

**Comment by polianomartini** [comment]
> There is no freeze, it just does not work:
> https://jsfiddle.net/ymctL65x/

Your example didn't work because it wasn't added to the library url. When adding the freezing mentioned by @chrisschaub occurs.

I even opened this other [issue](https://github.com/uNmAnNeR/imaskjs/issues/420) with the same problem.
