### ISSUE TITLE
Errors with Angular 12.1.0

### ISSUE THREAD

**Issue by slubowsky** [uNmAnNeR/imaskjs#501]
After updating to Angular 12.1.0, seeing build errors wherever Imask is used (but interestingly, not on all machines... maybe only starting with clean node_modules?)

e.g. In template use IMask
`<input class="form-control" formControlName="num" [imask]="{mask: '000-00-0000'}" [unmask]="true" />`

On build get error
```
Error: src/app/my-form/my-form.component.ngtypecheck.ts:9:36 - error TS1110: Type expected.      

9 const _ctor1: <Opts extends import().default.AnyMaskedOptions = any>(init: Pick<i4.IMaskDirective<Opts>, "imaskElement" | "imask" | "unmask">) => i4.IMaskDirective<Opts> = null!;
```

**Comment by cesco69** [comment]
Same for me...

**Comment by matheusrufinos** [comment]
I have the same situation here.
The error happens sometimes also running in development mode (ng serve). The project starts, but when making any changes to the code, on recompilation I get this error and the terminal is locked.
The build process also happens sometimes, which is a problem too, as I probably have a build artifact with a bug.

```typescript
error TS1110: Type expected.      

9 const _ctor1: <Opts extends import().default.AnyMaskedOptions = any>(init: Pick<i4.IMaskDirective<Opts>, "imaskElement" | "imask" | "unmask">) => i4.IMaskDirective<Opts> = null!;
```
