### ISSUE TITLE
Проблема с типами

### ISSUE THREAD

**Issue by gizeasy** [uNmAnNeR/imaskjs#503]
```ts
IMask.pipe(value || '', {
  mask: /^\d+$/,
}),
```

TS ругается: _Тип "{ mask: RegExp; }" не может быть назначен для типа "string"._

```ts
IMask.pipe(value || '', {
  mask: Date,
  pattern: inputFormat,
  min: new Date('0000-01-01T00:00:00'),
  max: new Date('9999-12-31T23:59:59'),
  lazy: true,
  format: (date) => format(date, inputFormat),
  parse: (string) => parse(string, inputFormat, new Date()),
  blocks: {
    yyyy: {
      mask: IMask.MaskedRange,
      from: 1,
      to: 9999,
    },
    MM: {
      mask: IMask.MaskedRange,
      from: 1,
      to: 12,
    },
    dd: {
      mask: IMask.MaskedRange,
      from: 1,
      to: 31,
    },
  },
  autofix: true,
  overwrite: true,
})
```

![image](https://user-images.githubusercontent.com/13190808/124096122-f828b680-da62-11eb-8de2-441117519cca.png)

c типами вообще какая-то бяда(( но все работает

может я что-то не так делаю?

**Comment by gizeasy** [comment]
![image](https://user-images.githubusercontent.com/13190808/124140958-a186a100-da91-11eb-8bda-9e9c667f82d2.png)

еще тут, ругается на недоступность

**Comment by uNmAnNeR** [comment]
да с типами надо сидеть разбираться заново. Я уже забыл что там понакодил год назад. Две системы типов поддерживать не очень хочется, надо оставлять только TS, но это работы на неделю. Так и живем. Может руки доберутся когда-нибудь, не закрывай таску.

**Comment by uNmAnNeR** [comment]
@gizeasy чекни плз на 6.1 если можешь

**Comment by gizeasy** [comment]
> @gizeasy чекни плз на 6.1 если можешь
Завтра чекну.

**Comment by gizeasy** [comment]
все также (( 

![image](https://user-images.githubusercontent.com/13190808/124582521-c183df00-de5a-11eb-84e1-20776790edbc.png)
