### ISSUE TITLE
Request for new release 

### ISSUE THREAD

**Issue by kjteh** [uNmAnNeR/imaskjs#504]
Hi @uNmAnNeR 

Can I request for a new release for the fix that you have merged in recently in: 
https://github.com/uNmAnNeR/imaskjs/pull/502

I  am doing an Angular upgrade currently from 11 to 12. Without the above fix release, we are unable to complete the upgrade task. If you have a timeline for the library release, would it possible to let us know?

Thanks for maintaining this great library all the time. <3

**Comment by uNmAnNeR** [comment]
@kjteh hey! I already forgot how to do it :) But I'll try on weekends. Thanks for supporting

**Comment by uNmAnNeR** [comment]
@kjteh please check

**Comment by kjteh** [comment]
It works great, appreciated!
