### ISSUE TITLE
'IMask' is undefined in IE11

### ISSUE THREAD

**Issue by elisabetperez** [uNmAnNeR/imaskjs#505]
hello all,
I'm getting an error in Internet Explorer 11 on Windows 10, where iMask is simply undefined and the masks are not working. Am I missing a polyfill or something? Everything's working fine on Chrome, Safari and Firefox.
This is my error:
`ReferenceError: 'IMask' is undefined
{
      [functions]: ,
      __proto__: { },
      description: "'IMask' is undefined",
      message: "'IMask' is undefined",
      name: "ReferenceError",
      number: -2146823279,
      stack: "ReferenceError: 'IMask' is undefined
}`

this is hoy I declare iMask:
import IMask from 'imask';

Thanks in advance!

**Comment by uNmAnNeR** [comment]
hi! once you are using ES imports you have to transpile it through Babel or some other tool (also not to forget install Imask from npm).
You need either to transpile it by yourself, or use transpiled version like `<script defer="" src="https://unpkg.com/imask"></script>`
