### ISSUE TITLE
Wrong numbers

### ISSUE THREAD

**Issue by bybbsy** [uNmAnNeR/imaskjs#506]
Hello, I've got some troubles with numbers 4-9 on the mask (https://codepen.io/jzamez/pen/KKmdGMp). If I type 1-3 it works fine, but If I type 4-9 it doesn't show any number. But if add 0 to each number it works fine. What's wrong?

**Comment by uNmAnNeR** [comment]
@bybbsy  hi! it's fine. it were designed to work this way for ranges with fixed length of characters. If you want to restrict input for integer numbers then you can use number mask with scale=0 and set min/max boundaries.
