### ISSUE TITLE
Substituting whole value

### ISSUE THREAD

**Issue by bam** [uNmAnNeR/imaskjs#513]
**Describe the bug**
Issue comes when I'm trying to substitute whole value. If current mask has fixed prefix, and you type new value when whole current value is selected, new value comes with part of fixed prefix.

**To Reproduce**
There are dynamic masks +{7} 000 ; (000) ; 0000
Current value: +7 911
Then select all
Type 5 (in my mask options should be used 0000 for all values except ^+79 and ^9)
So I expect that it will be value 5, but it is 75, because +7 added by default from old value

**Expected behavior**
Selected value must be substituted completely. SO in result I expect only 5.

**Environment:**
 - OS: macOS
 - Browser chrome
 - Version 91
 - IMask version 6.0.5
 - Framework/plugin version if used React-imask 6.0.5

**Comment by uNmAnNeR** [comment]
fixed in #606
