### ISSUE TITLE
Cursor position after mask with prefix

### ISSUE THREAD

**Issue by bam** [uNmAnNeR/imaskjs#514]
**Describe the bug**
Cursor placed at the beginning of value after typing first symbol when there was mask with fixed prefix.

**To Reproduce**
Run the [dynamic mask demo](https://imask.js.org/guide.html#masked-dynamic)
Type '7'
See +7| ___ ___-__-__ (cursor placed correctly)
Select all
Type '3'
See |3 (cursor at the beginning of string)

**Expected behavior**
Cursor placed after 3

**Environment:**
demo at the imask.js.org
Chrome 91

**Comment by MaximSaraev** [comment]
+1, have the same problem
