### ISSUE TITLE
Leading zero blocks the input

### ISSUE THREAD

**Issue by bam** [uNmAnNeR/imaskjs#515]
**Describe the bug**
Leading zero stops the input

**To Reproduce**
1. Open [demo](https://imask.js.org/guide.html#masked-number) for Number mask
2. Type 0
3. Type any non zero other number

**Expected behavior**
Value becomes the number from step 3.

**Environment:**
 - OS: macOS
 - Browser Chrome
 - Version 91
 - IMask version 6.1.0
 - Framework/plugin React 16

**Comment by bam** [comment]
Another one case with leading zeroes:
1. Type 2
2. Put cursor to the left
3. Type 0 (yes, it's able!)
4. Repeat 2 then 3

Result:
![image](https://user-images.githubusercontent.com/2446302/126207025-455d91ee-2f8e-4a73-b284-9014642f3be9.png)

But input after 2 or inbetween is blocked

**Comment by uNmAnNeR** [comment]
first case is not fixed (imo on input value should be either allowed or blocked but not replaced)
