### ISSUE TITLE
regex

### ISSUE THREAD

**Issue by lxregistry** [uNmAnNeR/imaskjs#517]
**Describe the bug**
what is wrong with this regex /^\d{7}\.\d{3,4}(\.\d{2}(\.\d{3})?)?$/ it is working in other side but not in imask

could you explain what is wrong here

**To Reproduce**
Steps and link to sandbox. You can use [jsfiddle](https://jsfiddle.net/), [StackBlitz](https://stackblitz.com/), [CodePen](https://codepen.io/), [CodeSandbox](https://codesandbox.io/) and any other.

**Expected behavior**

**Environment:**
 - IMask version
 - Framework/plugin version if used

**Additional context**

**Comment by uNmAnNeR** [comment]
regex is fine, but imask does not work this way, please read the guide first
