### ISSUE TITLE
Add react hook

### ISSUE THREAD

**Issue by uNmAnNeR** [uNmAnNeR/imaskjs#518]
**What problem you are trying to solve?**
be fresh and cool

**Describe the solution you'd like**
add freaking useless hook

**Describe alternatives you've considered**
https://github.com/tracksuitdev/use-imask

**Comment by tbjgolden** [comment]
@uNmAnNeR lmk if ya wanna hand with the react-imask project

happy to rewrite it (in backwards compatible way) with hooks, ts etc

**Comment by uNmAnNeR** [comment]
@tbjgolden i am not very skilled in React hooks. If you are then please review https://github.com/uNmAnNeR/imaskjs/blob/master/packages/react-imask/src/hook.js
let's do typings within #329 
i will try to figure out with comments and existing PR for typings, any help is very welcome
