### ISSUE TITLE
Dynamic pattern groups

### ISSUE THREAD

**Issue by uNmAnNeR** [uNmAnNeR/imaskjs#52]
e.g.
```js
var currencyInputMask = new IMask(element, {
  mask: '$num',
  groups: {
    num: {
      mask: Number  // ←- Currently only fixed-size string is available
    }
  }
});
```
Consider constrains:
* only greedy
* only for lazy mode (or fixed size placeholder?)

**Comment by tarasenych** [comment]
Привет!
Я правильно понимаю, что эта штука позволяет создать текстовую маску, часть которой будет проверяться как Number? Я создал пример на codepin, но работает некорректно - [https://codepen.io/tarasenych/pen/YLxEob](https://codepen.io/tarasenych/pen/YLxEob)

Есть ли возможность создать такую маску другим способом (например, изначально маска будет Number, после этого я обновлю настройки, где укажу маску '000$')? Может это как то возможно через создание двух экземпляров IMask и в коллбеке передавать значение разным объектам?

Огромное спасибо тебе за плагин, отличная работа!

**Comment by uNmAnNeR** [comment]
Thanks! Let us speak english here.
Yes, you are correct. Currently only `pattern` groups are available.
For now workaround could be to use `Function` mask and do all custom logic inside it. Or may be complex `RegExp` mask can be a good start. `Pattern` mask does not provide enough flexibility to use it for such cases now. May be [this one](https://github.com/uNmAnNeR/imaskjs/issues/43) could help.

**Comment by uNmAnNeR** [comment]
It is ok, if it solves your problem. But i can't recommend it as common solution because of limitations and hacky nature.
