### ISSUE TITLE
Vue-imask adding value after cursor when many inputs are clicked

### ISSUE THREAD

**Issue by kwiksilver3441** [uNmAnNeR/imaskjs#524]
**Describe the bug**
When the user clicks many inputs at once, some of the inputs get appended after the cursor, instead of before. 

**To Reproduce**
Steps and link to sandbox. You can use [jsfiddle](https://jsfiddle.net/), [StackBlitz](https://stackblitz.com/), [CodePen](https://codepen.io/), [CodeSandbox](https://codesandbox.io/) and any other.

**Expected behavior**
Like normal typing, values should never get confused and be placed after the cursor. 

**Environment:**
 - OS: Windows
 - Browser Brave
 - Version 1.27.109 Chromium: 92.0.4515.115 (Official Build) (64-bit)
 - IMask version "^6.1.0",
 - Framework/plugin version if used "^6.1.0",

**Additional context**
I understand the text may not be clear. So I created a small video to visually explain the issue. https://youtu.be/soVWuKjGRWc
I also use vuelidate. Perhaps there could be a conflict between the two plugins watching the same value?

**Comment by uNmAnNeR** [comment]
hi, I've checked it. What I can say is that seems like related to your specific context. It's hard to figure out which plugin affects input behavior. Imask reacts on `input` event, so seems like some of plugins emits it second time.
