### ISSUE TITLE
[React] "overwrite" option is not available in dynamic mask

### ISSUE THREAD

**Issue by vicasas** [uNmAnNeR/imaskjs#525]
**Describe the bug**
Using dynamic mask the alert message appears. This after having to use two types of masks for a text field of a form with a Material UI implementation.

> "overwrite" option is not available in dynamic mask, use this option in siblings 

Related #285?

EG:

```jsx
const masks = [{ mask: '000.000.000' }, { mask: 'a000 000 0000' }]

<IMaskInput
    mask={masks}
    onAccept={(value) => onChange({ target: { name, value } })}
    overwrite
/>
```

**Expected behavior**
An alert message should not appear.

**Environment:**
 - OS: Windows
 - Browser: All
 - IMask version: v6.1.0 (for React)
 - Framework/plugin version if used: Material UI v4

**Comment by uNmAnNeR** [comment]
@vicasas hi.

> Related #285?

no, it's different.

You just need to fix it just as it warns so put your `overwrite` prop inside each of mask options in array.

**Comment by vicasas** [comment]
@uNmAnNeR I keep getting the same warning

```jsx
const masks = [{ mask: '000.000.000', overwrite: true }, { mask: 'a000 000 0000', overwrite: true }]

<IMaskInput
    mask={masks}
    onAccept={(value) => onChange({ target: { name, value } })}
    overwrite
/>

```

> "overwrite" option is not available in dynamic mask, use this option in siblings

**Comment by uNmAnNeR** [comment]
@vicasas you have to remove `overwrite` from props:

```html
<IMaskInput
    ...
    overwrite <!-- this one -->
/>
```

**Comment by vicasas** [comment]
Yes, later I realized that there was an overwrite. Thanks! I will close this issue.
