### ISSUE TITLE
Time (HH:MM) mask

### ISSUE THREAD

**Issue by nerone** [uNmAnNeR/imaskjs#53]
Rather a help request then an issue. Need advice/example on implementing time mask. 

The RegExp for 24-hour time format would be like: 
```
/^([01]?\d|2[0-3]):[0-5]\d$/
```

I tried setting mask options like:
```
var maskOptions = {
    mask: 'HH{:}`MM',
    groups: {
        HH: {
            mask: '0[0]'
        },
        MM: {
            mask: '$0',
        }
    },
    definitions: {
        '$': /[0-5]/,
    }
};
```

, then updating mask pattern on-the-fly to validate hours properly (listening to `accept` event), but character shift didn’t work well.

Can anybody point me to the right direction please?

Thanks!

**Comment by uNmAnNeR** [comment]
@nerone lets simplify it using helpers.
```js
var maskOptions = {
  mask: 'HH{:}`MM',
  groups: {
    HH: new IMask.MaskedPattern.Group.Range([0, 23]),
    MM: new IMask.MaskedPattern.Group.Range([0, 59])
  }
}
```

**Comment by nerone** [comment]
I supposed this should be easy and straightforward. Thank you, @uNmAnNeR!

**Comment by kl3sk** [comment]
Tell me if I'm wrong but, it should be this now:

```javascript
let element = document.querySelector('input')
let maskOptions = {
  overwrite: true,
  autofix: true,
  mask: 'HH:MM',
  blocks: {
    HH: {
      mask: IMask.MaskedRange,
      placeholderChar: 'HH',
      from: 0,
      to: 23,
      maxLength: 2
    },
    MM: {
      mask: IMask.MaskedRange,
      placeholderChar: 'MM',
      from: 0,
      to: 59,
      maxLength: 2
    }
  }
}
let mask = IMask(element, maskOptions)
```

**Comment by plindelauf** [comment]
I just wanted to share the configuration that has given us the best time input experience:

    {
      value: "00:00 AM",
      timeMask: {
        overwrite: true,
        autofix: true,
        mask: "h{:}mm A",
        lazy:false, 
        blocks: {
          HH: {
            mask: function (value) {
              if (isNaN(value)) { return false; }
              const int_value = parseInt(value);
              return value.length < 3 && 0 <= int_value && int_value <= 24;
            },
            maxLength: 2
          },
          h: {
            mask: function (value) {
              if (isNaN(value)) { return false; }
              const int_value = parseInt(value);
              return value.length < 3 && 0 <= int_value && int_value <= 12;
            },
            maxLength: 2
          },
          mm: {
            mask: IMask.MaskedRange,
            placeholderChar: "0",
            from: 0,
            to: 59,
            maxLength: 2
          },
          A: {
            mask: IMask.MaskedEnum,
            enum: ["AM", "am", "PM", "pm", "aM", "Am", "pM", "Pm"]
          }
        }
      },
      onAccept(e) {
        e.detail.value = e.detail.value.toUpperCase(); // Always cast characters to upcase
        // The default placeholder is "_"; make sure we fill this with a relevant value     
        e.detail.value = e.detail.value.
          replace("__", "AM").
          replace("A_", "AM").
          replace("P_", "PM").
          replace("_M", "AM").
          replace("M_", "AM"); 
      },
      onComplete(e) {
        const maskRef = e.detail;
        console.log("complete", maskRef.unmaskedValue);
      }
    };

This supports both 24-hour input and 12-hour input. The example above is for 12-hour input. For 24-hour input, the value should be `00:00` and the mask `HH{:}mm`.

**Comment by iantearle** [comment]
@plindelauf how do you apply this to var momentMask = IMask(element, {}); ? I am getting mask property must be defined.

**Comment by iantearle** [comment]
@plindelauf Apologies, spotted it.

```
var momentMask = IMask(element[i], {
        overwrite: true,
        autofix: true,
        mask: 'h{:}mm A',
        lazy:false, 
        blocks: {
            HH: {
            mask: function (value) {
              if (isNaN(value)) { return false; }
              const int_value = parseInt(value);
              return value.length < 3 && 0 <= int_value && int_value <= 24;
            },
            maxLength: 2
            },
            h: {
            mask: function (value) {
              if (isNaN(value)) { return false; }
              const int_value = parseInt(value);
              return value.length < 3 && 0 <= int_value && int_value <= 12;
            },
            maxLength: 2
            },
            mm: {
            mask: IMask.MaskedRange,
            placeholderChar: '0',
            from: 0,
            to: 59,
            maxLength: 2
            },
            A: {
        mask: IMask.MaskedEnum,
        enum: ['AM', 'am', 'PM', 'pm', 'aM', 'Am', 'pM', 'Pm']
        }
        },
        onAccept(e) {
            e.detail.value = e.detail.value.toUpperCase(); // Always cast characters to upcase
            // The default placeholder is '_'; make sure we fill this with a relevant value     
            e.detail.value = e.detail.value.
            replace('__', 'AM').
            replace('A_', 'AM').
            replace('P_', 'PM').
            replace('_M', 'AM').
            replace('M_', 'AM'); 
        },
        onComplete(e) {
            const maskRef = e.detail;
            console.log('complete', maskRef.unmaskedValue);
        }
    });
```

**Comment by mukundkatpatal** [comment]
Can we have a similar mask for hour**s** : min?
For example 300 hours and 20 min? Where the hour value can be in thousands, completely dynamic number?
Is it possible to build a mask options for such a input?

**Comment by EliseyMartynov** [comment]
@kl3sk thank you! :) it hepled me a lot - just adapted it for React.

**Comment by T-G0d3X** [comment]
@EliseyMartynov can you please copy or give link how did you adapted it for React? Thanks

**Comment by Gabo-Puck** [comment]
> @EliseyMartynov can you please copy or give link how did you adapted it for React? Thanks

I know it's a little late and maybe you've already solve the problem. But for anyone wondering how to implement this specific mask in React:

```
import { useIMask, IMask } from "react-imask";
const maskOptions = {
  overwrite: true,
  autofix: true,
  mask: "HH:MM",
  blocks: {
    HH: {
      mask: IMask.MaskedRange,
      placeholderChar: "HH",
      from: 0,
      to: 23,
      maxLength: 2,
    },
    MM: {
      mask: IMask.MaskedRange,
      placeholderChar: "MM",
      from: 0,
      to: 59,
      maxLength: 2,
    },
  },
};
export default function HoraInput() {
  const { ref } = useIMask(maskOptions, {
    onAccept: (s) => {
      console.log({ accept: s });
    },
    onComplete: (s) => {
      console.log({ complete: s });
    },
  });
  return <input ref={ref} placeholder="00:00" />;
}

```

**Comment by Gabo-Puck** [comment]
> @EliseyMartynov can you please copy or give link how did you adapted it for React? Thanks

I know it's a little late and maybe you've already solve the problem. But for anyone wondering how to implement this specific mask in React:

```
import { useIMask, IMask } from "react-imask";
const maskOptions = {
  overwrite: true,
  autofix: true,
  mask: "HH:MM",
  blocks: {
    HH: {
      mask: IMask.MaskedRange,
      placeholderChar: "HH",
      from: 0,
      to: 23,
      maxLength: 2,
    },
    MM: {
      mask: IMask.MaskedRange,
      placeholderChar: "MM",
      from: 0,
      to: 59,
      maxLength: 2,
    },
  },
};
export default function HoraInput() {
  const { ref } = useIMask(maskOptions, {
    onAccept: (s) => {
      console.log({ accept: s });
    },
    onComplete: (s) => {
      console.log({ complete: s });
    },
  });
  return <input ref={ref} placeholder="00:00" />;
}

```

**Comment by radixdt2501** [comment]
@EliseyMartynov any update on react sandbox ?
