### ISSUE TITLE
Bug with a phone number

### ISSUE THREAD

**Issue by no4ch** [uNmAnNeR/imaskjs#538]
**Describe the bug**
I have phone number 7761112233, 776 111 22 33 pattern '+{7} ({7}00) 000 00 00'

**To Reproduce**
https://codepen.io/no4ch/pen/yLXVdVg

**Expected behavior**
I expects result '+7 (776) 111 22 33', but I have '+7 (761) 112 23 3_'. Mask can not see number, where number have 77 at the start

**Environment:**
 - OS: Windows
 - Browser: chrome
 - IMask version 6.0.7
 - laravel framework

**Additional context**

**Comment by uNmAnNeR** [comment]
`{7}` means that 7 should be treated as part of value if possible

so applying value 772 to `+{7} ({7}00) 000 00 00` means `+{7 from value} ({7 from value}2...`

but  applying value 792 to `+{7} ({7}00) 000 00 00` means `+{7 from value} ({7 from masked, skip char from value}92...`

so it's a desired behavior for lots of other cases. You case can be handled in several ways depending on requirements.
