### ISSUE TITLE
Toggling the the input control's visibility resets the mask's config to its initial value

### ISSUE THREAD

**Issue by dstj** [uNmAnNeR/imaskjs#539]
Hi, 

After implementing #500, I had this new issue.

**Describe the bug**
I've got a masked input defined as `<input #tb type="text" formControlName="amount" [imask]="iMaskCfg" unmask="typed">`

When updating a mask's configuration with `this.tb.maskRef.updateOptions({ mask: .... });`, if the `<input>` control is hidden and shown back again, the mask's config reverts back to the initial value, instead of keeping its updated version.

**Note**: Updating it with `this.iMaskCfg = { mask: ... };` does **not** have the problem.

**To Reproduce**
[Stackblitz reproduction](https://stackblitz.com/edit/angular-ivy-zsgnxx?file=src/app/app.component.html)

0) The mask is initially set to "fixed $ amount".
1) Switch it to "percentage"
2) Click "Toggle Visibility" twice (to hide and show them again)
3) The first input will display the `$` mask while the 2nd will display the correct `%` mask.

**Expected behavior**
After toggling the input's visibility, the mask should remain in it's updated state.

**Environment:**
Using imask v6.0.7 with Angular 11

**Comment by uNmAnNeR** [comment]
https://stackblitz.com/edit/angular-ivy-hmastm?file=src/app/app.component.ts

**Comment by dstj** [comment]
@uNmAnNeR I don't understand you comment.

From the diff, you seemed to have just replaced `this.tb.maskRef.updateOptions({ mask: .... });` that does not work with the working `this.iMaskCfg = { mask: ... }; ` as I said it did.

My bug report was about `this.tb.maskRef.updateOptions({ mask: .... });` that does not work. As that seems to be the intended way of updating the mask, I though important to report it.

**Comment by uNmAnNeR** [comment]
you are using [imask] directive in template so it overrides your config. Prefer declarative approach over imperative when possible.

**Comment by dstj** [comment]
> you are using [imask] directive in template so it overrides your config. Prefer declarative approach over imperative when possible.

Ah, OK, so I understand that `[imask]` and `this.tb.maskRef` are two distinct copies of the mask, and recreating the component reassigns `this.tb.maskRef` to the unmodified property...  that makes sense.

I was following the documentation exampled here: https://github.com/uNmAnNeR/imaskjs/tree/master/packages/angular-imask. Maybe adding a bit more doc on how to update the live mask with similar use cases would potentially help others as well as you did here with me. Thanks.
