### ISSUE TITLE
trigger mask on existing values

### ISSUE THREAD

**Issue by artknight** [uNmAnNeR/imaskjs#54]
How can i trigger the mask programmatically on a field that has already values filled in without doing `.trigger('change')`?

**Comment by uNmAnNeR** [comment]
`change` event triggers internal method:
```
mask._onChange();
```
Instead, you could use
```
mask.value = <new val>;
```
or
```
mask.updateValue();     // update model from view
mask.updateControl();   // update view from new model
```
But by design synchronization supposed to be done internally.
