### ISSUE TITLE
Angular module couldn't resolved. V.6.2.0

### ISSUE THREAD

**Issue by blueiceprj** [uNmAnNeR/imaskjs#544]
**Describe the bug**
Angular module couldn't resolve.

**Environment:**
 - IMask version 6.2.0

**Comment by uNmAnNeR** [comment]
fixed in 6.2.1

**Comment by blueiceprj** [comment]
Thank you for your quick reply.

**Comment by uNmAnNeR** [comment]
thanks for reporting!
