### ISSUE TITLE
Angular-IMask fails to compile with NGCC

### ISSUE THREAD

**Issue by bstaley** [uNmAnNeR/imaskjs#545]
**Describe the bug**
The latest version of angular imask breaks with ivy compile

**To Reproduce**
This is just a plain out-of-the-box angular 12 setup with `angular-imask: latest` plus `enableIvy: true`. https://stackblitz.com/edit/angular-qsx9w1

**Expected behavior**
NGCC compiles successfully 

**Environment:**
 - OS: windows 10
 - Browser: chrome
 - Version: 92
 - IMask version: latest, (6.2.0 dep within angular-imask)
 - Framework/plugin version if used: angular 12

**Additional context**
This issue started happening just around the time the new version was published yesterday

**Comment by uNmAnNeR** [comment]
i checked it on 6.1.0. it was not working as well, or is it?
anyway no ideas how to deal with it for now.

**Comment by uNmAnNeR** [comment]
so finally I downloaded your example and tried to build it locally. I had some errors about mismatching angular versions, but I fixed it and was successfully able to run it. You can check sources here: https://stackblitz.com/edit/angular-ivy-ur7qzb
It still does not work on stackblitz.com but seems like it's not imask problem.

**Comment by bstaley** [comment]
thanks for following up
