### ISSUE TITLE
Wrong number mask when changing value of input text by JS

### ISSUE THREAD

**Issue by MaiquelZF** [uNmAnNeR/imaskjs#546]
Hello,

First of all thank you for givev us the IMask!! ;)

here is the problem I have:
When we change the input value by code(JS) the masked value appears ok.
But after lost Focus on the input the masked value change wrongly...

Here there are the jsfiddle https://jsfiddle.net/za2fy3ud/1/

Or

```
<input id="input" type="text" value="100">

<script src="https://cdnjs.cloudflare.com/ajax/libs/imask/6.2.0/imask.min.js" integrity="sha512-HI23Dg1O8Npjtz/XNnbZXfdKV3Kj7nLMMPFclVHxljgTTGUL/9xWOqe8frXotl8z9khBCtzmRycZxcwz3KweJg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

 <script type="text/javascript" charset="utf-8">

 	var maskValor = {
	    mask: Number,
	    thousandsSeparator: '.',
	    radix: ',',  // fractional delimiter
	    mapToRadix: ['.'],
	    normalizeZeros: false,
	    scale: 2
	};

	var element = document.getElementById('input');
	IMask(element, maskValor);
	  
	document.getElementById('input').value="1.000,56";  

</script>
```

* Just click in the input (to get Focus) and then click out of the input (to lost focus) and then the mask get wrong.

**Comment by uNmAnNeR** [comment]
you have `mapToRadix: ['.'],` so in your initial value dot is mapped to radix. for `imask` it does not matter from where character comes from, was it user input or initial value so it processed characters uniformly. it means that you can't have `mapToRadix` char as a `thousandsSeparator` for now. Let me check if it could be handled the other way.

**Comment by uNmAnNeR** [comment]
fixed in https://github.com/uNmAnNeR/imaskjs/issues/695
