### ISSUE TITLE
Imaskjs-React Hook not working in NextJS

### ISSUE THREAD

**Issue by BengtHagemeister** [uNmAnNeR/imaskjs#547]
**Describe the bug**
When using the new imaskjs react hook in NextJS there is immediately an `Unhandled Runtime Error
Error: Invalid hook call. Hooks can only be called inside of the body of a function component.`

This could maybe have something todo with the package initialising its own react version (see https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react)

I have copied the two important files mixin.ts and hook.ts in my own project and it immediately works without any problems. So I think is has something todo with the package dependencies declaration. I was unfortunately not able to find the bug.

**To Reproduce**
The runtime error will immediately pop up. The example was taken from react-imask readme. https://stackblitz.com/edit/nextjs-eljhmp?file=pages/index.js

**Expected behavior**
There should be no runtime error.

**Environment:**
 - OS: MacOS
 - Browser Chrome
 - Version 93
 - React IMask version 6.2.1

**Comment by uNmAnNeR** [comment]
fixed on v6.2.2
