### ISSUE TITLE
Can't import angular-imask

### ISSUE THREAD

**Issue by maxkorz** [uNmAnNeR/imaskjs#55]
I updated angular-imask from 1.0.0 to 3.2.2 and got error:
```
Could not find a declaration file for module 'angular-imask'. '<path>/node_modules/angular-imask/dist/angular-imask.umd.js' implicitly has an 'any' type.
  Try `npm install @types/angular-imask` if it exists or add a new declaration (.d.ts) file containing `declare module 'angular-imask';`
```

**Comment by musatov** [comment]
I builded package locally and everything is correct. Problem only with incorrect publishing of npm package. I would like to ask author to just republish content of packages/angular-mask/dist directory. Locally it looks like the following:
<img width="606" alt="screen shot 2018-04-30 at 19 03 16" src="https://user-images.githubusercontent.com/182852/39434534-e612381c-4ca9-11e8-8d64-0a5109caf3a1.png">
But at the published package only angular-imask.umd.js is present.

Alexey, thank you for your cool library. Please help us to use it with our Angular apps smoothly :)

**Comment by uNmAnNeR** [comment]
Thanks for issue and sorry guys for long delay. Should be fixed now.
