### ISSUE TITLE
angular-imask 6.2.2 has bad dependency

### ISSUE THREAD

**Issue by slubowsky** [uNmAnNeR/imaskjs#550]
>npm i
npm ERR! code ETARGET
npm ERR! notarget No matching version found for imask@^6.2.2.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'angular-imask'

**Comment by uNmAnNeR** [comment]
should be solved now
