### ISSUE TITLE
Type IMaskModule does not have 'ɵmod' property.

### ISSUE THREAD

**Issue by blueiceprj** [uNmAnNeR/imaskjs#551]
**Describe the bug**
Angular application getting error and not running

**To Reproduce**

**Environment:**
 - Browser [chrome]
 - IMask 6.2.2
 - Framework/plugin version if used

**Additional context**

Uncaught Error: Type IMaskModule does not have 'ɵmod' property.
    at getNgModuleDef (core.js:1119)

**Comment by uNmAnNeR** [comment]
here is working example: https://stackblitz.com/edit/angular-ivy-ur7qzb
you can download and run locally. Let me know if you will have some errors.
In other cases please provide your sources to figure out.

**Comment by blueiceprj** [comment]
I have tried your example. Its getting error.
<img width="997" alt="Ekran Resmi 2021-09-15 13 33 49" src="https://user-images.githubusercontent.com/1829975/133426209-178ec16e-e2ec-4bec-970d-9aeb12fa7b2f.png">

**Comment by uNmAnNeR** [comment]
@blueiceprj you have to download it and run locally. Seems there are some problems with running it on stackblitz

**Comment by blueiceprj** [comment]
Thanks you for your reply. Its running as well. I think it would be a npm update error.
