### ISSUE TITLE
Add truncate option (similar to overwrite)

### ISSUE THREAD

**Issue by koculu** [uNmAnNeR/imaskjs#556]
**What problem you are trying to solve?**
I would like users to insert anywhere in the input box by shifting existing content to the right and truncated in the end. Current options either block key inputs or overwrite cursor position. This makes it impossible to add a char inside a text without deleting the remaining content when overwrite option is enabled. If overwrite option is disabled inserting only works when the mask is not full. If the mask is full key presses are ignored.

Actually, this is the default behavior of HTML input box (except truncating in the end) and most users will be more familiar with this approach.

Example use case:
```
const maskOptions = {
        overwrite: true,
        mask: '+0[0][0] (000) 000-00-00',
        placeholderChar: '_',
        lazy: false
      }
```
This phone mask covers all countries including single, double and triple digit country code.
Browser auto fills phone number as:
auto-filled input value: +491(234)-23-4_
where the phone number is correct but country code placement is not. User wants to add a space after +49.
The only way is to delete everything after +49 to add a space after +49.

**Describe the solution you'd like**
Add a truncate: boolean parameter which handles key inputs by inserting the character and shifting existing content to the right and truncating in the end.

**Describe alternatives you've considered**
I may add an input preview handler and do the shift operation manually but I believe it is not a good way of doing things.

Besides, Thank you for awesome mask component. This is really high quality component and deserves better popularity.

**Comment by uNmAnNeR** [comment]
will be something like `overwrite: 'shift'`
