### ISSUE TITLE
The way to unmask submitted value

### ISSUE THREAD

**Issue by Real-Gecko** [uNmAnNeR/imaskjs#559]
I use following JS snippet to initialize `number` inputs with `imaskjs`:
```js
$('input[type="number"]').each(function () {
    $(this).attr("type", "text")
    IMask(this, {
        mask: Number,  // enable number mask
        thousandsSeparator: ' ',  // any single char
        radix: '.',  // fractional delimiter
        mapToRadix: ['.', ','],
    });
})
```
Problem is the value sent to the server as is: `123 123.12` which causes issues in backend as it does not know how deal with extra `space` between number. Is there a way to unmask the value before sending?

**Comment by ziyaddin** [comment]
Have you tried using `unmaskedValue()` method?

**Comment by Real-Gecko** [comment]
So, on form submit I have to call `unmaskedValue()` to get the desired data and then send it to server?
Is there a way to do this _automagically_?

**Comment by ziyaddin** [comment]
> So, on form submit I have to call unmaskedValue() to get the desired data and then send it to server?

Yes.

> Is there a way to do this automagically?

As I know, there is no way. I guess, it is by design, so that you are able to manipulate data as you wish.

**Comment by igorLB** [comment]
I was stuck with same issue but I think I found a solution, I'm using vanilla javascript + stimulus.js

```javascript
export default class extends Controller {
    masks = []
    
    // component loaded
    connect() {
        this.applyMasks()
    }

    applyMasks() {
        document.querySelectorAll('[data-mask]').forEach(el => {
            const mask = el.dataset.mask;
            [...]
            const imask = IMask(el, imaskOptions)
            this.masks.push(imask);
        });
    }

    unmaskValues() {
        this.masks.forEach(imaksInstance => {
            imaksInstance.el.value = imaksInstance.unmaskedValue;
        });
    }

    async handleSubmit(event) {
        event.preventDefault();

        this.unmaskValues()

        const formData = new FormData(event.target);
        const body = new URLSearchParams(formData);

        try {
            const response = await fetch([...]), {
                method: 'POST',
                body: body
            });
        } catch (e) {
        }
    }
}
```
