### ISSUE TITLE
This dependency was not found (@vue/composition-api)

### ISSUE THREAD

**Issue by yooouuri** [uNmAnNeR/imaskjs#561]
**Describe the bug**
```
This dependency was not found:

* @vue/composition-api/dist/vue-composition-api.esm.js in ./node_modules/vue-demi/lib/index.mjs
```

Vue-demi does not install @vue/composition-api package:

```
vue-demi@^0.11.2:
  version "0.11.4"
  resolved "https://registry.yarnpkg.com/vue-demi/-/vue-demi-0.11.4.tgz#6101992fe4724cf5634018a16e953f3052e94e2a"
  integrity sha512-/3xFwzSykLW2HiiLie43a+FFgNOcokbBJ+fzvFXd0r2T8MYohqvphUyDQ8lbAwzQ3Dlcrb1c9ykifGkhSIAk6A==
```

So im forced to install it, but I don't want to...

**To Reproduce**
Install latest version of imaskjs (version "6.2.2")

**Expected behavior**
No error should be thrown.

**Environment:**
 - OS: Mac OS
 - Node: v14.18.0
 - IMask version: 6.2.2
 - Framework/plugin version if used: vue

**Additional context**

**Comment by uNmAnNeR** [comment]
hey! @yooouuri  can you try it on v6.4.2? thanks!
