### ISSUE TITLE
Property 'compiledMasks' does not exist on type 'AnyMasked'

### ISSUE THREAD

**Issue by aveselovskii** [uNmAnNeR/imaskjs#578]
**Describe the bug**
Second example from [masked-dynamic](https://imask.js.org/guide.html#masked-dynamic ) fails type checking

<img width="711" alt="Screenshot 2021-11-23 at 16 26 01" src="https://user-images.githubusercontent.com/43859009/143033028-6b8ce345-7a1b-4000-a886-73ae79dd6f05.png">

**To Reproduce**
Go to the project with TS, try to create a dynamic mask according to the example

**Environment:**
 - IMask 6.0.7

**Comment by ThijsBoudrez** [comment]
#554

**Comment by ThijsBoudrez** [comment]
Take look here #554
