### ISSUE TITLE
[Angular] numbers are not handled correctly

### ISSUE THREAD

**Issue by maxkorz** [uNmAnNeR/imaskjs#58]
Demo: https://stackblitz.com/edit/angular-hbfpwo?file=app%2Fapp.component.html

Issue 1: initial value for `maskedNumber` is set to `1000`. But the input is empty.
Issue 2: after I change value in the input, the value is being converted to string `"1000"`. It should be a number.

**Comment by uNmAnNeR** [comment]
@maxkorz try using `unmask='typed'` since v3.3.0

**Comment by maxkorz** [comment]
@uNmAnNeR it seems to work fine, thanks

**Comment by maxkorz** [comment]
@uNmAnNeR I found another issue. When I clear an input the value should be `null`, but imaskjs treats empty values as `0`

Demo: https://stackblitz.com/edit/angular-xwgwzv?file=app/app.component.html
remove text from inputs to see the difference

**Comment by uNmAnNeR** [comment]
@maxkorz that's a question, because `Number('') === 0`. Why it should be `null`?

**Comment by maxkorz** [comment]
@uNmAnNeR a blank value means "value is not set". According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null)
> The value null represents the intentional absence of any object value

How come your plugin treats the intentional absence of value as `0`?

**Comment by uNmAnNeR** [comment]
`Number` is a value type, it is not an object. Therefore it should always has a value.
Why empty string should be processed as `null` but not `0` just like js stands for?
