### ISSUE TITLE
angular-imask Angular 13 support

### ISSUE THREAD

**Issue by thekip** [uNmAnNeR/imaskjs#582]
The subject in the title. The Angular 13 switched to new APF (Angular Package Format) and encourage libary authors to build ptheir projects with new angular 13 compiler in partial ivy mode. 

For library authors it means just update angular dependencies and rebuild the package.

**Comment by uNmAnNeR** [comment]
should be fixed in 39a3867bbce20fd9a7f3903c4b7b56b97ff4e113
