### ISSUE TITLE
Problem on MaskedRange block. Cursor stucks on typing

### ISSUE THREAD

**Issue by LingVuDev** [uNmAnNeR/imaskjs#583]
**Describe the bug**
I have this imask config for my react app:
```
const config = {
    mask: "m{.}Y",
    blocks: {
      m: {
        mask: IMask.MaskedRange,
        from: 1,
        to: 12,
        maxLength: 2
      },
      Y: {
        mask: IMask.MaskedRange,
        from: "2020",
        to: "2030"
      }
    }
  };
 ```
 Usually it should be possible to type in values like `12.2021`, but this is not possible because the cursor jumps after trying to type it in.

The result is  that it always stucks at `12.20`.
 
**To Reproduce**
https://codesandbox.io/s/react-imask-input-box-masks-forked-4xc0p

**Expected behavior**

**Environment:**
 - OS: MacOS
 - Browser chrome
 - IMask version: 6.2.2
 - Framework/plugin version if used: react

**Comment by uNmAnNeR** [comment]
fixed in #606
