### ISSUE TITLE
useIMask hook is crashing when I pass the value property

### ISSUE THREAD

**Issue by rcanessa89** [uNmAnNeR/imaskjs#601]
**Describe the bug**
I'm trying to use the useIMask hook with a value but if crashing

**To Reproduce**
I'm defining this component

```
const PhoneInput = ({ value = '1234567890' }) => {
  const { ref: maskReference } = useIMask({
    value,
    mask: '(#00) 000-0000',
    definitions: {
      '#': /[1-9]/
    }
  });

  return (
    <input ref={maskReference} />
  );
};
```

![Screen Shot 2022-01-20 at 5 41 11 PM](https://user-images.githubusercontent.com/10558937/150439573-0b12e964-3222-4774-8297-666f9b1c8023.png)

**Expected behavior**
Should not crash the app and should change if the value prop change

**Environment:**
 - OS: MacOS Big Sure
 - Chrome
 - Version 97.0.4692.71 (Official Build) (x86_64)
 - IMask version 6.2.2
 - react-imask 6.2.2

**Comment by uNmAnNeR** [comment]
till 83f8ce8 there was not allowed to pass `value` property to the hook. Should work in the next release

**Comment by vmarcosp** [comment]
hey, @uNmAnNeR you know when the next release will be published?
