### ISSUE TITLE
Right-side mask character does not work in conjunction with decimals

### ISSUE THREAD

**Issue by bfeister** [uNmAnNeR/imaskjs#604]
**Describe the bug**

Given the codepen below, for currency, adding a decimal `.` character behaves as expected, but adding a decimal to percent (because the mask `%` character is to the right, presumably) does not work.

**To Reproduce**
1. Enter `3.3` in each input field.
2.  Observe that it doesn't work for the percent input field.
Note: I am using material-ui, and have reproduced the bug both with and without material-ui

https://codesandbox.io/s/hungry-cerf-nkuh6?file=/src/App.js

**Expected behavior**
Percent mask should accept decimals.

**Environment:**
 - OS: Mac OS Big Sur
 - Browser: Chrome
 - Version: 97.0.4692.71
 - IMask version: 6.2.2
 - Framework/plugin version if used

**Comment by uNmAnNeR** [comment]
dublicates https://github.com/uNmAnNeR/imaskjs/issues/486

**Comment by bfeister** [comment]
Thanks for referencing, I thought I reported previously but couldn't find it
