### ISSUE TITLE
react-imask: pass placeholder value to placeholder prop of underlying input

### ISSUE THREAD

**Issue by Donorlin** [uNmAnNeR/imaskjs#607]
**What problem you are trying to solve?**
Hi,
is it possible to implement passing placeholder value to placeholder property of the underlying input?

It can help with the styles.

Something like 
```
<input ... placeholder="+___ ___ ___ ___ ___ ___" />
```

Now it is shown as if it was a value.

Example of styles (my styles are changing the color of the input's placeholder)
![image](https://user-images.githubusercontent.com/31594179/152348642-e9968bab-8ffb-4e55-9f3f-f2ff2c34d02a.png)

I am using a simple setup with version 6.4.0 of react-imask
```
        <IMaskInput
            mask={"{+}000 000 000 000"}
            lazy={false}
            ...
        />
```

Thank you for your response and cool functionality.

**Comment by uNmAnNeR** [comment]
https://codesandbox.io/s/zealous-kalam-gduzkg?file=/src/App.js
seems like it's working
