### ISSUE TITLE
maskOptions not updated the mask, and not working decimal part?

### ISSUE THREAD

**Issue by sanyi9305** [uNmAnNeR/imaskjs#614]
**Describe the bug**
I would like update thousandsSeparator in the mask.
I made the new dynamic maskOptions and call mask.updateOptions(maskOptions) but this is not working. This was good in the 5.8 version.

And if I have a decimal number in the input field eg: 10.11 and if I press "." does not jump to the decimal part. This is a bug or a normal working?

old mask was:
maskOptions = {
            mask: [{
                    mask: "num",
                    startsWith: '+',
                    lazy: false,
                    blocks: {
                        num: {
                            mask: Number,
                            lazy: false,
                            overwrite: false,
                            scale: 2,
                            signed: true,
                            thousandsSeparator: ",",
                            padFractionalZeros: true,
                            normalizeZeros: true,
                            radix: ".",
                            mapToRadix: ["."],
                            min: 0,
                            max: 99999999,
                        }
                    }
                }, {
                    mask: "(num)",
                    startsWith: '-',
                    lazy: false,
                    blocks: {
                        num: {
                            mask: Number,
                            lazy: false,
                            overwrite: false,
                            scale: 2,
                            signed: true,
                            thousandsSeparator: ",",
                            padFractionalZeros: true,
                            normalizeZeros: true,
                            radix: ".",
                            mapToRadix: ["."],
                            min: 0,
                            max: 99999999,
                        }
                    }
                }, 
                {mask: Number,
                    maxLength: length,
                    autofix: true,
                    startsWith: '',
                    lazy: false,
                    overwrite: false,
                    scale: 2,
                    signed: true,
                    thousandsSeparator: ",",
                    padFractionalZeros: true,
                    normalizeZeros: true,
                    radix: ".",
                    mapToRadix: ["."],
                    min: 0,
                    max: 99999999,
                    
                }
            ],

            dispatch: function (appended, dynamicMasked) {

                var number = (appended + dynamicMasked.value);

                return dynamicMasked.compiledMasks.find(function (m) {

                    return number.indexOf(m.startsWith) === 0;

                });
            }
            

        };

And the new mask I change the thousandsSeparator: " ",     (space)

**Environment:**
 - Browser [chrome]
 - Version [98.0.4758.82]
 - IMask version :  6.4.0
 
Do I have to use it differently than before?

**Comment by uNmAnNeR** [comment]
cant reproduce. feel free to reopen if you have more info / working example
