### ISSUE TITLE
Cannot use blocs and array on hook syntax in react

### ISSUE THREAD

**Issue by AntonnyAGS** [uNmAnNeR/imaskjs#617]
**Describe the bug**
Get error on console when using array syntax and blocs, example:
       mask: [
              { mask: '' },
              {
                mask: 'R$ num',
                lazy: false,
                blocks: {
                  num: {
                    mask: Number,
                    padFractionalZeros: true,
                  },
                },
              },
            ], 

**Expected behavior**
Should result currency mask

**Environment:**
 - OS: Linux
 - Browser Chrome
 - IMask version: 6.4.2
 - Framework/plugin react

// I'm getting this error....
![image](https://user-images.githubusercontent.com/48499380/153952178-90ecb391-a308-44a3-9b47-801ffa4d5511.png)

I know that the warning I can resolving using value provided by hook... but that value cuase debounce on my MUI TextField 

THIS WORKS ALTHOUGH THE ERROR!!

**Comment by uNmAnNeR** [comment]
how do you use it. plz provide full example

**Comment by AntonnyAGS** [comment]
> Oh, sorry...
I wrapped it on my custom MUI input element like that:
`
export const Input = ({
  startIcon,
  endIcon,
  variant,
  validationRegister,
  mask,
  maskDefaultValue,
  ...props
}: CustomInputProps): JSX.Element => {
  if (mask) {
    const { ref, maskRef, setValue } = useIMask(mask, {
      onComplete: (value) => {
        setValue(value);
      },
    });

    useEffect(() => {
      if (maskDefaultValue) {
        setValue(maskDefaultValue);
        ref.current.value = maskDefaultValue;
        maskRef.current.value = maskDefaultValue;
      }
    }, [maskDefaultValue]);

    return (
      <StyledInput
        {...props}
        {...validationRegister}
        inputRef={ref}
        InputProps={props.InputProps ? { ...props.InputProps } : { startAdornment: startIcon, endAdornment: endIcon }}
        variant={variant || 'filled'}
      />
    );
  }
`
and my mask my mask object:
`
export const currencyMask: IMask.AnyMaskOptions = {
  mask: [
    { mask: '' },
    {
      mask: 'R$ num',
      lazy: false,
      blocks: {
        mask: Number,
        padFractionalZeros: true,
      }
    }
  ]
 }
`
On debugging it I see that this error is only threw when using ```padFractionalZeros```option in array syntax... and if a use it outside array I cant get decimals

**Comment by marcos-vinicios-dv** [comment]
I loved your lib but I have the same error it happens to me, if I need to send the code too.

Is there a workaround that can be used?
