### ISSUE TITLE
React IMaskMixin compatibility with MUI v5 TextField

### ISSUE THREAD

**Issue by igorgarbuz** [uNmAnNeR/imaskjs#623]
**What problem you are trying to solve?**
Cannot make work TextField wrapped into IMaskMixin. Value prop seems not to be passed correctly from IMaskMixin to TextField.

**Describe the solution you'd like**
Be able to passe MUI v5 TextField to IMaskMixin. 

**Describe alternatives you've considered**
Replace MUI v5 TextField by `<input>`

**Comment by TrejGun** [comment]
would be really nice to have this as mixin instead of ugly 3 levels deep workaround

**Comment by xzessmedia** [comment]
as workaround save this in your project and import from there

`import React from 'react';
import IMask from 'imask';
export declare type Falsy = false | 0 | "" | null | undefined;
export declare type MaskedElement = HTMLInputElement | HTMLTextAreaElement;
export declare type ReactMaskProps<Opts extends IMask.AnyMaskedOptions = IMask.AnyMaskedOptions, Unmask extends ('typed' | boolean) = false, Value = Unmask extends 'typed' ? IMask.InputMask<Opts>['typedValue'] : Unmask extends Falsy ? IMask.InputMask<Opts>['value'] : IMask.InputMask<Opts>['unmaskedValue']> = {
    onAccept?: (value: Value, maskRef: IMask.InputMask<Opts>, e?: InputEvent) => void;
    onComplete?: (value: Value, maskRef: IMask.InputMask<Opts>, e?: InputEvent) => void;
    unmask?: Unmask;
    value?: Value;
    inputRef: (el: MaskedElement) => void;
};
export declare type IMaskMixinProps<Opts extends IMask.AnyMaskedOptions = IMask.AnyMaskedOptions, Unmask extends ('typed' | boolean) = false, Value = Unmask extends 'typed' ? IMask.InputMask<Opts>['typedValue'] : Unmask extends Falsy ? IMask.InputMask<Opts>['value'] : IMask.InputMask<Opts>['unmaskedValue']> = IMask.AllMaskedOptions & ReactMaskProps<Opts, Unmask, Value>;
export declare type IMaskInputProps<Opts extends IMask.AnyMaskedOptions = IMask.AnyMaskedOptions, Unmask extends ('typed' | boolean) = false, Value = Unmask extends 'typed' ? IMask.InputMask<Opts>['typedValue'] : Unmask extends Falsy ? IMask.InputMask<Opts>['value'] : IMask.InputMask<Opts>['unmaskedValue']> = MaskedElement & IMaskMixinProps<Opts, Unmask, Value>;
export default function IMaskMixin<Opts extends IMask.AnyMaskedOptions = IMask.AnyMaskedOptions, Unmask extends ('typed' | boolean) = false, Value = Unmask extends 'typed' ? IMask.InputMask<Opts>['typedValue'] : Unmask extends Falsy ? IMask.InputMask<Opts>['value'] : IMask.InputMask<Opts>['unmaskedValue']>(ComposedComponent: React.ComponentType<IMaskMixinProps<Opts, Unmask, Value>>): React.ComponentType<any>;
`

**Comment by uNmAnNeR** [comment]
guys i do not have time to figure out/rollup a project with MUI so please create a simple case in a sandbox to run. feel free to reopen
