### ISSUE TITLE
Dynamic masks: error throwing when overflow value

### ISSUE THREAD

**Issue by PurpleTape** [uNmAnNeR/imaskjs#632]
Hello!

**Describe the bug**
If you specify the maximum length value in the dynamic mask, and then try to enter another some character, an error will occur

**To Reproduce**
1. Go to https://imask.js.org/guide.html#masked-dynamic
2. Click "demo"
3. Open browser console
4. Write some max length value (ex: 000000000)
5. Move cursor to some place before end
6. Write "0" again
7. See error

**Expected behavior**
imask prevents entering unavailable values in the field and the error does not occur if you try to do this 

**Environment:**
 - OS: macOS
 - Browser: Firefox 97.0.1, Chrome 96.0.4664.55
 - IMask version: 6.4.2
 - Framework/plugin: no

**Error example**
<img width="584" alt="изображение" src="https://user-images.githubusercontent.com/9420536/155273996-5bb04876-12c1-4fe0-a766-7b1e9e140c99.png">

**Comment by keremkutlubay** [comment]
This bug can be fixed with pattern.js changing with line of  288 from

      const blockDetails = block._appendChar(ch, { ...flags, _beforeTailState: flags._beforeTailState?._blocks[bi] });
to
      const blockDetails = block._appendChar(ch, { ...flags, _beforeTailState: flags._beforeTailState?._blocks?.[bi] });

**Comment by uNmAnNeR** [comment]
fixed, will be released soon

**Comment by keremkutlubay** [comment]
Thank you.
