### ISSUE TITLE
mask{Number} does not work as expected on safari (MacOS) (react-imask)

### ISSUE THREAD

**Issue by jamesrees77** [uNmAnNeR/imaskjs#635]
**Describe the bug**
When you use mask{number} on MacOS Safari, and have a type of "number", using the arrows to increase the value concats the previous value and the new value together (i.e 9 becomes 109)

**Expected behavior**
Should just increment by 1

**Environment:**
 - OS: MacOS
 - Browser: safari
 - Version: 15.2
 - IMask version : 6.4.2
<img width="239" alt="Screenshot 2022-02-28 at 14 02 01" src="https://user-images.githubusercontent.com/36487155/156021480-bd4ce72c-7cde-4c59-828b-c3b69f1a4258.png">
<img width="180" alt="Screenshot 2022-02-28 at 14 02 06" src="https://user-images.githubusercontent.com/36487155/156021510-d27e40cc-9425-4409-a9e7-ee06b2726688.png">

**Comment by Zhanadil1509** [comment]
@uNmAnNeR not only on mac, but also on pc and android
