### ISSUE TITLE
React controlled input with monetary value

### ISSUE THREAD

**Issue by Luccasoli** [uNmAnNeR/imaskjs#641]
**Describe the bug**
Even dont writing any comma, imask inject one inside input and block values with 3 digits or more

**To Reproduce**
code: https://codesandbox.io/s/monetary-comma-radix-separator-8uzfuy?file=/src/App.js:0-602
video: https://user-images.githubusercontent.com/31039396/157121811-084f99ec-bf3c-4259-8da1-0ea4819fef37.mp4

try typing a number with many digits

**Expected behavior**
the numbers typed appear while I don't type a comma or reach a maximum number of digits

**Environment:**
 - OS: Windows
 - Browser: chrome
 - Version: 99.0.4844.51 64 bits
 - IMask version: 6.4.2
 - Framework/plugin version if used: react-imask

**Additional context**
It would be great to have examples of controlled input in the documentation

**Comment by uNmAnNeR** [comment]
if you use `unmaskedValue` in model then also have to pass `unmaskedValue` to the hook. not just `value`
