### ISSUE TITLE
ä,ö,ü and ß can not be used in the placeholder string in IE

### ISSUE THREAD

**Issue by FlorianKalinna** [uNmAnNeR/imaskjs#645]
**Describe the bug**
When clicking inside the text of the input mask the cursor always jumps to the front. And when you click outside the input field again the input field is being cleared. The following error is displayed in the browser console "Unable to get property '0' of an undefined or null reference". 

**To Reproduce**
Input Mask with value filled through props and dynamic mask with 2 mask objects. 

```typescript
import React, { useRef } from "react";
import { IMaskInput } from "react-imask";

export default function FlowInputMask(props) {
  const ref = useRef(null);
  const { value, setValue } = props;

  return (
    <IMaskInput
      placeholder={"Bitte ausfüllen"}
      placeholderChar={"_"}
      mask={[{ mask: "0000000-0-0000" }, { mask: "0000-0" }]}
      value={value}
      onAccept={(val) => setValue(val as string)}
      ref={ref}
    ></IMaskInput>
  );
}
```

**Expected behavior**
Input field is not being cleared when focus goes away. Cursor does not jump to the front when clicking inside the input field.

**Environment:**
 - OS: Windows
 - Browser IE 
 - IMask version 4.6.2
 - Framework/plugin react 17.0.2

**Additional context**
Problem only occurs with IE. In Chrome everything works fine

**Comment by uNmAnNeR** [comment]
not a placeholder issue, fixed, will be released soon
