### ISSUE TITLE
Deleting a date with Vue plugin deletes the entire date, not the right-most characters

### ISSUE THREAD

**Issue by timmyomahony** [uNmAnNeR/imaskjs#648]
## Describe the bug
When using the [Vue Plugin](https://github.com/uNmAnNeR/imaskjs/tree/master/packages/vue-imask) with Vue 3 composition (but also regular component AFAIK), hitting backspace once you have entered a date deletes the entire date. This is not the same functionality as the vanilla JS examples here: https://imask.js.org/ (where you can delete individual numbers without deleting the date)

### Via the Vue Plugin (incorrect behavior):
![CleanShot 2022-03-29 at 14 05 58](https://user-images.githubusercontent.com/615149/160617944-7febdc46-8557-4837-843b-cf767adbfb35.gif)

### From the Native Examples (correct behavior):
![CleanShot 2022-03-29 at 14 02 06](https://user-images.githubusercontent.com/615149/160617254-9a1abe3b-ed2e-42bd-a3cb-d8e4a43a9bd5.gif)

## To Reproduce
Using the [default composition API from the examples](https://github.com/uNmAnNeR/imaskjs/tree/master/packages/vue-imask#mask-composable-vue-3):

https://codesandbox.io/s/vue-imask-date-delete-issue-txsipr?file=/src/App.vue

## Expected behavior
Instead of deleting the entire date, only the right-most numbers should be deleted.

## Environment:
 - OS: **MacOS**
 - Browser **Firefox (but Chrome too)**
 - Version **98.0.02**
 - IMask version **6.4.2**
 - Framework/plugin version if used **6.4.2**

**Comment by uNmAnNeR** [comment]
fixed in v6.4.3
