### ISSUE TITLE
Receiving Jest TypeError for imask 6.4.2

### ISSUE THREAD

**Issue by nzacca** [uNmAnNeR/imaskjs#649]
**Describe the bug**
When running tests in Jest for an Angular app, we are receiving an error after updating to imask `6.4.2` from `6.1.0`.

```bash
TypeError: (0 , import_imask.default) is not a function

... <snipped for brevity>

      at DefaultImaskFactory.create (../../node_modules/angular-imask/fesm2020/angular-imask.mjs:221:16)
      at IMaskDirective.initMask (../../node_modules/angular-imask/fesm2020/angular-imask.mjs:138:38)
      at IMaskDirective.ngAfterViewInit (../../node_modules/angular-imask/fesm2020/angular-imask.mjs:70:18)
```

**To Reproduce**
TODO will update with a reproduction soon.

**Expected behavior**
Jest tests can run without error.

**Environment:**
 - OS: Windows/Linux
 - Browser: N/A
 - IMask version: 6.4.2
 - Framework/plugin version: angular-imask 6.4.2; Angular 13.3

**Additional context**
I'm currently investigating if this is related some how to a circular dependency issue within imask. Found this issue which appears to be the same problem: https://github.com/kulshekhar/ts-jest/issues/1873

Just to note, 6.4.2 runs just fine in the app. We're only receiving the above error when running tests.

**Comment by davidmccoy-8451** [comment]
Am seeing the same error

**Comment by berthertogen** [comment]
Same issue here, upgrading from 6.2.2 to 6.4.2 (angular 13)

**Comment by berthertogen** [comment]
Quick update, we were able to resolve this issue by providing our own implementation of the DefaultImaskFactory. 
Took the code from https://github.com/uNmAnNeR/imaskjs/blob/master/packages/angular-imask/src/default-imask-factory.ts and put it in our own project.
Registered the provider in our module:
```
{ provide: IMaskFactory, useClass: DefaultImaskFactory },
```

**Comment by guaycuru** [comment]
Reverting to v6.1.0 fixed this for me

**Comment by pumano** [comment]
@uNmAnNeR have you plans to fix that error in unit testing or provide possibility to import default imask factory (for example from "angular-imask/testing" entry point?

**Comment by uNmAnNeR** [comment]
@pumano hey! I personally do not use Jest so i am probably a bit out of context.
Anyway I've checked links from comments above but have not found any solution. So if you have one then let me know.
Also you can check https://github.com/uNmAnNeR/imaskjs/issues/407
and yes i can export default factory but it does not look to me as a fix.

**Comment by uNmAnNeR** [comment]
feel free to reopen if you find proper solution or even better create PR

**Comment by kremerd** [comment]
For us it helped to switch from

```ts
import IMask from 'imask';
// ...
const inputMask = IMask(inputElement, { ...config })
```

to

```ts
import { InputMask } from 'imask';
// ...
const inputMask = new InputMask(inputElement, { ...config })
```

**Comment by jscheinhorn** [comment]
I faced the same TypeError using React.

Updating the jest mock solved the issue:

`jest.mock('imask/esm/imask', () =>
  jest.fn(() => ({
    on: () => jest.fn(),
    off: () => jest.fn(),
    updateOptions: () => jest.fn(),
    destroy: () => jest.fn(),
    value: () => jest.fn(),
    unmaskedValue: () => jest.fn(),
    typedValue: () => jest.fn(),
  })),
)`

Include whatever methods you're using.

**Comment by pumano** [comment]
Looks like I can mock imask using angular way:


Mocked service:
```
@Injectable()
export class MockIMaskFactory implements IMaskFactory {
  create(el: any, opts: any): any {
    return new MockedInputMask();
  }
}

export class MockedInputMask {
  on(ev: string, handler: any): this {
    return this;
  }
  off(ev: string, handler?: any): this {
    return this;
  }
  updateOptions() {
    return jest.fn();
  }
  destroy() {
    return jest.fn();
  }
  value() {
    return jest.fn();
  }
  unmaskedValue() {
    return jest.fn();
  }
  typedValue() {
    return jest.fn();
  }
}
```

usage:
```
beforeEach(async () => {
  await TestBed.configureTestingModule({
    imports: [ReactiveFormsModule, IMaskModule],
    declarations: [DatePickerComponent],
    providers: [{ provide: IMASK_FACTORY, useClass: MockIMaskFactory }],
  }).compileComponents();
});
```

**Comment by seanlawrenz** [comment]
This issue has me blocked from upgrading and ultimately holding off on Angular 16. 

The above solutions by mocking imask work within a repro that is using imask, but that repo is distributed as a UI library. 

The consuming applications are throwing this error on testing and there seems to be no way to calm it down. Why is this behavior happening in imask but no other default exported 3rd party applications?

**Comment by sdielmann** [comment]
In case someone stumbles upon this problem again, this is what solved it for me:

```typescript
// my.component.spec.ts
import { IMASK_FACTORY } from 'angular-imask';
import { AnyMaskedOptions, InputMask } from 'imask';

class IMaskFactory {
  create(el: HTMLInputElement, opts: any): InputMask<AnyMaskedOptions> {
    return new InputMask(el, opts);
  }
}

// ...

describe('MyComponentThatUsesAngularIMask', () => {
  beforeEach(async () => {
      const ui = await render(MyComponentThatUsesAngularIMask, {
      // Overwrite the default IMask factory used by the IMask Angular directive
      providers: [{ provide: IMASK_FACTORY, useClass: IMaskFactory }],
    });
  });

  // ...
})
```

The important change is that the mask constructor is imported as `InputMask` class. This also works in commonjs scenarios like my Jest test.

I used this solution on Angular 15.2.10 and `angular-imask` on 6.6.3.

> Note: I am using [Testing Library for Angular](https://testing-library.com/docs/angular-testing-library/intro/), but it should work the same in standard Angular tests using the TestBed.
