### ISSUE TITLE
Using Mask without UI doesn't properly account for optional characters in pattern mask

### ISSUE THREAD

**Issue by Chnoch** [uNmAnNeR/imaskjs#65]
I'm trying to format a value without using a HTML Input field. I have some optional characters in the pattern (see code example below). 

```
export const format = (value: string) => {
    const maskOptions = {
        mask: '00-0[00000]-0',
    };
    const masked = IMask.createMask(maskOptions);

    return masked.resolve(value);
};
```

This will properly format a value that fills the whole pattern:
`format('123456789') // returns 12-345678-9`. 
However when passing only part of the string it will format the optional characters instead of the mandatory ones:
`format('12345') // returns 12-345 instead of 12-34-5`

**Comment by uNmAnNeR** [comment]
@Chnoch It is not a bug, mask is greedy by nature. Otherwise behavior will be undefined, because mask could be very complex and there is no common way to predict character distribution.

**Comment by Chnoch** [comment]
Ok makes sense. In that case it's probably easier to just format it manually and not rely on imask. Thanks anyway!

**Comment by uNmAnNeR** [comment]
@Chnoch i think it's possible to do what you want with dynamic mask:
```js
new IMask(document.getElementById('input'), {
  mask: [],
  dispatch: function (appended, dynamicMasked) {
    var val = (dynamicMasked.value + appended).replace(/\D/g,'');

    return IMask.createMask({
      mask: '00-0[' + '0'.repeat(Math.min(5, Math.max(0, val.length - 4))) + ']-0',
    });
  }
});
```
Looks strange, but can help.
