### ISSUE TITLE
I am using angular-imask: 6.0.5 with angular 13

### ISSUE THREAD

**Issue by uNmAnNeR** [uNmAnNeR/imaskjs#650]
I am using angular-imask: 6.0.5 with angular 13
There is date input which changes when user enters value using imask, it used to work before with angular 9 version, after upgrading to angular 13, i am getting the below error when user edits/enters value imask input field

![imask_error](https://user-images.githubusercontent.com/56347569/160740608-e77eb677-604b-4d36-81e1-44289a69708b.png)

Not sure what is causing this issue, any suggestion would be helpful.

_Originally posted by @bnuel in https://github.com/uNmAnNeR/imaskjs/issues/507#issuecomment-1082563665_

**Comment by bnuel** [comment]
Due to security reason i cant provide sandbox link, it is ok if i post video about the issue

**Comment by uNmAnNeR** [comment]
probably is already fixed and will be released in the next version
