### ISSUE TITLE
Angular IMask pipe rounds off the value after the decimal point if a string/number with 15 digits decimal part is typed

### ISSUE THREAD

**Issue by aishwaryasharma14** [uNmAnNeR/imaskjs#653]
**Describe the bug**
Angular IMask pipe rounds off the value after the decimal point if a number with 15 digits decimal part is typed

**To Reproduce**
Use the following code to get the unmasked value of input type text field and enter a number like 124354656778655.8989, it rounds off the fractional part and outputs 124354656778655.9

```
public getUnmaskedValue(value: string): string {
    const radix = '.';
    return IMask.pipe(
      value?.toString() || '',
      {
        mask: Number,
        thousandsSeparator: ',',
        signed: true,
        radix: radix,
        scale: 5
      },
      IMask.PIPE_TYPE.MASKED,
      IMask.PIPE_TYPE.TYPED,
    );
}
```

**Expected behavior**
The fractional part after the decimal point should not round off and should show the exact entered value.

**Environment:**
 - OS: Windows
 - Browser: Chrome
 - Version: 100.0.4896.60
 - IMask:  "angular-imask": "6.4.2"
 - Framework/plugin version: "angular-imask": "6.4.2"

**Additional context**

**Comment by aishwaryasharma14** [comment]
@uNmAnNeR Is there a workaround for this?

**Comment by uNmAnNeR** [comment]
same as https://github.com/uNmAnNeR/imaskjs/issues/699
