### ISSUE TITLE
Is there a way to have IMaskMixin accept custom prop types in TypeScript?

### ISSUE THREAD

**Issue by Asghwor** [uNmAnNeR/imaskjs#654]
I'm trying to create a masked component around Material UI's TextField, using IMaskMixin, like so:

```tsx
import { TextField } from "@mui/material";
import { IMaskMixin } from "react-imask";

export const MaskedTextField = IMaskMixin((props) => (
  <TextField {...props} />
))
```

```ts
<MaskedTextField mask="aaa" helperText="Error!" />
```

However, I get type errors in the component passed to IMaskMixin because there seems to be no way to get its props to include the type of the internal component.

![image](https://user-images.githubusercontent.com/30949004/161860047-f9fcd865-0eff-4c8d-9694-1a441322eb76.png)

I also get type errors when trying to pass props to the resulting component that belong to the internal component, even though it passes it properly when TypeScript is disabled using `@ts-ignore`:

![image](https://user-images.githubusercontent.com/30949004/161860094-ae65f902-e0a0-42bd-99a0-5d84c511211a.png)

Is there a way to have IMaskMixin and its resulting component accept generic types for props in addition to its defaults?

**Comment by bradbyte** [comment]
@Asghwor I have the exact same issue.. here's my temporary work around... 

```tsx
import { AnyMaskedOptions, MaskElement } from "imask";
import { ComponentType,} from "react";
import { IMaskMixin, IMask } from "react-imask";

// these are your MUI props or whatever custom component props you want.
type InputProps = {};

// these seem to be the defaults, you could extend as needed
type IMaskProps = IMaskInputProps<
  AnyMaskedOptions,
  false,
  string,
  MaskElement | HTMLTextAreaElement | HTMLInputElement
>;

export const MaskedInput: ComponentType<IMaskProps & InputProps> = IMaskMixin(({ inputRef, ...props }) => (
  <Input ref={inputRef} {...props} />
));
```

**Comment by Asghwor** [comment]
@bradbyte I also managed to create a workaround using nested components:

```tsx
import { TextField, TextFieldProps } from "@mui/material";
import { ComponentProps } from "react";
import { IMaskMixin } from "react-imask";

const InternalMaskTextField = IMaskMixin((props) => (
  <TextField {...props as any}/>
))

type MaskProps = ComponentProps<typeof InternalMaskTextField>

export const MaskTextField = (props: TextFieldProps & MaskProps) => {
  return <InternalMaskTextField {...props} />
}
```

I did try your version, but I ended up getting a linting error on the `ref` prop.

It would be nice to have something less hacky and not having to use `any`, though.

**Comment by RyKilleen** [comment]
This is a pretty painful setup, and likely pretty common for anyone trying to integrate with `react-hook-form` `useController`.

I'd love to not have to mangle types while abstracting a `MaskedInput` component

**Comment by hakankaan** [comment]
> @bradbyte I also managed to create a workaround using nested components:
> 
> ```tsx
> import { TextField, TextFieldProps } from "@mui/material";
> import { ComponentProps } from "react";
> import { IMaskMixin } from "react-imask";
> 
> const InternalMaskTextField = IMaskMixin((props) => (
>   <TextField {...props as any}/>
> ))
> 
> type MaskProps = ComponentProps<typeof InternalMaskTextField>
> 
> export const MaskTextField = (props: TextFieldProps & MaskProps) => {
>   return <InternalMaskTextField {...props} />
> }
> ```
> 
> I did try your version, but I ended up getting a linting error on the `ref` prop.
> 
> It would be nice to have something less hacky and not having to use `any`, though.

I get the error in the below. And react-hook-form does not work with this item. Do you have any suggestions?

```
react_devtools_backend.js:4026 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `EditHotel`.
    at MaskTextField
```

This is how i used it:
```
```

**Comment by EduardoLopes** [comment]
After a lot of tests, i tried using hooks and i end up with this working code:

PS: `Input` here is a styled input using [stitches](https://stitches.dev/) 

```js
export type MaskedInputProps = {
  maskOptions: IMask.AnyMaskedOptions;
} & InputProps;

export const MaskedInput = forwardRef<HTMLInputElement, MaskedInputProps>(
  (props, ref) => {
    const { maskOptions, ...rest } = props;

    const [opts, setOpts] = useState<IMask.AnyMaskedOptions>(maskOptions);
    const { ref: inputMaskRef } = useIMask(opts);

    useEffect(() => {
      setOpts(maskOptions);
    }, [maskOptions]);
   
    // tick to make it work with react-hook-forms and useIMask
    function handleRefs(instance: HTMLInputElement | null) {
      if (ref) {
        if (typeof ref === "function") {
          ref(instance);
        } else {
          ref.current = instance;
        }
      }

      if (instance) {
        inputMaskRef.current = instance;
      }
    }

    return <Input ref={handleRefs} {...rest} />;
  }
);

MaskedInput.displayName = "MaskedInput";
```

**Comment by RyKilleen** [comment]
Here was my approach without hooks, though I very much like your approach:

```tsx
import { ComponentProps, forwardRef } from 'react'
import { FieldValues, UseControllerProps } from 'react-hook-form'
import { IMaskInput } from 'react-imask'

import { styled } from '../stitches-config'

const StyledMaskedInput = styled(IMaskInput, { /** your styles here */})

export type MaskedInputProps = {
  mask: ComponentProps<typeof IMaskInput>['mask'] 
  unmask?: 'typed' | boolean
  placeholder?: string
} & UseControllerProps<FieldValues, any> &
  typeof StyledMaskedInput

const MaskedInput = forwardRef<
  HTMLInputElement,
  typeof StyledMaskedInput
>((props, ref) => {
  // @ts-ignore
  return <StyledMaskedInput ref={ref} {...props} />
})


export default MaskedInput
```

**Comment by uNmAnNeR** [comment]
you can do now
```ts
const MyInput = IMaskMixin<
  IMask.AnyMaskedOptions, // Mask options
  false, // Unmask?
  string, // value type
  HTMLInputElement, // wrapped element type
  { placeholder: string }, // here is your custom props
>(({ placeholder }) => (
  <input placeholder={placeholder} />
));
```

i have an idea to rearrange parameters of the template in v7.0 to do it like:
1. element type
2. mask type
3. additional props
4. Unmask?
5. Value type

**Comment by LuizHAP** [comment]
> After a lot of tests, i tried using hooks and i end up with this working code:
> 
> PS: `Input` here is a styled input using [stitches](https://stitches.dev/)
> 
> ```js
> export type MaskedInputProps = {
>   maskOptions: IMask.AnyMaskedOptions;
> } & InputProps;
> 
> export const MaskedInput = forwardRef<HTMLInputElement, MaskedInputProps>(
>   (props, ref) => {
>     const { maskOptions, ...rest } = props;
> 
>     const [opts, setOpts] = useState<IMask.AnyMaskedOptions>(maskOptions);
>     const { ref: inputMaskRef } = useIMask(opts);
> 
>     useEffect(() => {
>       setOpts(maskOptions);
>     }, [maskOptions]);
>    
>     // tick to make it work with react-hook-forms and useIMask
>     function handleRefs(instance: HTMLInputElement | null) {
>       if (ref) {
>         if (typeof ref === "function") {
>           ref(instance);
>         } else {
>           ref.current = instance;
>         }
>       }
> 
>       if (instance) {
>         inputMaskRef.current = instance;
>       }
>     }
> 
>     return <Input ref={handleRefs} {...rest} />;
>   }
> );
> 
> MaskedInput.displayName = "MaskedInput";
> ```

I founded a fixed on typescript in your solution with casting a mutable ref on inputMaskRef

```
import IMask from 'imask'
import {
  ComponentProps,
  forwardRef,
  MutableRefObject,
  useEffect,
  useState,
} from 'react'
import { useIMask } from 'react-imask'
import { Input } from '../Input'

export type MaskedInputProps = {
  maskOptions: IMask.AnyMaskedOptions
} & ComponentProps<typeof Input>

export const MaskedInput = forwardRef<HTMLInputElement, MaskedInputProps>(
  (props, ref) => {
    const { maskOptions, ...rest } = props

    const [opts, setOpts] = useState<IMask.AnyMaskedOptions>(maskOptions)
    const { ref: IMaskInput } = useIMask(opts)
    const inputMaskRef = IMaskInput as MutableRefObject<HTMLInputElement>

    useEffect(() => {
      setOpts(maskOptions)
    }, [maskOptions])

    function handleRefs(instance: HTMLInputElement | null) {
      if (ref) {
        if (typeof ref === 'function') {
          ref(instance)
        } else {
          ref.current = instance
        }
      }

      if (instance) {
        inputMaskRef.current = instance
      }
    }

    return <Input ref={handleRefs} {...rest} />
  },
)
```

**Comment by LuizHAP** [comment]
I have a question, when I used this implementation above when I paste or use a browser history value on the field, the input doesn't recognize the value, only leaving the input. Why this happened @uNmAnNeR ?

**Comment by Sunset-Kim** [comment]
I solve ts error below code.

```ts
export const MaskNumberField: ComponentType<
  IMaskInputProps<HTMLInputElement> & NumberInputProps
> = IMaskMixin(({ inputRef, ...props }) => {
  return <NumberInput ref={inputRef} {...props} />
})
```

**Comment by hertles** [comment]
Here is the simplest way to create IMask wrapper for mui `TextField` without any TS error, type assertments, etc.

```tsx
import { IMaskInputProps, IMaskMixin } from 'react-imask';
import {
  ComponentType,
  ForwardRefExoticComponent,
  PropsWithoutRef,
  RefAttributes,
} from 'react';
import { TextField, TextFieldProps } from '@mui/material';

type MaskedInputProps = IMaskInputProps<HTMLInputElement> &
  Omit<TextFieldProps, 'size'> & {
    inputSize?: TextFieldProps['size'];
  };

const MaskedInput: ForwardRefExoticComponent<
  PropsWithoutRef<MaskedInputProps> &
    RefAttributes<ComponentType<MaskedInputProps>>
> = IMaskMixin(({ ref, inputSize, ...props }) => (
  <TextField {...props} size={inputSize} />
));
```

libraries versions:

- "react-imask": "7.6.1",
- "@mui/material": "^6.1.6",

Hope this helps someone!
