### ISSUE TITLE
[angular] Reset form with masked input

### ISSUE THREAD

**Issue by bossqone** [uNmAnNeR/imaskjs#66]
Hello,
we are using masked inputs within template-driven form for (datatable) filters with reset functionality.
Problem is when user click's on reset button (`<button type="reset">`) - input value (or more likely mask, as it should be empty) disappears.

Here is example:
https://stackblitz.com/edit/angular-xpyohw?file=src%2Fapp%2Fapp.component.html

Thanks,
Lukas

**Comment by bossqone** [comment]
I've tested plain JS implementation with same result - https://stackblitz.com/edit/js-8pkycd?file=index.js

**Comment by uNmAnNeR** [comment]
@bossqone Hello!
I don't see any problems with mask. Reset button clears all inputs inside form and does not fires any events on inputs. So probably there is no way for mask to detect this changes.
Therefore if you want to update values on reset form, subscribe for `reset` form event and do custom logic there. But better _reactive_ way is not to reset view, but reset model and view will be updated respectively.
