### ISSUE TITLE
Date and Number masks work incorrectly when using react-imask

### ISSUE THREAD

**Issue by Seasle** [uNmAnNeR/imaskjs#664]
**Describe the bug**
When using `react-imask@6.4.2` it was found that masks for dates and numbers do not work correctly. Previously used Vue and plugin `vue-imask@6.4.2` in which such problems were not noticed.

**To Reproduce**
Sandbox: https://codesandbox.io/s/react-imask-issue-demo-xhn6gx

Steps to reproduce:

- Problem 1 - Date mask
  1. Fill in the "Date mask" field with a date, for example `12/22/2023`;
  2. Press the Backspace key;
  3. Value is `DD/MM/YYYY`.
- Problem 2 - Number mask
  1. Fill in the "Number mask" field with a number, for example `100`;
  2. Delete entered value;
  3. Value is `0`.

Also, if you delete a character from anywhere, the value of the field will be broken.

**Expected behavior**

- Problem 1 - Date mask
  1. Fill in the "Date mask" field with a date, for example `12/22/2023`;
  2. Press the Backspace key;
  3. Value is `12/22/202Y`.
- Problem 2 - Number mask
  1. Fill in the "Number mask" field with a number, for example `100`;
  2. Delete entered value;
  3. Value is `''` (empty field).

**Environment:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 100.0.4896.127
 - IMask version: 6.4.2
 - React: 17.0.2

**Additional context**
If you downgrade the version to 6.2.2 - everything works.

**Comment by raschettilucia** [comment]
I also have this exact same issue

**Comment by kirillkychkin** [comment]
Detected problem with vue-imask 6.4.2

**Comment by nzacca** [comment]
Related issue to problem 2 described here: https://github.com/uNmAnNeR/imaskjs/issues/718

#718 pertains to resetting the control in the Angular framework specifically but I think the underlying issue is the same/related.

**Comment by uNmAnNeR** [comment]
fixed in https://github.com/uNmAnNeR/imaskjs/issues/613
