### ISSUE TITLE
Conflict between Dojo and jQuery

### ISSUE THREAD

**Issue by Bitcosoftware** [uNmAnNeR/imaskjs#665]
**Describe the bug**
A clear and concise description of what the bug is. Is it related to core functionality or plugin to some framework.

I am not sure exactly why, I am just not that smart.  But my application uses jQuery and I use the ESRI Javascript component for GIS Mapping.  I found that when I setup my call to ESRI Javascript using this:

    `<script src="https://js.arcgis.com/4.21/" asp-append-version="true"></script>`

before I use IMask, IMask does not get registered and can't be found on the DOM.  If I put the IMask declaration for the javascript reference before the ESRI it will work just fine.  Took me about 6 hours to figure this out trying to follow the code.

**To Reproduce**
Steps and link to sandbox. You can use [jsfiddle](https://jsfiddle.net/), [StackBlitz](https://stackblitz.com/), [CodePen](https://codepen.io/), [CodeSandbox](https://codesandbox.io/) and any other.

I am using Blazor and I am developing my own blazor components.  I created the MaskInput component using IMask and my testing worked fine.  When I put my MaskInput component into my main project, it would work and would crash telling me that IMask didn't exist.  After testing, I found that if I put the following script tag before I put in my IMask script, it will not work.  If I reverse them and put IMask first and then the ESRI script second, it works.  I used the following:

    `<script src="https://js.arcgis.com/4.21/" asp-append-version="true"></script>`

**Expected behavior**

I expected IMask to work.

**Environment:**
 - OS: [e.g. iOS] - Windows 11
 - Browser [e.g. chrome, safari] - Chrome
 - Version [e.g. 22] - Version  100.0.4896.127
 - IMask version  - 5x
 - Framework/plugin version if used - None

**Additional context**

**Comment by uNmAnNeR** [comment]
feel free to reopen once have an example to reproduce
