### ISSUE TITLE
The date example does not work if you change pattern: you may not insert last character

### ISSUE THREAD

**Issue by giacomok** [uNmAnNeR/imaskjs#675]
**Describe the bug**
If you use date example from the website and change pattern from `'Y-`m-`d'` to `'d-`m-`Y'` you may not insert last character.

**To Reproduce**
Just copy the code from here https://imask.js.org/guide.html#masked-date and change pattern.

**Expected behavior**
Insert the date 01-01-2020

**Environment:**
No plugin used. I get imask from CDN.

**Comment by andreymaznyak** [comment]
I have same problem

**Comment by Ansalibrahim** [comment]
Same for me..

**Comment by Zykhatslover** [comment]
It looks like the problem comes from the separator.. When you use `.`, it works, whenever you use another seperator (`/`, `-`, etc.) you're not able to input the last character...

**Comment by bradrisse** [comment]
```
format={(date: Date) => {
    var day: number | string = date.getDate();
    var month: number | string = date.getMonth() + 1;
    var year: number = date.getFullYear();

    if (day < 10) day = "0" + day;
    if (month < 10) month = "0" + month;

    return [day, month, year].join("-");
  }}
```

```
  parse={(str) => {
    console.log("parse: str ", str);
    var yearMonthDay: any = str.split("-");
    console.log("yearMonthDay ", yearMonthDay);
    return new Date(yearMonthDay[2], yearMonthDay[1] - 1, yearMonthDay[0]);
  }}
```

This issue requires both the format and parse functions. 

1. You need to return format in the day-month-year `[day, month, year].join("-");`
2. In the parse function you need to swap the year and day in the new  Date `new Date(yearMonthDay[2], yearMonthDay[1] - 1, yearMonthDay[0])`

**Comment by Ricky-ClarkIII** [comment]
@bradrisse That worked perfectly. I missed this [note](https://imask.js.org/guide.html#masked-date:~:text=if%20you%20set,options.) the documentation regarding parse and format being required if you provide a pattern. Thank you 😊
