### ISSUE TITLE
Min and Max does not work for Vue component

### ISSUE THREAD

**Issue by veer3383** [uNmAnNeR/imaskjs#68]
I wanted to Make a percentage field  using number mask by  allowing numbers in the range of 1 to 100,
I saw it working in your demo  [here](https://unmanner.github.io/imaskjs/guide.html#number)

I have tried using
`<ImaskInput v-model="props.item.value" :mask="Number" :radix="radix" :mapToRadix="mapRadix" min ="1" max="100"  />`

but it does not restrict the input, if i type 1000, it accepts the entire value.

i checked the source,
number.js (imask package) has the following parameters
```
  @param {number} opts.min
  @param {number} opts.max
```
but i guess this is missing from imask.component.js (Vue-imask package)

**Comment by uNmAnNeR** [comment]
@veer3383 try using vue props, not html props

**Comment by veer3383** [comment]
In [this]( https://github.com/uNmAnNeR/imaskjs/blob/master/packages/vue-imask/src/imask.component.js file ) , **props**  ( for number ) does not have min and max number mask property.
Actual [number.js](https://github.com/uNmAnNeR/imaskjs/blob/master/packages/imask/src/masked/number.js ) of imask package  has min and max
 ```
// number
    radix: String,
    thousandsSeparator: String,
    mapToRadix: Array,
    scale: Number,
    signed: Boolean,
    normalizeZeros: Boolean,
    padFractionalZeros: Boolean,
```

in my node modules  vue-imask.js i tried adding min and max props, and it just worked.
```
      // number
      radix: String,
      thousandsSeparator: String,
      mapToRadix: Array,
      scale: Number,
      signed: Boolean,
      normalizeZeros: Boolean,
      padFractionalZeros: Boolean,
      min:Number,
      max:Number,
```

**Comment by uNmAnNeR** [comment]
@veer3383  ok, thanks. I will fix it.

**Comment by veer3383** [comment]
can i fork and fix this and send a pull request? will you merge it? It is one of the important feature i need.

**Comment by uNmAnNeR** [comment]
@veer3383 yes, i will and will update only Vue-plugin

**Comment by veer3383** [comment]
@uNmAnNeR  done.

**Comment by uNmAnNeR** [comment]
@veer3383 [check it out](https://www.npmjs.com/package/vue-imask)

**Comment by veer3383** [comment]
@uNmAnNeR  Cool..  thanks. i was waiting for it to get published.
