### ISSUE TITLE
Is there "rejected" kind of event?

### ISSUE THREAD

**Issue by uhfath** [uNmAnNeR/imaskjs#681]
**What problem you are trying to solve?**
When a user types something that is not accepted by the mask it would be a nice UX to inform that it's an invalid input (with some hint under control).

**Describe the solution you'd like**
Some sort of a "rejected" event which is fired along with a attempted key when it's not accepted as a valid input.

**Comment by uNmAnNeR** [comment]
mask is not only about typing in input. if you want handle such cases - subscribe on `input` and check if it was changed or not. Could not be "rejected" event by design of imask.
