### ISSUE TITLE
Bug in react-imask README file

### ISSUE THREAD

**Issue by Mikilll94** [uNmAnNeR/imaskjs#684]
**Describe the bug**

There is a bug in imask-react example.

![Screenshot 2022-06-10 at 13 05 55](https://user-images.githubusercontent.com/17653648/173052138-b3b1aa04-109f-4f73-9e27-3b4aff139f08.png)
https://github.com/uNmAnNeR/imaskjs/tree/master/packages/react-imask

How is this line supposed to work?
```js
  inputRef={el => this.input = el}
```

There is no `this` in functional components in React.

**To Reproduce**
Not applicable. This is a bug in docs.

**Expected behavior**
Example should present working code.

**Environment:**
Not applicable.

**Comment by aibrahim3546** [comment]
@Mikilll94 For anyone that are confused. The `inputRef` doesn't accept the `useRef` variable as props (idk why). It is a function that contain the input ref as parameter.

Here is the working code:
```jsx
const inputRef = useRef(null)

...
<IMaskInput
  inputRef={el => {
    inputRef.current = el
  }}
/>
...
```

**Comment by uNmAnNeR** [comment]
fixed
