### ISSUE TITLE
* pattern not working after a fixed caracter with a pattern mask

### ISSUE THREAD

**Issue by julienNlT** [uNmAnNeR/imaskjs#688]
**Describe the bug**
The problem occurs when trying to type one of the fixed caracter after them.
For exemple , for this patterm mask "BUG***", i am not able to type 'B', 'U', or 'G' for the first * caracter.

**To Reproduce**
https://codesandbox.io/s/musing-rhodes-nqpq0d?file=/src/InputMask.tsx:0-39

**Expected behavior**
Expected to be able to type fixed caracter after them.

**Environment:**
 - OS: macOS
 - Browser chrome
 - Version 102
 - IMask version 6.4.2
 - Framework/plugin version if used

**Additional context**
I am using the mixin method with react-imask

Thanks for any help

**Comment by uNmAnNeR** [comment]
not a bug actually.
what you do is:
input -> raw value -> convert to unmasked value -> set unmasked value back to input as raw value.
the last step is wrong. if you need unmasked value you have to use `unmask={true}`
