### ISSUE TITLE
`Value` is in undefined when using `IMaskMixin`

### ISSUE THREAD

**Issue by majidsajadi** [uNmAnNeR/imaskjs#689]
**Describe the bug**
`IMaskMixin` would remove `value` from `props.

**To Reproduce**
```jsx
import { IMaskMixin } from "react-imask";

import { ComponentProps } from "react";
import { Input, InputProps } from "../input";

const InternalMaskTextField = IMaskMixin((t) => {
  const { inputRef,value, ...props  } = t

  console.log(value) // undefined

  // rest
});

type MaskProps = ComponentProps<typeof InternalMaskTextField>;

export const MaskInput = (props: InputProps & MaskProps) => {
  console.log(props.value); // 'string'
  return <InternalMaskTextField {...props}  />;
};

```

**Expected behavior**
Not removing any input default props such as `value`

**Additional context**
i guess the problem is because we are calling `_extractNonMaskProps` in the render. why not call `_extractMaskOptionsFromProps` instead?

**Comment by uNmAnNeR** [comment]
fixed in 1255d82ed54cb4c96b50b08050b0004830f531ce
