### ISSUE TITLE
Mask with date

### ISSUE THREAD

**Issue by kriss145** [uNmAnNeR/imaskjs#69]
Hi,

I have the problem with the plugin.
I can't enter the last number in the input field.
It's stopped, ex: 2000-02-1[here is the problem to enter a number]

Could u help me?

My code:
`
const dateMask = new IMask(document.querySelector('.js-mask-birthday'), { // eslint-disable-line
      mask: Date,
      pattern: 'Y{-}`m{-}`d',
      lazy: false
})
`

**Comment by uNmAnNeR** [comment]
Hello!
For custom date pattern you have to provide `parse` and `format` props. For details please see example in a guide.

**Comment by Lepshiz** [comment]
Приветствую!

Сразу благодарю за хорошую библиотеку, но вчера столкнулся с очень большой проблемой. В Date маске не нашел возможности добавить в конец паттерна фиксированный символ, пример:
`Y{年}`m{月}`d{日}`
_(это китайская маска для ввода даты)_

скрипт не дает ввести последний символ (в группе DD), на сколько смог разобраться, после заполнения динамической части все следующие фиксированные части отбрасываются и передаются в `doValidate() -> isDateExist(this.value)` для проверки с результатом работы `this.format(this.parse(str))`, которые, в моем случае, возвращают корректно заполненную маску с фиксированным символом в конце. В итоге doValidate возвращает false и заполнить маску не удается. 

Это умышленное ограничение или баг? Есть ли какой-нибудь обходной путь в моем случае? 

Извиняюсь за русский, Спасибо!

**Comment by uNmAnNeR** [comment]
@Lepshiz хорошо что не на китайском :)
Фиксированные символы добавляются при вводе автоматически, и, поскольку маска для дат - это частный случай паттерн-маски, то это поведение работает и для нее. Поэтому в валидатор попадает значение с фикс. символами, что судя по всему корректно.
Насколько я понял, нужен нестандартный формат для даты. Это значит, что нужно переопределять `format` и `parse` для конкретного случая и внутри уже что-то вырезать или добавлять, учитывая фикс. символы.

**Comment by Lepshiz** [comment]
@uNmAnNeR спасибо за ответ.

Да, я так и сделал, переопределил parse и format, тут пример проблемы:
https://codesandbox.io/s/y364vqo31x

Добавил логи в parse и format, они срабатываю когда пытаешься заполнить последний символ, но в логах видно, что format получает dateObj и возвращает корректную строку 2111年11月11日 (для даты 2111.11.11), а вот в parse уже аргумент выглядит так: 2111年11月11 , хотя результат работы parse тоже корректный (отсутствие фикс. символа не мешает распарсить строку)

Проблема в том, что сам объект MaskedDate, на момент выполнения doValidate, имеет значение this.value === '2111年11月11', и сравнивает его с результатом вызова this.format(this.parse(str)), которые возвращаю корректную строку '2111年11月11日', в итоге doValidate возвращает false и последний символ не пишется. Мне кажется тут явно где-то баг.

Можно упростить пример и добавить в паттерн date маски фикс. символ в конце и такую маску заполнить не получится.

**Comment by uNmAnNeR** [comment]
Да, забавная ситуация получается. Если формат возвращает строку с фикс. символом, то не проходит случай без него. И наоборот.

Думаю в этой ситуации проще всего наследоваться от `MaskedDate` и переопределить `isDateExist`.
В 4.0.0 я подумаю на тем чтобы можно было перееопределять логику `this.format(this.parse(str)) === str`, но в любом случае лучшего способа для общих случаев я не вижу.

**Comment by Lepshiz** [comment]
Ясно, я глубоко не залазил в исходный код, но, как я понимаю, на фикс версии надеяться не стоит?

**Comment by uNmAnNeR** [comment]
да, не стоит.
