### ISSUE TITLE
react-imask: Invalid mask value with useIMask hook, eager mode and fixed number characters in a mask 

### ISSUE THREAD

**Issue by rade363** [uNmAnNeR/imaskjs#690]
**Describe the bug**
The issue occurs under under the following circumstances:
-  the `useIMask()` hook is used,
- the eager mode is turned on,
- the fixed characters part in a mask contains a digit (e.g. `+{1} 000 000-00-00`).

This will result in the following input value that cannot be changed: `+1 111 111-11-11`
This way the mask `+{13} 000 000-00-00` will result in `+13 131 313-13-13`

**To Reproduce**
[CodeSandbox](https://codesandbox.io/s/react-imask-invalid-value-3dld72?file=/src/App.js)

**Expected behavior**
Input must not be filled repeatedly with the number from the fixed characters mask part.
Input must be editable.

**Environment:**
 - OS: macOS 12.4 
 - Browser: Chrome
 - Version: 102 (arm64)
 - IMask version: 6.4.2
 - Framework/plugin version if used: React 17.0.2 / React 18.0.0

**Additional context**
- The behavior is correct when the eager mode is turned off, example: [CodeSandbox](https://codesandbox.io/s/react-imask-eager-mode-disabled-8gkddj?file=/src/App.js)
- The behavior is correct when the fixed mask part does not contain digits, example: [CodeSandbox](https://codesandbox.io/s/react-imask-no-digits-in-fixed-part-jw59ny?file=/src/App.js)
- The behavior is correct when controlled `<ImaskInput />` component is used, example: [CodeSandbox](https://codesandbox.io/s/react-imask-native-input-solution-myg3hx?file=/src/App.js)
- The behavior is correct when `IMaskMixin()` is used, example: [CodeSandbox](https://codesandbox.io/s/react-imask-hoc-solution-yu03g6?file=/src/App.js)
- The behavior is correct when the [Pattern Mask demo](https://imask.js.org/guide.html#masked-pattern) is used with the same config:

<img width="797" alt="pattern-mask-demo" src="https://user-images.githubusercontent.com/6594020/174770996-18e561ca-5f3d-470a-9acd-051f653f1d20.png">

**Comment by uNmAnNeR** [comment]
@rade363 thanks a lot for detailed description and example. nice catch indeed
