### ISSUE TITLE
wrong converting money

### ISSUE THREAD

**Issue by durancanyilmaz** [uNmAnNeR/imaskjs#695]
First state: 5300 coming fron database and imask convert 5.300,00. That nice. 
![image](https://user-images.githubusercontent.com/33418107/177619588-42f96876-c60c-4e58-8143-cec97c726df5.png)
Second state: I change some number and click anywhere (like edit button ..etc)
![image](https://user-images.githubusercontent.com/33418107/177619885-f0900eb0-a3e4-4044-8043-11318b464d6c.png)
Last state: TADA ! I have wrong money in input (also in database). It have to 5390 but imask converted 5,39. 
![image](https://user-images.githubusercontent.com/33418107/177619967-4993c1a5-388e-4193-be75-cc0550a377f4.png)
I dont get it. Help please.
```
<script src="https://unpkg.com/imask@6.4.2/dist/imask.js"></script>
 <script>
    $(document).ready(function () {
        function para(){
            return [
                { mask: '' },
                {
                    mask: 'num',
                    lazy: true,
                    blocks: {
                        num: {
                            mask: Number,
                            scale: 2,
                            thousandsSeparator: '.',
                            padFractionalZeros: true,
                            radix: ',',
                            mapToRadix: ['.'],
                        }
                    }
                }
            ];
        }
        var mask = IMask(
            document.getElementById('alis_tl'), {
                mask: para()
            }
        );
</script>
```

**Comment by uNmAnNeR** [comment]
now `mapToRadix` is working only for input
