### ISSUE TITLE
Angular IMask: mat-datepicker problem

### ISSUE THREAD

**Issue by mhagnumdw** [uNmAnNeR/imaskjs#696]
**Describe the bug**
Problem with Angular Material Components Mat-Datepicker component: https://material.angular.io/components/datepicker/overview

`ERROR Error: More than one custom value accessor matches form control with unspecified name attribute`

![image](https://user-images.githubusercontent.com/17688846/178505903-5c992093-1eff-4349-b133-0b9ab79557e6.png)

**To Reproduce**
See and open web console: https://stackblitz.com/edit/angular-wst7ra?file=src%2Fapp%2Fdatepicker-overview-example.html,src%2Fapp%2Fdatepicker-overview-example.ts

**Expected behavior**
That the component is loaded and the mask works correctly.

**Environment:**
 - OS: Fedora 35
 - Browser: Chrome v103
 - IMask version: 6.4.2 (angular-imask)
 - Framework/plugin version: Angular 14.0.0, Angular Material 14.0.4

**Comment by uNmAnNeR** [comment]
it's not a problem with imask. it's a way Angular is designed. So you have to use 2 inputs for 2 ValueAccessors
