### ISSUE TITLE
Angular IMask: end of input truncated

### ISSUE THREAD

**Issue by mhagnumdw** [uNmAnNeR/imaskjs#697]
**Describe the bug**
When using the date mask and using the `'m{/}d{/}Y'` pattern, the last digit is truncated from the input, but its value in the model is ok. See image below.

![image](https://user-images.githubusercontent.com/17688846/178508789-8090b5ea-be1c-4ebb-8627-c5ddd975d531.png)

obs: If I change mask to `'m{.}d{.}Y'` (dot instead of slash), end is not truncated in input.

**To Reproduce**
See, open web console and enter a date: https://stackblitz.com/edit/angular-wst7ra-q97kvq?file=src%2Fapp%2Fdatepicker-overview-example.html,src%2Fapp%2Fdatepicker-overview-example.ts

**Expected behavior**
That all characters appear in the input. May it not be truncated.

**Environment:**
OS: Fedora 35
Browser: Chrome v103
IMask version: 6.4.2 (angular-imask)
Framework/plugin version: Angular 14.0.0, Angular Material 14.0.4

**Comment by mgarciaebo** [comment]
I confirm this issue. It seems to happen using any custom pattern.

**Comment by exhilaratedguy** [comment]
This is also happening with React (v17.0) and is not specific to Angular.

**Comment by uNmAnNeR** [comment]
guys please read the guide first before using it. i wrote it for you
![image](https://user-images.githubusercontent.com/1927921/180984582-248b4ae1-8076-48fc-b051-02cc809c9477.jpeg)

**Comment by mhagnumdw** [comment]
@uNmAnNeR , tks!

Solution: https://stackblitz.com/edit/angular-wst7ra-k7ahjy?file=src%2Fapp%2Fdatepicker-overview-example.ts

Solution with ptBR and date-fns: https://stackblitz.com/edit/angular-wst7ra-tumqgs?file=src%2Fapp%2Fdatepicker-overview-example.ts
