### ISSUE TITLE
Min Date bug

### ISSUE THREAD

**Issue by idlinnes** [uNmAnNeR/imaskjs#70]
`mask: {
        mask: Date,
        pattern: 'Y-`m-`d',
        lazy: false,
        min: '2018-06-20',
        max: '2018-09-18',
        format: date => {
          return format(date, datePattern)
        },
        parse: str => {
          return parse(str, datePattern, new Date())
        }
      },`
min - сегодняшний день (к примеру 2018-06-20)
и когда я начинаю вводить - 2018-02-2_ то конечно же не могу ввести последнее число так как дата получается меньше минимальной
я не могу ввести год 2017.
НО почему я МОГУ ввести 02 (месяц) - ведь он уже не подходит по  min
как можно это пофиксить? 
временный фикс это добавить 
`groups: {
          m: new IMask.MaskedPattern.Group.Range(['06', '09']),
          Y: new IMask.MaskedPattern.Group.Range([2018, 2018])
        },`
но это нужно парсить параметры max и min (данные в конфигурации статичны но на самом деле там переменные)
может есть более лучшее решение?

**Comment by uNmAnNeR** [comment]
min и max - это даты, а не строки

**Comment by idlinnes** [comment]
как я и написал - это пример
в реальности min = new Date()

**Comment by idlinnes** [comment]
пример
https://codesandbox.io/s/14xnz7p8ql

**Comment by uNmAnNeR** [comment]
@idlinnes спасибо, теперь понятно. Компонент маски слишком общий. Единственная проверка, которая там есть - это когда дата целиком заполнена, проверяется корректность и интервалы. месяца захардкожены на [1, 12], дни на [1, 31]. Я даже если захочу, то вряд ли смогу добавить более сложные проверки в ближайшем будущем.
Вижу два варианта: через группы как у вас, вполне себе решение. Группы по идее должны нормально обновляться при смене параметров. Второй вариант - добавить валидатор (свойство `validate`), выковыривать месяцы/дни и делать проверки там.

**Comment by idlinnes** [comment]
Спасибо за ответ.
Решение с группами нормальное но приходится извращатся в способ
this.mask.groups.m = new IMask.MaskedPattern.Group.Range(функция которая возвращает нужный массив)
так как new IMask.MaskedPattern.Group.Range(вычисляемое свойство) - не работает. ну собственно понятно почему)

**Comment by uNmAnNeR** [comment]
@idlinnes да, validate как раз для этих целей задумывался.
Пока не закрываем задачу. Скоро в 4.0 выпилятся группы и интервалы, с датами попробую добавить еще немного магии.
