### ISSUE TITLE
Error using dynamic masks

### ISSUE THREAD

**Issue by subpx** [uNmAnNeR/imaskjs#701]
**Describe the bug**
When using dynamic masks and the dispatch option, editing the input value causes an error. 
Uncaught TypeError: Cannot read properties of undefined (reading ...)

**To Reproduce**
See [codepen demo](https://codepen.io/subpx/pen/poLPprV)
This is copied from the example on the website.
To get the error, enter a number beginning with 7 eg: 753454535. Then enter a number in the middle or delete a number.

**Expected behaviour**
No error

**Comment by subpx** [comment]
Looks like this may be fixed by #676

**Comment by subpx** [comment]
@uNmAnNeR thanks I see that this may be fixed in your recent commit. When will it be released?

**Comment by hassanasad** [comment]
@uNmAnNeR Waiting anxiously for it to be released (on npm).
