### ISSUE TITLE
Compatibility problems when upgrading to vue 2.7

### ISSUE THREAD

**Issue by vate** [uNmAnNeR/imaskjs#704]
In the process of upgrading to vue 2.7 I got these error messages on console, each one repeated and related to any component, for example:

`The setup binding property "buttonComponent" is already declared`

Looks like composition API for vue is being run twice and hence the errors

The new 2.7 version gets rid of the [@vue/composition-api ](https://github.com/vuejs/composition-api) plugin and directly imports composition API related functions from vue directly without the need of the old plugin.

So then, I remove the plugin, but get this error in the build:

```
ERROR  Failed to compile with 1 error 
This dependency was not found:
* @vue/composition-api/dist/vue-composition-api.mjs in ./node_modules/vue-demi/lib/index.mjs
```

Looks like `vue-demi` is still looking for this, that's probably why Vuejs version 2.7[ requires upgrading vue-demi to at least version 0.13.0](https://blog.vuejs.org/posts/vue-2-7-naruto.html) that doesn't depend on the old `@vue/composition-api` plugin.

![imagen](https://user-images.githubusercontent.com/1636418/181722130-3c8348cf-f537-4cf9-80f6-5f843d936ba7.png)

When I run npm list `vue-demi` I get
```
`-- vue-imask@6.4.2
  `-- vue-demi@0.12.5
```
I found that the required version by imask is 0.12.1:
https://github.com/uNmAnNeR/imaskjs/blob/a0651deddeb1a1cd630b4bbcf361be3d7cf15e84/packages/vue-imask/package.json#L28

Is there any way that upgrading `vue-demi` to 0.13.1 on the `vue-imask` plugin could solve this?

Thanks! 🙌🏻

**Comment by Sated** [comment]
@vate hi, if you use yarn as package manager, you can try add  
```
"resolutions": {
  "vue-demi": "^0.13.0"
}
````
or equivalent for npm v8.3.0+:

```
{
  "overrides": {
    "vue-demi": "^0.13.0"
  }
}
```
in your package.json file

**Comment by vate** [comment]
Just a question @uNmAnNeR, are there any plans to release a new version soon with the fix done here?

**Comment by uNmAnNeR** [comment]
@vate yes
