### ISSUE TITLE
How to set input type "number" with IMaskInput?

### ISSUE THREAD

**Issue by ArtiomPirog** [uNmAnNeR/imaskjs#707]
I have a **IMaskInput** component.
Looks like:

`<IMaskInput 
	mask="0000"
	autoFocus
	value={smsCode}
	onAccept={changeCode}
	lazy={false}
	placeholderChar={"•"}
/>`
![image](https://user-images.githubusercontent.com/109672875/182081271-84b3fe94-e67c-4c91-af32-dd05a1d5c4f3.png)

If i set **type="number"** (i need it on phones for numeric keyboard), it stops working (no mask, no data entry). 
How can I fix it? I definitely need a numeric keyboard...

**Comment by ArtiomPirog** [comment]
I forgot. 
There must be a placeholderChar - if 1 digit is entered, the placeholder is also reduced by 1 element.

![image](https://user-images.githubusercontent.com/109672875/182087309-aefcf0ba-b16c-4dff-9767-f67c4bc9ee12.png)

**Comment by vendramini** [comment]
I don't think that any others types but 'text' would work properly.

You could try adding inputMode='numeric' and a pattern='\d*'.
