### ISSUE TITLE
MaskedNumber option "signed" does not prevent negative numbers

### ISSUE THREAD

**Issue by micDropper** [uNmAnNeR/imaskjs#713]
**Describe the bug**
For `mask: Number` type masks, the `signed` option should disallow negatives when `signed=false`. This does not work [in the demo on the imask website](https://imask.js.org/guide.html#masked-number). I did note that one of my project unit tests does flip the sign when `signed=false`, but a different unit test in the same project will not flip the sign.

**To Reproduce**

1. Visit [the imask website](imask.js.org/guide.html#masked-number)
2. Activate the "Masked Number" demo
3. Be sure "Signed" is unchecked and click "Apply"
4. Input `-1`
5. Observe output is still `-1` but should be `1`

**Expected behavior**
Inputting `-1` should either not be possible or should result in `1` onBlur

**Environment:**
 - OS: windows
 - Browser: chrome 
 - Version: v103.0.5060.134
 - IMask version: v6.4.2
 - Framework/plugin version if used: N/A

**Comment by uNmAnNeR** [comment]
`signed` will be removed in the next major release
