### ISSUE TITLE
Number MaskType resetting control value to 0

### ISSUE THREAD

**Issue by nzacca** [uNmAnNeR/imaskjs#718]
**Describe the bug**
When a Number mask type is used, a value is set on the control, and the form is reset, the control value is set to `0` instead of `null`.

**To Reproduce**

* https://stackblitz.com/edit/angular-ivy-gkt1j9?file=src%2Fapp%2Fhello.component.ts

**Expected behavior**
Expect control value to be `null`. This is causing problems on forms where required validation is used on a control and the form is reset. The form appears to be empty but since the control value is 0, it passes validation.

**Environment:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Latest
 - IMask version: 6.1.0+
 - Framework/plugin version: Angular IMask 6.1.0+

**Additional context**

Problem appears to be how the `typedValue` is calculated in the Number mask: https://github.com/uNmAnNeR/imaskjs/blob/master/packages/imask/src/masked/number.js#L337

When the value is reset to `null`, `undefined`, or the `empty string`, this will be converted to 0 as the typedValue which in turn gets set to the control value.

**Comment by uNmAnNeR** [comment]
this is not a bug in my opinion but desired behaviour. `null` is not a valid `number`. it's another type. If you want to have nulls for some numbers you can subclass from MaskedNumber and implement anything you want.

**Comment by nzacca** [comment]
@uNmAnNeR I understand your position but I think the underlying issue is that the control itself has a value that does not match the input after the control is reset.

If the value is reset and the input is cleared, I would expect the control value to reflect the reset value. It is unexpected that the control value is 0.

**Comment by uNmAnNeR** [comment]
@nzacca i was thinking about this.
From my point of view behaviour that you describes depends on type of the value/model.

In the issue that you describes
> this causes required validation to pass even though nothing has been entered into the input box.

seems like you in the model you have not just number but `number | null` or `number | ''`. But that's not a type of the NumberMask which is just `number`.

So if you say that it's a number (unmask="typed") then it should not be empty nor null/undefined. Or still you can implement your own `NullableNumberMask` but it will be differ from the current solution.
Another way is to use (unmask=true) handle just raw strings. In that case view<->model conversion is done somewhere else.
But in both scenarios we keep invariants defined for the model.

> Even resetting to undefined would be acceptable.

You can pass any value there but it does not mean that it should work right? Depends on the model again.

**Comment by nzacca** [comment]
@uNmAnNeR 

Thank you for your response.

I have taken your suggestion and overridden the `typedValue` in `NumberMask` to:

```
return this.isNumeric(this.unmaskedValue) ? Number(this.unmaskedValue) : null;
```

This is working for us but I will explore your other suggestion of `unmask=true` as well. Thank you very much!
