### ISSUE TITLE
How can i enable submit button

### ISSUE THREAD

**Issue by ivan-ilinov** [uNmAnNeR/imaskjs#72]
How can i enable disabled submit button if the entered value is valid? Any callback functions?

```
var mask = new IMask(
  element,
  {
    mask: [
      {
        mask: '+{7}(000)000-00-00'
      },
      {
        mask: /^\S*@?\S*$/
      }
    ]
  }
);
```

**Comment by uNmAnNeR** [comment]
@ivan-ilinov see [guide#common](https://unmanner.github.io/imaskjs/guide.html#common)

**Comment by ivan-ilinov** [comment]
Did you mean commit parameter?
