### ISSUE TITLE
Is it possible to update Vue-Imask to work with vue.js 2.7.10?

### ISSUE THREAD

**Issue by well-prado** [uNmAnNeR/imaskjs#722]
So, since Vue.js 2.7 will be the last release for Vue 2, I was wondering if it's possible to update the Vue-Imask lib to work with this version.

Since the Composition API is now built-in, you can't have the Composition API plugin anymore. And for that reason, the imask lib is trying to find the Composition API in a folder that is not there anymore.

So I was wondering if it's possible to adjust the lib to find the Composition API in the correct folder.

Thanks!

**Comment by seahindeniz** [comment]
You might need to check #704

**Comment by uNmAnNeR** [comment]
fixed, right?
