### ISSUE TITLE
Masked class is not found for provided mask

### ISSUE THREAD

**Issue by seahindeniz** [uNmAnNeR/imaskjs#723]
**Describe the bug**
I have tried using the tree-shaking suggestions on docs however, got failed

**To Reproduce**
https://stackblitz.com/edit/typescript-zwmmgy?file=index.ts

**Expected behavior**
To make it work just like importing `import IMask from 'imask';` 

**Environment:**
 - OS: [e.g. iOS] Mac
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] 104
 - IMask version 6.4.2

**Comment by seahindeniz** [comment]
I'm not sure what can I import more
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/5789670/186470023-8d8526d4-7b0f-4c96-9e27-77b8ec7e4d0a.png">

**Comment by uNmAnNeR** [comment]
@seahindeniz works
https://stackblitz.com/edit/typescript-2dmtvt?file=index.ts
