### ISSUE TITLE
Add REMOVE and INSERT to eager options

### ISSUE THREAD

**Issue by uNmAnNeR** [uNmAnNeR/imaskjs#727]
### Discussed in https://github.com/uNmAnNeR/imaskjs/discussions/703

<div type='discussions-op-text'>

<sup>Originally posted by **mattstobbs** July 27, 2022</sup>
Hey, I'm using a simple mask of `'0000 0000'`. It works great when typing numbers but when the backspace is clicked, if there are only four numbers left, there is a trailing space. For example
```
"1234"
{Click 5}
"1234 5"
{Backspace}
"1234 "
```
Is there a way to remove the trailing space on backspace?</div>

**Comment by renerlemes** [comment]
@uNmAnNeR how to use this feature?
