### ISSUE TITLE
Vue-imask 6.4.3-alpha.0 fails esm on vite build

### ISSUE THREAD

**Issue by OliverGrimsley** [uNmAnNeR/imaskjs#738]
**Describe the bug**
Vite build - version 6.4.3-alpha.0 of Vue-imask missing ESM build component

Error:

`Error: Build failed with 7 errors:`
`node_modules/vue-imask/esm/component.js:4:7: ERROR: Could not resolve "imask/esm/imask"`
`node_modules/vue-imask/esm/component2.js:1:18: ERROR: Could not resolve "imask/esm/imask"`
`node_modules/vue-imask/esm/component3-composition.js:1:7: ERROR: Could not resolve "imask/esm/imask"`
`node_modules/vue-imask/esm/composable.js:2:18: ERROR: Could not resolve "imask/esm/imask"`
`node_modules/vue-imask/esm/directive.js:2:18: ERROR: Could not resolve "imask/esm/imask"`

**To Reproduce**
update package.json to 6.4.3-alpha.0, try to build app in Vite, fails.  v 6.4.2 builds fine

**Expected behavior**
The app to build without errors

**Environment:**
 - OS: MacOSX
 - Browser - n/a build fails
 - IMask version see notes above
 - Framework/plugin version if used - Vue, v 3.2.39, Vite 3.1.1.

**Additional context**
n/a

**Comment by uNmAnNeR** [comment]
@OliverGrimsley thanks for reporting. please check v6.4.3-alpha.1

**Comment by OliverGrimsley** [comment]
:thumbsup: Working!  Thx for a great plugin
