### ISSUE TITLE
Updating lazy option does not work with dynamic nested mask

### ISSUE THREAD

**Issue by MikeMatusz** [uNmAnNeR/imaskjs#742]
**Describe the bug**
Trying to toggle the visibility of the placeholder using the solution described on #497.  The StackBlitz link provided in the comment no longer works if upgraded to 6.4.0 or newer.

**To Reproduce**
Navigate to this [StackBlitz example](https://stackblitz.com/edit/imask-nested-mask-5p9kaz?file=index.js).  Observer both inputs show the mask only when focused.  Update the `imask` dependency to 6.4.0 and observe that the Nested mask example no long functions correctly.

**Expected behavior**
Should work as prior to version 6.4.0 in this example

**Environment:**
 - OS: MacOS
 - Browser: Chrome
 - Version 105
 - IMask version: 6.4.0

**Additional context**
From debugging, I believe it may be related to changes made to `maskEquals` in [this commit](https://github.com/uNmAnNeR/imaskjs/commit/adae5a57921eadc1dd54a8a25404b5bf4fcf899e#diff-d4f677e46a5c373ecc18c0c5bef1ae9bc3c0f8c465e4aa5bcb399d2f4c8813a6) that are now preventing the mask from being updated if the `lazy` option is the only thing that's changing.

**Comment by nghuuphuoc** [comment]
I have the same issue.

**Comment by nghuuphuoc** [comment]
The issue still happens with the latest release, v6.5.0 (https://jsfiddle.net/phuocng/kmtpuesn/)
May I know when you have the plan to fix it?

**Comment by uNmAnNeR** [comment]
@nghuuphuoc try v6.5.1-alpha.1
