### ISSUE TITLE
MutableRefObject

### ISSUE THREAD

**Issue by kodermax** [uNmAnNeR/imaskjs#743]
https://github.com/uNmAnNeR/imaskjs/blob/0b9690a6fc01164b95f3514e9df0a7a836aac1d7/packages/react-imask/src/hook.ts#L15
А почему тут перестал быть MutableRefObject
моя конструкция reassign перестала работать
```
const refAssigner = (el: any) => {
    props.inputRef(el)
    ref.current = el
  }
```

**Comment by uNmAnNeR** [comment]
конструкция не перестала работать, проверка типов перестала работать.
хз, c одной стороны внутри плагина реф не меняется, с другой стороны он возвращается наружу, где он должен был изменен в любом случае. Так что наверно он все таки должен быть изменяемым
