### ISSUE TITLE
How to set input props like "type", "autocomplete", "autofocus" & etc. ?

### ISSUE THREAD

**Issue by YegorDovydenko** [uNmAnNeR/imaskjs#748]
How can I do for example:
` <input type="tel" autocomplete="one-time-code" autofocus />`
 with **IMaskInput** ?

**Comment by vendramini** [comment]
I'm facing the same problem. Couldn't we pass html's input's props? Like:

![image](https://user-images.githubusercontent.com/510878/192398466-1a66338d-32b7-4b71-b647-61d125c0b05e.png)

I can't use any of them: `placeholder, disabled, defaultValue, className, onBlur`

**Comment by johnnysprone** [comment]
Important note: No native HTML properties for inputs (placeholder, id, name, type, value, auto-complete, among others) are accepted by the typescript in the <IMaskInput /> component, triggering the error: "Property 'xxx' does not exist on type 'IntrinsicAttributes'...". I use react v18.2.0 and react-imask v6.4.3.

**Comment by szbartnik** [comment]
@YegorDovydenko @vendramini @johnnysprone 

It has been broken in `6.4.3`. Just discovered it after upgrading the lib. Please try to downgrade to `6.4.2` which works ok. Still, I guess it wasn't desired to introduce such breaking changes in patch version right @uNmAnNeR ?

**Comment by vendramini** [comment]
Nice catch @szbartnik. You've saved my time, I was doing everything again using the hook. Thanks!

**Comment by Meligy** [comment]
Yeah. It's quite hard to tell where it broke though, maybe in `packages/react-imask/src/mixin.ts` or `packages/react-imask/src/input.ts`.
https://github.com/uNmAnNeR/imaskjs/compare/v6.4.2...v6.4.3

**Comment by hansoksendahl** [comment]
Both `autoComplete`, `inputMode` and possibly other properties disappeared from the `IMaskInput` type with the change to 6.4.3. The `inputMode` prop in particular is needed to hint to mobile clients which keyboard to use. I consider `6.4.3` to be a broken version of this library.

**Comment by abnerpsoares** [comment]
> @YegorDovydenko @vendramini @johnnysprone
> 
> It has been broken in `6.4.3`. Just discovered it after upgrading the lib. Please try to downgrade to `6.4.2` which works ok. Still, I guess it wasn't desired to introduce such breaking changes in patch version right @uNmAnNeR ?

Thank you so much! You saved me a lot of time.

**Comment by szbartnik** [comment]
@uNmAnNeR You shouldn't close issues when it's not followed by immediate NPM package release. Library's new users will have the buggy `6.4.3` installed by default which is really confusing when they don't see any related issues open. You end-up with more & more new issues created about exactly the same thing.

**Comment by Meligy** [comment]
I might have written the last comment differently since we are grateful for all the great free work you do, but yeah - I have to agree with the premise, would appreciate a release for the closed issues, this one and the sister one  as mentioned in https://github.com/uNmAnNeR/imaskjs/issues/761#issuecomment-1427313782

Thanks a lot for everything.
