### ISSUE TITLE
Custom placeholder

### ISSUE THREAD

**Issue by grishkovelli** [uNmAnNeR/imaskjs#75]
Hi. Tell me please, can I use custom placeholder instead of the underscore? I would like to see DD-MM-YYYY for my custom mask DD-MM-YYYY in an input.

```
       new IMask(elem, {
          mask: 'DD-MM-YYYY',
          lazy: false,
          customPlaceholder: 'DD-MM-YYYY',
          groups: {
            YYYY: new IMask.MaskedPattern.Group.Range([1900, 2020]),
            MM: new IMask.MaskedPattern.Group.Range([1, 12]),
            DD: new IMask.MaskedPattern.Group.Range([1, 31])
          }
        })
```

**Comment by uNmAnNeR** [comment]
@grishkovelli Hello! Currently it is not possible. Only `placeholderChar` option is available, but it applies on a whole mask.
I plan to release `v4.0.0` soon in which full-featured nested masks will be available to use in `groups`. So it will be possible to specify `placeholderChar` for each group.

**Comment by kilgarenone** [comment]
@uNmAnNeR Is custom placeholder(e.g. `YYYY/MM/DD`) possible with the Date mask `{ mask: Date }` ?

**Comment by russpitre** [comment]
This works great.  The blocks config below will produce **mm/dd/yyyy --:-- --** as my input placeholder. Great package, thanks for the hard work.

`    blocks: {
      yyyy: {
        mask: IMask.MaskedRange,
        from: 1900,
        to: 2100,
        placeholderChar: 'y',
      },
      MM: {
        mask: IMask.MaskedRange,
        from: 1,
        to: 12,
        placeholderChar: 'm',
      },
      dd: {
        mask: IMask.MaskedRange,
        from: 1,
        to: 31,
        placeholderChar: 'd',
      },
      hh: {
        mask: IMask.MaskedRange,
        from: 0,
        to: 12,
        placeholderChar: '-',
      },
      HH: {
        mask: IMask.MaskedRange,
        from: 0,
        to: 23,
        placeholderChar: '-',
      },
      mm: {
        mask: IMask.MaskedRange,
        from: 0,
        to: 59,
        placeholderChar: '-',
      },
      aa: {
        mask: IMask.MaskedEnum,
        enum: ['AM', 'PM'],
        prepare: str => str.toUpperCase(),
        placeholderChar: '-',
      },
    },
`

**Comment by pruthvi224** [comment]
When I pass 2024 for YYYY block, instead of displaying YYYY in placeholder it is displaying 2YYY. 
Is there a way to display YYYY all the time ?

blocks: {
      yyyy: {
        mask: IMask.MaskedRange,
        from: 2024,
        to: 2100,
        placeholderChar: 'y',
      },
      MM: {
        mask: IMask.MaskedRange,
        from: 1,
        to: 12,
        placeholderChar: 'm',
      },
      dd: {
        mask: IMask.MaskedRange,
        from: 1,
        to: 31,
        placeholderChar: 'd',
      }
    },
