### ISSUE TITLE
Error when trying to test the react-imask with react-test-renderer - "TypeError: Cannot read property 'isContentEditable' of null

### ISSUE THREAD

**Issue by React-JJ** [uNmAnNeR/imaskjs#750]
**Describe the bug**
Error when trying to test the react-imask with react-test-renderer - "TypeError: Cannot read property 'isContentEditable' of null"

**To Reproduce**
Create a react project. Add a test file
App.test.js
`import { IMaskInput } from 'react-imask'; 
describe('React Date Mask snapshot test',() => { it('renders correctly', () => { 
const tree = renderer .create(<IMaskInput mask={Date} />) .toJSON(); 
expect(tree).toMatchSnapshot(); }); 
})`

**Expected behavior**
The mask control should work with react-test-renderer.

**Environment:**
 - Browser chrome
 - Version 6.4.2
 - IMask 6.4.3

**Comment by uNmAnNeR** [comment]
not related to imask
https://stackoverflow.com/questions/40852131/refs-are-null-in-jest-snapshot-tests-with-react-test-renderer
https://github.com/facebook/react/issues/7740
