### ISSUE TITLE
angular-imask with lazy:false option triggers focus after resetting a control in IE11

### ISSUE THREAD

**Issue by chesminsky** [uNmAnNeR/imaskjs#76]
Hello.
Thanks for the lib !

I discovered strange bug and spent a whole day to understand whats wrong and failed.
As i mentioned in title - I use imask directive with lazy false option
I want to reset a control and then it focused, and thats unexpected.

Browser IE11.

no bug in Chrome. 
no bug with lazy: true

demo:  https://stackblitz.com/edit/angular-imask

**Comment by uNmAnNeR** [comment]
@chesminsky probably it is IE bug similar to [this](https://github.com/angular/angular.js/issues/8242). Sorry, but i think nothing i can do.

**Comment by chesminsky** [comment]
@uNmAnNeR so sad, because imask almost suited all my needs.
What i tried to do basically is to clear invalid input on blur
Maybe there is another way to achieve that?
I searched in docs but not found such option.
Does imask support clearing invalid mask on blur ?

**Comment by uNmAnNeR** [comment]
@chesminsky Yep, IE always makes me sad.
1) you can subscribe on focus event and prevent it
2) you can change `activeElement` manually
IMask does the only think what it should do - masking input. Other actions like validation have to be processed on application side.

**Comment by chesminsky** [comment]
@uNmAnNeR  thanks , i will try
