### ISSUE TITLE
Using `lazy` option shows placeholder as value

### ISSUE THREAD

**Issue by majapersson** [uNmAnNeR/imaskjs#760]
**Describe the bug**
When using the `lazy` option together with a pattern mask for the React component, the component renders with the placeholder as a value, so that the user has to delete the existing value before inputting a new one.

**To Reproduce**
Minimal reproducible version here: https://codesandbox.io/s/empty-sound-2lc5r4

**Expected behavior**
I would expect that when using the `lazy` option, the placeholder is always shown as a placeholder instead of a value and that when focusing on the input, it would be possible to start typing immediately without having to delete an existing value.

**Environment:**
 - OS: MacOS Catalina 
 - Browser: Chrome Version 106, Firefox 106 and Safari 15.6.1
 - IMask version: 6.4.2

**Comment by uNmAnNeR** [comment]
described here https://stackoverflow.com/a/72072443/2361203
probably using value as state should solve it
