### ISSUE TITLE
react-imask does not expose input properties like 'placeholder'

### ISSUE THREAD

**Issue by ayonix** [uNmAnNeR/imaskjs#761]
**Describe the bug**
react-imask 6.4.3 seems to have a regression in its type definitions.
The example in https://github.com/uNmAnNeR/imaskjs/tree/master/packages/react-imask has an error when used with typescript.

**To Reproduce**
https://codesandbox.io/s/react-typescript-forked-69wqty?file=/src/App.tsx

**Expected behavior**
Placeholder should be availble in the type definition.

**Environment:**
 - IMask version: react-imask 6.4.3
 - React 17.0.2

**Comment by Meligy** [comment]
I could also see this wit React 18, react-imask@6.4.3, and TypeScript typescript@4.8.4

**Comment by Radu-Dunarentu** [comment]
Hello, I used placeholderChar instead of placeholder to solve my issue. Hope it works for you too. 
https://github.com/uNmAnNeR/imaskjs/issues/329#issuecomment-869425622

**Comment by Kris-Pelteshki** [comment]
Same here 👀

**Comment by uNmAnNeR** [comment]
fixed in 2befe78

**Comment by Meligy** [comment]
Can it be released please if it's fixed? Thanks.

**Comment by uNmAnNeR** [comment]
was reverted because of #846

**Comment by franck-boucher** [comment]
So what's the current workaround to pass a `placeholder` to my input ?
