### ISSUE TITLE
pipe doesn't work well with block masks

### ISSUE THREAD

**Issue by giubatt** [uNmAnNeR/imaskjs#766]
**Describe the bug**
The `IMask.pipe` and `IMask.createPipe` don't work well when the mask has `blocks`, for example with this config:
```tsx
{
  mask: "$ num K",
  blocks: {
    num: {
      mask: Number,
      signed: true,
      radix: ".",
      thousandsSeparator: ","
    }
  }
}
```

on most values passed to the pipe it only formats the string into `$ num` without anything that comes after

**To Reproduce**
https://codesandbox.io/s/kind-rgb-sq9snw?file=/src/index.ts

**Expected behavior**
All masked values should be in the `$ num K` format, not only on `$ num`

**Environment:**
 - react-imask v6.4.3

**Additional context**

**Comment by giubatt** [comment]
as a workaround for this specific mask I'm adding extra spaces at the end of the string, then it formats as expected, added an example of this in the codesandbox

**Comment by uNmAnNeR** [comment]
it's because of `lazy` is `true` by default. Using `lazy: false` is a fix.

**Comment by giubatt** [comment]
> it's because of `lazy` is `true` by default. Using `lazy: false` is a fix.

oh wow, did not know that, thanks!
