### ISSUE TITLE
Placeholder for optional definition character

### ISSUE THREAD

**Issue by nghuuphuoc** [uNmAnNeR/imaskjs#768]
I am using the pattern mask (`00000[-0000]`) to represent a US zipcode which can be either a 5-digits or 9-digits number.

After pressing the first 5 digits, the input doesn't display the placeholder (`_` for the possible characters):

https://user-images.githubusercontent.com/4226036/200259088-69cbf73c-e598-435e-a12b-c966adbf075c.mp4

I expect that it should only display the placeholder for the first 5 digits (`_____`), and then as soon as I type more digits, the placeholder for remaining digits will be displayed:

https://user-images.githubusercontent.com/4226036/200259848-84a0d744-4377-41a4-b067-544787e69746.mp4

Is it possible?

**Comment by nghuuphuoc** [comment]
I also tried dynamic mask, but it seems that it doesn't support lazy placeholder:
https://jsfiddle.net/4183L7hu/4/

```js
var element = document.getElementById('selector');
var maskOptions = {
  lazy: false,
  mask: [
    {
      mask: '00000',      
    },
    {
      mask: '00000-0000',
    }
  ]
};
var mask = IMask(element, maskOptions);
```

**Comment by uNmAnNeR** [comment]
@nghuuphuoc this is completely correct solution. Optional characters should not have placeholder imo.
