### ISSUE TITLE
Mask not formatting value when setting value in an useEffect

### ISSUE THREAD

**Issue by GhostyJade** [uNmAnNeR/imaskjs#772]
**Describe the bug**
When I set the mask value using an useEffect, it doesn't update the masked value on the input (using either a mui input or a html input field)

**To Reproduce**
I've created a [CodeSandbox](https://codesandbox.io/s/suspicious-sound-dqkvb5)

**Expected behavior**
The value in the field should be 1.000,00

**Environment:**
 - OS: [e.g. iOS] Windows 11 Version 21H2 (Build 22000.1098)
 - Browser [e.g. chrome, safari]: Chrome
 - Version [e.g. 22]: 106.0.5249.119 
 - IMask version: latest (6.4.3)
 - Framework/plugin version if used: imask-react: latest (6.4.3)

**Comment by uNmAnNeR** [comment]
as i see `useEffect` updates the value. but `setValue` accepts string, not number. if you need number then you have to use `setTypedValue` instead. About mui i case not sure i can help
