### ISSUE TITLE
Parsing issue with date mask patterns with ending literals

### ISSUE THREAD

**Issue by MSDOStoevsky** [uNmAnNeR/imaskjs#774]
In the react-imask library, using the dates of different locales, there are issues parsing and formatting dates whose formats include an ending literal. The literal is being cut off and the date cannot be parsed in a clean way (i.e., using Intl or other date processing libraries that work off of Intl).

**To Reproduce**
https://codesandbox.io/s/vigorous-moore-dycivu?file=/src/App.tsx

Using the input, enter a date that follows the YYYY/MM/DD format. (In the Korean Intl locale the format literally is "YYYY. MM. DD.") Observe the console trail when the date is to be completed, when the parse and format functions are to be triggered. 

You'll note that despite the pattern being fixed, the date string being fed to the parse function drops the final literal for an unknown reason. This causes errors when attempting to process the date according to the exact locale.

**Expected behavior**
I expect the date being sent to the parse function to preserve the original pattern that was sent via the pattern prop.

**Environment:**
 - OS: MacOS Ventura 13
 - Browser: Firefox
 - Version: 106.0.4 
 - IMask version: 6.4.3
 - Framework/plugin version if used: react-imask 6.4.3

**Comment by smellai** [comment]
Even using the same configuration [copied/pasted from the examples page](https://imask.js.org/guide.html#masked-date), I'm not able to see the last inserted character

https://codesandbox.io/s/quirky-stallman-1y4m26?file=/src/App.tsx

**Comment by smellai** [comment]
apparently it works fine with the default pattern, but not with custom one (using slashes as separator for example)

https://user-images.githubusercontent.com/1763268/207837012-0a5f6fe1-4f7c-4f1c-a205-c7c446192445.mov

**Comment by MSDOStoevsky** [comment]
> Even using the same configuration [copied/pasted from the examples page](https://imask.js.org/guide.html#masked-date), I'm not able to see the last inserted character
> 
> https://codesandbox.io/s/quirky-stallman-1y4m26?file=/src/App.tsx

![image](https://user-images.githubusercontent.com/10935446/207939273-7861e595-1f68-49db-8146-7463767af1d4.png)

On that example the issue is not about stripping the end character being sent to the `parse` function, it's with Luxon DateTime not quite understanding the format keys used. https://moment.github.io/luxon/#/parsing?id=table-of-tokens

**Comment by uNmAnNeR** [comment]
you have to make sure that condition is met:
`format(parse(str)) === str`
then the considered to be valid. otherwise the last check when string is complete is not passed
