### ISSUE TITLE
react-imask: Cursor not pointing at correct place

### ISSUE THREAD

**Issue by aibrahim3546** [uNmAnNeR/imaskjs#775]
**Describe the bug**
**I am using `react-imask`**

I am trying to update the mask value manually. Here is the case:

Mask: `00/00`

Scenario:
- When user enter value more than 1 (`val > 1`). I will be appending `0` infront. so it will become.
- Example: If the value is `2` it will become `02`.
- The problem is that when I append the `0`. The cursor stays in the middle. I have attached video on this.

**To Reproduce**
- Mask: `00/00`
- inside `onAccept`

```tsx
const [value, setValue] = useState('')

...
<IMaskInput
  mask="00/00"
  value={value}
  onAccept={(val) => {
     if (val.length === 1 && Number(val) > 1) {
        setValue(`0${val}`)
      } else setValue(val)
    }
  }
/>
...
```

**Expected behavior**

- Cursor should be at behind

**Environment:**
 - Browser Chrome - Version [e.g. 22]
 - IMask - none
 - Framework/plugin version if used - react-imask (6.4.2)

Video: 

https://user-images.githubusercontent.com/31366174/201017469-eccd33fc-a93f-449c-8f65-32d4de59ef35.mov

**Comment by uNmAnNeR** [comment]
if you update the value manually then you also have to update cursor position manually as long as they are bound together. The solution here is to use proper mask that handles your case internally during input and then cursor will be automatically updated.

**Comment by saewitz** [comment]
I had a similar problem. Got it to work like this:

```javascript
mask = "MM/YY"
blocks = {
  {
    MM: {
      mask: IMask.MaskedRange,
      from: 1,
      to: 12,
      autofix: 'pad',
    },
    YY: {
      mask: '00',
    },
  }
}
```

References: https://imask.js.org/guide.html#masked-pattern, https://imask.js.org/guide.html#autofix
