### ISSUE TITLE
useIMask hook 6.4.3 is crashing when I pass the value property

### ISSUE THREAD

**Issue by rafde** [uNmAnNeR/imaskjs#777]
**Describe the bug**
useIMask hook 6.4.3 is crashing when I pass the value property

**To Reproduce**
```js
  const [value, setValue] = useState("");
  const iMaskEventProps = useMemo(
    () => ({
      onAccept(val) {
        setValue(val);
      }
    }),
    [setValue]
  );
  const iMaskOptions = useMemo(
    () => ({
      mask: "a00 aa00"
    }),
    []
  );
  const iMaskProps = useIMask(
    {
      ...iMaskOptions,
      value, // crashes hook. Removing this will fix it
    },
    iMaskEventProps
  );
```
https://codesandbox.io/s/react-imask-input-box-masks-forked-i3d0ik?file=/src/index.js

**Expected behavior**
should not crash hook.

**Environment:**
 - OS: `Mac OS 12.6` [probably crashes for all OSes]
 - Browser: `Chrome` [probably crashes for all browsers]
 - Version: `107.0.5304.110 (Official Build) (x86_64)` [probably crashes for all versions]
 - react-imask version: `6.4.3`
 - Framework/plugin version if used

**Additional context**
supposedly resolved in https://github.com/uNmAnNeR/imaskjs/issues/601

**Comment by uNmAnNeR** [comment]
yeah the interface of the hook was changed that's why it's not working as you expected. now `value` and `setValue` is returned from the hook. check it here https://github.com/uNmAnNeR/imaskjs/tree/master/packages/react-imask#using-hook
