### ISSUE TITLE
imask.directive: NgModel not updated with undefined imask

### ISSUE THREAD

**Issue by fsz** [uNmAnNeR/imaskjs#78]
**Description**
Using the imask directive with an undefined input parameter does not update the NgModel value on changes. You can still type something into the input, but the NgModel remains null.

**Simplified Reproduction**
Property in component: 
_mask = undefined;_

Usage in  template:
_<input [imask]="mask" />_

**Expectation**
The input should be usable as if there is no imask directive attached to it.

**Comment by uNmAnNeR** [comment]
@fsz thanks for issue, i will be able to check it on next week.
