### ISSUE TITLE
unmask="typed" does not accept null values

### ISSUE THREAD

**Issue by ChristianKlima** [uNmAnNeR/imaskjs#795]
If unmasked="typed" is set, null cannot be assigned. It is then always expected that the transferred value corresponds to the type. This makes the "typed" setting unusable for us. In our forms, values ​​must also be able to be set to null. If they are null, they are not transmitted to the backend. Null is something other than an empty string, for example. It would be good if one could at least allow null values ​​optionally.

Please have a look at the following example:
https://stackblitz.com/edit/angular-ivy-jyrv9p

**Comment by uNmAnNeR** [comment]
is it what you need?
```
maskToDot = {
  mask: /^\+?[^a-z|+]*$/,
  format: v => v == null ? '' : v,
};
```
