### ISSUE TITLE
IMask inputs 0 when last digit is deleted

### ISSUE THREAD

**Issue by igorMondu** [uNmAnNeR/imaskjs#798]
**Describe the bug**

When using a Number mask, after entering some number and after deleting the last digit, 0 will appear in the input and the cursor will move in front of it. This does not happen with 6.2.2. It started to happen since 6.3.

**To Reproduce**
https://codesandbox.io/s/chakra-ui-react-imask-react-hook-form-forked-0j7mmt

**Expected behavior**
It should not put 0 in the input when the last digit is deleted in the input, the input should be empty.

**Environment:**
 - OS: Mac Os
 - Browser Edge
 - Version 108.0.1462.41
 - IMask version: 6.4.3
 - ReactJS

**Comment by GhostyJade** [comment]
I've tested your codesandbox but on Chrome on Windows 11 it works like expected...

**Comment by ookil** [comment]
Can this be released?

**Comment by GhostyJade** [comment]
Can you please release this fix? Thanks.

**Comment by enginewisesolutions** [comment]
Can this be released? If not the issue isn't closed on our end @uNmAnNeR
