### ISSUE TITLE
Library doesn't work with moduleResolution higher than Node16

### ISSUE THREAD

**Issue by petruspierre** [uNmAnNeR/imaskjs#799]
**Describe the bug**
Probably related to https://github.com/microsoft/TypeScript/issues/49160
I use `moduleResolution: "NodeNext"` in my typescript project and I'm trying to use IMask, but I'm getting the following error: 
```
This expression is not callable.
  Type 'typeof import("/home/petrus/tas/tmi/app/node_modules/imask/index")' has no call signatures.ts(2349)
```

It only works with `moduleResolution: "node"` 

**To Reproduce**
Reproduce using this repo https://github.com/petruspierre/imask-nodenext-issue

**Expected behavior**
Should work independently of the moduleResolution method

**Environment:**
 - "typescript": "4.9.4"

**Comment by uNmAnNeR** [comment]
@petruspierre hey! seems like i am a bit late. but is it still relevant?
i've tried to reproduce your case but on my mac it does not throw any error when using `"moduleResolution": "NodeNext"`
