### ISSUE TITLE
Vue plugin

### ISSUE THREAD

**Issue by uNmAnNeR** [uNmAnNeR/imaskjs#8]

**Comment by yacinehmito** [comment]
I'm up for the challenge if you're interested!

What I have in mind is a vue directive that would proxy the `input` and `changed` events and apply the mask.

What do you think? I can start working on this right away if you're ok with the approach.

**Comment by uNmAnNeR** [comment]
sure, i am interested.
I think mask should not override any events, but add new ones. I also follow this way in imask-core and find it proper. If you are familiar with Angular you could look at [example directive](https://github.com/uNmAnNeR/imaskjs/blob/gh-pages/plugins/angular/src/imask.directive.ts) to get the idea. May be [this vue plugin](https://github.com/text-mask/text-mask/tree/master/vue) for another popular mask can help if it is not outdated.

Also for plugins i found some advices for myself, it can be helpful for you also to make it better:
- target latest stable version of a framework
- don't commit `dist` folder, but force build before publishing to npm
- prefer `peerDependencies` over `dependencies` as much as possible
- define new `accept` and `complete` events
- implement update options, but don't optimize it (diff check, etc...) - this stuff is alread done internally
- use `rollup` over `webpack` if possible (but for Angular only webpack is suitable now)

I am open for any ideas to make things better.
So if you are still here - please put your code [here](https://github.com/uNmAnNeR/imaskjs/tree/gh-pages/plugins/vue)

**Comment by yacinehmito** [comment]
Nice write up! I'll keep you posted.

**Comment by aussieboi** [comment]
here to help if needed, let me know, cheers :)

**Comment by uNmAnNeR** [comment]
@yacinehmito @aussieboi 
there is a [PR for Vue plugin](https://github.com/uNmAnNeR/imaskjs/pull/13). I wrote some comments on it. Let's do it the best.
