### ISSUE TITLE
Wrong phone number on input after paste with '8' in begin

### ISSUE THREAD

**Issue by BulatSa** [uNmAnNeR/imaskjs#800]
**Describe the bug**
Wrong phone number on input after paste.

**To Reproduce**
Paste `89041234567` and get a wrong result on input field.
![image](https://user-images.githubusercontent.com/8298469/209127138-b33814ab-5e53-45c9-9235-7174b8a6424c.png)

**Expected behavior**
After paste `89041234567` field have a correct number, like this 
![image](https://user-images.githubusercontent.com/8298469/209127491-209cd20f-4da9-4df0-8e2c-424384b7b614.png)

**Environment:**
- OS: Mac Os
- Browser Edge
- Version 108.0.1462.41
- IMask version: 6.4.3

**Comment by uNmAnNeR** [comment]
it's not wrong. it's correctly handles your input. If you want to handle phones starting from '8' in a differ way use custom `prepare` callbacks
