### ISSUE TITLE
IMaskMixin on safari has the problem of accent marks being duplicated

### ISSUE THREAD

**Issue by fabiodanil2** [uNmAnNeR/imaskjs#802]
**Describe the bug**
When trying to extend existing components using IMaskMixin. The value submitted by the user is correct but the MaskedFunction_value shows a different result.  This only happens on safari while using characters with accent marks, on chrome the results are correct.

- Safari
<img width="381" alt="Screenshot 2022-12-30 at 09 59 43" src="https://user-images.githubusercontent.com/72746067/210058397-b9e7376c-d1ec-4bce-be7d-e758a25ed477.png">

- Chrome
<img width="670" alt="Screenshot 2022-12-30 at 10 10 11" src="https://user-images.githubusercontent.com/72746067/210059015-c92f95e5-303c-44fe-9498-d072bd7947c1.png">

**Expected behavior**
It should work like in chrome

**Environment:**
 - Browser: safari
 -  "react-imask": "6.4.3",

**Comment by uNmAnNeR** [comment]
seems like it should be fixed in https://github.com/uNmAnNeR/imaskjs/commit/3a390bb1889f660bc12d9c233a993a23e750aea9
