### ISSUE TITLE
email mask

### ISSUE THREAD

**Issue by long76** [uNmAnNeR/imaskjs#81]
я использую
` var mask3 = new IMask(document.getElementById('oemail'), {
            mask: /^[a-z0-9_\.-]+@[a-z0-9-]+\.([a-z]{2,4}\.)?[a-z]{2,4}$/
        });`

при вводе ничего не происходит, не дает ничего ввести.

**Comment by uNmAnNeR** [comment]
@long76 а регулярку то проверяли?
```
> /^[a-z0-9_\.-]+@[a-z0-9-]+\.([a-z]{2,4}\.)?[a-z]{2,4}$/.test('a')
> false
```

**Comment by long76** [comment]
@uNmAnNeR да на [https://github.com/RobinHerbots/Inputmask](url) все работало

**Comment by uNmAnNeR** [comment]
@long76 я пример привел выше - одна буква уже не подходит. Эта маска работает по другому принципу. Почитайте гайд со строки `Also make sure that mask or validator works with any of intermediate states, not just final value.`

**Comment by long76** [comment]
разобрался вот рабочий пример
`var mask3 = new IMask(document.getElementById('oemail'), {

            mask:function (value) {
                if(/^[a-z0-9_\.-]+$/.test(value))
                    return true;
                if(/^[a-z0-9_\.-]+@$/.test(value))
                    return true;
                if(/^[a-z0-9_\.-]+@[a-z0-9-]+$/.test(value))
                    return true;
                if(/^[a-z0-9_\.-]+@[a-z0-9-]+\.$/.test(value))
                    return true;
                if(/^[a-z0-9_\.-]+@[a-z0-9-]+\.[a-z]{1,4}$/.test(value))
                    return true;
                if(/^[a-z0-9_\.-]+@[a-z0-9-]+\.[a-z]{1,4}\.$/.test(value))
                    return true;
                if(/^[a-z0-9_\.-]+@[a-z0-9-]+\.[a-z]{1,4}\.[a-z]{1,4}$/.test(value))
                    return true;
                return false;
                    }
        });`

**Comment by long76** [comment]
жаль что красиво сделать 
```js
var zipMask = new IMask(document.getElementById('oemail'), {
            mask: 'N{@}D{.}Y[{.}Z]',
            lazy: false,
            definitions: {
                'N': /[a-z0-9_\.-]+/,
                'D':/[a-z0-9_\.-]+/,
                'Y':/[a-z]{2,4}/,
                'Z':/[a-z]{2,4}/
            }
        });
```
я прочитал что в документации что **Pattern Mask - mask is fixed in size** но почему нельзя при фокусе показывать маску позволяя ввести нужное количество символов?

**Comment by uNmAnNeR** [comment]
@long76 вариант решения так себе. Попробуйте ввести корректное значение и стереть всю часть перед @. Красиво можно будет в v4.0.0. Но не через definitions, а через groups, потому что первое работает посимвольно.

**Comment by long76** [comment]
@uNmAnNeR стер всю часть перед @ и все стерлось,в общем-то нормальное поведение, а так спасибо, буду ждать релиза.
