### ISSUE TITLE
Masking from the back

### ISSUE THREAD

**Issue by mdrbohlav** [uNmAnNeR/imaskjs#82]
Hello, is it possible to mask the value from the back? I have mask set as `00{:}00{:}00` and when I type for example only 3 numbers it puts the colon after the second number but I want it after the first one.

Maybe the table will be better.

Typed | Masked | After Blur | Required Masked | Required After Blur
------------ | ------------- | ------------ | ------------- | ------------
457 | 45:7 | 00:45:07 | 4:57 | 00:04:57

**Comment by uNmAnNeR** [comment]
@mdrbohlav i suppose you've already implemented some logic on blur but it does not work. So i might do on blur:
- get only numbers
- trim zeros at start if any exists
- number of zeros at start to shift = total numbers (6)  - current numbers length
- set new value = zeros + numbers

But in general - i dont see any out of box solution to your case.

**Comment by mdrbohlav** [comment]
Well, the blur logic does not work because of the wrong position of the colon. I was not sure if I am maybe missing some options I could pass to the IMask.

Thanks anyway
