### ISSUE TITLE
Input be cleared when re-render the component

### ISSUE THREAD

**Issue by sucy6330133** [uNmAnNeR/imaskjs#828]
**What problem you are trying to solve?**
The input value for the component has been cleared when re-render is triggered.
I have created a example here
https://codesandbox.io/s/react-imask-input-box-masks-forked-f8yui0?file=/src/index.js

The component is using 'a{-}00000' as a pattern mask and the original value for this component is 'u-87878'. The 'u' can be removed without clearing the rest of the value when editing.
However, in our scenario, the components are presenting a list of objects, when one of the object has been removed from the list, it will trigger the component be re-rendered. So the original value here for the component will be ' 87878' after removing the u. I have use the reset button to demonstrate the problem. After reset button be pressed, the ' 87878' has been cleared.

**Describe the solution you'd like**
We are expecting the ' 87878' remains as the value for this component. Or, if there are other way to present the similar requirement, we would love to know. Thanks for helping out here.

**Comment by uNmAnNeR** [comment]
you can make 'u' optional then reset will work

**Comment by sucy6330133** [comment]
If u is optional, it will be different behaviour. The mask basically has been changed, and we still need the place holder there to indicate that the mask is expecting an input.

**Comment by uNmAnNeR** [comment]
then try to use dynamic mask to satisfy both conditions. anyway it's a question of mask usage not an issue.
