### ISSUE TITLE
Angular-imask 6.4.3 is incompatible with angular v13

### ISSUE THREAD

**Issue by mihailTheStudent** [uNmAnNeR/imaskjs#829]
Hi, @uNmAnNeR 
The bug is still reproduced 🙁
Currently load angular-imask v.6.4.3 and get the same error

![image](https://user-images.githubusercontent.com/90143649/220591007-c54f019e-9a22-46ef-90d2-e87c6cfdfa9b.png)

Angular version is ^13.0.0 (loaded 13.3.12)

Please, check, how to fix it.

_Originally posted by @mihailTheStudent in https://github.com/uNmAnNeR/imaskjs/issues/741#issuecomment-1439761814_

**Comment by uNmAnNeR** [comment]
@mihailTheStudent alright. can you try `angular-imask@6.5.0-alpha.0` ?

**Comment by uNmAnNeR** [comment]
I use official tool for bundling libraries (ng-packgr) and i need to update build chain from time to time. Sometimes it breaks compatibility. IMO it should be a problem of framework/tools not the library maintainer. I am not able to build bunch of versions for every major release for every framework. Sorry about that but seems like the only way to fix it is to update your project to angular v15.
