### ISSUE TITLE
Vue plugin issue - padFractionalZeros parameter

### ISSUE THREAD

**Issue by Sevenka** [uNmAnNeR/imaskjs#83]
Hello, I have a problem with `padFractionalZeros` parameter for `imask-input` component. In the original demo for Number mask with `padFractionalZeros: true` we see, that fractional zeros show only when blur event fires. But in Vue component they show instantly on input and it is not possible to input fractional decimals after typing the main part. Can you provide more information for it?

**Comment by uNmAnNeR** [comment]
@Sevenka nothing to say, i dont use Vue. if you provide working example i can try to figure out.
