### ISSUE TITLE
RegEx mask for urls (`https://`) not working, but why?

### ISSUE THREAD

**Issue by katerlouis** [uNmAnNeR/imaskjs#831]
**Describe the bug**
I must be crazy, but the simplest example isn't working:

**To Reproduce**
[Codepen](https://codepen.io/katerlouis/pen/MWqJZaj)

**Code**
```js
IMask(
  document.getElementById('myInput'),
  {
    //mask: /^[1-6]\d{0,5}$/ // this works
    //mask: /^https\S+$/, // not working
    mask: /^(https)\S+$/, // why doesnt this work?
  })
```

**Expected behavior**
I expect the input to only allow writing `https` in the beginning, but instead it just doesnt allow anything. Nothing can be typed :(

**Environment:**
doesn't matter; tested the codepen on different systems

**Additional context**
The regex seems fine: https://regex101.com/r/nRGl0b/1

**Comment by uNmAnNeR** [comment]
hi. he is a piece from guide for you
![image](https://user-images.githubusercontent.com/1927921/228493129-31aa70f9-581c-4eeb-a6fd-53be806b39c6.png)

**Comment by renerlemes** [comment]
@katerlouis Did you get your code to work? I have the same problem

**Comment by katerlouis** [comment]
> @katerlouis Did you get your code to work? I have the same problem

I dropped the feature altogether for now, so no I haven't gotten any further, sorry :(

**Comment by ipatieff** [comment]
The solution is not perfect, but try `Pattern` mask

```ts
mask: `https://${"*".repeat(300)}`
```
https://imask.js.org/guide.html#masked-pattern

¯\_(ツ)_/¯
