### ISSUE TITLE
Throw warnings about onChange handler

### ISSUE THREAD

**Issue by DonikaV** [uNmAnNeR/imaskjs#839]
```
client.js?4d30:1 Warning: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.
    at input
```
How I can avoid this warning if I can not use onChange?

**Comment by uNmAnNeR** [comment]
seems like it's not a warning from imask. So probably you need to ask someone else.
But if you still think i can help you then please provide some example in a sandbox to run and feel free to reopen this issue.
