### ISSUE TITLE
Complete event not fire with optional symbols

### ISSUE THREAD

**Issue by SinnerAir** [uNmAnNeR/imaskjs#84]
I use 0[00].0[00].0[00].0[00] as option mask. If input value in textbox  is 1.1.1.1 then complete event not fires.
Live example: https://plnkr.co/edit/akE7pu8N2nJFk68HIuKP?p=preview

**Comment by uNmAnNeR** [comment]
@SinnerAir Thanks for the issue, I need some time to figure out.

**Comment by uNmAnNeR** [comment]
fixed in v4.0.0
