### ISSUE TITLE
Currency with dot radix not masked correctly

### ISSUE THREAD

**Issue by fgiorgio** [uNmAnNeR/imaskjs#841]
Hi, I'm trying to mask a decimal value coming from a database as currency. Database's decimals use dot as radix, while I want to use comma in the UI. The following script reproduces the issue, decimals are not parsed correctly.

https://jsfiddle.net/47pk21ob/

What I'm doing wrong?

Thanks

**Comment by uNmAnNeR** [comment]
hi, you want to map thousands separator to the radix. But it does not work the way you expected causing inconsistency.
Seems like that it's not the right configuration. I understand your idea behind but don't see any way to make it work for mask whether it should be kept as a separator or mapped to a radix.

**Comment by fgiorgio** [comment]
> hi, you want to map thousands separator to the radix. But it does not work the way you expected causing inconsistency. Seems like that it's not the right configuration. I understand your idea behind but don't see any way to make it work for mask whether it should be kept as a separator or mapped to a radix.

Hi @uNmAnNeR, thanks for the reply. I've tried to change the thousands separator, so there's a space as separator and the dot mapped to radix. The problem is the same, you can see it in the example below:

https://jsfiddle.net/9hwpvr6u/

Thanks

**Comment by uNmAnNeR** [comment]
@fgiorgio initial value in input is considered to be masked by default. So if you want to apply mask on existing value it should be "123,45" - dot is already mapped.
Or otherwise if you have unmasked value then you have to do `mask.unmaskedValue = '123.45'`
but it doesn't seem to work at the moment. I will check it out.

**Comment by uNmAnNeR** [comment]
@fgiorgio about second case you can try using v6.5.1-alpha.0 with fix

**Comment by wanderson7** [comment]
I'm using **v6.4.2** and It's working, but when I updated to v6.6.1 the same error happened.
