### ISSUE TITLE
[React] Issue with unmask prop type in version 6.6.0

### ISSUE THREAD

**Issue by pzi** [uNmAnNeR/imaskjs#846]
**Describe the bug**
Given the following component which is working fine in v6.4.3

```tsx
import * as React from 'react';

import type {InputBaseComponentProps} from '@mui/material';
import {useFormikContext} from 'formik';
import {IMaskInput} from 'react-imask';

const BSBMask = React.forwardRef<HTMLInputElement, InputBaseComponentProps>(({onChange: _onChange, ...props}, ref) => {
  const {setFieldValue} = useFormikContext();

  return (
    <IMaskInput
      {...props}
      inputRef={ref as React.RefCallback<HTMLInputElement>}
      unmask={true}
      onAccept={(value) => {
        setFieldValue(props.name, value);
      }}
      mask="000-000"
    />
  );
});

export default BSBMask;
```

We are getting the following type issue after upgrading to version 6.6.0.

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/2037851/232441592-73b73064-6d41-430c-9abd-8e0fa317b57b.png">

**To Reproduce**
When using this component in Stackblitz it seems to be working fine: https://stackblitz.com/edit/react-ts-yqmeqa?file=BSBMask.tsx

**Expected behavior**
Not having any type issues with the unmask field as `true` is an accepted value.

**Environment:**
 - OS: [e.g. iOS] macOS 11.7.6
 - Browser [e.g. chrome, safari] Brave 
 - Version [e.g. 22] Version 1.50.114 Chromium: 112.0.5615.49 (Official Build) (x86_64)
 - IMask version 6.6.0
 - Framework/plugin version if used: react-imask

**Additional context**
Restarting the TS server didn't help.

**Comment by ahmadi-akbar** [comment]
same here

<img width="869" alt="image" src="https://user-images.githubusercontent.com/48069695/233144614-9c787644-52d3-4712-a666-eb013936e57b.png">


- IMask version 6.6.0
- Framework/plugin version if used: react-imask

**Comment by Mario-Eis** [comment]
This issue was introduced in v6.5.0 and is also preventing us from upgrading to newer versions.
