### ISSUE TITLE
Prevent console warn when using dynamic mask as a pattern block

### ISSUE THREAD

**Issue by guillaumefugere** [uNmAnNeR/imaskjs#848]
**What problem you are trying to solve?**

When using a `dynamic mask option` as a value for pattern `blocks`. The following console warn always show:

```
"eager" option is not available in dynamic mask, use this option in siblings
"overwrite" option is not available in dynamic mask, use this option in siblings
```

It is impossible to remove those options, since they are always added to the base options provided.

```
const maskedBlock = createMask({
  parent: this,
  lazy: this.lazy,
  eager: this.eager,
  placeholderChar: this.placeholderChar,
  displayChar: this.displayChar,
  overwrite: this.overwrite,
  ...this.blocks[bName],
});
```

The [createMask()](https://github.com/uNmAnNeR/imaskjs/blob/4835b9e70b47a18b5aac3e4ccc183a9f786664c0/packages/imask/src/masked/pattern.js#L108) usage in question.

**To Reproduce**

[jsfiddle](https://jsfiddle.net/Fugereman/vyc2z8n3/22/)

**Describe the solution you'd like**

Type check the block mask options. If it is a dynamic mask, do not include `eager` and `overwrite` properties from parent (`this`).

**Describe alternatives you've considered**

Using a dynamic mask without parent. But this was breaking the prevent back shift feature that we require.

**Other**

We are also getting this error in our project with dynamic mask in pattern blocks.

```
"skipInvalid" option is not available in dynamic mask, use this option in siblings
```

We never define the `skipInvalid` property anywere. Something call this dynamic mask setter somewere when used in a block. But I was unable to reproduce as of now.

**Comment by uNmAnNeR** [comment]
@guillaumefugere hi, which version do you use?

**Comment by guillaumefugere** [comment]
@uNmAnNeR Got quite deep in the configuration indeed. I'm using version 6.5.1, but it's still present in 6.6.0. Very nice library by the way!

**Comment by uNmAnNeR** [comment]
What was done in v.7.0.0:
- Dynamic mask bypasses common props (overwrite, eager, skipInvalid) to children.
- Getters for these props still return the currently selected mask prop or dynamic mask prop if no mask is selected
