### ISSUE TITLE
[Angular] Breaking Change in 6.5.0

### ISSUE THREAD

**Issue by stevenimhof** [uNmAnNeR/imaskjs#849]
**Describe the bug**
I use this library in a component library. I added this library in package like this: `"angular-imask": "^6.4.3"`.

We now got the feedback that our users see the following build error when they use our library in an Angular 15 App:

```
./node_modules/[***masked***]/fesm2020/[***masked***].mjs:167:12-27 - Error: export 'IMaskFactory' (imported as 'i1') was not found in 'angular-imask' (possible exports: DEFAULT_IMASK_ELEMENT, DefaultImaskFactory, IMASK_FACTORY, IMaskDirective, IMaskModule, IMaskPipe, MASKEDINPUT_VALUE_ACCESSOR, PIPE_TYPE, pipe)
```

If we would have not used a "^" for this dependency version it would still work. But with the "^" it installs the newest minor version (6.5.x) which changed the behaviour. But such a change should be in a major version.

It got even mentioned in the PR that it should be a major version. See MR: https://github.com/uNmAnNeR/imaskjs/pull/808

**Expected behavior**
The change should be in version 7.x.x.

**Environment:**
 - OS: macOS
 - IMask version 6.5.0
 - Angular 15

**Comment by uNmAnNeR** [comment]
yes i understand your point. in general you are right.

The thing here is that Angular introduced breaking changes and even if nothing was changed in the library it just stops working. That what happened when they are updated to 13 if i am not mistaken. Some interfaces were changed.
Second thing is that i keep same version for core and plugins. I tried another strategy but this made me struggling.
So i decided that I will not go to up the major version in such situations.
See like the Angular guys also keep in sync versions of there libraries but make others to break there components when new Angular is released. So personally i don't feel any guilt on myself with imask here. it's just a sad compromise.
If your users want to update to ng15 then another issues with v6.4.3 are waiting them. They should update anyway.
The best case if you can make imask a peer dependency to get rid of this burden in future.

It's already been released, so let's learn from it and move on.

**Comment by pumano** [comment]
That breaking change comes with [commit](https://github.com/uNmAnNeR/imaskjs/commit/a89e1442ffc6e772a1eda6c447450f72ab9beed3)
but just need to change imports and all works
