### ISSUE TITLE
NullableMaskedNumber Implementation

### ISSUE THREAD

**Issue by DywiTom** [uNmAnNeR/imaskjs#853]
Hello!

First of all, thanks for your great work.
I saw that many people asked for a native feature for

```
class NullableMaskedNumber extends IMask.MaskedNumber {
  // @ts-ignore
  get typedValue() {
    return this.unmaskedValue !== ''
      ? // @ts-ignore
        super.typedValue
      : null;
  }
  set typedValue(num) {
    super.typedValue = num;
  }
}
```

Can you implement it please?

Its better instead of always creating 
mask = new NullableMaskedNumber({}) ....

Thanks,
Tom

**Comment by uNmAnNeR** [comment]
hi, thanks for the idea.
it's possible to pass a class to the imask factory like:
```js
const mask = IMask(el, { mask: NullableMaskedNumber, /* options */ };
```
so you don't have always create new instance by yourself.
You can even do `IMask.NullableMaskedNumber = NullableMaskedNumber` after your class declaration and it will work as well.
In general i don't think it should be done in the core.

**Comment by DywiTom** [comment]
Hey @uNmAnNeR, thanks for your answer!
I tried to solve the problem as you suggested it, but it's not working. (see [Stackblitz](https://stackblitz.com/edit/dywi-imask?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html))
NgModel does not update to number but it should, what do i wrong?
That is the reason why i am asking for a native feature for that. I want to solve it with a directive.

**Comment by uNmAnNeR** [comment]
@DywiTom it does work with `imask` directive https://stackblitz.com/edit/dywi-imask-qd5joa
if you need a custom directive then it's out of scope of this plugin so i probably can't help you further.

**Comment by DywiTom** [comment]
Thanks for your awesome help!  I donated you a coffee 👍🏻

**Comment by uNmAnNeR** [comment]
since 7.1.0 `expose` property can be used:
https://stackblitz.com/edit/dywi-imask-wbgxnw?file=src%2Fapp%2Fapp.component.ts
