### ISSUE TITLE
createPipe with Number mask bug

### ISSUE THREAD

**Issue by leonovi** [uNmAnNeR/imaskjs#854]
**Describe the bug**
While using "Number" mask with createPipe, it is not possible to make a float number.

**To Reproduce**
edit: https://stackblitz.com/edit/js-imask-czzhlk?file=index.js
app: https://js-imask-czzhlk.stackblitz.io

**Expected behavior**
it is probably correct to give a ',' or '.' to enter

**Environment:**
 - OS: MacOs
 - All browsers
 - IMask version: 6.61

**Comment by uNmAnNeR** [comment]
Pipe produces the same results for `123` and `123.` => `123`. It's completely correct behaviour.
Just like `Number('123') === Number('123.')`
it's not correct to use `pipe` in that case. You must you regular `mask` here.
