### ISSUE TITLE
Circular Type Reference Error in 'imask' Library TypeScript Definitions

### ISSUE THREAD

**Issue by amanx11** [uNmAnNeR/imaskjs#856]
Hi there,

I hope this message finds you well. I would like to bring to your attention an issue I encountered while using the 'imask' library in a TypeScript project. The error is related to circular type references within the library's TypeScript definitions, causing a compilation error.

Here are the details of the error I encountered:
`ERROR in node_modules/imask/index.d.ts:154:5 - error TS2502: 'definitions' is referenced directly or indirectly in its own type annotation.
154     definitions: { [key: string]: MaskedPattern.PatternDefinition };
        ~~~~~~~~~~~
node_modules/imask/index.d.ts:190:10 - error TS2456: Type alias 'PatternDefinition' circularly references itself.
190     type PatternDefinition = AnyMask | AnyMasked | AnyMaskedOptions & Pick<
             ~~~~~~~~~~~~~~~~~
node_modules/imask/index.d.ts:467:15 - error TS2456: Type alias 'AnyMask' circularly references itself.
467   export type AnyMask = AnyMaskedOptions['mask'];
`
Here are the details of my environment:

TypeScript version: 3.8.3
'imask' library version: 6.6.1 (also tried with other versions like 6.6.0, 6.4.2, 6.4.3)
I have attempted the following steps to resolve the issue but without success:

1. Updated the 'imask' library to the latest version.
2. Cleared the TypeScript cache by deleting the node_modules/.cache directory and reinstalling dependencies.
3. Reviewed my TypeScript configuration (tsconfig.json) to ensure it aligns with the library's requirements.

Despite these efforts, the circular type reference error persists.

Could you please investigate this issue further and provide guidance on how to resolve it? If needed, I'm more than willing to provide additional information or assist in any way I can to help resolve this problem.

Thank you for your attention to this matter. I appreciate the effort you put into maintaining the 'imask' library and supporting the community.

**Comment by uNmAnNeR** [comment]
@amanx11  thanks for reporting. should be fixed in 7.0.0 which is currently under development.
