### ISSUE TITLE
Allow Asynchronous imaskElement Directive for Angular-Imask

### ISSUE THREAD

**Issue by howlettga** [uNmAnNeR/imaskjs#857]
**What problem you are trying to solve?**
A lot of DOM lookup works asynchronously in many libraries. The angular-imask library provides a directive for defining a function to get the direct input element off of more complex input component. However it has to be synchronous and so will not work with frameworks that provide asynchronous lookup.

**Describe the solution you'd like**
Add a directive to `angular-imask/src/imask.directive.ts` called something like `imaskElementAsync` that would be defined with `async (elementRef: ElementRef, directiveRef: any) => IMask.MaskElement`

**Describe alternatives you've considered**
I could manually build the element lookup but then I am subjected to it breaking if the library changes their component's internal definitions in any way. It would be better to use the defined API. Take Ionic as the example (my use case) https://ionicframework.com/docs/api/input#methods. They provide a getInputElement API method on their custom input, but it returns a promise so can't be used directly with the imaskElement directive.

**Comment by uNmAnNeR** [comment]
Hi, I am personally against adding complexity if it is not necessary. Imask does not need it itself. It's a purpose of some kind of adapter. I feel like there should be another way to solve it. What if you do something like this:
```
ionInputElement;
opts={mask: Number};

@Element() el: HTMLElement;

componentDidLoad(){
  this.ionInputElement.getInputElement().then((el) => this.el = el);
}

render() {
  return (
    <ion-input
      ref={(ionEl) => this.ionInputElement = ionEl}         
      [imask]="el ? opts : null" />
  );
}
```

I did not test it. But if it suddenly works then you are good. No internal stuff is used.

**Comment by uNmAnNeR** [comment]
ok, let me know if it still does not work for you
