### ISSUE TITLE
+ symbol

### ISSUE THREAD

**Issue by kamaliev** [uNmAnNeR/imaskjs#86]
Hello.

I use this rules

`
this.mask = IMask.createMask({
          mask: [
            {
              mask: '{+38} (000) 000-00-00',
              expression: /\+38\s\([\d]{3}\)\s[\d]{3}-[\d]{2}-[\d]{2}/,
              startsWith: '38',
              lazy: true,
              country: 'Ua'
            },
            {
              mask: '{+7} (000) 000-00-00',
              expression: /\+7\s\([\d]{3}\)\s[\d]{3}-[\d]{2}-[\d]{2}/,
              startsWith: '7',
              lazy: true,
              country: 'Ru'
            },
            {
              mask: '8 (000) 000-00-00',
              expression: /8\s\([\d]{3}\)\s[\d]{3}-[\d]{2}-[\d]{2}/,
              startsWith: '8',
              lazy: true,
              country: 'Ru'
            },
            {
              mask: '0000000000000',
              startsWith: '',
              country: 'unknown'
            },
          ],
          dispatch: function (appended, dynamicMasked) {
            const number = (dynamicMasked.value + appended).replace(/\D/g, '');

            const res = dynamicMasked.compiledMasks.find(function (m) {
              return number.indexOf(m.startsWith) === 0;
            });
            
            return res;
          }
        }
      );
`

But when I press + symbol nothing happen. How I add + symbol write with this rules?

**Comment by uNmAnNeR** [comment]
@kamaliev hi!
Look at your dispatch fn: `const number = (dynamicMasked.value + appended).replace(/\D/g, '');` will trim `+`. So it just does not work as you expect.
