### ISSUE TITLE
React-imask's hook never sets `initialized` state to true, if props never mutated

### ISSUE THREAD

**Issue by aktanoff** [uNmAnNeR/imaskjs#860]
**Describe the bug**
Hello!
I've researched, that react-imask's hooks: setValue, setUnmaskedValue don't work, when we use it with passing into useIMask hook constant properties, or properties that memoized(and never changed) by React's useCallback + useMemo

That's because of `initialized` state variable is [setting up with incorrect value in useEffect hook](https://github.com/uNmAnNeR/imaskjs/blame/master/packages/react-imask/src/hook.ts#L79), that creates instance of IMask

We should use here `Boolean(maskRef.current)`, instead of `Boolean(mask)`

**To Reproduce**
you can check this codesandbox, where i made example which using setUnmaskedValue
https://codesandbox.io/s/brave-danny-00mogo?file=/src/App.tsx

**Expected behavior**
initialized variable, sets in true, after IMask instance succesfully created, and setValue, setUnmaskedValue should work well after it.

**Environment:**
 - OS: Mac OS 12.6 Monterey
 - Browser Chrome
 - Version 113.0.5672.134
 - IMask version 6.6.1
 - Framework/plugin version React 18.2.0

**Additional context**
https://github.com/uNmAnNeR/imaskjs/blame/2c3f872ca200ae7622aad6922b7d3092a175931f/packages/react-imask/src/hook.ts#L79

**Comment by uNmAnNeR** [comment]
@aktanoff thanks for reporting and providing PR. Merged
