### ISSUE TITLE
On accept - help

### ISSUE THREAD

**Issue by luisgomes2701** [uNmAnNeR/imaskjs#865]
I am implementing a monetary mask where it only accepts negative values.

When the user types in a number and that number does not have the negative sign, I add it.
But then the cursor doesn't take into account the addition of the - sign.

What is the best solution to reposition the cursor?

in the accept mask I have this:

if(Mask.masked.currentMask.unmaskedValue > 0){
   Mask.typedValue = (parseInt(Mask.unmaskedValue) * -1).toString(); 
   Mask.updateCursor(Mask.cursorPos + 1);
}

it does everything you want, except put the cursor in the right place.
From what I saw, the oninput event is not taking into account the new value but only the typed number

**Comment by uNmAnNeR** [comment]
@luisgomes2701 hi, some magic is here: https://codesandbox.io/s/react-imask-input-box-masks-forked-nlstpr?file=/src/index.js

but i think if number mask can accept only negative values then it should add `-` automatically. Will add in v7.0.0
