### ISSUE TITLE
react-imask alpha published on npm with latest-tag

### ISSUE THREAD

**Issue by BC-M** [uNmAnNeR/imaskjs#867]
**Describe the bug**

The react-imask `7.0.0-alpha2` has been made available on npm with the "latest" tag. 

See [npm-dist-tag#purpose](https://docs.npmjs.com/cli/v9/commands/npm-dist-tag#purpose):

> By default, the latest tag is used by npm to identify the current version of a package, and npm install <pkg> (without any @<version> or @<tag> specifier) installs the latest tag. Typically, projects only use the latest tag for stable release versions, and use other tags for unstable versions such as prereleases.

**Expected behavior**

Alpha versions should be deployed with the alpha tag instead of the latest tag.

**Comment by uNmAnNeR** [comment]
@BC-M thanks. alpha is deployed now with `next` tag.

**Comment by BC-M** [comment]
@uNmAnNeR Alpha is deployed as "latest" again. 😞 

![Bildschirmfoto 2023-07-06 um 12 56 52](https://github.com/uNmAnNeR/imaskjs/assets/40334865/01724fa1-6027-4de0-8f09-f0cdcc1973d4)

**Comment by uNmAnNeR** [comment]
@BC-M don't worry that's different :) just tired of writing documentation but features/tests are fine. So not a mistake
