### ISSUE TITLE
error react-imask negative number

### ISSUE THREAD

**Issue by hieunv1** [uNmAnNeR/imaskjs#868]
**Describe the bug**
mask: Number,
            thousandsSeparator: ',',
            scale: 2,
            signed: true,
            radix: '.',
            mapToRadix: ['.'],
            min: -100000000,
when I input -, value auto is -0, 

**To Reproduce**

**Environment:**

 - IMask version :"react-imask": "^6.6.2",

**Additional context**

**Comment by uNmAnNeR** [comment]
@hieunv1 hi, i can't reproduce it: https://codesandbox.io/s/chakra-ui-react-imask-react-hook-form-forked-9ql8v8?file=/src/App.tsx

please provide a link and reopen
