### ISSUE TITLE
Error when importing the v7 project as ESM module

### ISSUE THREAD

**Issue by farhan-syah** [uNmAnNeR/imaskjs#869]
**Describe the bug**
When importing the package  as ESM module, I received this error:

```
failed to import "imask/esm" 
-> imask@7.0.0-alpha.3/node_modules/imask/esm/index.js:1
-> export { default as InputMask } from './controls/input.js
-> SyntaxError: Unexpected token 'export'
```

**To Reproduce**

Import the file, such as:

```js
Import IMask from 'imask';
import { imask } from '@imask/svelte';
```

**Environment:**

 - IMask version : 7.0.0-alpha.3

**Suggested solution**

If the package is targetting to be a pure ESM, `"type": "module"` should be added to the package.json. 

Reference:
- Pure ESM package : [https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c](url)
- Official ESM guide : [https://www.typescriptlang.org/docs/handbook/esm-node.html#type-in-packagejson-and-new-extensions](url)

**Comment by uNmAnNeR** [comment]
@farhan-syah hi, i tried to reproduce it but without success.
it's actually not a pure esm module. Both `@imask/svelte` and `imask` packages contain stuff to support esm and non-esm environments in `package.json` like:
```
  "main": "dist/svelte-imask.js",
  "module": "esm/index.js",
```
You are referring to the documentation for `nodejs` but `imask` is primarily for browsers and setting `type: module` sometimes breaks existing build pipelines so this property was not intentionally set. IMask provides `umd` build and can be used in non-esm mode.

i am open if you have any other points to discuss.

**Comment by farhan-syah** [comment]
> @farhan-syah were you able to find a workaround?

Yes. I just create a fork from the original, add the "type": "module" and link to my fork instead of the original package.
