### ISSUE TITLE
custom validation

### ISSUE THREAD

**Issue by y-nk** [uNmAnNeR/imaskjs#87]
It would be very helpful to have a function to add custom validation : 

```
{
  mask: Date,
  validate(date) {
    return date.getDay() !== 0 // we don't validate sundays
  }
}
```

What do you think ?

**Comment by uNmAnNeR** [comment]
@y-nk  It already there: `validate (stringValue, masked)`.
To get date: `masked.date` (returns `null` if not complete).

**Comment by y-nk** [comment]
@uNmAnNeR thanks
