### ISSUE TITLE
Dynamic Mask dispatch has wrong value

### ISSUE THREAD

**Issue by DywiTom** [uNmAnNeR/imaskjs#870]
**Describe the bug**

When removing the first 0 of 0,00 the dispatch function returns the wrong value and selects the wrong mask

See [Stackblitz](https://stackblitz.com/edit/dywi-imask-myx1j5?file=src%2Fapp%2Fapp.component.ts) and gif:

![Animation (0)](https://github.com/uNmAnNeR/imaskjs/assets/87300270/bfe35cd9-64fc-47e4-9dd6-4aee81f4bd26)

**To Reproduce**
[Stackblitz](https://stackblitz.com/edit/dywi-imask-myx1j5?file=src%2Fapp%2Fapp.component.ts)

**Expected behavior**

**Comment by uNmAnNeR** [comment]
@DywiTom `masked.value` does not contain the entire value on the dispatch step. You have also check `tail`. Check https://stackblitz.com/edit/dywi-imask-r3jm4g?file=src%2Fapp%2Fapp.component.ts

but seems like you don't need dispatch at all https://stackblitz.com/edit/dywi-imask-jmfyuj?file=src%2Fapp%2Fapp.component.ts

**Comment by DywiTom** [comment]
@uNmAnNeR i thought about that same solution, but i am not sure how to solve that without creating an new object for every input. I can't write "mask: NullableMaskedDynamic", i need to declare "d %" there? MMy goal is to have a percent symbol only when there is a number, and the value should be a number or null.

If you can help me, I will definitely treat you to a big coffee! Greetings! You rock.

**Comment by uNmAnNeR** [comment]
@DywiTom you can try something like this https://stackblitz.com/edit/dywi-imask-3midae?file=src%2Fapp%2Fapp.component.ts

**Comment by uNmAnNeR** [comment]
can be done in 7.1.0 via `expose`:
https://stackblitz.com/edit/dywi-imask-wbgxnw?file=src%2Fapp%2Fapp.component.ts

**Comment by DywiTom** [comment]
@uNmAnNeR nice feature, awesome! But don't understand why the first expose replace the value of the first mask (empty string)?
