### ISSUE TITLE
Digit pattern mask allows non-digit entries

### ISSUE THREAD

**Issue by sebestenyb** [uNmAnNeR/imaskjs#872]
The pattern mask of `mask:'0000'` allows me to enter `+`, `-`, and `.` signs. 
After entering one of these the input allows entering a number with any length, longer than 4 digits.

_Originally posted by @sebestenyb in https://github.com/uNmAnNeR/imaskjs/discussions/734#discussioncomment-6192394_

**Comment by uNmAnNeR** [comment]
@sebestenyb I cannot reproduce it. Please provide a link to run an example. Thanks

**Comment by sebestenyb** [comment]
Sorry, I am working on it, it is somewhat challenging to strip it down.
But I've noticed that our input type is set to `number`. If I change it to `text`, it works as it should.

**Comment by uNmAnNeR** [comment]
@sebestenyb yes, only `text` type is working. So i close the issue
