### ISSUE TITLE
Pattern mask with number mask display wrong initial value

### ISSUE THREAD

**Issue by matthias-dev** [uNmAnNeR/imaskjs#873]
**Describe the bug**
Using Number IMask within Pattern Mask within Angular App and initial values are displayed in wrong way. initialValue of 12.3 is displayed with "123,000" instead of "12,300".
I thinks it's the same bug as [#866](https://github.com/uNmAnNeR/imaskjs/issues/866) but within pattern mask.

**To Reproduce**
Example on [StackBlitz](https://stackblitz.com/edit/stackblitz-starters-notfes?file=src%2Fmain.ts)

**Expected behavior**
initial number value of 12.3 should be converted to "12,300"

**Environment:**
 - Windows 10
 - chrome
 - imask 6.6.3
 - angular 16.0.4

**Comment by uNmAnNeR** [comment]
Hi. It works correctly. Check https://github.com/uNmAnNeR/imaskjs/issues/384
A workaround for this is to subclass pattern mask and overwrite get/set for typedValue to proxy it to number block inside.

**Comment by cmpsleo** [comment]
Hi, @uNmAnNeR could you show me a given example with react and imask hook related to this issue?

I forked your example with Chakra-ui and changed to my scenario on [codesandbox here](https://codesandbox.io/s/chakra-ui-react-imask-react-hook-form-forked-vx3358?file=/src/App.tsx).

**Comment by uNmAnNeR** [comment]
@cmpsleo hi, you can get some idea in examples from https://github.com/uNmAnNeR/imaskjs/issues/870

**Comment by matthias-dev** [comment]
Subclassing and overwrite typedValue works, thanks for that.

But I think that this use case is one of the first reasons for using a masking library, that should work out of the box, without such workaround. Putting a quantity unit at the end of a numeric value like ("12,34 €" or "47,111 kg") is a very common tasks.
Maybe there is a much simpler solution for this instead of using a pattern mask?
`mask: 'num €',
    blocks: {
      num: ...
    }`

**Comment by uNmAnNeR** [comment]
@matthias-dev yes there should be an easier way to do it. This issue addresses to the same problem https://github.com/uNmAnNeR/imaskjs/issues/384
but i have no solution for now

**Comment by uNmAnNeR** [comment]
since 7.1.0 `expose` option can be used to expose values from blocks/dynamic array

**Comment by matthias-dev** [comment]
Thanks @uNmAnNeR, it works. Now I can remove my custom mask.
