### ISSUE TITLE
Type RegExp in Angular

### ISSUE THREAD

**Issue by DywiTom** [uNmAnNeR/imaskjs#874]
**Describe the bug**
It's not possible to set Type 'RegExp' to mask within the interface IMask.AllMaskedOptions
and IMask.MaskedRegExpOptions does not exists.
I am not sure how to get RegExp in Angular working.

**To Reproduce**
[Stackblitz](https://stackblitz.com/edit/dywi-imask-jcu3pb?file=src%2Fapp%2Fapp.component.ts)

**Expected behavior**
- IMask.MaskedRegExpOptions should exist
- IMask.AllMaskedOptions should accept RegExp
- Maybe some docs to that (see #366),
i think this issue is not solved yet

**Environment:**
See stackblitz

Thanks!

**Comment by uNmAnNeR** [comment]
@DywiTom hi, try v7.0. Should be fixed there.

**Comment by DywiTom** [comment]
@uNmAnNeR thanks for your answer, i tried it. but i got this error:

`The entrypoint for 'angular-imask' could not successfully be resolved. The file '/turbo_modules/angular-imask@7.0.0-alpha.5/index.js' does not exist. Please log an issue with the package author or check for an updated version of the package.`

Angular 16.1.1

**Comment by uNmAnNeR** [comment]
@DywiTom strange thing. something went wrong on release probably because of https://github.com/lerna/lerna/issues/3731
v7.0 released and fixed now
