### ISSUE TITLE
Doc Update

### ISSUE THREAD

**Issue by tiarebalbi** [uNmAnNeR/imaskjs#877]
Since the return of the method resolve was removed in version 7.0.0, what's the alternative? Doc still showing old usage.

https://github.com/uNmAnNeR/imaskjs/blob/68ebe8d4b29a5665e88cd3fa10f4ac34a7d3121b/docs/guide.html#L142

**Comment by uNmAnNeR** [comment]
Thanks for reporting. The alternative is to get value property after `resolve`:
```typescript
masked.resolve('71234567890');
var maskedValue = masked.value;
``` 
I will update guide soon.
