### ISSUE TITLE
Mask character definition type does not accept Regexp

### ISSUE THREAD

**Issue by rabuckley** [uNmAnNeR/imaskjs#878]
**To Reproduce**

Attempting to assign a Regex definition gives type error `Type 'RegExp' is not assignable to type 'FactoryOpts'`.

This example from the docs fails to compile:

```ts
var zipMask = IMask(element, {
  mask: '#00000',
  definitions: {
    // <any single char>: <same type as mask (RegExp, Function, etc.)>
    // defaults are '0', 'a', '*'
    '#': /[1-6]/
  }
});
```

[Stackblitz reproduction](https://stackblitz.com/edit/typescript-3qcnej?file=index.ts)

**Expected behavior**

Should work? Or if deliberate breaking change in 7 then documentation needs updating at https://imask.js.org/guide.html#masked-pattern

**Environment:**
 - IMask version: 7.0.0

**Comment by CallOBock** [comment]
Same error. Need help
