### ISSUE TITLE
Specify special values in date inputmask

### ISSUE THREAD

**Issue by be-ndee** [uNmAnNeR/imaskjs#88]
Hi,
I have the following setup:

```
var momentFormat = 'DD.MM.YYYY';
var momentMask = new IMask(document.getElementById('datePickerInput'), {
    mask: Date,
    pattern: momentFormat,
    lazy: false,
    min: new Date(0, 0, 0),
    max: new Date(9999, 12, 12),

    format: function (date) {
        return moment(date).format(momentFormat);
    },
    parse: function (str) {
        return moment(str, momentFormat);
    },

    groups: {
        YYYY: new IMask.MaskedPattern.Group.Range([1, 9999]),
        MM: new IMask.MaskedPattern.Group.Range([1, 12]),
        DD: new IMask.MaskedPattern.Group.Range([1, 31]),
    }
});
```

Now I can enter any date between `01.01.1900` and `31.12.9999`. Is there a possibility to accept something like `??.03.2013` or `??.03.????`? So that some blocks in the date have a specified special format? So that I can say in my configuration for the day the numbers 1 to 31 are allowed and the concrete value `??`? Is this understandable and is it possible?

>

**Comment by uNmAnNeR** [comment]
@be-ndee you can configure `groups` option to set specific ranges.
