### ISSUE TITLE
useMask onAccept gets triggered on mount

### ISSUE THREAD

**Issue by srowe0091** [uNmAnNeR/imaskjs#881]
**Describe the bug**
It seems the onAccept in `useMask` gets triggered as soon as the hook gets mounted.

**Expected behavior**
onAccept to not fire when mounted

**Additional context**
I dont have the onChange event handler attached to the input, could the `ref` be triggering something?

**Comment by uNmAnNeR** [comment]
@srowe0091 yes, onAccept is called whenever the hook is initialized.
Why does it cause some problems?
How do you think it should work? Note that the value may change when the mask is applied.

**Comment by srowe0091** [comment]
@uNmAnNeR thanks for the reply. This is causing an issue for fields that are required. Basically, since the onChange of the field is passed into the onAccept, and since the onAccept triggers on the mount, it will run through the form validation and since its a required field and on mount the onAccept value is just an empty string, the user will be immediately presented with an error on the page load when the user hasn't even touched the field.

**Comment by uNmAnNeR** [comment]
@srowe0091 `onAccept` callback has `event` as 3rd parameter. You can check if it's `undefined` then it's initialization step. Does it work for you?

**Comment by srowe0091** [comment]
@uNmAnNeR that does work! thank you so much!
