### ISSUE TITLE
maintain group size when user deletes a char

### ISSUE THREAD

**Issue by y-nk** [uNmAnNeR/imaskjs#89]
example with a date picker : 

with mask defined as something like `yyyy/MM/dd`, when a user types, it's perfect.
I can do "2018/08/30" with no problem. But if i place the caret on `2018` and press `backspace` to delete the `1`, the input result is : `2080/8X/XX`, but it should be : `20X8/08/30`

Any direction on how to achieve that ?

**Comment by uNmAnNeR** [comment]
@y-nk to set max date? Or you don't want to restrict year, just keep remain characters?

**Comment by y-nk** [comment]
@uNmAnNeR yeah, i just want to keep the remain characters, so the "user input" characters don't move from one group to an other. if you press backspace.

**Comment by uNmAnNeR** [comment]
@y-nk use backquote to prevent characters shifting back: ``yyyy/`MM/`dd``

**Comment by y-nk** [comment]
@uNmAnNeR thanks!
