### ISSUE TITLE
Daterange issue after upgrade to version 7

### ISSUE THREAD

**Issue by smellai** [uNmAnNeR/imaskjs#896]
**Describe the bug**
After upgrade to version 7 my date range picker doesn't work anymore, also some type checks issues in the codesandbox

**To Reproduce**
[CodeSandbox](https://codesandbox.io/s/compassionate-poincare-nfv3hm).
Example works with version 6, it doesn't with version 7.

**Expected behavior**
accept string as default value, change the value programmatically on button click

**Environment:**
 - OS: Macos
 - Browser chrome

 - IMask version 7
 - Framework/plugin version: React 17.0.2

**Comment by uNmAnNeR** [comment]
the bug actually was fixed.
You need to use value/setValue and not typedValue/setTypedValue in this example.
If you do not provide format/parse callbacks then `typedValue` works just like `unmaskedValue`.
Before 7.0 it worked like `value` and it's not correct.

**Comment by smg99** [comment]
@uNmAnNeR I am also facing an identical issue. Upgrading from 6.0.3 to 7.0.1 , no code change except version upgrade. any hint?
<img width="597" alt="image" src="https://github.com/uNmAnNeR/imaskjs/assets/7676130/6ca95292-e8d1-47cf-bce1-66f39ac7350c">
