### ISSUE TITLE
useIMask with `Number` mask initializes input with "0"

### ISSUE THREAD

**Issue by jmcolella** [uNmAnNeR/imaskjs#897]
**Describe the bug**
When using the `useIMask` hook and providing the `Number` constructor as the `mask` option, the controlled input is initialized with a value of `0` if no defaultValue is provided.

This may be due to the change introduced [here](https://github.com/uNmAnNeR/imaskjs/commit/0b9690a6fc01164b95f3514e9df0a7a836aac1d7#diff-3bb9414f6bda43bfe752aa64c6cc772ba707438812206f5ba1e5bcae6814506eR63), which calls the `_onAccept` function when initializing the `useIMask` hook. 

**To Reproduce**
[CodeSandbox](https://codesandbox.io/p/sandbox/wonderful-heyrovsky-4v99hm?file=%2Fsrc%2FApp.tsx) 

1. Create a component with the `useIMask` hook with the following options: `{ mask: Number }`
2. Attach the returned `ref` to an `input` element
3. Observe the rendered `input` element with a value of `0`

**Expected behavior**
When no default value is given, the `useIMask` hook should not create a default value of `0` for a `Number` mask.

**Environment:**
 - OS: MacOS 12.6.5
 - Browser Chrome
 - Version 114.0.5735.198
 - IMask version 7.0.1

**Additional context**
N/A

**Comment by srowe0091** [comment]
I would love for this to get resolved as I just ran into this today. If there was a possible way to just create the mask manually, I'd be okay with that. Basically allowing any number of integers with then optional decimals would be the mask

**Comment by c01nd01r** [comment]
An alternative solution would be to use a regular expression.

All digits:
```ts
  const { ref } = useIMask({
    mask: /^[0-9]*$/,
  });
```
Without leading zeros:
```ts
  const { ref } = useIMask({
    mask: /^[1-9][0-9]*$/,
  });
```

**Comment by milosmil183** [comment]
I'm not sure why this is marked as resolved. I'm still seeing the same issue on my end.

**Comment by milosmil183** [comment]
Sorry, it seems there was a new version published to fix the issue, I will check again.

**Comment by srsad** [comment]
Unfortunately, the problem is still there

**Comment by cameronkloot** [comment]
I'm using the useIMask hook for a custom input component. This is what I used to get rid of the initial zero: 

```
useEffect(() => {
    if (!value) {
      setTypedValue('' as any) // clears 0 initial value
    }
  }, [])
```

With `value` being the initial value passed to the custom input and used as `defaultTypedValue`.

**Comment by ggomarighetti** [comment]
I have exactly the opposite problem, in my use case 0 is a valid value and when I pass it as defaultTypedValue, the input is blank, it is not until the user manually types “'0” that the value is set.
