### ISSUE TITLE
Date mask demo not working in guide page

### ISSUE THREAD

**Issue by kouts** [uNmAnNeR/imaskjs#90]
Date mask demo as shown in this guide page here: [https://unmanner.github.io/imaskjs/guide.html#date](https://unmanner.github.io/imaskjs/guide.html#date)
does not work correctly.

**Comment by uNmAnNeR** [comment]
@kouts what do you mean? Please give more details

**Comment by kouts** [comment]
My mistake, it works alright.
I didn't realize there is a restriction in place.
