### ISSUE TITLE
Show full mask only on focus

### ISSUE THREAD

**Issue by dakota-kallas** [uNmAnNeR/imaskjs#900]
### **What problem you are trying to solve?**
I want the mask of my input to only show when I am focused within that input control.

### **Describe the solution you'd like**
It would be nice if you added a property to the mask that allowed it to show on focus, maybe even another option for showing on hover as well (that could be useful). It would also be nice if the cursor loaded before the mask is added to the input when focused to avoid the cursor having to jump to the beginning.

Something like `showOnFocus` and `showOnHover` for mask properties would be great!

### **Describe alternatives you've considered**
In order to do this currently, I need to add an even listener that will update the mask options lazy value on focus and focus out. Along with that, the cursor will jump from the end to the beginning when I do this. 
Here is a codepen link to what I am talking about: https://codepen.io/dakota-kallas/pen/vYQxeJb?editors=1010

**Comment by uNmAnNeR** [comment]
hi, thanks for reporting.
I try to keep mask abstract from native input as much as possible. I am definitely not ready to take responsibility for focusing/styling etc. kind of things. Your example seems good enough to me. If you need to set the cursor somewhere in the input after updating options it's really easy to do either via `mask.alignCursor` or native `input.select`. 🙏
