### ISSUE TITLE
Static Characters In Optional Section

### ISSUE THREAD

**Issue by chrisbarton126** [uNmAnNeR/imaskjs#901]
**Describe the bug**
Using static characters within an optional section results in the characters always being present in the output.

**To Reproduce**
Define a pattern with an optional section that contains static characters:

```
var im = IMask(document.getElementById('input'), {
   mask: "000[-000]"
});
```

https://codesandbox.io/s/unruffled-wood-pn397q

**Expected behavior**
Given the mask above, I would have expected the hyphen character to only be included if the user went beyond entering the initial 3 digits. Instead, the input initially shows "___-", and after typing the first 3 digits the underlying value is "123-" despite the hyphen being optional.

**Environment:**
 - OS: Windows 10
 - Browser Chrome
 - Version 114.0.5735.199
 - IMask version: 7.1.0-alpha.0

**Additional context**
This could just be a misunderstanding on my part of how the pattern system works, if so then any guidance towards achieving the goal would be appreciated.

**Comment by uNmAnNeR** [comment]
hi, for now you can use dynamic mask:
```js
{
  mask: [
    { mask: '000' },
    { mask: '000-000' },
  ]
}
```

**Comment by chrisbarton126** [comment]
@uNmAnNeR thanks for the response, I've also managed to toy with the `eager` property, which appears to do the trick when the optional content directly follows a static character. 

In my use case, I'm allowing external users to enter a pattern that is then enforced on the front-end application, so unfortunately providing an array of masks would not be ideal for the users doing the configuration.

However, I do have another query which is about a method that could be used to verify whether an input value matches the pattern mask or not? When specifying a pattern such as `000{-0000}` the input field allows input of just `12` and doesn't show there being any problem, even though it doesn't adhere to the mask pattern that's been specified. Is there a method available that could be used to perform manual validation, where we pass `12` in, and it gives a boolean indicating whether it matches the pattern or not?

Thanks!

**Comment by uNmAnNeR** [comment]
@chrisbarton126
```js
var im = IMask(document.getElementById('input'), {
   mask: "000[-000]"
}).on('complete', () => 'completed!');

// OR

im.masked.isComplete
```

**Comment by uNmAnNeR** [comment]
hope this helped
