### ISSUE TITLE
vue-imask 7.1.0 has some dependencies to imask 7.1.0-alpha.2

### ISSUE THREAD

**Issue by tbl0605** [uNmAnNeR/imaskjs#905]
Hi,
after upgrading to vue-imask 7.1.0, I see some dependencies to imask 7.1.0-alpha.2 in my `package-lock.json` file.

Culprit seems to be [this line](https://github.com/uNmAnNeR/imaskjs/blob/1930b74557d1c82055fb3f1ce09b952d66af237d/packages/vue-imask/package.json#L39C16-L39C29) in the package.json from the vue-imask package

**Comment by uNmAnNeR** [comment]
@tbl0605 hi, thanks for quick feedback. v7.1.1 is released
