### ISSUE TITLE
"expose" is missing in interface MaskedDynamicOptions

### ISSUE THREAD

**Issue by DywiTom** [uNmAnNeR/imaskjs#907]
**Describe the bug**

My code:

```
export const percentMask: MaskedDynamicOptions = {
  mask: [
    { mask: '' },
    {
      mask: 'd %',
      lazy: false,
      expose: true,
      blocks: {
        d: {
          mask: Number,
          expose: true,
          scale: 2,
          thousandsSeparator: '.',
          radix: ',',
          padFractionalZeros: true,
          normalizeZeros: true,
          overwrite: false,
          min: -9999999999,
          max: 9999999999
        }
      }
    }
  ]
}
```

`error TS2322: Type '{ mask: string; lazy: false; expose: 
true; blocks: { d: { mask: NumberConstructor; expose: true; scale: number; thousandsSeparator: string; radix: string; padFractionalZeros: true; normalizeZeros: true; overwrite: false; min: number; max: number; }; }; }' is not assignable to type 'FactoryArg'.
  Object literal may only specify known properties, and 'expose' does not exist in type 'RegExp | 
DateConstructor | NumberConstructor | DynamicMaskType | Masked<any> | FactoryOpts | ((value: string, masked: Masked<...>) => boolean)'.`

**To Reproduce**

**Expected behavior**
No error

**Environment:**
 - imask v7.1.2
 - angular-imask v7.1.2

**Additional context**

**Comment by uNmAnNeR** [comment]
@DywiTom i can't reproduce the issue:
https://stackblitz.com/edit/dywi-imask-wbgxnw?file=src%2Fapp%2Fapp.component.ts

**Comment by DywiTom** [comment]
Ah i see sorry, there was a problem with NullableMaskedNumber.... thanks.

close
