### ISSUE TITLE
angular-imask: Can't bind to 'imask' since it isn't a known property of 'input'

### ISSUE THREAD

**Issue by mikelgo** [uNmAnNeR/imaskjs#908]
**Describe the bug**
Compilation fails due to the error `Can't bind to 'imask' since it isn't a known property of 'input'`

**To Reproduce**
create a new Angular Project with v15.+ and `imask` and `angular-imask` with version 7.x.x.

You can use [this repo](https://github.com/mikelgo/angular-imask-repro) for a reproduction  
Run `git clone`, `npm i` and `ng serve`
you should get the compilation error

**Expected behavior**
No compilation error

**Additional context**
When expecting the installed package and e.g. looking at `IMaskDirective`:
<img width="1367" alt="image" src="https://github.com/uNmAnNeR/imaskjs/assets/29756792/9d68db94-3630-4308-8605-e71b6309f131">

**Comment by uNmAnNeR** [comment]
It works fine on v16. Angular is known for breaking interfaces in almost every major version. I am not willing to support them all so just support the latest. It's easy to fix but hard to maintain. I probably can't help you more than just to suggest you to upgrade Angular to v16.

**Comment by mikelgo** [comment]
I can totally understand your point. 
Just out of curiosity, do you remember what did break with angular 15?

**Comment by uNmAnNeR** [comment]
@mikelgo as far as i remember nothing in the plugin was changed. It had stopped working in v16, i upgraded Angular + ng-packagr, rebuilt and that's it.
