### ISSUE TITLE
Issue between mapToRadix and radix

### ISSUE THREAD

**Issue by ooigheehong** [uNmAnNeR/imaskjs#91]
When mapToRadix = '.' , radix char = '.' , scale = 2
It able to enter four 0 => 0 000

When mapToRadix = '' , radix char = '.' , scale = 2
It able to enter four 0 => 0 000

When mapToRadix = '.' , radix char = ',' , scale = 2
It able to enter one 0 which is in the correct way => 0

Is it the expected behavior?

**Comment by uNmAnNeR** [comment]
@ooigheehong `mapToRadix` is array

**Comment by ooigheehong** [comment]
@uNmAnNeR evenif I set it into array, it still the same

**Comment by ooigheehong** [comment]
![imaskissue](https://user-images.githubusercontent.com/23492569/44977471-b6b5eb00-af9a-11e8-99a4-498c815ae537.gif)

**Comment by uNmAnNeR** [comment]
seems strange :) thanks for details
