### ISSUE TITLE
IMask is exposed as a global in window

### ISSUE THREAD

**Issue by kouts** [uNmAnNeR/imaskjs#93]
IMask is exposed as a global inside the ```window``` object if it is imported as an ES2015 module.
So ```import IMask from 'imask';``` results in a ```window.IMask``` being exposed.

**Comment by uNmAnNeR** [comment]
@kouts yes, but why this is an issue? in what cases?

**Comment by kouts** [comment]
When imported as a module I think that the expected behavior would be that ```IMask``` is available in the
context it was imported. That's one of the points of using modules I think.

**Comment by uNmAnNeR** [comment]
@kouts yes, it is. But currently mask resolves circular dependencies this way. If there will be some issues with that behavior i might do something but i dont see any problems so far. If application use modules then it does not care about globals at all.
