### ISSUE TITLE
FactoryStaticOpts type doesn't accept many of valid masks

### ISSUE THREAD

**Issue by aktanoff** [uNmAnNeR/imaskjs#932]
**Describe the bug**
If using FactoryStaticOpts type to describe mask config options, then at least MaskedRange, MaskedEnum masks getting to be unassignable to this type.

code example:
```
const maskOptions: FactoryStaticOpts = {
  mask: "Ple\\ase fill ye\\ar 19YY, month MM \\and v\\alue VL",
  lazy: false, // make placeholder always visible

  blocks: {
    YY: {
      mask: "00"
    },

    MM: {
      mask: IMask.MaskedRange,
      from: 1,
      to: 12
    },

    VL: {
      mask: IMask.MaskedEnum,
      enum: ["TV", "HD", "VR"]
    }
  }
};
```

**To Reproduce**
Example of this typization bug:
https://codesandbox.io/s/adoring-visvesvaraya-2tpgl3?file=/src/App.tsx

**Expected behavior**
There should be some universal type to create constants that are assignable to be used in createMask

**Environment:**
 - OS: MacOS 13.4
 - Browser doesn't matter
 - Version doesn't matter
 - IMask version 7.1.3
 - Framework/plugin version React 18.2.0

**Comment by uNmAnNeR** [comment]
fixed in 882e73be9ca277bd0a826111eaf6f18649309536
