### ISSUE TITLE
auto unmask feature !

### ISSUE THREAD

**Issue by baxing** [uNmAnNeR/imaskjs#934]
**What problem you are trying to solve?**
Now, I try to unmask by use : mask.unmaskedValue manually.
Because if I use Number mask with thousandsSeparator, I can't get value directly form input value.
So if use add the feature about : Automatically unmask the value when retrieved, It will be a very good thing to use.
 
**Describe the solution you'd like**
May be add the property such "autoUnmask" to auto unmask the value wheh get the value form input but still display masked on input follow the value is 1234.56, in the input still show 1,234.56 (in case thousandsSeparator is ',') and if get value from this input, I will get the value 1234.56 correctly(is not 1,234.56). This is the meaning of the autoUnmask I mentioned.

Thanks in advance if you consider adding this feature.

**Comment by uNmAnNeR** [comment]
it's the same value `input.value` and what is shown in input. Autounmasking in other libs related to monkey patching which is bad idea. I can't do it sorry. But you can do it by yourself if you want.
