### ISSUE TITLE
copy/paste not working properly

### ISSUE THREAD

**Issue by maksimgcdev** [uNmAnNeR/imaskjs#937]
**Describe the bug**
when pasting copied value, wrong value is pasted

**To Reproduce**

\<IMaskInput mask="ABC1-0000"\/\>
mask="ABC1-0000"

1. enter value: ABC1-2345
2. select all (ctrl-A)
3. copy selection (ctrl-c)
4. select all for replace (ctrl-A)
5. paste (ctrl-v)

**Expected behavior**
expected value that we copied: ABC1-2345
but we get wrong value: ABC1-1234

**Environment:**
 - Browser chrome
 - Example sundbox: https://codesandbox.io/s/cool-hertz-rg9tkw?file=/src/App.js:229-260

**Comment by Leland** [comment]
Your mask right now on that Sandbox is:

`<IMaskInput mask="АДВ1-0000" />`

Which is noticeably different from:

`<IMaskInput mask="ABC1-0000"/>`

**Comment by maksimgcdev** [comment]
@Leland I corrected the sandbox. But it doesn't matter since this error is the same with 

`<IMaskInput mask="АДВ1-0000" />`

**Comment by smg99** [comment]
@maksimgcdev sandbox seems to be working now (Tested on Mac Chrome), I have identical situation for vue. did you found any solution for your question above?

**Comment by uNmAnNeR** [comment]
it uses 6.4.3. I updated it to 7x and it works fine
