### ISSUE TITLE
Max Length stopped Woking after version 7.0.0

### ISSUE THREAD

**Issue by GoncaloNevesCorreia** [uNmAnNeR/imaskjs#938]
**Describe the bug**
The property 'maxLength' does not take any effect in the mask.

**To Reproduce**
Im using NextJS with MUI and react-imask (IMaskInput) for the TextFields. It was working fine in version 6.6.3 and the prop maxLength stopped taking effect after version 7.0.0.
I have confirmed that if i roll back to version 6.6.3 it works as expected.

**Expected behavior**
I should limit the string size to a specific length, like it was doing in version 6.6.3

**Environment:**
 - OS: Debian GNU/Linux 11
 - Browser Chrome
 - Version 116.0.5845.111
 - IMask version 7.1.3
 - Framework/plugin React / Next

**Comment by zhyph** [comment]
I'm having the same problem, it looks like that using “maxlength” instead of “maxLength” does work, but it keeps warning me on the console about this. (“Invalid DOM property `maxlength`. Did you mean `maxLength`?”)
