### ISSUE TITLE
Where is the old version?

### ISSUE THREAD

**Issue by nicrf** [uNmAnNeR/imaskjs#94]
Hi,

Now at 4.0.0, I got many problem, where I can find the old version?

**Comment by uNmAnNeR** [comment]
Hi!
https://unpkg.com/imask@3.4.0/dist/imask.js ?
What problems did you get?

**Comment by nicrf** [comment]
Hi,

Thank you, I got problem with the new enum mask, the old way was not compatible. I generate a list of enum into the script with my server from database.

**Comment by uNmAnNeR** [comment]
Hm, ok. I thought nobody uses it... :)
Btw, v4.0.0 goes more flexable way, try moving to it and feel free to open an issue if something will go wrong.
