### ISSUE TITLE
Undo/Redo not working

### ISSUE THREAD

**Issue by Leland** [uNmAnNeR/imaskjs#942]
**Describe the bug**
When I undo (e.g. via <kbd>Cmd</kbd>/<kbd>Ctrl</kbd>-<kbd>Z</kbd>), I expect something to happen.

Instead, nothing happens.

**To Reproduce**
1. Visit https://imask.js.org/
2. Focus "Pattern (Secure)", and enter some text
3. Unfocus the field (e.g. by pressing <kbd>Tab</kbd>) and undo

**Expected behavior**
The change would be undone. Contrast to behavior of an unscripted input element: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text

**Environment:**
 - OS: macOS
 - Browser: Chrome
 - Version: 116.0.5845.140
 - IMask version: N/A
 - Framework/plugin version if used: N/A

**Additional context**

This bug is blocking the ability to test _redoing_ changes, so this bug is also for that. That is – undoing something and then redoing it (on macOS this is <kbd>Cmd</kbd>-<kbd>Shift</kbd>-<kbd>Z</kbd>)

**Comment by uNmAnNeR** [comment]
i did what you described:
- focus input (`Name (4 to 8 characters)`)
- type `asd`
- press `Tab`
- undo

nothing happened (Mac/Chrome).

I don't think it's a mask issue, but a web standards issue. Some time ago I tried to handle undo/redo and encountered different issues in different browsers. So probably this never be fixed.

**Comment by Leland** [comment]
Interesting. Yeah, I just looked at around 10 different masking libraries and _all_ of them exhibit a similar problem.
