### ISSUE TITLE
Property 'lazy' does not exist on type 'ReactMaskOpts'.

### ISSUE THREAD

**Issue by olivier-drieux** [uNmAnNeR/imaskjs#944]
**Describe the bug**
I'm attempting to create a component that should, by default, offer the 'lazy' option for the useIMask hook. However, I'm encountering difficulties in making this work. While I can successfully pass the 'lazy' prop to the Mask component from my App.tsx file, I'm struggling to extract this 'lazy' prop from the Mask component's props

![Capture d’écran 2023-09-08 à 15 48 43](https://github.com/uNmAnNeR/imaskjs/assets/27553827/ce0588cc-9b7d-4728-a245-e0815a1021ee)

**To Reproduce**
https://codesandbox.io/s/react-typescript-forked-ds4zz7?file=/src/Mask.tsx
Go into Mask.tsx component and the extracted "lazy" props shows a TypeScript error.

**Expected behavior**
The 'lazy' prop can be successfully extracted from the Mask component's props without any TypeScript errors.

**Environment:**
 - IMask 7.1.3
 - React 18.0.2

**Comment by uNmAnNeR** [comment]
`lazy` is available only for pattern mask so you need to use `React.FC<MaskedPatternOptions>`
