### ISSUE TITLE
Send custom props to IMaskMixin using React and Typescript

### ISSUE THREAD

**Issue by JC-Tirado-86** [uNmAnNeR/imaskjs#946]
**Describe the bug**
I am extending a custom input using IMaskMixin but I need to send a custom prop and haven't be able to do it.

![custom prop](https://github.com/uNmAnNeR/imaskjs/assets/31074467/28beee2c-dfe8-4bf5-8d30-9346155bb585)

I know this was already asked and answered here https://github.com/uNmAnNeR/imaskjs/issues/654#issuecomment-1245411575  but those solutions seem to be for an older version. I am currently using 'react-imask: 7.1.3'.

**Expected behavior**
IMaskMixin accept custom props

**Environment:**
 - IMask version - 'react-imask: 7.1.3'

**Comment by Natalia-Shell** [comment]
@JC-Tirado-86 any luck getting it to work? Also having a hard time with passing some props to IMaskMixin, not even the value.

**Comment by petrakow** [comment]
would be interested on a solution... 🤷

**Comment by bennyxguo** [comment]
This work for the latest version

```tsx
const MaskedDateInput = IMaskMixin<InputMask, { placeholder: string }>(
    ({ inputRef, ...props }) => (
      <Input
        {...props}
        label={t('users.form.lastName')}
        name="lastName"
        type="text"
        id="lastName"
        placeholder={props.placeholder}
        disabled={isLoading()}
        ref={inputRef as RefObject<HTMLInputElement>}
      />
    ),
  );
```
