### ISSUE TITLE
Autocomplete / Autofix with enum

### ISSUE THREAD

**Issue by Vincz** [uNmAnNeR/imaskjs#951]
**What problem you are trying to solve?**
I'd like to auto-complete and auto-fix an enum mask. For example, let's say I have an enum with "Jan", "Nov", "Dec".

**Describe the solution you'd like**
If the user input "N", it auto-complete to "Nov" as it's the only value matching.
Also, if the user input "n", it fixes it to "N" and... autocomplete the rest as above.

**Describe alternatives you've considered**
No alternative considered.

**Comment by uNmAnNeR** [comment]
Nice feature, but seems to me to be outside the scope of masking.

**Comment by uNmAnNeR** [comment]
case-insensitive comparison can be done using `matchValue` option, e.g.:
```js
matchValue: (estr, istr, matchFrom) => IMask.MaskedEnum.DEFAULTS.matchValue(estr.toLowerCase(), istr.toLowerCase(), matchFrom),
```

**Comment by joacub** [comment]
this fails when pasting, eliminates chars
