### ISSUE TITLE
CJS version of `react-imask` stopped working since 7.0.1

### ISSUE THREAD

**Issue by R-Oscar** [uNmAnNeR/imaskjs#956]
**Describe the bug**
CJS version of `react-imask` stopped working since 7.0.1

**To Reproduce**
I've made a basic setup with minimalistic webpack + babel configs in my [repo](https://github.com/R-Oscar/imask-cjs/tree/main)
Reproduction is simple: `npm i && npm run dev`
You'll see an error message in console:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'oneOfType')
    at eval (react-imask.js:17:38)
```
  If you rollback to version `7.0.1`, however, it works fine.

**Expected behavior**
It should be working using CJS bundle as well

**Additional context**
Obviously it has something to do with `type: "module"` added in package.json, but fix to this problem would be highly appreciated since there are still lots of people who use cjs in production

**Comment by smellai** [comment]
Even if I'm using it in ESM only project, this is causing issues with in the jest environment in my case

**Comment by shainegordon** [comment]
yeah, this is a problem, and I had to resort to they following "hack"

added this to `package.json` -> `scripts`

`"dependencies": "node ./other/change_imask_package_type.js"`

which does the following

```
const fs = require('fs')
const path = require('path')
​
// Define the directories where you want to locate and modify package.json files
const directories = ['node_modules/react-imask', 'node_modules/imask']
​
// Function to update "type" field to "commonjs"
function updatePackageJson(packageJsonPath) {
    try {
        const packageJson = require('../' + packageJsonPath)
        if (packageJson.type === 'module') {
            packageJson.type = 'commonjs'
            fs.writeFileSync(packageJsonPath, JSON.stringify(packageJson, null, 2))
            console.log(`Updated ${packageJsonPath}`)
        }
    } catch (error) {
        console.error(`Error updating ${packageJsonPath}: ${error.message}`)
    }
}
​
// Iterate through the specified directories and update package.json files
directories.forEach(directory => {
    const packageJsonPath = path.join(directory, 'package.json')
    if (fs.existsSync(packageJsonPath)) {
        updatePackageJson(packageJsonPath)
    } else {
        console.error(`package.json not found in ${directory}`)
    }
})
```


very dirty, but because this library is a dependency of an internal library maintained by another team, I didn't have much options
