### ISSUE TITLE
Feature requested: Support for Ionic

### ISSUE THREAD

**Issue by niconaso** [uNmAnNeR/imaskjs#96]
Do you have any plan to support Ionic Framework?
In Ionic the input is wrapped in a component named ion-input. Perhaps is easy to select the input child of ion-input and apply the mask. You'd make the whole Ionic community very happy.

**Comment by uNmAnNeR** [comment]
@niconaso done in v4.1.0 - added new options for Angular plugin `[imaskElement]`, see details [here](https://github.com/uNmAnNeR/imaskjs/tree/master/packages/angular-imask)

**Comment by lucastllima** [comment]
Hey @uNmAnNeR is there any example of usage on ionic of this update? I couldn't apply it in my project :/ Thanks!

**Comment by uNmAnNeR** [comment]
@lucastllima hi! i guess no. I don't use ionic personally. The fix https://github.com/uNmAnNeR/imaskjs/pull/97 was about adding possibility to overwrite `elementRef` to be able to pass ionic elements instead of html inputs.

**Comment by lucastllima** [comment]
Like this? It says:

**- imaskElement is not a function**


```
<ion-input
id="CEP"
#CEP="ngModel"
[imaskElement]="CEP"
>
</ion-input>
```
