### ISSUE TITLE
react-imask: Error [ERR_REQUIRE_ESM]: require() of ES Module not supported.

### ISSUE THREAD

**Issue by frederike-ramin** [uNmAnNeR/imaskjs#961]
**Describe the bug**
Very similar to this issue, only for React: https://github.com/uNmAnNeR/imaskjs/issues/899
Cannot import `IMask`.

**To Reproduce**
Start a Remix project (unsure if it also happens in other frameworks).
Import `IMask` like the following:
```
import IMask from "imask";

const MaskedInput = () => {
  IMask(<input />, {})
};
```
Try to start the development environment.
Get the following error:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module [project]/node_modules/imask/dist/imask.js from [project]/build/index.js not supported.
imask.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename imask.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in [project]/node_modules/imask/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).
```

**Expected behavior**
No error ;)

**Environment:**
 - IMask version: 7.1.3
 - Used Framework: Remix 1.17.1
 - Language: TypeScript 4.9.5
 - ES2019

**Comment by smellai** [comment]
Same issue here:
Environment:

- iMask 7.1.3
- Framework: next 12.3.1
- Typescript: 4.7.4

**Comment by uNmAnNeR** [comment]
@frederike-ramin hi, a walked through the remix tutorial https://remix.run/docs/en/main/start/quickstart#the-root-route
remix version is 2.3.1. importing imask is working fine. There also new cjs build was added for imask recently. It will be released soon. Please check and reopen if needed.
