### ISSUE TITLE
Example provided for react hook provides incorrect types

### ISSUE THREAD

**Issue by vixducis** [uNmAnNeR/imaskjs#962]
**Describe the bug**
I'm using the react plugin for this library. I'm considering the very minimal example provide for the hook variant of the plugin:
```typescript
const { ref } = useIMask({ mask: Number });
return <input ref={ref} />;
```

The ref attribute on the input element will return a typescript error since not all types for the `InputMaskElement` union cover the attributes for an `InputElement`. I'm by no means a typescript wizard, so I don't have a good solution. The problem of course is that you don't know at the time of creation of the ref element what react element it will be assigned to, meaning it should be indicated at time of creation of the hook. Currently i'm doing the following (but obviously I don't like the type casting):
```typescript
ref={ref as MutableRefObject<HTMLInputElement | null>}
```

**How to reproduce**
https://stackblitz.com/edit/vitejs-vite-3nnghw?file=src%2FApp.tsx

**Comment by uNmAnNeR** [comment]
you can specify a type for `useIMask`:
https://stackblitz.com/edit/vitejs-vite-q2ggbl?file=src%2FApp.tsx
