### ISSUE TITLE
The first keystroke is skipped if the mask consists of a number and a character after it.

### ISSUE THREAD

**Issue by Rex4r** [uNmAnNeR/imaskjs#964]
I have input:

    <input
      :id="id"
      v-imask="maskOptions"
      :value="state.value"
      @accept="handleAccept"
    />

    maskOptions = {
      mask: 'num%',
      eager: true,
      blocks: {
        num: {
          mask: Number,
          scale: 6,
          radix: ',',
          mapToRadix: ['.', ','],
          max: 99.999999,
          min: 1,
        },
      },
    };

When I start entering numbers into a field, after putting focus on it, if the field is empty, then the first digit is always skipped.
The "input" and "keypress" event fires, but the "accept" event does not.

**Comment by uNmAnNeR** [comment]
i can not reproduce the issue. In my case it works fine. Pls create a sandbox with repro. thanks
