### ISSUE TITLE
Vue-imask in vue ^2.7

### ISSUE THREAD

**Issue by captain-zsa** [uNmAnNeR/imaskjs#975]
I use plugin in vue 2.7.10. In this version vue@composition-api is present by default, but imask not worked if composition-api not instaled. When I install composition-api and use imask-input, I see many errors:
<img width="1318" alt="Снимок экрана 2023-12-15 в 14 15 05" src="https://github.com/uNmAnNeR/imaskjs/assets/18168845/f9cf88c0-9789-49a6-8f23-b9c62225a5be">
(and more).

Maybe someone knows how to resolve these problems?

**Comment by uNmAnNeR** [comment]
@captain-zsa check this is the same issue https://github.com/uNmAnNeR/imaskjs/issues/974

**Comment by captain-zsa** [comment]
Why #974 is answer on my question?.. Sorry, but i'm not understand)) What I should do?  freezed vue-imask version to 7.1.3 ?

Now I install @vue/composition-api@1.7.2 and have error
"@vue/composition-api@1.7.2 has incorrect peer dependency "vue@>= 2.5 < 2.7".

I think this is the main problem.

What I do:
install nuxt 2.15.8, install vue-imask latest version, install @vue/composition-api and @nuxtjs/composition-api
(assembly example https://github.com/captain-zsa/vue2-imask ).

**Comment by uNmAnNeR** [comment]
> Why https://github.com/uNmAnNeR/imaskjs/issues/974 is answer on my question?.. Sorry, but i'm not understand)) What I should do? freezed vue-imask version to 7.1.3 ?

that was the first assumption not the key one. The errors on your original screenshot are the same as described #974. Solution has been further described.

> Now I install @vue/composition-api@1.7.2 and have error
"@vue/composition-api@1.7.2 has incorrect peer dependency "vue@>= 2.5 < 2.7".

> I think this is the main problem.

`vue-imask` does not depend on composition-api directly. It is used under `vue-demi` package. So you can address this question them https://github.com/vueuse/vue-demi
Btw support for Vue2 will be dropped in the next major `imask` version.
