### ISSUE TITLE
only works with 1 element?

### ISSUE THREAD

**Issue by awgul** [uNmAnNeR/imaskjs#98]
Hey,

I try this:
`var numberMask = new IMask(
  document.querySelectorAll('input.decimal'),
  {
    mask: Number,
    min: -10000,
    max: 10000,
    thousandsSeparator: ' '
  });`

And it doesn't work at all.
Does this plugin work only per 1 element?
I have more fields on page.

**Comment by uNmAnNeR** [comment]
You are right, only for 1 element. For array of elements you could use native js `forEach`.

**Comment by awgul** [comment]
Hey, Thanks. I will do so.
