### ISSUE TITLE
Unable to type last character for year in date

### ISSUE THREAD

**Issue by JasonFoglia** [uNmAnNeR/imaskjs#980]
**Describe the bug**
Using Angular 17, but need to use with Angular 13, tested only in StackBlitz.
Unable to type full year. And last character doesn't fire onAccept. Changed to include MaxLength for year, set to 4. 

**To Reproduce**
[StackBlitz](https://stackblitz.com/edit/stackblitz-starters-jhf1ns)

**Expected behavior**
The full date should be typed

**Environment:**
 - OS: Windows
 - Browser: Edge
 - Version: 
 - IMask version: 7.2.1
 - Framework/plugin version: 7.2.1

**Comment by robkuz** [comment]
I have the same issue

**Comment by uNmAnNeR** [comment]
@JasonFoglia you must specify `parse` method along with `format` option.

**Comment by robkuz** [comment]
using `parse` and `format` wont help.
Whatever I do, whichever Blocks I am using, which ever pattern and which ever order I use in the patterns.
the last digit wont appear in the input field. It does appear thou in the parse function and the correct value also is generated in the format function.

Below is my code which uses unpoly.js

```
up.compiler("[up-mask]", function (element) {
    const createMask = (value) => {
        switch (value.toLowerCase()) {
            case "number": return Number;
            case "date": return Date;
            default: return value;
        }
    }
    console.log("000 up-mask", element)
    const value = element.getAttribute("up-mask")
    if (value) {
        try {
            console.log("100 up-mask", value)
            const data = JSON.parse(value)
            const options = {
                mask: createMask(data.mask),
                lazy: false,
            }
            if (data.mask.toLowerCase() === "number") {
                if (data.min) {
                    options.min = data.min
                }
                if (data.max) {
                    options.max = data.max
                }
            }
            if (data.mask.toLowerCase() === "date") {
                if (data.min) {
                    options.min = new Date(data.min)
                }
                if (data.max) {
                    options.max = new Date(data.max)
                }
                const format = (date) => {
                    console.log("100 FORMAT", date)
                    var day = date.getDate();
                    var month = date.getMonth() + 1;
                    var year = date.getFullYear();
                
                    if (day < 10) day = "0" + day;
                    if (month < 10) month = "0" + month;
                
                    const result = [year, month, day].join('-');
                    console.log("200 FORMAT", result)
                    return result
                }
                
                const parse = (str) => {
                    console.log("100 PARSE", str)
                    var yearMonthDay = str.split('-');
                    var date = new Date(yearMonthDay[0], yearMonthDay[1] - 1, yearMonthDay[2])
                    console.log("200 PARSE",date)
                    return date;
                }

                const blocks = {
                    Y: {
                      mask: IMask.MaskedRange,
                      from: 1900,
                      to: 2090,
                    },
                    M: {
                      mask: IMask.MaskedRange,
                      from: 1,
                      to: 12,
                    },
                    D: {
                      mask: IMask.MaskedRange,
                      from: 1,
                      to: 31,
                    },
                }
                options.pattern = 'Y-M-D'
                options.blocks = blocks
                options.format = format
                options.parse = parse
                }
            const m = IMask(element, options);

        }
        catch (e) {
            console.log("up-mask", e)
        }
    }
    console.log("up-mask", value)
});
```

**Comment by uNmAnNeR** [comment]
@robkuz it works fine with your example as well: https://stackblitz.com/edit/stackblitz-starters-gdk7hy?file=src%2Fmain.ts
if you enter non-existent date then you can not enter the last digit. If you do not need validation for Date then use pure pattern mask instead.

**Comment by JasonFoglia** [comment]
@robkuz This works but is not correct. 
https://stackblitz.com/edit/stackblitz-starters-f88oxu

Using this date M/D/Y 12/20/1980 which is a valid date. And I'm using very simple pattern instead of trying format and parse.
Using your example if you switch the year to be last it doesn't work for the last digit in the year. 
'M-D-Y'

**Comment by robkuz** [comment]
> @robkuz it works fine with your example as well: https://stackblitz.com/edit/stackblitz-starters-gdk7hy?file=src%2Fmain.ts if you enter non-existent date then you can not enter the last digit. If you do not need validation for Date then use pure pattern mask instead.

Now i have it working. The difference thou seems to be the conversion of the parts into Numbers before feeding the value into the Date constructor. All of this is pretty strange as the date object created in either way looks like a valid date.

Thanks anyhow. It works now

**Comment by JasonFoglia** [comment]
> @uNmAnNeR

Even though this was closed I provided how the mask uses one kind of date format vs others. Can you please look at this stackblitz https://stackblitz.com/edit/stackblitz-starters-f88oxu?
