### ISSUE TITLE
Unexpected character removed

### ISSUE THREAD

**Issue by jhonimaike** [uNmAnNeR/imaskjs#986]
**Describe the bug**
If I set a mask with group separator to "." and decimal separator in ","
When trying to remove the decimal digits and the decimal separator, the library also removes the last character of the integer value and moves the decimal separator "," to the place of the group separator

**To Reproduce**
Steps and link to sandbox. You can use [jsfiddle](https://jsfiddle.net/euEmail/5rkum7t0/1/)

**Expected behavior**
It should maintain the value correctly, not eliminating the last digit of the entire value

https://github.com/uNmAnNeR/imaskjs/assets/42501674/69aa4668-f78a-44ff-a351-ac0a5f37d128

**Comment by uNmAnNeR** [comment]
hi, you probably need to report this issue here https://github.com/RobinHerbots/Inputmask/issues
