### ISSUE TITLE
Cursor error on input

### ISSUE THREAD

**Issue by davidhernandeze** [uNmAnNeR/imaskjs#99]
I have this implementation of IMask:
```
numberMask = new IMask(
              document.getElementById('tiebreaker-answer'),
              {
                mask: Number,
                min: 0,
                max: 40000000,
                thousandsSeparator: ', '
              });
```

If you  type "1" then "2" then "3" then "4" then "5"
You will see that the number that turns out is "12,534" instead of "12,345" because after typing 4 the cursor change their position.

**Comment by davidhernandeze** [comment]
When I remove the space after comma, it works well.

**Comment by uNmAnNeR** [comment]
@davidhernandeze  currently `thousandsSeparator` should be a single char.
