### ISSUE TITLE
Add Support for <q-input> Quasar framework

### ISSUE THREAD

**Issue by satish123satish123** [uNmAnNeR/imaskjs#997]
not working with q-input tag of Quasar framework

<q-input
          v-model="value"
          :v-imask="mask"
          @accept="onAccept"
          @complete="onComplete"
        />

const value = ref(null)
const mask = {
  mask: '+{7}(000)000-00-00',
  lazy: true,
}

**Comment by Shyam-Chen** [comment]
You need to create a Vue directive yourself to locate the `<input>` within the UI library.

**Comment by uNmAnNeR** [comment]
i am not sure but according to the Quasar docs it should be possible to use vue directives/composables. So you can use `vue-imask`.
